.section .rodata
.align 2
nonmatching D_800E3C94_A5F044

dlabel D_800E3C94_A5F044
    /* A5F044 800E3C94 */ .asciz "Ｔｏｄｄ"
    /* A3D4A3EFA3E4A3E400000000 */
.align 2
enddlabel D_800E3C94_A5F044

.align 2
nonmatching D_800E3CA0_A5F050

dlabel D_800E3CA0_A5F050
    /* A5F050 800E3CA0 */ .asciz "　　　　　　　"
    /* A1A1A1A1A1A1A1A1A1A1A1A1A1A10000 */
.align 2
enddlabel D_800E3CA0_A5F050


.section .text
/* Generated by spimdisasm 1.42.2 */

nonmatching func_800E28C0_A5DC70, 0x164

glabel func_800E28C0_A5DC70
    /* A5DC70 800E28C0 27BDFFB0 */  addiu      $sp, $sp, -0x50
    /* A5DC74 800E28C4 3C0E800E */  lui        $t6, %hi(D_800E3C94_A5F044)
    /* A5DC78 800E28C8 AFBF001C */  sw         $ra, 0x1C($sp)
    /* A5DC7C 800E28CC 25CE3C94 */  addiu      $t6, $t6, %lo(D_800E3C94_A5F044)
    /* A5DC80 800E28D0 8DD80000 */  lw         $t8, 0x0($t6)
    /* A5DC84 800E28D4 27A20044 */  addiu      $v0, $sp, 0x44
    /* A5DC88 800E28D8 3C19800E */  lui        $t9, %hi(D_800E3CA0_A5F050)
    /* A5DC8C 800E28DC AC580000 */  sw         $t8, 0x0($v0)
    /* A5DC90 800E28E0 8DCF0004 */  lw         $t7, 0x4($t6)
    /* A5DC94 800E28E4 27393CA0 */  addiu      $t9, $t9, %lo(D_800E3CA0_A5F050)
    /* A5DC98 800E28E8 27A70034 */  addiu      $a3, $sp, 0x34
    /* A5DC9C 800E28EC AC4F0004 */  sw         $t7, 0x4($v0)
    /* A5DCA0 800E28F0 91D80008 */  lbu        $t8, 0x8($t6)
    /* A5DCA4 800E28F4 3C038017 */  lui        $v1, %hi(D_80168130_AE34E0)
    /* A5DCA8 800E28F8 24638130 */  addiu      $v1, $v1, %lo(D_80168130_AE34E0)
    /* A5DCAC 800E28FC A0580008 */  sb         $t8, 0x8($v0)
    /* A5DCB0 800E2900 8F290000 */  lw         $t1, 0x0($t9)
    /* A5DCB4 800E2904 3C018017 */  lui        $at, %hi(D_8016814C_AE34FC)
    /* A5DCB8 800E2908 24040001 */  addiu      $a0, $zero, 0x1
    /* A5DCBC 800E290C ACE90000 */  sw         $t1, 0x0($a3)
    /* A5DCC0 800E2910 8F280004 */  lw         $t0, 0x4($t9)
    /* A5DCC4 800E2914 ACE80004 */  sw         $t0, 0x4($a3)
    /* A5DCC8 800E2918 8F290008 */  lw         $t1, 0x8($t9)
    /* A5DCCC 800E291C ACE90008 */  sw         $t1, 0x8($a3)
    /* A5DCD0 800E2920 9B29000E */  lwr        $t1, 0xE($t9)
    /* A5DCD4 800E2924 B8E9000E */  swr        $t1, 0xE($a3)
    /* A5DCD8 800E2928 A020814C */  sb         $zero, %lo(D_8016814C_AE34FC)($at)
    /* A5DCDC 800E292C AFA20030 */  sw         $v0, 0x30($sp)
    /* A5DCE0 800E2930 AFA70028 */  sw         $a3, 0x28($sp)
    /* A5DCE4 800E2934 0C002F2A */  jal        ohWait
    /* A5DCE8 800E2938 AFA3002C */   sw        $v1, 0x2C($sp)
    /* A5DCEC 800E293C 3C0A8017 */  lui        $t2, %hi(D_80168130_AE34E0)
    /* A5DCF0 800E2940 914A8130 */  lbu        $t2, %lo(D_80168130_AE34E0)($t2)
    /* A5DCF4 800E2944 8FA3002C */  lw         $v1, 0x2C($sp)
    /* A5DCF8 800E2948 8FA50028 */  lw         $a1, 0x28($sp)
    /* A5DCFC 800E294C 1140000C */  beqz       $t2, .L800E2980_A5DD30
    /* A5DD00 800E2950 8FA60030 */   lw        $a2, 0x30($sp)
    /* A5DD04 800E2954 90640000 */  lbu        $a0, 0x0($v1)
    /* A5DD08 800E2958 90AB0000 */  lbu        $t3, 0x0($a1)
  .L800E295C_A5DD0C:
    /* A5DD0C 800E295C 24A50001 */  addiu      $a1, $a1, 0x1
    /* A5DD10 800E2960 008B1026 */  xor        $v0, $a0, $t3
    /* A5DD14 800E2964 0002102B */  sltu       $v0, $zero, $v0
    /* A5DD18 800E2968 54400006 */  bnel       $v0, $zero, .L800E2984_A5DD34
    /* A5DD1C 800E296C 906C0000 */   lbu       $t4, 0x0($v1)
    /* A5DD20 800E2970 90640001 */  lbu        $a0, 0x1($v1)
    /* A5DD24 800E2974 24630001 */  addiu      $v1, $v1, 0x1
    /* A5DD28 800E2978 5480FFF8 */  bnel       $a0, $zero, .L800E295C_A5DD0C
    /* A5DD2C 800E297C 90AB0000 */   lbu       $t3, 0x0($a1)
  .L800E2980_A5DD30:
    /* A5DD30 800E2980 906C0000 */  lbu        $t4, 0x0($v1)
  .L800E2984_A5DD34:
    /* A5DD34 800E2984 3C038017 */  lui        $v1, %hi(D_80168130_AE34E0)
    /* A5DD38 800E2988 24638130 */  addiu      $v1, $v1, %lo(D_80168130_AE34E0)
    /* A5DD3C 800E298C 1580001C */  bnez       $t4, .L800E2A00_A5DDB0
    /* A5DD40 800E2990 3C048012 */   lui       $a0, %hi(D_80118110_A934C0)
  .L800E2994_A5DD44:
    /* A5DD44 800E2994 90CD0000 */  lbu        $t5, 0x0($a2)
    /* A5DD48 800E2998 24630001 */  addiu      $v1, $v1, 0x1
    /* A5DD4C 800E299C A06DFFFF */  sb         $t5, -0x1($v1)
    /* A5DD50 800E29A0 90CE0000 */  lbu        $t6, 0x0($a2)
    /* A5DD54 800E29A4 11C00003 */  beqz       $t6, .L800E29B4_A5DD64
    /* A5DD58 800E29A8 00000000 */   nop
    /* A5DD5C 800E29AC 1000FFF9 */  b          .L800E2994_A5DD44
    /* A5DD60 800E29B0 24C60001 */   addiu     $a2, $a2, 0x1
  .L800E29B4_A5DD64:
    /* A5DD64 800E29B4 0C0DAA39 */  jal        func_8036A8E4
    /* A5DD68 800E29B8 8C848110 */   lw        $a0, %lo(D_80118110_A934C0)($a0)
    /* A5DD6C 800E29BC 3C048012 */  lui        $a0, %hi(D_80118110_A934C0)
    /* A5DD70 800E29C0 8C848110 */  lw         $a0, %lo(D_80118110_A934C0)($a0)
    /* A5DD74 800E29C4 00002825 */  or         $a1, $zero, $zero
    /* A5DD78 800E29C8 0C0DAE7B */  jal        func_8036B9EC
    /* A5DD7C 800E29CC 00003025 */   or        $a2, $zero, $zero
    /* A5DD80 800E29D0 3C048012 */  lui        $a0, %hi(D_80118110_A934C0)
    /* A5DD84 800E29D4 3C058017 */  lui        $a1, %hi(D_80168130_AE34E0)
    /* A5DD88 800E29D8 24A58130 */  addiu      $a1, $a1, %lo(D_80168130_AE34E0)
    /* A5DD8C 800E29DC 0C0DB226 */  jal        func_8036C898
    /* A5DD90 800E29E0 8C848110 */   lw        $a0, %lo(D_80118110_A934C0)($a0)
    /* A5DD94 800E29E4 240F000A */  addiu      $t7, $zero, 0xA
    /* A5DD98 800E29E8 AFAF0010 */  sw         $t7, 0x10($sp)
    /* A5DD9C 800E29EC 24040060 */  addiu      $a0, $zero, 0x60
    /* A5DDA0 800E29F0 24057FFF */  addiu      $a1, $zero, 0x7FFF
    /* A5DDA4 800E29F4 24060054 */  addiu      $a2, $zero, 0x54
    /* A5DDA8 800E29F8 0C008A96 */  jal        auPlaySoundWithParams
    /* A5DDAC 800E29FC 3C073F80 */   lui       $a3, (0x3F800000 >> 16)
  .L800E2A00_A5DDB0:
    /* A5DDB0 800E2A00 3C048017 */  lui        $a0, %hi(D_80168130_AE34E0)
    /* A5DDB4 800E2A04 0C02FD13 */  jal        func_800BF44C_5C2EC
    /* A5DDB8 800E2A08 24848130 */   addiu     $a0, $a0, %lo(D_80168130_AE34E0)
    /* A5DDBC 800E2A0C 0C008A39 */  jal        auPlaySound
    /* A5DDC0 800E2A10 24040042 */   addiu     $a0, $zero, 0x42
    /* A5DDC4 800E2A14 8FBF001C */  lw         $ra, 0x1C($sp)
    /* A5DDC8 800E2A18 27BD0050 */  addiu      $sp, $sp, 0x50
    /* A5DDCC 800E2A1C 03E00008 */  jr         $ra
    /* A5DDD0 800E2A20 00000000 */   nop
endlabel func_800E28C0_A5DC70
