.section .rodata
.align 2
nonmatching D_803A68F0_87A0A0

dlabel D_803A68F0_87A0A0
    /* 87A0A0 803A68F0 */ .asciz "\\l"
    /* 5C6C0000 */
.align 2
.align 2
    /* 87A0A4 803A68F4 */ .asciz ""
    /* 00000000 */
.align 2
.align 2
    /* 87A0A8 803A68F8 */ .asciz ""
    /* 00000000 */
.align 2
.align 2
    /* 87A0AC 803A68FC */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_803A68F0_87A0A0


.section .text
/* Generated by spimdisasm 1.42.1 */

nonmatching func_80374F30_8486E0, 0xEC

glabel func_80374F30_8486E0
    /* 8486E0 80374F30 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 8486E4 80374F34 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 8486E8 80374F38 AFA50024 */  sw         $a1, 0x24($sp)
    /* 8486EC 80374F3C AFA40020 */  sw         $a0, 0x20($sp)
    /* 8486F0 80374F40 AFA0001C */  sw         $zero, 0x1C($sp)
    /* 8486F4 80374F44 240500B4 */  addiu      $a1, $zero, 0xB4
    /* 8486F8 80374F48 0C0DAE7B */  jal        func_8036B9EC_83F19C
    /* 8486FC 80374F4C 24060020 */   addiu     $a2, $zero, 0x20
    /* 848700 80374F50 3C05803A */  lui        $a1, %hi(D_803A68F0_87A0A0)
    /* 848704 80374F54 24A568F0 */  addiu      $a1, $a1, %lo(D_803A68F0_87A0A0)
    /* 848708 80374F58 0C0DB226 */  jal        UIElement_PrintText
    /* 84870C 80374F5C 8FA40020 */   lw        $a0, 0x20($sp)
    /* 848710 80374F60 0C0DBAE0 */  jal        func_8036EB80_842330
    /* 848714 80374F64 00002025 */   or        $a0, $zero, $zero
    /* 848718 80374F68 0C002F2A */  jal        ohWait
    /* 84871C 80374F6C 24040001 */   addiu     $a0, $zero, 0x1
    /* 848720 80374F70 0C02A8E3 */  jal        func_800AA38C
    /* 848724 80374F74 00002025 */   or        $a0, $zero, $zero
    /* 848728 80374F78 8C4E0018 */  lw         $t6, 0x18($v0)
    /* 84872C 80374F7C 31CFC000 */  andi       $t7, $t6, 0xC000
    /* 848730 80374F80 55E0000A */  bnel       $t7, $zero, .L80374FAC_84875C
    /* 848734 80374F84 8C430014 */   lw        $v1, 0x14($v0)
  .L80374F88_848738:
    /* 848738 80374F88 0C002F2A */  jal        ohWait
    /* 84873C 80374F8C 24040001 */   addiu     $a0, $zero, 0x1
    /* 848740 80374F90 0C02A8E3 */  jal        func_800AA38C
    /* 848744 80374F94 00002025 */   or        $a0, $zero, $zero
    /* 848748 80374F98 8C580018 */  lw         $t8, 0x18($v0)
    /* 84874C 80374F9C 3319C000 */  andi       $t9, $t8, 0xC000
    /* 848750 80374FA0 1320FFF9 */  beqz       $t9, .L80374F88_848738
    /* 848754 80374FA4 00000000 */   nop
    /* 848758 80374FA8 8C430014 */  lw         $v1, 0x14($v0)
  .L80374FAC_84875C:
    /* 84875C 80374FAC 34098000 */  ori        $t1, $zero, 0x8000
    /* 848760 80374FB0 240B4000 */  addiu      $t3, $zero, 0x4000
    /* 848764 80374FB4 30688000 */  andi       $t0, $v1, 0x8000
    /* 848768 80374FB8 11000002 */  beqz       $t0, .L80374FC4_848774
    /* 84876C 80374FBC 306A4000 */   andi      $t2, $v1, 0x4000
    /* 848770 80374FC0 AFA9001C */  sw         $t1, 0x1C($sp)
  .L80374FC4_848774:
    /* 848774 80374FC4 11400002 */  beqz       $t2, .L80374FD0_848780
    /* 848778 80374FC8 306C1000 */   andi      $t4, $v1, 0x1000
    /* 84877C 80374FCC AFAB001C */  sw         $t3, 0x1C($sp)
  .L80374FD0_848780:
    /* 848780 80374FD0 11800002 */  beqz       $t4, .L80374FDC_84878C
    /* 848784 80374FD4 240D1000 */   addiu     $t5, $zero, 0x1000
    /* 848788 80374FD8 AFAD001C */  sw         $t5, 0x1C($sp)
  .L80374FDC_84878C:
    /* 84878C 80374FDC 8FAE0024 */  lw         $t6, 0x24($sp)
    /* 848790 80374FE0 11C00003 */  beqz       $t6, .L80374FF0_8487A0
    /* 848794 80374FE4 00000000 */   nop
    /* 848798 80374FE8 0C008A39 */  jal        auPlaySound
    /* 84879C 80374FEC 2404004D */   addiu     $a0, $zero, 0x4D
  .L80374FF0_8487A0:
    /* 8487A0 80374FF0 0C002F2A */  jal        ohWait
    /* 8487A4 80374FF4 24040001 */   addiu     $a0, $zero, 0x1
    /* 8487A8 80374FF8 0C0DAA39 */  jal        func_8036A8E4_83E094
    /* 8487AC 80374FFC 8FA40020 */   lw        $a0, 0x20($sp)
    /* 8487B0 80375000 0C0DBAE0 */  jal        func_8036EB80_842330
    /* 8487B4 80375004 24040001 */   addiu     $a0, $zero, 0x1
    /* 8487B8 80375008 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 8487BC 8037500C 8FA2001C */  lw         $v0, 0x1C($sp)
    /* 8487C0 80375010 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 8487C4 80375014 03E00008 */  jr         $ra
    /* 8487C8 80375018 00000000 */   nop
endlabel func_80374F30_8486E0
