.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.0 */

nonmatching D_802F0350_5ED420

dlabel D_802F0350_5ED420
    /* 5ED420 802F0350 3DCCCCCD */ .float 0.1000000015
enddlabel D_802F0350_5ED420

nonmatching D_802F0354_5ED424

dlabel D_802F0354_5ED424
    /* 5ED424 802F0354 3D0EFA35 */ .float 0.03490658477
    /* 5ED428 802F0358 00000000 */ .float 0
    /* 5ED42C 802F035C 00000000 */ .float 0
enddlabel D_802F0354_5ED424
