.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.0 */

.align 3
nonmatching D_802ECD10_7C62A0

dlabel D_802ECD10_7C62A0
    /* 7C62A0 802ECD10 3FB999999999999A */ .double 0.100000000000000006
enddlabel D_802ECD10_7C62A0

nonmatching D_802ECD18_7C62A8

dlabel D_802ECD18_7C62A8
    /* 7C62A8 802ECD18 3DCCCCCD */ .float 0.1000000015
    /* 7C62AC 802ECD1C 00000000 */ .float 0
enddlabel D_802ECD18_7C62A8
