.section .rodata
.align 2
nonmatching D_80203888_9FA1F8

dlabel D_80203888_9FA1F8
    /* 9FA1F8 80203888 */ .asciz "You have collected"
    /* 596F75206861766520636F6C6C65637465640000 */
.align 2
enddlabel D_80203888_9FA1F8

.align 2
nonmatching D_8020389C_9FA20C

dlabel D_8020389C_9FA20C
    /* 9FA20C 8020389C */ .asciz "%d PKMN Signs."
    /* 256420504B4D4E205369676E732E0000 */
.align 2
enddlabel D_8020389C_9FA20C


.section .text
/* Generated by spimdisasm 1.42.0 */

nonmatching func_801E0C3C_9D75AC, 0x118

glabel func_801E0C3C_9D75AC
    /* 9D75AC 801E0C3C 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 9D75B0 801E0C40 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 9D75B4 801E0C44 AFA40020 */  sw         $a0, 0x20($sp)
    /* 9D75B8 801E0C48 8FAE0020 */  lw         $t6, 0x20($sp)
    /* 9D75BC 801E0C4C 05C00004 */  bltz       $t6, .L801E0C60_9D75D0
    /* 9D75C0 801E0C50 00000000 */   nop
    /* 9D75C4 801E0C54 29C10006 */  slti       $at, $t6, 0x6
    /* 9D75C8 801E0C58 14200003 */  bnez       $at, .L801E0C68_9D75D8
    /* 9D75CC 801E0C5C 00000000 */   nop
  .L801E0C60_9D75D0:
    /* 9D75D0 801E0C60 10000038 */  b          .L801E0D44_9D76B4
    /* 9D75D4 801E0C64 00000000 */   nop
  .L801E0C68_9D75D8:
    /* 9D75D8 801E0C68 8FAF0020 */  lw         $t7, 0x20($sp)
    /* 9D75DC 801E0C6C 3C048020 */  lui        $a0, %hi(D_80202D34_9F96A4)
    /* 9D75E0 801E0C70 000FC080 */  sll        $t8, $t7, 2
    /* 9D75E4 801E0C74 00982021 */  addu       $a0, $a0, $t8
    /* 9D75E8 801E0C78 0C02FCF5 */  jal        func_800BF3D4_5C274
    /* 9D75EC 801E0C7C 8C842D34 */   lw        $a0, %lo(D_80202D34_9F96A4)($a0)
    /* 9D75F0 801E0C80 1440000C */  bnez       $v0, .L801E0CB4_9D7624
    /* 9D75F4 801E0C84 00000000 */   nop
    /* 9D75F8 801E0C88 8FB90020 */  lw         $t9, 0x20($sp)
    /* 9D75FC 801E0C8C 3C058020 */  lui        $a1, %hi(D_80202E8C_9F97FC)
    /* 9D7600 801E0C90 3C048023 */  lui        $a0, %hi(D_80230C30_A275A0)
    /* 9D7604 801E0C94 00194080 */  sll        $t0, $t9, 2
    /* 9D7608 801E0C98 00A82821 */  addu       $a1, $a1, $t0
    /* 9D760C 801E0C9C 8CA52E8C */  lw         $a1, %lo(D_80202E8C_9F97FC)($a1)
    /* 9D7610 801E0CA0 8C840C30 */  lw         $a0, %lo(D_80230C30_A275A0)($a0)
    /* 9D7614 801E0CA4 0C0782E3 */  jal        func_801E0B8C_9D74FC
    /* 9D7618 801E0CA8 00003025 */   or        $a2, $zero, $zero
    /* 9D761C 801E0CAC 1000000A */  b          .L801E0CD8_9D7648
    /* 9D7620 801E0CB0 00000000 */   nop
  .L801E0CB4_9D7624:
    /* 9D7624 801E0CB4 8FA90020 */  lw         $t1, 0x20($sp)
    /* 9D7628 801E0CB8 3C058020 */  lui        $a1, %hi(D_80202EA4_9F9814)
    /* 9D762C 801E0CBC 3C048023 */  lui        $a0, %hi(D_80230C30_A275A0)
    /* 9D7630 801E0CC0 00095080 */  sll        $t2, $t1, 2
    /* 9D7634 801E0CC4 00AA2821 */  addu       $a1, $a1, $t2
    /* 9D7638 801E0CC8 8CA52EA4 */  lw         $a1, %lo(D_80202EA4_9F9814)($a1)
    /* 9D763C 801E0CCC 8C840C30 */  lw         $a0, %lo(D_80230C30_A275A0)($a0)
    /* 9D7640 801E0CD0 0C0782E3 */  jal        func_801E0B8C_9D74FC
    /* 9D7644 801E0CD4 00003025 */   or        $a2, $zero, $zero
  .L801E0CD8_9D7648:
    /* 9D7648 801E0CD8 0C0DB528 */  jal        func_8036D4A0
    /* 9D764C 801E0CDC 00002025 */   or        $a0, $zero, $zero
    /* 9D7650 801E0CE0 0C0773D7 */  jal        func_801DCF5C_9D38CC
    /* 9D7654 801E0CE4 27A4001C */   addiu     $a0, $sp, 0x1C
    /* 9D7658 801E0CE8 3C048023 */  lui        $a0, %hi(D_80230C30_A275A0)
    /* 9D765C 801E0CEC 8C840C30 */  lw         $a0, %lo(D_80230C30_A275A0)($a0)
    /* 9D7660 801E0CF0 00002825 */  or         $a1, $zero, $zero
    /* 9D7664 801E0CF4 0C0DAE7B */  jal        func_8036B9EC
    /* 9D7668 801E0CF8 00003025 */   or        $a2, $zero, $zero
    /* 9D766C 801E0CFC 3C048023 */  lui        $a0, %hi(D_80230C30_A275A0)
    /* 9D7670 801E0D00 3C058020 */  lui        $a1, %hi(D_80203888_9FA1F8)
    /* 9D7674 801E0D04 24A53888 */  addiu      $a1, $a1, %lo(D_80203888_9FA1F8)
    /* 9D7678 801E0D08 0C0DB226 */  jal        func_8036C898
    /* 9D767C 801E0D0C 8C840C30 */   lw        $a0, %lo(D_80230C30_A275A0)($a0)
    /* 9D7680 801E0D10 3C048023 */  lui        $a0, %hi(D_80230C30_A275A0)
    /* 9D7684 801E0D14 8C840C30 */  lw         $a0, %lo(D_80230C30_A275A0)($a0)
    /* 9D7688 801E0D18 00002825 */  or         $a1, $zero, $zero
    /* 9D768C 801E0D1C 0C0DAE7B */  jal        func_8036B9EC
    /* 9D7690 801E0D20 24060012 */   addiu     $a2, $zero, 0x12
    /* 9D7694 801E0D24 3C048023 */  lui        $a0, %hi(D_80230C30_A275A0)
    /* 9D7698 801E0D28 3C058020 */  lui        $a1, %hi(D_8020389C_9FA20C)
    /* 9D769C 801E0D2C 24A5389C */  addiu      $a1, $a1, %lo(D_8020389C_9FA20C)
    /* 9D76A0 801E0D30 8C840C30 */  lw         $a0, %lo(D_80230C30_A275A0)($a0)
    /* 9D76A4 801E0D34 0C0DD467 */  jal        func_8037519C
    /* 9D76A8 801E0D38 8FA6001C */   lw        $a2, 0x1C($sp)
    /* 9D76AC 801E0D3C 10000001 */  b          .L801E0D44_9D76B4
    /* 9D76B0 801E0D40 00000000 */   nop
  .L801E0D44_9D76B4:
    /* 9D76B4 801E0D44 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 9D76B8 801E0D48 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 9D76BC 801E0D4C 03E00008 */  jr         $ra
    /* 9D76C0 801E0D50 00000000 */   nop
endlabel func_801E0C3C_9D75AC
