.section .late_rodata
nonmatching D_80043D40

dlabel D_80043D40
    /* 44940 80043D40 BDDD6712 */ .float -0.1081067473
enddlabel D_80043D40

nonmatching D_80043D44

dlabel D_80043D44
    /* 44944 80043D44 C23249A5 */ .float -44.57191849
enddlabel D_80043D44

nonmatching D_80043D48

dlabel D_80043D48
    /* 44948 80043D48 BE25CB3D */ .float -0.161908105
enddlabel D_80043D48

nonmatching D_80043D4C

dlabel D_80043D4C
    /* 4494C 80043D4C C17C6261 */ .float -15.77401829
enddlabel D_80043D4C

nonmatching D_80043D50

dlabel D_80043D50
    /* 44950 80043D50 BF0E39D2 */ .float -0.555569768
enddlabel D_80043D50

nonmatching D_80043D54

dlabel D_80043D54
    /* 44954 80043D54 C040000D */ .float -3.000003099
enddlabel D_80043D54

nonmatching D_80043D58

dlabel D_80043D58
    /* 44958 80043D58 3FC90FDB */ .float 1.570796371
enddlabel D_80043D58

nonmatching D_80043D5C

dlabel D_80043D5C
    /* 4495C 80043D5C BFC90FDB */ .float -1.570796371
enddlabel D_80043D5C


.section .text
/* Generated by spimdisasm 1.42.1 */

nonmatching atanf, 0x128

glabel atanf
    /* 1A594 80019994 44801000 */  mtc1       $zero, $f2
    /* 1A598 80019998 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 1A59C 8001999C 46026032 */  c.eq.s     $f12, $f2
    /* 1A5A0 800199A0 00000000 */  nop
    /* 1A5A4 800199A4 45020004 */  bc1fl      .L800199B8
    /* 1A5A8 800199A8 44810000 */   mtc1      $at, $f0
    /* 1A5AC 800199AC 03E00008 */  jr         $ra
    /* 1A5B0 800199B0 46001006 */   mov.s     $f0, $f2
    /* 1A5B4 800199B4 44810000 */  mtc1       $at, $f0
  .L800199B8:
    /* 1A5B8 800199B8 24020001 */  addiu      $v0, $zero, 0x1
    /* 1A5BC 800199BC 3C01BF80 */  lui        $at, (0xBF800000 >> 16)
    /* 1A5C0 800199C0 460C003C */  c.lt.s     $f0, $f12
    /* 1A5C4 800199C4 00000000 */  nop
    /* 1A5C8 800199C8 45020004 */  bc1fl      .L800199DC
    /* 1A5CC 800199CC 44812000 */   mtc1      $at, $f4
    /* 1A5D0 800199D0 1000000A */  b          .L800199FC
    /* 1A5D4 800199D4 460C0303 */   div.s     $f12, $f0, $f12
    /* 1A5D8 800199D8 44812000 */  mtc1       $at, $f4
  .L800199DC:
    /* 1A5DC 800199DC 00001025 */  or         $v0, $zero, $zero
    /* 1A5E0 800199E0 4604603C */  c.lt.s     $f12, $f4
    /* 1A5E4 800199E4 00000000 */  nop
    /* 1A5E8 800199E8 45000004 */  bc1f       .L800199FC
    /* 1A5EC 800199EC 00000000 */   nop
    /* 1A5F0 800199F0 460C0303 */  div.s      $f12, $f0, $f12
    /* 1A5F4 800199F4 10000001 */  b          .L800199FC
    /* 1A5F8 800199F8 24020002 */   addiu     $v0, $zero, 0x2
  .L800199FC:
    /* 1A5FC 800199FC 460C6002 */  mul.s      $f0, $f12, $f12
    /* 1A600 80019A00 3C018004 */  lui        $at, %hi(D_80043D40)
    /* 1A604 80019A04 C4263D40 */  lwc1       $f6, %lo(D_80043D40)($at)
    /* 1A608 80019A08 3C018004 */  lui        $at, %hi(D_80043D44)
    /* 1A60C 80019A0C C42A3D44 */  lwc1       $f10, %lo(D_80043D44)($at)
    /* 1A610 80019A10 3C018004 */  lui        $at, %hi(D_80043D48)
    /* 1A614 80019A14 C4243D48 */  lwc1       $f4, %lo(D_80043D48)($at)
    /* 1A618 80019A18 46060203 */  div.s      $f8, $f0, $f6
    /* 1A61C 80019A1C 3C018004 */  lui        $at, %hi(D_80043D4C)
    /* 1A620 80019A20 460A4400 */  add.s      $f16, $f8, $f10
    /* 1A624 80019A24 C42A3D4C */  lwc1       $f10, %lo(D_80043D4C)($at)
    /* 1A628 80019A28 3C018004 */  lui        $at, %hi(D_80043D50)
    /* 1A62C 80019A2C 46100483 */  div.s      $f18, $f0, $f16
    /* 1A630 80019A30 46049180 */  add.s      $f6, $f18, $f4
    /* 1A634 80019A34 C4243D50 */  lwc1       $f4, %lo(D_80043D50)($at)
    /* 1A638 80019A38 3C018004 */  lui        $at, %hi(D_80043D54)
    /* 1A63C 80019A3C 46060203 */  div.s      $f8, $f0, $f6
    /* 1A640 80019A40 460A4400 */  add.s      $f16, $f8, $f10
    /* 1A644 80019A44 C42A3D54 */  lwc1       $f10, %lo(D_80043D54)($at)
    /* 1A648 80019A48 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 1A64C 80019A4C 46100483 */  div.s      $f18, $f0, $f16
    /* 1A650 80019A50 46049180 */  add.s      $f6, $f18, $f4
    /* 1A654 80019A54 44812000 */  mtc1       $at, $f4
    /* 1A658 80019A58 24010001 */  addiu      $at, $zero, 0x1
    /* 1A65C 80019A5C 46060203 */  div.s      $f8, $f0, $f6
    /* 1A660 80019A60 460A4400 */  add.s      $f16, $f8, $f10
    /* 1A664 80019A64 46100483 */  div.s      $f18, $f0, $f16
    /* 1A668 80019A68 46049180 */  add.s      $f6, $f18, $f4
    /* 1A66C 80019A6C 460C3082 */  mul.s      $f2, $f6, $f12
    /* 1A670 80019A70 10400007 */  beqz       $v0, .L80019A90
    /* 1A674 80019A74 00000000 */   nop
    /* 1A678 80019A78 10410007 */  beq        $v0, $at, .L80019A98
    /* 1A67C 80019A7C 24010002 */   addiu     $at, $zero, 0x2
    /* 1A680 80019A80 10410009 */  beq        $v0, $at, .L80019AA8
    /* 1A684 80019A84 00000000 */   nop
    /* 1A688 80019A88 03E00008 */  jr         $ra
    /* 1A68C 80019A8C 00000000 */   nop
  .L80019A90:
    /* 1A690 80019A90 03E00008 */  jr         $ra
    /* 1A694 80019A94 46001006 */   mov.s     $f0, $f2
  .L80019A98:
    /* 1A698 80019A98 3C018004 */  lui        $at, %hi(D_80043D58)
    /* 1A69C 80019A9C C4283D58 */  lwc1       $f8, %lo(D_80043D58)($at)
    /* 1A6A0 80019AA0 03E00008 */  jr         $ra
    /* 1A6A4 80019AA4 46024001 */   sub.s     $f0, $f8, $f2
  .L80019AA8:
    /* 1A6A8 80019AA8 3C018004 */  lui        $at, %hi(D_80043D5C)
    /* 1A6AC 80019AAC C42A3D5C */  lwc1       $f10, %lo(D_80043D5C)($at)
    /* 1A6B0 80019AB0 46025001 */  sub.s      $f0, $f10, $f2
    /* 1A6B4 80019AB4 03E00008 */  jr         $ra
    /* 1A6B8 80019AB8 00000000 */   nop
endlabel atanf
