.section .late_rodata
nonmatching D_80043D60

dlabel D_80043D60
    /* 44960 80043D60 40490FDB */ .float 3.141592741
enddlabel D_80043D60

nonmatching D_80043D64

dlabel D_80043D64
    /* 44964 80043D64 3FC90FDB */ .float 1.570796371
enddlabel D_80043D64


.section .text
/* Generated by spimdisasm 1.42.2 */

nonmatching atan2f, 0x100

glabel atan2f
    /* 1A6BC 80019ABC 44801000 */  mtc1       $zero, $f2
    /* 1A6C0 80019AC0 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 1A6C4 80019AC4 F7B40010 */  sdc1       $f20, 0x10($sp)
    /* 1A6C8 80019AC8 460E103C */  c.lt.s     $f2, $f14
    /* 1A6CC 80019ACC 46006506 */  mov.s      $f20, $f12
    /* 1A6D0 80019AD0 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 1A6D4 80019AD4 45020006 */  bc1fl      .L80019AF0
    /* 1A6D8 80019AD8 4602703C */   c.lt.s    $f14, $f2
    /* 1A6DC 80019ADC 0C006665 */  jal        atanf
    /* 1A6E0 80019AE0 460E6303 */   div.s     $f12, $f12, $f14
    /* 1A6E4 80019AE4 10000031 */  b          .L80019BAC
    /* 1A6E8 80019AE8 8FBF001C */   lw        $ra, 0x1C($sp)
    /* 1A6EC 80019AEC 4602703C */  c.lt.s     $f14, $f2
  .L80019AF0:
    /* 1A6F0 80019AF0 00000000 */  nop
    /* 1A6F4 80019AF4 4502001B */  bc1fl      .L80019B64
    /* 1A6F8 80019AF8 4602A032 */   c.eq.s    $f20, $f2
    /* 1A6FC 80019AFC 4602A03C */  c.lt.s     $f20, $f2
    /* 1A700 80019B00 24020001 */  addiu      $v0, $zero, 0x1
    /* 1A704 80019B04 460EA003 */  div.s      $f0, $f20, $f14
    /* 1A708 80019B08 45000003 */  bc1f       .L80019B18
    /* 1A70C 80019B0C 00000000 */   nop
    /* 1A710 80019B10 10000001 */  b          .L80019B18
    /* 1A714 80019B14 2402FFFF */   addiu     $v0, $zero, -0x1
  .L80019B18:
    /* 1A718 80019B18 4602003C */  c.lt.s     $f0, $f2
    /* 1A71C 80019B1C 00000000 */  nop
    /* 1A720 80019B20 45020004 */  bc1fl      .L80019B34
    /* 1A724 80019B24 46000306 */   mov.s     $f12, $f0
    /* 1A728 80019B28 10000002 */  b          .L80019B34
    /* 1A72C 80019B2C 46000307 */   neg.s     $f12, $f0
    /* 1A730 80019B30 46000306 */  mov.s      $f12, $f0
  .L80019B34:
    /* 1A734 80019B34 0C006665 */  jal        atanf
    /* 1A738 80019B38 AFA20020 */   sw        $v0, 0x20($sp)
    /* 1A73C 80019B3C 8FA20020 */  lw         $v0, 0x20($sp)
    /* 1A740 80019B40 3C018004 */  lui        $at, %hi(D_80043D60)
    /* 1A744 80019B44 C4243D60 */  lwc1       $f4, %lo(D_80043D60)($at)
    /* 1A748 80019B48 44824000 */  mtc1       $v0, $f8
    /* 1A74C 80019B4C 46002181 */  sub.s      $f6, $f4, $f0
    /* 1A750 80019B50 468042A0 */  cvt.s.w    $f10, $f8
    /* 1A754 80019B54 460A3002 */  mul.s      $f0, $f6, $f10
    /* 1A758 80019B58 10000014 */  b          .L80019BAC
    /* 1A75C 80019B5C 8FBF001C */   lw        $ra, 0x1C($sp)
    /* 1A760 80019B60 4602A032 */  c.eq.s     $f20, $f2
  .L80019B64:
    /* 1A764 80019B64 00000000 */  nop
    /* 1A768 80019B68 4503000F */  bc1tl      .L80019BA8
    /* 1A76C 80019B6C 46001006 */   mov.s     $f0, $f2
    /* 1A770 80019B70 4602A03C */  c.lt.s     $f20, $f2
    /* 1A774 80019B74 24020001 */  addiu      $v0, $zero, 0x1
    /* 1A778 80019B78 45000003 */  bc1f       .L80019B88
    /* 1A77C 80019B7C 00000000 */   nop
    /* 1A780 80019B80 10000001 */  b          .L80019B88
    /* 1A784 80019B84 2402FFFF */   addiu     $v0, $zero, -0x1
  .L80019B88:
    /* 1A788 80019B88 44828000 */  mtc1       $v0, $f16
    /* 1A78C 80019B8C 3C018004 */  lui        $at, %hi(D_80043D64)
    /* 1A790 80019B90 C4243D64 */  lwc1       $f4, %lo(D_80043D64)($at)
    /* 1A794 80019B94 468084A0 */  cvt.s.w    $f18, $f16
    /* 1A798 80019B98 46049002 */  mul.s      $f0, $f18, $f4
    /* 1A79C 80019B9C 10000003 */  b          .L80019BAC
    /* 1A7A0 80019BA0 8FBF001C */   lw        $ra, 0x1C($sp)
    /* 1A7A4 80019BA4 46001006 */  mov.s      $f0, $f2
  .L80019BA8:
    /* 1A7A8 80019BA8 8FBF001C */  lw         $ra, 0x1C($sp)
  .L80019BAC:
    /* 1A7AC 80019BAC D7B40010 */  ldc1       $f20, 0x10($sp)
    /* 1A7B0 80019BB0 27BD0028 */  addiu      $sp, $sp, 0x28
    /* 1A7B4 80019BB4 03E00008 */  jr         $ra
    /* 1A7B8 80019BB8 00000000 */   nop
endlabel atan2f
