#include "common.h"

Gfx jynx_part10_draw_near[] = {
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsDPSetTile(G_IM_FMT_RGBA, G_IM_SIZ_16b, 0, 0x0000, G_TX_LOADTILE, 0, G_TX_NOMIRROR | G_TX_WRAP, 5, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_WRAP, 5, G_TX_NOLOD),
    gsDPSetTile(G_IM_FMT_RGBA, G_IM_SIZ_16b, 8, 0x0000, G_TX_RENDERTILE, 0, G_TX_NOMIRROR | G_TX_CLAMP, 5, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_CLAMP, 5, G_TX_NOLOD),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetTileSize(G_TX_RENDERTILE, 0, 0, 0x007C, 0x007C),
    gsDPSetTextureImage(G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, jynx_tex_hair_png),
    gsDPLoadSync(),
    gsDPLoadBlock(G_TX_LOADTILE, 0, 0, 1023, 256),
    gsDPPipeSync(),
    gsSPClearGeometryMode(G_CULL_BACK),
    gsSPModifyVertex(0, G_MWO_POINT_ST, 0x020F020F),
    gsSPModifyVertex(1, G_MWO_POINT_ST, 0x000F020F),
    gsSPModifyVertex(2, G_MWO_POINT_ST, 0x020F020F),
    gsSPModifyVertex(3, G_MWO_POINT_ST, 0x03EF020F),
    gsSPVertex(&jynx_vtx[194], 2, 5),
    gsSP1Triangle(6, 1, 0, 0),
    gsSPModifyVertex(1, G_MWO_POINT_ST, 0x03EF020F),
    gsSPModifyVertex(4, G_MWO_POINT_ST, 0x000F020F),
    gsSP2Triangles(3, 6, 0, 0, 2, 1, 5, 0),
    gsSP1Triangle(4, 2, 5, 0),
    gsDPPipeSync(),
    gsDPPipeSync(),
    gsSPSetGeometryMode(G_CULL_BACK),
    gsSPEndDisplayList(),
};
