#include "common.h"

Gfx jynx_part5_draw_far[] = {
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsDPSetTile(G_IM_FMT_RGBA, G_IM_SIZ_16b, 0, 0x0000, G_TX_LOADTILE, 0, G_TX_NOMIRROR | G_TX_WRAP, 5, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_WRAP, 5, G_TX_NOLOD),
    gsDPSetTile(G_IM_FMT_RGBA, G_IM_SIZ_16b, 8, 0x0000, G_TX_RENDERTILE, 0, G_TX_NOMIRROR | G_TX_CLAMP, 5, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_CLAMP, 5, G_TX_NOLOD),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetTileSize(G_TX_RENDERTILE, 0, 0, 0x007C, 0x007C),
    gsDPSetTextureImage(G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, jynx_tex_hair_png),
    gsDPLoadSync(),
    gsDPLoadBlock(G_TX_LOADTILE, 0, 0, 1023, 256),
    gsDPPipeSync(),
    gsSPClearGeometryMode(G_CULL_BACK),
    gsSPModifyVertex(0, G_MWO_POINT_ST, 0x034103E4),
    gsSPModifyVertex(1, G_MWO_POINT_ST, 0x03FF03BA),
    gsSPModifyVertex(2, G_MWO_POINT_ST, 0x000F03EF),
    gsSPModifyVertex(3, G_MWO_POINT_ST, 0x03EF03EF),
    gsSPModifyVertex(4, G_MWO_POINT_ST, 0x000F03EF),
    gsSPModifyVertex(5, G_MWO_POINT_ST, 0x03EF03EF),
    gsSPVertex(&jynx_vtx[408], 6, 6),
    gsSP2Triangles(4, 11, 5, 0, 11, 10, 5, 0),
    gsSP2Triangles(11, 4, 9, 0, 1, 0, 8, 0),
    gsSP2Triangles(7, 3, 2, 0, 7, 6, 3, 0),
    gsDPPipeSync(),
    gsDPPipeSync(),
    gsSPSetGeometryMode(G_CULL_BACK),
    gsSPEndDisplayList(),
};
