.section .late_rodata
nonmatching D_802E3960_734B60

dlabel D_802E3960_734B60
    /* 734B60 802E3960 40490FDB */ .float 3.141592741
    /* 734B64 802E3964 00000000 */ .float 0
    /* 734B68 802E3968 00000000 */ .float 0
    /* 734B6C 802E396C 00000000 */ .float 0
enddlabel D_802E3960_734B60


.section .text
/* Generated by spimdisasm 1.42.0 */

nonmatching func_802DF280_730480, 0xB8

glabel func_802DF280_730480
    /* 730480 802DF280 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* 730484 802DF284 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 730488 802DF288 AFB00018 */  sw         $s0, 0x18($sp)
    /* 73048C 802DF28C 8C820048 */  lw         $v0, 0x48($a0)
    /* 730490 802DF290 3C05802E */  lui        $a1, %hi(D_802E3634_734834)
    /* 730494 802DF294 00808025 */  or         $s0, $a0, $zero
    /* 730498 802DF298 8C4E004C */  lw         $t6, 0x4C($v0)
    /* 73049C 802DF29C 24A53634 */  addiu      $a1, $a1, %lo(D_802E3634_734834)
    /* 7304A0 802DF2A0 25CF0014 */  addiu      $t7, $t6, 0x14
    /* 7304A4 802DF2A4 AFAF0024 */  sw         $t7, 0x24($sp)
    /* 7304A8 802DF2A8 8C980058 */  lw         $t8, 0x58($a0)
    /* 7304AC 802DF2AC 0C0D7C4E */  jal        Pokemon_SetAnimation
    /* 7304B0 802DF2B0 AFB80020 */   sw        $t8, 0x20($sp)
    /* 7304B4 802DF2B4 0C006785 */  jal        randRange
    /* 7304B8 802DF2B8 24040168 */   addiu     $a0, $zero, 0x168
    /* 7304BC 802DF2BC 44822000 */  mtc1       $v0, $f4
    /* 7304C0 802DF2C0 3C01802E */  lui        $at, %hi(D_802E3960_734B60)
    /* 7304C4 802DF2C4 C4283960 */  lwc1       $f8, %lo(D_802E3960_734B60)($at)
    /* 7304C8 802DF2C8 468021A0 */  cvt.s.w    $f6, $f4
    /* 7304CC 802DF2CC 3C014334 */  lui        $at, (0x43340000 >> 16)
    /* 7304D0 802DF2D0 44818000 */  mtc1       $at, $f16
    /* 7304D4 802DF2D4 8FB90024 */  lw         $t9, 0x24($sp)
    /* 7304D8 802DF2D8 3C05802E */  lui        $a1, %hi(func_802DF338_730538)
    /* 7304DC 802DF2DC 24A5F338 */  addiu      $a1, $a1, %lo(func_802DF338_730538)
    /* 7304E0 802DF2E0 46083282 */  mul.s      $f10, $f6, $f8
    /* 7304E4 802DF2E4 02002025 */  or         $a0, $s0, $zero
    /* 7304E8 802DF2E8 46105483 */  div.s      $f18, $f10, $f16
    /* 7304EC 802DF2EC 0C0D7B7E */  jal        Pokemon_StartPathProc
    /* 7304F0 802DF2F0 E732000C */   swc1      $f18, 0xC($t9)
    /* 7304F4 802DF2F4 8FA80020 */  lw         $t0, 0x20($sp)
    /* 7304F8 802DF2F8 02002025 */  or         $a0, $s0, $zero
    /* 7304FC 802DF2FC 24050001 */  addiu      $a1, $zero, 0x1
    /* 730500 802DF300 0C0D7EFC */  jal        Pokemon_WaitForFlag
    /* 730504 802DF304 AD0000AC */   sw        $zero, 0xAC($t0)
    /* 730508 802DF308 3C01802E */  lui        $at, %hi(D_802E0EB4_7320B4)
    /* 73050C 802DF30C A4200EB4 */  sh         $zero, %lo(D_802E0EB4_7320B4)($at)
    /* 730510 802DF310 0C0D7F5C */  jal        Pokemon_RunCleanup
    /* 730514 802DF314 02002025 */   or        $a0, $s0, $zero
    /* 730518 802DF318 02002025 */  or         $a0, $s0, $zero
    /* 73051C 802DF31C 0C0D7B16 */  jal        Pokemon_SetState
    /* 730520 802DF320 00002825 */   or        $a1, $zero, $zero
    /* 730524 802DF324 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 730528 802DF328 8FB00018 */  lw         $s0, 0x18($sp)
    /* 73052C 802DF32C 27BD0030 */  addiu      $sp, $sp, 0x30
    /* 730530 802DF330 03E00008 */  jr         $ra
    /* 730534 802DF334 00000000 */   nop
endlabel func_802DF280_730480
