.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.42.1 */

.align 2
nonmatching D_80042D50

dlabel D_80042D50
    /* 43950 80042D50 */ .asciz "                                "
    /* 202020202020202020202020202020202020202020202020202020202020202000000000 */
.align 2
enddlabel D_80042D50

.align 2
nonmatching D_80042D74

dlabel D_80042D74
    /* 43974 80042D74 */ .asciz "00000000000000000000000000000000"
    /* 303030303030303030303030303030303030303030303030303030303030303000000000 */
.align 2
.align 2
    /* 43998 80042D98 */ .asciz ""
    /* 00000000 */
.align 2
.align 2
    /* 4399C 80042D9C */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_80042D74
