#include "common.h"

Gfx mew_hd_part17_pre[] = {
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_NONE),
    gsSPTexture(0x07C0, 0x0FC0, 0, G_TX_RENDERTILE, G_ON),
    gsSPVertex(&mew_hd_vtx[54], 1, 7),
    gsSPVertex(&mew_hd_vtx[56], 1, 8),
    gsSPVertex(&mew_hd_vtx[50], 1, 9),
    gsSPVertex(&mew_hd_vtx[52], 1, 10),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsSPTexture(0x07C0, 0x07C0, 0, G_TX_RENDERTILE, G_ON),
    gsSPVertex(&mew_hd_vtx[16], 1, 6),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPSetCombineLERP(PRIMITIVE, 0, SHADE, 0, 0, 0, 0, PRIMITIVE, 0, 0, 0, COMBINED, 0, 0, 0, COMBINED),
    gsSPTexture(0x00C0, 0x00C0, 0, G_TX_RENDERTILE, G_ON),
    gsSPVertex(&mew_hd_vtx[79], 1, 2),
    gsSPVertex(&mew_hd_vtx[77], 1, 3),
    gsSPVertex(&mew_hd_vtx[76], 1, 4),
    gsSPVertex(&mew_hd_vtx[81], 1, 5),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsSPTexture(0x07C0, 0x07C0, 0, G_TX_RENDERTILE, G_ON),
    gsSPVertex(&mew_hd_vtx[14], 1, 0),
    gsSPVertex(&mew_hd_vtx[17], 1, 1),
    gsSPEndDisplayList(),
};
