#include "common.h"

Gfx mew_part1_pre_near[] = {
    gsDPPipeSync(),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsSPTexture(0x07C0, 0x0FC0, 0, G_TX_RENDERTILE, G_ON),
    gsSPVertex(&mew_vtx[48], 2, 10),
    gsSPVertex(&mew_vtx[39], 1, 12),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsSPTexture(0x07C0, 0x07C0, 0, G_TX_RENDERTILE, G_ON),
    gsSPVertex(&mew_vtx[0], 1, 5),
    gsSPVertex(&mew_vtx[12], 1, 6),
    gsSPVertex(&mew_vtx[1], 2, 7),
    gsSPVertex(&mew_vtx[11], 1, 9),
    gsSPVertex(&mew_vtx[13], 1, 13),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPSetCombineLERP(PRIMITIVE, 0, SHADE, 0, 0, 0, 0, PRIMITIVE, 0, 0, 0, COMBINED, 0, 0, 0, COMBINED),
    gsSPTexture(0x00C0, 0x00C0, 0, G_TX_RENDERTILE, G_ON),
    gsSPVertex(&mew_vtx[58], 1, 4),
    gsDPPipeSync(),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsSPTexture(0x07C0, 0x0FC0, 0, G_TX_RENDERTILE, G_ON),
    gsSPVertex(&mew_vtx[53], 1, 1),
    gsSPVertex(&mew_vtx[44], 1, 3),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsSPTexture(0x07C0, 0x07C0, 0, G_TX_RENDERTILE, G_ON),
    gsSPVertex(&mew_vtx[24], 1, 0),
    gsSPVertex(&mew_vtx[8], 1, 2),
    gsSPEndDisplayList(),
};
