.section .late_rodata
nonmatching D_802ECDF0_7C6380

dlabel D_802ECDF0_7C6380
    /* 7C6380 802ECDF0 7F7FFFFF */ .float 3.402823466e+38
    /* 7C6384 802ECDF4 00000000 */ .float 0
    /* 7C6388 802ECDF8 00000000 */ .float 0
    /* 7C638C 802ECDFC 00000000 */ .float 0
enddlabel D_802ECDF0_7C6380


.section .text
/* Generated by spimdisasm 1.42.2 */

nonmatching func_802CF8BC_7A8E4C, 0x144

glabel func_802CF8BC_7A8E4C
    /* 7A8E4C 802CF8BC 27BDFF90 */  addiu      $sp, $sp, -0x70
    /* 7A8E50 802CF8C0 AFBF003C */  sw         $ra, 0x3C($sp)
    /* 7A8E54 802CF8C4 AFB40038 */  sw         $s4, 0x38($sp)
    /* 7A8E58 802CF8C8 AFB30034 */  sw         $s3, 0x34($sp)
    /* 7A8E5C 802CF8CC AFB20030 */  sw         $s2, 0x30($sp)
    /* 7A8E60 802CF8D0 AFB1002C */  sw         $s1, 0x2C($sp)
    /* 7A8E64 802CF8D4 AFB00028 */  sw         $s0, 0x28($sp)
    /* 7A8E68 802CF8D8 F7B60020 */  sdc1       $f22, 0x20($sp)
    /* 7A8E6C 802CF8DC F7B40018 */  sdc1       $f20, 0x18($sp)
    /* 7A8E70 802CF8E0 8C820048 */  lw         $v0, 0x48($a0)
    /* 7A8E74 802CF8E4 8C8E0058 */  lw         $t6, 0x58($a0)
    /* 7A8E78 802CF8E8 3C0F802D */  lui        $t7, %hi(D_802D41C8_7AD758)
    /* 7A8E7C 802CF8EC 8C50004C */  lw         $s0, 0x4C($v0)
    /* 7A8E80 802CF8F0 25EF41C8 */  addiu      $t7, $t7, %lo(D_802D41C8_7AD758)
    /* 7A8E84 802CF8F4 AFAE0060 */  sw         $t6, 0x60($sp)
    /* 7A8E88 802CF8F8 8DF90000 */  lw         $t9, 0x0($t7)
    /* 7A8E8C 802CF8FC 27B20048 */  addiu      $s2, $sp, 0x48
    /* 7A8E90 802CF900 3C0142C8 */  lui        $at, (0x42C80000 >> 16)
    /* 7A8E94 802CF904 AE590000 */  sw         $t9, 0x0($s2)
    /* 7A8E98 802CF908 8DF80004 */  lw         $t8, 0x4($t7)
    /* 7A8E9C 802CF90C 4481B000 */  mtc1       $at, $f22
    /* 7A8EA0 802CF910 3C01802F */  lui        $at, %hi(D_802ECDF0_7C6380)
    /* 7A8EA4 802CF914 AE580004 */  sw         $t8, 0x4($s2)
    /* 7A8EA8 802CF918 8DF90008 */  lw         $t9, 0x8($t7)
    /* 7A8EAC 802CF91C 0080A025 */  or         $s4, $a0, $zero
    /* 7A8EB0 802CF920 27B30054 */  addiu      $s3, $sp, 0x54
    /* 7A8EB4 802CF924 AE590008 */  sw         $t9, 0x8($s2)
    /* 7A8EB8 802CF928 C424CDF0 */  lwc1       $f4, %lo(D_802ECDF0_7C6380)($at)
    /* 7A8EBC 802CF92C 8FA80060 */  lw         $t0, 0x60($sp)
    /* 7A8EC0 802CF930 26100004 */  addiu      $s0, $s0, 0x4
    /* 7A8EC4 802CF934 4604B03C */  c.lt.s     $f22, $f4
    /* 7A8EC8 802CF938 8D090070 */  lw         $t1, 0x70($t0)
    /* 7A8ECC 802CF93C 45000016 */  bc1f       .L802CF998_7A8F28
    /* 7A8ED0 802CF940 8D310048 */   lw        $s1, 0x48($t1)
    /* 7A8ED4 802CF944 02602025 */  or         $a0, $s3, $zero
  .L802CF948_7A8ED8:
    /* 7A8ED8 802CF948 02402825 */  or         $a1, $s2, $zero
    /* 7A8EDC 802CF94C 0C0297A6 */  jal        fx_getPosVelDObj
    /* 7A8EE0 802CF950 02203025 */   or        $a2, $s1, $zero
    /* 7A8EE4 802CF954 C7A60054 */  lwc1       $f6, 0x54($sp)
    /* 7A8EE8 802CF958 C6080004 */  lwc1       $f8, 0x4($s0)
    /* 7A8EEC 802CF95C C7B0005C */  lwc1       $f16, 0x5C($sp)
    /* 7A8EF0 802CF960 24040001 */  addiu      $a0, $zero, 0x1
    /* 7A8EF4 802CF964 46083281 */  sub.s      $f10, $f6, $f8
    /* 7A8EF8 802CF968 E7AA0054 */  swc1       $f10, 0x54($sp)
    /* 7A8EFC 802CF96C C612000C */  lwc1       $f18, 0xC($s0)
    /* 7A8F00 802CF970 460A5182 */  mul.s      $f6, $f10, $f10
    /* 7A8F04 802CF974 46128101 */  sub.s      $f4, $f16, $f18
    /* 7A8F08 802CF978 46042202 */  mul.s      $f8, $f4, $f4
    /* 7A8F0C 802CF97C E7A4005C */  swc1       $f4, 0x5C($sp)
    /* 7A8F10 802CF980 0C002F2A */  jal        ohWait
    /* 7A8F14 802CF984 46083500 */   add.s     $f20, $f6, $f8
    /* 7A8F18 802CF988 4614B03C */  c.lt.s     $f22, $f20
    /* 7A8F1C 802CF98C 00000000 */  nop
    /* 7A8F20 802CF990 4503FFED */  bc1tl      .L802CF948_7A8ED8
    /* 7A8F24 802CF994 02602025 */   or        $a0, $s3, $zero
  .L802CF998_7A8F28:
    /* 7A8F28 802CF998 3C05802D */  lui        $a1, %hi(D_802D4190_7AD720)
    /* 7A8F2C 802CF99C 24A54190 */  addiu      $a1, $a1, %lo(D_802D4190_7AD720)
    /* 7A8F30 802CF9A0 0C0D7C4E */  jal        Pokemon_SetAnimation
    /* 7A8F34 802CF9A4 02802025 */   or        $a0, $s4, $zero
    /* 7A8F38 802CF9A8 8FAA0060 */  lw         $t2, 0x60($sp)
    /* 7A8F3C 802CF9AC 02802025 */  or         $a0, $s4, $zero
    /* 7A8F40 802CF9B0 24050001 */  addiu      $a1, $zero, 0x1
    /* 7A8F44 802CF9B4 0C0D7EFC */  jal        Pokemon_WaitForFlag
    /* 7A8F48 802CF9B8 AD4000AC */   sw        $zero, 0xAC($t2)
    /* 7A8F4C 802CF9BC 3C05802D */  lui        $a1, %hi(D_802D417C_7AD70C)
    /* 7A8F50 802CF9C0 24A5417C */  addiu      $a1, $a1, %lo(D_802D417C_7AD70C)
    /* 7A8F54 802CF9C4 0C0D7C4E */  jal        Pokemon_SetAnimation
    /* 7A8F58 802CF9C8 02802025 */   or        $a0, $s4, $zero
    /* 7A8F5C 802CF9CC 02802025 */  or         $a0, $s4, $zero
    /* 7A8F60 802CF9D0 0C0D7B16 */  jal        Pokemon_SetState
    /* 7A8F64 802CF9D4 00002825 */   or        $a1, $zero, $zero
    /* 7A8F68 802CF9D8 8FBF003C */  lw         $ra, 0x3C($sp)
    /* 7A8F6C 802CF9DC D7B40018 */  ldc1       $f20, 0x18($sp)
    /* 7A8F70 802CF9E0 D7B60020 */  ldc1       $f22, 0x20($sp)
    /* 7A8F74 802CF9E4 8FB00028 */  lw         $s0, 0x28($sp)
    /* 7A8F78 802CF9E8 8FB1002C */  lw         $s1, 0x2C($sp)
    /* 7A8F7C 802CF9EC 8FB20030 */  lw         $s2, 0x30($sp)
    /* 7A8F80 802CF9F0 8FB30034 */  lw         $s3, 0x34($sp)
    /* 7A8F84 802CF9F4 8FB40038 */  lw         $s4, 0x38($sp)
    /* 7A8F88 802CF9F8 03E00008 */  jr         $ra
    /* 7A8F8C 802CF9FC 27BD0070 */   addiu     $sp, $sp, 0x70
endlabel func_802CF8BC_7A8E4C
