.section .late_rodata
nonmatching D_8038A2CC_52A6DC

dlabel D_8038A2CC_52A6DC
    /* 52A6DC 8038A2CC 3A03126F */ .float 0.0005000000237
enddlabel D_8038A2CC_52A6DC

nonmatching D_8038A2D0_52A6E0

dlabel D_8038A2D0_52A6E0
    /* 52A6E0 8038A2D0 3A03126F */ .float 0.0005000000237
enddlabel D_8038A2D0_52A6E0

nonmatching jtbl_8038A2D4_52A6E4

dlabel jtbl_8038A2D4_52A6E4
    /* 52A6E4 8038A2D4 80356E24 */ .word .L80356E24_4F7234
    /* 52A6E8 8038A2D8 80356FA0 */ .word .L80356FA0_4F73B0
    /* 52A6EC 8038A2DC 80356FA0 */ .word .L80356FA0_4F73B0
    /* 52A6F0 8038A2E0 80356F68 */ .word .L80356F68_4F7378
    /* 52A6F4 8038A2E4 80356EA8 */ .word .L80356EA8_4F72B8
    /* 52A6F8 8038A2E8 80356F28 */ .word .L80356F28_4F7338
    /* 52A6FC 8038A2EC 80356EE8 */ .word .L80356EE8_4F72F8
enddlabel jtbl_8038A2D4_52A6E4


.section .text
/* Generated by spimdisasm 1.42.0 */

nonmatching initUI, 0xC1C

glabel initUI
    /* 4F67B0 803563A0 27BDFFB0 */  addiu      $sp, $sp, -0x50
    /* 4F67B4 803563A4 AFA50054 */  sw         $a1, 0x54($sp)
    /* 4F67B8 803563A8 AFBF0034 */  sw         $ra, 0x34($sp)
    /* 4F67BC 803563AC AFA40050 */  sw         $a0, 0x50($sp)
    /* 4F67C0 803563B0 AFA60058 */  sw         $a2, 0x58($sp)
    /* 4F67C4 803563B4 AFA7005C */  sw         $a3, 0x5C($sp)
    /* 4F67C8 803563B8 3C058035 */  lui        $a1, %hi(func_80355EF0_4F6300)
    /* 4F67CC 803563BC 24A55EF0 */  addiu      $a1, $a1, %lo(func_80355EF0_4F6300)
    /* 4F67D0 803563C0 3C078000 */  lui        $a3, (0x80000000 >> 16)
    /* 4F67D4 803563C4 24060009 */  addiu      $a2, $zero, 0x9
    /* 4F67D8 803563C8 0C002904 */  jal        omAddGObj
    /* 4F67DC 803563CC 24040007 */   addiu     $a0, $zero, 0x7
    /* 4F67E0 803563D0 AFA20048 */  sw         $v0, 0x48($sp)
    /* 4F67E4 803563D4 00402025 */  or         $a0, $v0, $zero
    /* 4F67E8 803563D8 0C00275C */  jal        omGObjAddDObj
    /* 4F67EC 803563DC 00002825 */   or        $a1, $zero, $zero
    /* 4F67F0 803563E0 8FAE0048 */  lw         $t6, 0x48($sp)
    /* 4F67F4 803563E4 3C03803B */  lui        $v1, %hi(PlayerMatrixStore)
    /* 4F67F8 803563E8 2463E4A0 */  addiu      $v1, $v1, %lo(PlayerMatrixStore)
    /* 4F67FC 803563EC 8DC40048 */  lw         $a0, 0x48($t6)
    /* 4F6800 803563F0 240F0001 */  addiu      $t7, $zero, 0x1
    /* 4F6804 803563F4 24180002 */  addiu      $t8, $zero, 0x2
    /* 4F6808 803563F8 24190003 */  addiu      $t9, $zero, 0x3
    /* 4F680C 803563FC A06F0000 */  sb         $t7, 0x0($v1)
    /* 4F6810 80356400 A0780001 */  sb         $t8, 0x1($v1)
    /* 4F6814 80356404 A0790002 */  sb         $t9, 0x2($v1)
    /* 4F6818 80356408 AC83004C */  sw         $v1, 0x4C($a0)
    /* 4F681C 8035640C 2405003E */  addiu      $a1, $zero, 0x3E
    /* 4F6820 80356410 00003025 */  or         $a2, $zero, $zero
    /* 4F6824 80356414 00003825 */  or         $a3, $zero, $zero
    /* 4F6828 80356418 0C0023FF */  jal        omDObjAddMtx
    /* 4F682C 8035641C AFA40044 */   sw        $a0, 0x44($sp)
    /* 4F6830 80356420 0C026A33 */  jal        getIdleScript
    /* 4F6834 80356424 00000000 */   nop
    /* 4F6838 80356428 3C03803B */  lui        $v1, %hi(ProgressFlags)
    /* 4F683C 8035642C 3C01803B */  lui        $at, %hi(gIdleScript)
    /* 4F6840 80356430 AC22E518 */  sw         $v0, %lo(gIdleScript)($at)
    /* 4F6844 80356434 2463E51C */  addiu      $v1, $v1, %lo(ProgressFlags)
    /* 4F6848 80356438 AC600000 */  sw         $zero, 0x0($v1)
    /* 4F684C 8035643C 0C02FF28 */  jal        checkPlayerFlag
    /* 4F6850 80356440 2404000C */   addiu     $a0, $zero, 0xC
    /* 4F6854 80356444 3C03803B */  lui        $v1, %hi(ProgressFlags)
    /* 4F6858 80356448 24010001 */  addiu      $at, $zero, 0x1
    /* 4F685C 8035644C 14410004 */  bne        $v0, $at, .L80356460_4F6870
    /* 4F6860 80356450 2463E51C */   addiu     $v1, $v1, %lo(ProgressFlags)
    /* 4F6864 80356454 8C6A0000 */  lw         $t2, 0x0($v1)
    /* 4F6868 80356458 354B1000 */  ori        $t3, $t2, 0x1000
    /* 4F686C 8035645C AC6B0000 */  sw         $t3, 0x0($v1)
  .L80356460_4F6870:
    /* 4F6870 80356460 0C02FF28 */  jal        checkPlayerFlag
    /* 4F6874 80356464 2404000D */   addiu     $a0, $zero, 0xD
    /* 4F6878 80356468 3C03803B */  lui        $v1, %hi(ProgressFlags)
    /* 4F687C 8035646C 24010001 */  addiu      $at, $zero, 0x1
    /* 4F6880 80356470 14410004 */  bne        $v0, $at, .L80356484_4F6894
    /* 4F6884 80356474 2463E51C */   addiu     $v1, $v1, %lo(ProgressFlags)
    /* 4F6888 80356478 8C6C0000 */  lw         $t4, 0x0($v1)
    /* 4F688C 8035647C 358D2000 */  ori        $t5, $t4, 0x2000
    /* 4F6890 80356480 AC6D0000 */  sw         $t5, 0x0($v1)
  .L80356484_4F6894:
    /* 4F6894 80356484 0C02FF28 */  jal        checkPlayerFlag
    /* 4F6898 80356488 24040005 */   addiu     $a0, $zero, 0x5
    /* 4F689C 8035648C 3C03803B */  lui        $v1, %hi(ProgressFlags)
    /* 4F68A0 80356490 24010001 */  addiu      $at, $zero, 0x1
    /* 4F68A4 80356494 14410004 */  bne        $v0, $at, .L803564A8_4F68B8
    /* 4F68A8 80356498 2463E51C */   addiu     $v1, $v1, %lo(ProgressFlags)
    /* 4F68AC 8035649C 8C6E0000 */  lw         $t6, 0x0($v1)
    /* 4F68B0 803564A0 35CF0020 */  ori        $t7, $t6, 0x20
    /* 4F68B4 803564A4 AC6F0000 */  sw         $t7, 0x0($v1)
  .L803564A8_4F68B8:
    /* 4F68B8 803564A8 0C02FF28 */  jal        checkPlayerFlag
    /* 4F68BC 803564AC 00002025 */   or        $a0, $zero, $zero
    /* 4F68C0 803564B0 3C03803B */  lui        $v1, %hi(ProgressFlags)
    /* 4F68C4 803564B4 24010001 */  addiu      $at, $zero, 0x1
    /* 4F68C8 803564B8 14410004 */  bne        $v0, $at, .L803564CC_4F68DC
    /* 4F68CC 803564BC 2463E51C */   addiu     $v1, $v1, %lo(ProgressFlags)
    /* 4F68D0 803564C0 8C780000 */  lw         $t8, 0x0($v1)
    /* 4F68D4 803564C4 37190001 */  ori        $t9, $t8, 0x1
    /* 4F68D8 803564C8 AC790000 */  sw         $t9, 0x0($v1)
  .L803564CC_4F68DC:
    /* 4F68DC 803564CC 0C02FF28 */  jal        checkPlayerFlag
    /* 4F68E0 803564D0 24040001 */   addiu     $a0, $zero, 0x1
    /* 4F68E4 803564D4 3C03803B */  lui        $v1, %hi(ProgressFlags)
    /* 4F68E8 803564D8 24010001 */  addiu      $at, $zero, 0x1
    /* 4F68EC 803564DC 14410004 */  bne        $v0, $at, .L803564F0_4F6900
    /* 4F68F0 803564E0 2463E51C */   addiu     $v1, $v1, %lo(ProgressFlags)
    /* 4F68F4 803564E4 8C6A0000 */  lw         $t2, 0x0($v1)
    /* 4F68F8 803564E8 354B0002 */  ori        $t3, $t2, 0x2
    /* 4F68FC 803564EC AC6B0000 */  sw         $t3, 0x0($v1)
  .L803564F0_4F6900:
    /* 4F6900 803564F0 0C02FF28 */  jal        checkPlayerFlag
    /* 4F6904 803564F4 24040002 */   addiu     $a0, $zero, 0x2
    /* 4F6908 803564F8 3C03803B */  lui        $v1, %hi(ProgressFlags)
    /* 4F690C 803564FC 24010001 */  addiu      $at, $zero, 0x1
    /* 4F6910 80356500 14410004 */  bne        $v0, $at, .L80356514_4F6924
    /* 4F6914 80356504 2463E51C */   addiu     $v1, $v1, %lo(ProgressFlags)
    /* 4F6918 80356508 8C6C0000 */  lw         $t4, 0x0($v1)
    /* 4F691C 8035650C 358D0004 */  ori        $t5, $t4, 0x4
    /* 4F6920 80356510 AC6D0000 */  sw         $t5, 0x0($v1)
  .L80356514_4F6924:
    /* 4F6924 80356514 0C02FE19 */  jal        func_800BF864_5C704
    /* 4F6928 80356518 00000000 */   nop
    /* 4F692C 8035651C 3C03803B */  lui        $v1, %hi(ProgressFlags)
    /* 4F6930 80356520 28410004 */  slti       $at, $v0, 0x4
    /* 4F6934 80356524 14200004 */  bnez       $at, .L80356538_4F6948
    /* 4F6938 80356528 2463E51C */   addiu     $v1, $v1, %lo(ProgressFlags)
    /* 4F693C 8035652C 8C6E0000 */  lw         $t6, 0x0($v1)
    /* 4F6940 80356530 35CF0100 */  ori        $t7, $t6, 0x100
    /* 4F6944 80356534 AC6F0000 */  sw         $t7, 0x0($v1)
  .L80356538_4F6948:
    /* 4F6948 80356538 3C18803B */  lui        $t8, %hi(gIdleScript)
    /* 4F694C 8035653C 8F18E518 */  lw         $t8, %lo(gIdleScript)($t8)
    /* 4F6950 80356540 53000006 */  beql       $t8, $zero, .L8035655C_4F696C
    /* 4F6954 80356544 8C620000 */   lw        $v0, 0x0($v1)
    /* 4F6958 80356548 0C0D41E2 */  jal        func_80350788_4F0B98
    /* 4F695C 8035654C 8FA40048 */   lw        $a0, 0x48($sp)
    /* 4F6960 80356550 3C03803B */  lui        $v1, %hi(ProgressFlags)
    /* 4F6964 80356554 2463E51C */  addiu      $v1, $v1, %lo(ProgressFlags)
    /* 4F6968 80356558 8C620000 */  lw         $v0, 0x0($v1)
  .L8035655C_4F696C:
    /* 4F696C 8035655C 3C058035 */  lui        $a1, %hi(func_80350224_4F0634)
    /* 4F6970 80356560 24A50224 */  addiu      $a1, $a1, %lo(func_80350224_4F0634)
    /* 4F6974 80356564 30591000 */  andi       $t9, $v0, 0x1000
    /* 4F6978 80356568 13200005 */  beqz       $t9, .L80356580_4F6990
    /* 4F697C 8035656C 304A2000 */   andi      $t2, $v0, 0x2000
    /* 4F6980 80356570 24030001 */  addiu      $v1, $zero, 0x1
    /* 4F6984 80356574 3C01803B */  lui        $at, %hi(ZoomSwitchMode)
    /* 4F6988 80356578 10000004 */  b          .L8035658C_4F699C
    /* 4F698C 8035657C A023E520 */   sb        $v1, %lo(ZoomSwitchMode)($at)
  .L80356580_4F6990:
    /* 4F6990 80356580 3C01803B */  lui        $at, %hi(ZoomSwitchMode)
    /* 4F6994 80356584 A020E520 */  sb         $zero, %lo(ZoomSwitchMode)($at)
    /* 4F6998 80356588 24030001 */  addiu      $v1, $zero, 0x1
  .L8035658C_4F699C:
    /* 4F699C 8035658C 11400004 */  beqz       $t2, .L803565A0_4F69B0
    /* 4F69A0 80356590 304B0020 */   andi      $t3, $v0, 0x20
    /* 4F69A4 80356594 3C01803B */  lui        $at, %hi(IsAxisYInverted)
    /* 4F69A8 80356598 10000003 */  b          .L803565A8_4F69B8
    /* 4F69AC 8035659C A023E521 */   sb        $v1, %lo(IsAxisYInverted)($at)
  .L803565A0_4F69B0:
    /* 4F69B0 803565A0 3C01803B */  lui        $at, %hi(IsAxisYInverted)
    /* 4F69B4 803565A4 A020E521 */  sb         $zero, %lo(IsAxisYInverted)($at)
  .L803565A8_4F69B8:
    /* 4F69B8 803565A8 11600004 */  beqz       $t3, .L803565BC_4F69CC
    /* 4F69BC 803565AC 304C0100 */   andi      $t4, $v0, 0x100
    /* 4F69C0 803565B0 3C01803B */  lui        $at, %hi(IsDashEngineAvailable)
    /* 4F69C4 803565B4 10000003 */  b          .L803565C4_4F69D4
    /* 4F69C8 803565B8 A023E522 */   sb        $v1, %lo(IsDashEngineAvailable)($at)
  .L803565BC_4F69CC:
    /* 4F69CC 803565BC 3C01803B */  lui        $at, %hi(IsDashEngineAvailable)
    /* 4F69D0 803565C0 A020E522 */  sb         $zero, %lo(IsDashEngineAvailable)($at)
  .L803565C4_4F69D4:
    /* 4F69D4 803565C4 11800004 */  beqz       $t4, .L803565D8_4F69E8
    /* 4F69D8 803565C8 24060001 */   addiu     $a2, $zero, 0x1
    /* 4F69DC 803565CC 3C01803B */  lui        $at, %hi(IsTutorialEnabled)
    /* 4F69E0 803565D0 10000003 */  b          .L803565E0_4F69F0
    /* 4F69E4 803565D4 A020E515 */   sb        $zero, %lo(IsTutorialEnabled)($at)
  .L803565D8_4F69E8:
    /* 4F69E8 803565D8 3C01803B */  lui        $at, %hi(IsTutorialEnabled)
    /* 4F69EC 803565DC A023E515 */  sb         $v1, %lo(IsTutorialEnabled)($at)
  .L803565E0_4F69F0:
    /* 4F69F0 803565E0 3C01803B */  lui        $at, %hi(ForceDashEngineDisabled)
    /* 4F69F4 803565E4 A020E514 */  sb         $zero, %lo(ForceDashEngineDisabled)($at)
    /* 4F69F8 803565E8 3C01803B */  lui        $at, %hi(D_803AE516_54E926)
    /* 4F69FC 803565EC A020E516 */  sb         $zero, %lo(D_803AE516_54E926)($at)
    /* 4F6A00 803565F0 8FA40048 */  lw         $a0, 0x48($sp)
    /* 4F6A04 803565F4 0C00230A */  jal        omCreateProcess
    /* 4F6A08 803565F8 2407000B */   addiu     $a3, $zero, 0xB
    /* 4F6A0C 803565FC 3C058035 */  lui        $a1, %hi(func_80350AE8_4F0EF8)
    /* 4F6A10 80356600 24A50AE8 */  addiu      $a1, $a1, %lo(func_80350AE8_4F0EF8)
    /* 4F6A14 80356604 8FA40048 */  lw         $a0, 0x48($sp)
    /* 4F6A18 80356608 24060001 */  addiu      $a2, $zero, 0x1
    /* 4F6A1C 8035660C 0C00230A */  jal        omCreateProcess
    /* 4F6A20 80356610 24070009 */   addiu     $a3, $zero, 0x9
    /* 4F6A24 80356614 3C058035 */  lui        $a1, %hi(func_80350950_4F0D60)
    /* 4F6A28 80356618 24A50950 */  addiu      $a1, $a1, %lo(func_80350950_4F0D60)
    /* 4F6A2C 8035661C 8FA40048 */  lw         $a0, 0x48($sp)
    /* 4F6A30 80356620 24060001 */  addiu      $a2, $zero, 0x1
    /* 4F6A34 80356624 0C00230A */  jal        omCreateProcess
    /* 4F6A38 80356628 24070009 */   addiu     $a3, $zero, 0x9
    /* 4F6A3C 8035662C 3C058035 */  lui        $a1, %hi(func_803512FC_4F170C)
    /* 4F6A40 80356630 24A512FC */  addiu      $a1, $a1, %lo(func_803512FC_4F170C)
    /* 4F6A44 80356634 8FA40048 */  lw         $a0, 0x48($sp)
    /* 4F6A48 80356638 24060001 */  addiu      $a2, $zero, 0x1
    /* 4F6A4C 8035663C 0C00230A */  jal        omCreateProcess
    /* 4F6A50 80356640 24070009 */   addiu     $a3, $zero, 0x9
    /* 4F6A54 80356644 3C058035 */  lui        $a1, %hi(func_80351534_4F1944)
    /* 4F6A58 80356648 24A51534 */  addiu      $a1, $a1, %lo(func_80351534_4F1944)
    /* 4F6A5C 8035664C AFA5003C */  sw         $a1, 0x3C($sp)
    /* 4F6A60 80356650 8FA40048 */  lw         $a0, 0x48($sp)
    /* 4F6A64 80356654 24060001 */  addiu      $a2, $zero, 0x1
    /* 4F6A68 80356658 0C00230A */  jal        omCreateProcess
    /* 4F6A6C 8035665C 24070009 */   addiu     $a3, $zero, 0x9
    /* 4F6A70 80356660 8FA5003C */  lw         $a1, 0x3C($sp)
    /* 4F6A74 80356664 0C002F77 */  jal        ohPauseProcessByFunction
    /* 4F6A78 80356668 8FA40048 */   lw        $a0, 0x48($sp)
    /* 4F6A7C 8035666C 3C058035 */  lui        $a1, %hi(func_80351768_4F1B78)
    /* 4F6A80 80356670 24A51768 */  addiu      $a1, $a1, %lo(func_80351768_4F1B78)
    /* 4F6A84 80356674 8FA40048 */  lw         $a0, 0x48($sp)
    /* 4F6A88 80356678 24060001 */  addiu      $a2, $zero, 0x1
    /* 4F6A8C 8035667C 0C00230A */  jal        omCreateProcess
    /* 4F6A90 80356680 24070009 */   addiu     $a3, $zero, 0x9
    /* 4F6A94 80356684 3C058035 */  lui        $a1, %hi(func_803507EC_4F0BFC)
    /* 4F6A98 80356688 24A507EC */  addiu      $a1, $a1, %lo(func_803507EC_4F0BFC)
    /* 4F6A9C 8035668C 8FA40048 */  lw         $a0, 0x48($sp)
    /* 4F6AA0 80356690 00003025 */  or         $a2, $zero, $zero
    /* 4F6AA4 80356694 0C00230A */  jal        omCreateProcess
    /* 4F6AA8 80356698 24070009 */   addiu     $a3, $zero, 0x9
    /* 4F6AAC 8035669C 3C013F00 */  lui        $at, (0x3F000000 >> 16)
    /* 4F6AB0 803566A0 44802000 */  mtc1       $zero, $f4
    /* 4F6AB4 803566A4 44813000 */  mtc1       $at, $f6
    /* 4F6AB8 803566A8 3C048036 */  lui        $a0, %hi(gMovementState)
    /* 4F6ABC 803566AC 24846BA4 */  addiu      $a0, $a0, %lo(gMovementState)
    /* 4F6AC0 803566B0 3C018039 */  lui        $at, %hi(D_8038A2CC_52A6DC)
    /* 4F6AC4 803566B4 E4840000 */  swc1       $f4, 0x0($a0)
    /* 4F6AC8 803566B8 E4860004 */  swc1       $f6, 0x4($a0)
    /* 4F6ACC 803566BC C428A2CC */  lwc1       $f8, %lo(D_8038A2CC_52A6DC)($at)
    /* 4F6AD0 803566C0 00002825 */  or         $a1, $zero, $zero
    /* 4F6AD4 803566C4 8FA60050 */  lw         $a2, 0x50($sp)
    /* 4F6AD8 803566C8 8FA70054 */  lw         $a3, 0x54($sp)
    /* 4F6ADC 803566CC 0C038FBA */  jal        func_800E3EE8_61698
    /* 4F6AE0 803566D0 E4880028 */   swc1      $f8, 0x28($a0)
    /* 4F6AE4 803566D4 0C0D45DA */  jal        func_80351768_4F1B78
    /* 4F6AE8 803566D8 8FA40048 */   lw        $a0, 0x48($sp)
    /* 4F6AEC 803566DC 8FA80044 */  lw         $t0, 0x44($sp)
    /* 4F6AF0 803566E0 3C028036 */  lui        $v0, %hi(gMovementState)
    /* 4F6AF4 803566E4 24426BA4 */  addiu      $v0, $v0, %lo(gMovementState)
    /* 4F6AF8 803566E8 C44A000C */  lwc1       $f10, 0xC($v0)
    /* 4F6AFC 803566EC 8D0D004C */  lw         $t5, 0x4C($t0)
    /* 4F6B00 803566F0 3C038038 */  lui        $v1, %hi(gObjPlayer)
    /* 4F6B04 803566F4 24632C00 */  addiu      $v1, $v1, %lo(gObjPlayer)
    /* 4F6B08 803566F8 E5AA0008 */  swc1       $f10, 0x8($t5)
    /* 4F6B0C 803566FC C4500010 */  lwc1       $f16, 0x10($v0)
    /* 4F6B10 80356700 8D0E004C */  lw         $t6, 0x4C($t0)
    /* 4F6B14 80356704 3C018038 */  lui        $at, %hi(gPlayerDObj)
    /* 4F6B18 80356708 3C0D8038 */  lui        $t5, %hi(D_80382C94_5230A4)
    /* 4F6B1C 8035670C E5D0000C */  swc1       $f16, 0xC($t6)
    /* 4F6B20 80356710 C4520014 */  lwc1       $f18, 0x14($v0)
    /* 4F6B24 80356714 8D0F004C */  lw         $t7, 0x4C($t0)
    /* 4F6B28 80356718 25AD2C94 */  addiu      $t5, $t5, %lo(D_80382C94_5230A4)
    /* 4F6B2C 8035671C 3C098001 */  lui        $t1, %hi(renDrawSprite)
    /* 4F6B30 80356720 E5F20010 */  swc1       $f18, 0x10($t7)
    /* 4F6B34 80356724 C4440018 */  lwc1       $f4, 0x18($v0)
    /* 4F6B38 80356728 8D18004C */  lw         $t8, 0x4C($t0)
    /* 4F6B3C 8035672C 3C078000 */  lui        $a3, (0x80000000 >> 16)
    /* 4F6B40 80356730 25297768 */  addiu      $t1, $t1, %lo(renDrawSprite)
    /* 4F6B44 80356734 E704001C */  swc1       $f4, 0x1C($t8)
    /* 4F6B48 80356738 C4460018 */  lwc1       $f6, 0x18($v0)
    /* 4F6B4C 8035673C 8D19004C */  lw         $t9, 0x4C($t0)
    /* 4F6B50 80356740 3C058035 */  lui        $a1, %hi(func_80356124_4F6534)
    /* 4F6B54 80356744 240C0001 */  addiu      $t4, $zero, 0x1
    /* 4F6B58 80356748 E7260020 */  swc1       $f6, 0x20($t9)
    /* 4F6B5C 8035674C C4480020 */  lwc1       $f8, 0x20($v0)
    /* 4F6B60 80356750 8D0A004C */  lw         $t2, 0x4C($t0)
    /* 4F6B64 80356754 24190001 */  addiu      $t9, $zero, 0x1
    /* 4F6B68 80356758 24A56124 */  addiu      $a1, $a1, %lo(func_80356124_4F6534)
    /* 4F6B6C 8035675C E5480024 */  swc1       $f8, 0x24($t2)
    /* 4F6B70 80356760 8FAB0048 */  lw         $t3, 0x48($sp)
    /* 4F6B74 80356764 240AFFFF */  addiu      $t2, $zero, -0x1
    /* 4F6B78 80356768 24040019 */  addiu      $a0, $zero, 0x19
    /* 4F6B7C 8035676C AC6B0000 */  sw         $t3, 0x0($v1)
    /* 4F6B80 80356770 AC282C04 */  sw         $t0, %lo(gPlayerDObj)($at)
    /* 4F6B84 80356774 3C018039 */  lui        $at, %hi(D_8038A2D0_52A6E0)
    /* 4F6B88 80356778 C42AA2D0 */  lwc1       $f10, %lo(D_8038A2D0_52A6E0)($at)
    /* 4F6B8C 8035677C 3C018038 */  lui        $at, %hi(D_80382C44_523054)
    /* 4F6B90 80356780 AFAB004C */  sw         $t3, 0x4C($sp)
    /* 4F6B94 80356784 E42A2C44 */  swc1       $f10, %lo(D_80382C44_523054)($at)
    /* 4F6B98 80356788 8D0E004C */  lw         $t6, 0x4C($t0)
    /* 4F6B9C 8035678C 3C0B8036 */  lui        $t3, %hi(D_80366DF0_507200)
    /* 4F6BA0 80356790 256B6DF0 */  addiu      $t3, $t3, %lo(D_80366DF0_507200)
    /* 4F6BA4 80356794 8DD80008 */  lw         $t8, 0x8($t6)
    /* 4F6BA8 80356798 00003025 */  or         $a2, $zero, $zero
    /* 4F6BAC 8035679C ADB80000 */  sw         $t8, 0x0($t5)
    /* 4F6BB0 803567A0 8DCF000C */  lw         $t7, 0xC($t6)
    /* 4F6BB4 803567A4 ADAF0004 */  sw         $t7, 0x4($t5)
    /* 4F6BB8 803567A8 8DD80010 */  lw         $t8, 0x10($t6)
    /* 4F6BBC 803567AC 240E0009 */  addiu      $t6, $zero, 0x9
    /* 4F6BC0 803567B0 ADB80008 */  sw         $t8, 0x8($t5)
    /* 4F6BC4 803567B4 3C0D8035 */  lui        $t5, %hi(func_80355F18_4F6328)
    /* 4F6BC8 803567B8 25AD5F18 */  addiu      $t5, $t5, %lo(func_80355F18_4F6328)
    /* 4F6BCC 803567BC AFAD0028 */  sw         $t5, 0x28($sp)
    /* 4F6BD0 803567C0 AFA9003C */  sw         $t1, 0x3C($sp)
    /* 4F6BD4 803567C4 AFAE002C */  sw         $t6, 0x2C($sp)
    /* 4F6BD8 803567C8 AFAC0024 */  sw         $t4, 0x24($sp)
    /* 4F6BDC 803567CC AFAB0020 */  sw         $t3, 0x20($sp)
    /* 4F6BE0 803567D0 AFAA001C */  sw         $t2, 0x1C($sp)
    /* 4F6BE4 803567D4 AFA70018 */  sw         $a3, 0x18($sp)
    /* 4F6BE8 803567D8 AFB90014 */  sw         $t9, 0x14($sp)
    /* 4F6BEC 803567DC 0C0030DF */  jal        ohCreateSprite
    /* 4F6BF0 803567E0 AFA90010 */   sw        $t1, 0x10($sp)
    /* 4F6BF4 803567E4 3C018038 */  lui        $at, %hi(D_80382C38_523048)
    /* 4F6BF8 803567E8 AFA20048 */  sw         $v0, 0x48($sp)
    /* 4F6BFC 803567EC AC222C38 */  sw         $v0, %lo(D_80382C38_523048)($at)
    /* 4F6C00 803567F0 8C4F0048 */  lw         $t7, 0x48($v0)
    /* 4F6C04 803567F4 3C01803B */  lui        $at, %hi(MainCameraReticles)
    /* 4F6C08 803567F8 3C058036 */  lui        $a1, %hi(D_80367580_507990)
    /* 4F6C0C 803567FC 24A57580 */  addiu      $a1, $a1, %lo(D_80367580_507990)
    /* 4F6C10 80356800 00402025 */  or         $a0, $v0, $zero
    /* 4F6C14 80356804 0C00282D */  jal        omGObjAddSprite
    /* 4F6C18 80356808 AC2FE440 */   sw        $t7, %lo(MainCameraReticles)($at)
    /* 4F6C1C 8035680C 3C01803B */  lui        $at, %hi(D_803AE444_54E854)
    /* 4F6C20 80356810 AC22E444 */  sw         $v0, %lo(D_803AE444_54E854)($at)
    /* 4F6C24 80356814 AFA20040 */  sw         $v0, 0x40($sp)
    /* 4F6C28 80356818 24440010 */  addiu      $a0, $v0, 0x10
    /* 4F6C2C 8035681C 2405008F */  addiu      $a1, $zero, 0x8F
    /* 4F6C30 80356820 0C009862 */  jal        spX2Move
    /* 4F6C34 80356824 24060067 */   addiu     $a2, $zero, 0x67
    /* 4F6C38 80356828 8FA40040 */  lw         $a0, 0x40($sp)
    /* 4F6C3C 8035682C 24050004 */  addiu      $a1, $zero, 0x4
    /* 4F6C40 80356830 24840010 */  addiu      $a0, $a0, 0x10
    /* 4F6C44 80356834 0C00985C */  jal        spSetAttribute
    /* 4F6C48 80356838 AFA40038 */   sw        $a0, 0x38($sp)
    /* 4F6C4C 8035683C 2418007F */  addiu      $t8, $zero, 0x7F
    /* 4F6C50 80356840 8FA40038 */  lw         $a0, 0x38($sp)
    /* 4F6C54 80356844 AFB80010 */  sw         $t8, 0x10($sp)
    /* 4F6C58 80356848 240500FF */  addiu      $a1, $zero, 0xFF
    /* 4F6C5C 8035684C 240600FF */  addiu      $a2, $zero, 0xFF
    /* 4F6C60 80356850 0C009850 */  jal        spColor
    /* 4F6C64 80356854 240700FF */   addiu     $a3, $zero, 0xFF
    /* 4F6C68 80356858 3C058036 */  lui        $a1, %hi(D_80367D10_508120)
    /* 4F6C6C 8035685C 24A57D10 */  addiu      $a1, $a1, %lo(D_80367D10_508120)
    /* 4F6C70 80356860 0C00282D */  jal        omGObjAddSprite
    /* 4F6C74 80356864 8FA40048 */   lw        $a0, 0x48($sp)
    /* 4F6C78 80356868 3C01803B */  lui        $at, %hi(D_803AE448_54E858)
    /* 4F6C7C 8035686C AC22E448 */  sw         $v0, %lo(D_803AE448_54E858)($at)
    /* 4F6C80 80356870 AFA20040 */  sw         $v0, 0x40($sp)
    /* 4F6C84 80356874 24440010 */  addiu      $a0, $v0, 0x10
    /* 4F6C88 80356878 2405008F */  addiu      $a1, $zero, 0x8F
    /* 4F6C8C 8035687C 0C009862 */  jal        spX2Move
    /* 4F6C90 80356880 24060067 */   addiu     $a2, $zero, 0x67
    /* 4F6C94 80356884 8FA40040 */  lw         $a0, 0x40($sp)
    /* 4F6C98 80356888 24050004 */  addiu      $a1, $zero, 0x4
    /* 4F6C9C 8035688C 24840010 */  addiu      $a0, $a0, 0x10
    /* 4F6CA0 80356890 0C00985C */  jal        spSetAttribute
    /* 4F6CA4 80356894 AFA40038 */   sw        $a0, 0x38($sp)
    /* 4F6CA8 80356898 2419007F */  addiu      $t9, $zero, 0x7F
    /* 4F6CAC 8035689C 8FA40038 */  lw         $a0, 0x38($sp)
    /* 4F6CB0 803568A0 AFB90010 */  sw         $t9, 0x10($sp)
    /* 4F6CB4 803568A4 240500FF */  addiu      $a1, $zero, 0xFF
    /* 4F6CB8 803568A8 240600FF */  addiu      $a2, $zero, 0xFF
    /* 4F6CBC 803568AC 0C009850 */  jal        spColor
    /* 4F6CC0 803568B0 240700FF */   addiu     $a3, $zero, 0xFF
    /* 4F6CC4 803568B4 3C058036 */  lui        $a1, %hi(D_80367DC0_5081D0)
    /* 4F6CC8 803568B8 24A57DC0 */  addiu      $a1, $a1, %lo(D_80367DC0_5081D0)
    /* 4F6CCC 803568BC 0C00282D */  jal        omGObjAddSprite
    /* 4F6CD0 803568C0 8FA40048 */   lw        $a0, 0x48($sp)
    /* 4F6CD4 803568C4 3C01803B */  lui        $at, %hi(D_803AE44C_54E85C)
    /* 4F6CD8 803568C8 AC22E44C */  sw         $v0, %lo(D_803AE44C_54E85C)($at)
    /* 4F6CDC 803568CC AFA20040 */  sw         $v0, 0x40($sp)
    /* 4F6CE0 803568D0 24440010 */  addiu      $a0, $v0, 0x10
    /* 4F6CE4 803568D4 0C00985C */  jal        spSetAttribute
    /* 4F6CE8 803568D8 24050004 */   addiu     $a1, $zero, 0x4
    /* 4F6CEC 803568DC 8FA40040 */  lw         $a0, 0x40($sp)
    /* 4F6CF0 803568E0 2405009D */  addiu      $a1, $zero, 0x9D
    /* 4F6CF4 803568E4 24060075 */  addiu      $a2, $zero, 0x75
    /* 4F6CF8 803568E8 0C009862 */  jal        spX2Move
    /* 4F6CFC 803568EC 24840010 */   addiu     $a0, $a0, 0x10
    /* 4F6D00 803568F0 3C058037 */  lui        $a1, %hi(D_80368038_508448)
    /* 4F6D04 803568F4 24A58038 */  addiu      $a1, $a1, %lo(D_80368038_508448)
    /* 4F6D08 803568F8 0C00282D */  jal        omGObjAddSprite
    /* 4F6D0C 803568FC 8FA40048 */   lw        $a0, 0x48($sp)
    /* 4F6D10 80356900 3C01803B */  lui        $at, %hi(D_803AE458_54E868)
    /* 4F6D14 80356904 AC22E458 */  sw         $v0, %lo(D_803AE458_54E868)($at)
    /* 4F6D18 80356908 AFA20040 */  sw         $v0, 0x40($sp)
    /* 4F6D1C 8035690C 24440010 */  addiu      $a0, $v0, 0x10
    /* 4F6D20 80356910 0C00985C */  jal        spSetAttribute
    /* 4F6D24 80356914 24050004 */   addiu     $a1, $zero, 0x4
    /* 4F6D28 80356918 8FA40040 */  lw         $a0, 0x40($sp)
    /* 4F6D2C 8035691C 240A007F */  addiu      $t2, $zero, 0x7F
    /* 4F6D30 80356920 AFAA0010 */  sw         $t2, 0x10($sp)
    /* 4F6D34 80356924 24840010 */  addiu      $a0, $a0, 0x10
    /* 4F6D38 80356928 AFA40038 */  sw         $a0, 0x38($sp)
    /* 4F6D3C 8035692C 240500FF */  addiu      $a1, $zero, 0xFF
    /* 4F6D40 80356930 240600FF */  addiu      $a2, $zero, 0xFF
    /* 4F6D44 80356934 0C009850 */  jal        spColor
    /* 4F6D48 80356938 240700FF */   addiu     $a3, $zero, 0xFF
    /* 4F6D4C 8035693C 8FA40038 */  lw         $a0, 0x38($sp)
    /* 4F6D50 80356940 2405004E */  addiu      $a1, $zero, 0x4E
    /* 4F6D54 80356944 0C009862 */  jal        spX2Move
    /* 4F6D58 80356948 2406003A */   addiu     $a2, $zero, 0x3A
    /* 4F6D5C 8035694C 8FA40038 */  lw         $a0, 0x38($sp)
    /* 4F6D60 80356950 3C0542A4 */  lui        $a1, (0x42A40000 >> 16)
    /* 4F6D64 80356954 0C00A214 */  jal        spScale
    /* 4F6D68 80356958 3C063F80 */   lui       $a2, (0x3F800000 >> 16)
    /* 4F6D6C 8035695C 3C058037 */  lui        $a1, %hi(D_80368038_508448)
    /* 4F6D70 80356960 24A58038 */  addiu      $a1, $a1, %lo(D_80368038_508448)
    /* 4F6D74 80356964 0C00282D */  jal        omGObjAddSprite
    /* 4F6D78 80356968 8FA40048 */   lw        $a0, 0x48($sp)
    /* 4F6D7C 8035696C 3C01803B */  lui        $at, %hi(D_803AE45C_54E86C)
    /* 4F6D80 80356970 AC22E45C */  sw         $v0, %lo(D_803AE45C_54E86C)($at)
    /* 4F6D84 80356974 AFA20040 */  sw         $v0, 0x40($sp)
    /* 4F6D88 80356978 24440010 */  addiu      $a0, $v0, 0x10
    /* 4F6D8C 8035697C 0C00985C */  jal        spSetAttribute
    /* 4F6D90 80356980 24050004 */   addiu     $a1, $zero, 0x4
    /* 4F6D94 80356984 8FA40040 */  lw         $a0, 0x40($sp)
    /* 4F6D98 80356988 240B007F */  addiu      $t3, $zero, 0x7F
    /* 4F6D9C 8035698C AFAB0010 */  sw         $t3, 0x10($sp)
    /* 4F6DA0 80356990 24840010 */  addiu      $a0, $a0, 0x10
    /* 4F6DA4 80356994 AFA40038 */  sw         $a0, 0x38($sp)
    /* 4F6DA8 80356998 240500FF */  addiu      $a1, $zero, 0xFF
    /* 4F6DAC 8035699C 240600FF */  addiu      $a2, $zero, 0xFF
    /* 4F6DB0 803569A0 0C009850 */  jal        spColor
    /* 4F6DB4 803569A4 240700FF */   addiu     $a3, $zero, 0xFF
    /* 4F6DB8 803569A8 8FA40038 */  lw         $a0, 0x38($sp)
    /* 4F6DBC 803569AC 2405004E */  addiu      $a1, $zero, 0x4E
    /* 4F6DC0 803569B0 0C009862 */  jal        spX2Move
    /* 4F6DC4 803569B4 240600B4 */   addiu     $a2, $zero, 0xB4
    /* 4F6DC8 803569B8 8FA40038 */  lw         $a0, 0x38($sp)
    /* 4F6DCC 803569BC 3C0542A4 */  lui        $a1, (0x42A40000 >> 16)
    /* 4F6DD0 803569C0 0C00A214 */  jal        spScale
    /* 4F6DD4 803569C4 3C063F80 */   lui       $a2, (0x3F800000 >> 16)
    /* 4F6DD8 803569C8 3C058037 */  lui        $a1, %hi(D_80368038_508448)
    /* 4F6DDC 803569CC 24A58038 */  addiu      $a1, $a1, %lo(D_80368038_508448)
    /* 4F6DE0 803569D0 0C00282D */  jal        omGObjAddSprite
    /* 4F6DE4 803569D4 8FA40048 */   lw        $a0, 0x48($sp)
    /* 4F6DE8 803569D8 3C01803B */  lui        $at, %hi(D_803AE460_54E870)
    /* 4F6DEC 803569DC AC22E460 */  sw         $v0, %lo(D_803AE460_54E870)($at)
    /* 4F6DF0 803569E0 AFA20040 */  sw         $v0, 0x40($sp)
    /* 4F6DF4 803569E4 24440010 */  addiu      $a0, $v0, 0x10
    /* 4F6DF8 803569E8 0C00985C */  jal        spSetAttribute
    /* 4F6DFC 803569EC 24050004 */   addiu     $a1, $zero, 0x4
    /* 4F6E00 803569F0 8FA40040 */  lw         $a0, 0x40($sp)
    /* 4F6E04 803569F4 240C007F */  addiu      $t4, $zero, 0x7F
    /* 4F6E08 803569F8 AFAC0010 */  sw         $t4, 0x10($sp)
    /* 4F6E0C 803569FC 24840010 */  addiu      $a0, $a0, 0x10
    /* 4F6E10 80356A00 AFA40038 */  sw         $a0, 0x38($sp)
    /* 4F6E14 80356A04 240500FF */  addiu      $a1, $zero, 0xFF
    /* 4F6E18 80356A08 240600FF */  addiu      $a2, $zero, 0xFF
    /* 4F6E1C 80356A0C 0C009850 */  jal        spColor
    /* 4F6E20 80356A10 240700FF */   addiu     $a3, $zero, 0xFF
    /* 4F6E24 80356A14 8FA40038 */  lw         $a0, 0x38($sp)
    /* 4F6E28 80356A18 2405004E */  addiu      $a1, $zero, 0x4E
    /* 4F6E2C 80356A1C 0C009862 */  jal        spX2Move
    /* 4F6E30 80356A20 2406003C */   addiu     $a2, $zero, 0x3C
    /* 4F6E34 80356A24 8FA40038 */  lw         $a0, 0x38($sp)
    /* 4F6E38 80356A28 3C053F80 */  lui        $a1, (0x3F800000 >> 16)
    /* 4F6E3C 80356A2C 0C00A214 */  jal        spScale
    /* 4F6E40 80356A30 3C064270 */   lui       $a2, (0x42700000 >> 16)
    /* 4F6E44 80356A34 3C058037 */  lui        $a1, %hi(D_80368038_508448)
    /* 4F6E48 80356A38 24A58038 */  addiu      $a1, $a1, %lo(D_80368038_508448)
    /* 4F6E4C 80356A3C 0C00282D */  jal        omGObjAddSprite
    /* 4F6E50 80356A40 8FA40048 */   lw        $a0, 0x48($sp)
    /* 4F6E54 80356A44 3C01803B */  lui        $at, %hi(D_803AE464_54E874)
    /* 4F6E58 80356A48 AC22E464 */  sw         $v0, %lo(D_803AE464_54E874)($at)
    /* 4F6E5C 80356A4C AFA20040 */  sw         $v0, 0x40($sp)
    /* 4F6E60 80356A50 24440010 */  addiu      $a0, $v0, 0x10
    /* 4F6E64 80356A54 0C00985C */  jal        spSetAttribute
    /* 4F6E68 80356A58 24050004 */   addiu     $a1, $zero, 0x4
    /* 4F6E6C 80356A5C 8FA40040 */  lw         $a0, 0x40($sp)
    /* 4F6E70 80356A60 240D007F */  addiu      $t5, $zero, 0x7F
    /* 4F6E74 80356A64 AFAD0010 */  sw         $t5, 0x10($sp)
    /* 4F6E78 80356A68 24840010 */  addiu      $a0, $a0, 0x10
    /* 4F6E7C 80356A6C AFA40038 */  sw         $a0, 0x38($sp)
    /* 4F6E80 80356A70 240500FF */  addiu      $a1, $zero, 0xFF
    /* 4F6E84 80356A74 240600FF */  addiu      $a2, $zero, 0xFF
    /* 4F6E88 80356A78 0C009850 */  jal        spColor
    /* 4F6E8C 80356A7C 240700FF */   addiu     $a3, $zero, 0xFF
    /* 4F6E90 80356A80 8FA40038 */  lw         $a0, 0x38($sp)
    /* 4F6E94 80356A84 240500F0 */  addiu      $a1, $zero, 0xF0
    /* 4F6E98 80356A88 0C009862 */  jal        spX2Move
    /* 4F6E9C 80356A8C 2406003C */   addiu     $a2, $zero, 0x3C
    /* 4F6EA0 80356A90 8FA40038 */  lw         $a0, 0x38($sp)
    /* 4F6EA4 80356A94 3C053F80 */  lui        $a1, (0x3F800000 >> 16)
    /* 4F6EA8 80356A98 0C00A214 */  jal        spScale
    /* 4F6EAC 80356A9C 3C064270 */   lui       $a2, (0x42700000 >> 16)
    /* 4F6EB0 80356AA0 3C058037 */  lui        $a1, %hi(D_803706E0_510AF0)
    /* 4F6EB4 80356AA4 24A506E0 */  addiu      $a1, $a1, %lo(D_803706E0_510AF0)
    /* 4F6EB8 80356AA8 0C00282D */  jal        omGObjAddSprite
    /* 4F6EBC 80356AAC 8FA40048 */   lw        $a0, 0x48($sp)
    /* 4F6EC0 80356AB0 3C01803B */  lui        $at, %hi(D_803AE468_54E878)
    /* 4F6EC4 80356AB4 AC22E468 */  sw         $v0, %lo(D_803AE468_54E878)($at)
    /* 4F6EC8 80356AB8 AFA20040 */  sw         $v0, 0x40($sp)
    /* 4F6ECC 80356ABC 24440010 */  addiu      $a0, $v0, 0x10
    /* 4F6ED0 80356AC0 0C00985C */  jal        spSetAttribute
    /* 4F6ED4 80356AC4 24050004 */   addiu     $a1, $zero, 0x4
    /* 4F6ED8 80356AC8 8FA40040 */  lw         $a0, 0x40($sp)
    /* 4F6EDC 80356ACC 00002825 */  or         $a1, $zero, $zero
    /* 4F6EE0 80356AD0 00003025 */  or         $a2, $zero, $zero
    /* 4F6EE4 80356AD4 0C009862 */  jal        spX2Move
    /* 4F6EE8 80356AD8 24840010 */   addiu     $a0, $a0, 0x10
    /* 4F6EEC 80356ADC 3C058038 */  lui        $a1, %hi(D_80378D88_519198)
    /* 4F6EF0 80356AE0 24A58D88 */  addiu      $a1, $a1, %lo(D_80378D88_519198)
    /* 4F6EF4 80356AE4 0C00282D */  jal        omGObjAddSprite
    /* 4F6EF8 80356AE8 8FA40048 */   lw        $a0, 0x48($sp)
    /* 4F6EFC 80356AEC 3C01803B */  lui        $at, %hi(D_803AE46C_54E87C)
    /* 4F6F00 80356AF0 AC22E46C */  sw         $v0, %lo(D_803AE46C_54E87C)($at)
    /* 4F6F04 80356AF4 AFA20040 */  sw         $v0, 0x40($sp)
    /* 4F6F08 80356AF8 24440010 */  addiu      $a0, $v0, 0x10
    /* 4F6F0C 80356AFC 0C00985C */  jal        spSetAttribute
    /* 4F6F10 80356B00 24050004 */   addiu     $a1, $zero, 0x4
    /* 4F6F14 80356B04 8FA40040 */  lw         $a0, 0x40($sp)
    /* 4F6F18 80356B08 00002825 */  or         $a1, $zero, $zero
    /* 4F6F1C 80356B0C 240600BB */  addiu      $a2, $zero, 0xBB
    /* 4F6F20 80356B10 0C009862 */  jal        spX2Move
    /* 4F6F24 80356B14 24840010 */   addiu     $a0, $a0, 0x10
    /* 4F6F28 80356B18 0C0D65F5 */  jal        func_803597D4_4F9BE4
    /* 4F6F2C 80356B1C 00000000 */   nop
    /* 4F6F30 80356B20 8FA40058 */  lw         $a0, 0x58($sp)
    /* 4F6F34 80356B24 93A5005F */  lbu        $a1, 0x5F($sp)
    /* 4F6F38 80356B28 0C0D7273 */  jal        func_8035C9CC_4FCDDC
    /* 4F6F3C 80356B2C 8FA60060 */   lw        $a2, 0x60($sp)
    /* 4F6F40 80356B30 0C0D7468 */  jal        func_8035D1A0_4FD5B0
    /* 4F6F44 80356B34 00000000 */   nop
    /* 4F6F48 80356B38 0C0D78DF */  jal        func_8035E37C_4FE78C
    /* 4F6F4C 80356B3C 00000000 */   nop
    /* 4F6F50 80356B40 0C0D6235 */  jal        func_803588D4_4F8CE4
    /* 4F6F54 80356B44 00000000 */   nop
    /* 4F6F58 80356B48 3C01425C */  lui        $at, (0x425C0000 >> 16)
    /* 4F6F5C 80356B4C 44818000 */  mtc1       $at, $f16
    /* 4F6F60 80356B50 3C0E8038 */  lui        $t6, %hi(gMainCamera)
    /* 4F6F64 80356B54 8DCE2C30 */  lw         $t6, %lo(gMainCamera)($t6)
    /* 4F6F68 80356B58 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 4F6F6C 80356B5C 44819000 */  mtc1       $at, $f18
    /* 4F6F70 80356B60 3C01803B */  lui        $at, %hi(D_803AE478_54E888)
    /* 4F6F74 80356B64 E5D00020 */  swc1       $f16, 0x20($t6)
    /* 4F6F78 80356B68 44802000 */  mtc1       $zero, $f4
    /* 4F6F7C 80356B6C E432E478 */  swc1       $f18, %lo(D_803AE478_54E888)($at)
    /* 4F6F80 80356B70 3C01803B */  lui        $at, %hi(D_803AE47C_54E88C)
    /* 4F6F84 80356B74 3C058001 */  lui        $a1, %hi(ohUpdateDefault)
    /* 4F6F88 80356B78 24A5BC84 */  addiu      $a1, $a1, %lo(ohUpdateDefault)
    /* 4F6F8C 80356B7C 2404001A */  addiu      $a0, $zero, 0x1A
    /* 4F6F90 80356B80 00003025 */  or         $a2, $zero, $zero
    /* 4F6F94 80356B84 3C078000 */  lui        $a3, (0x80000000 >> 16)
    /* 4F6F98 80356B88 0C002904 */  jal        omAddGObj
    /* 4F6F9C 80356B8C E424E47C */   swc1      $f4, %lo(D_803AE47C_54E88C)($at)
    /* 4F6FA0 80356B90 240FFFFF */  addiu      $t7, $zero, -0x1
    /* 4F6FA4 80356B94 AFA20048 */  sw         $v0, 0x48($sp)
    /* 4F6FA8 80356B98 AFAF0010 */  sw         $t7, 0x10($sp)
    /* 4F6FAC 80356B9C 00402025 */  or         $a0, $v0, $zero
    /* 4F6FB0 80356BA0 8FA5003C */  lw         $a1, 0x3C($sp)
    /* 4F6FB4 80356BA4 24060001 */  addiu      $a2, $zero, 0x1
    /* 4F6FB8 80356BA8 0C002A29 */  jal        omLinkGObjDL
    /* 4F6FBC 80356BAC 3C078000 */   lui       $a3, (0x80000000 >> 16)
    /* 4F6FC0 80356BB0 8FA40048 */  lw         $a0, 0x48($sp)
    /* 4F6FC4 80356BB4 3C018038 */  lui        $at, %hi(ObjectPauseMenu)
    /* 4F6FC8 80356BB8 3C058038 */  lui        $a1, %hi(D_80378ED8_5192E8)
    /* 4F6FCC 80356BBC 24A58ED8 */  addiu      $a1, $a1, %lo(D_80378ED8_5192E8)
    /* 4F6FD0 80356BC0 0C00282D */  jal        omGObjAddSprite
    /* 4F6FD4 80356BC4 AC242C6C */   sw        $a0, %lo(ObjectPauseMenu)($at)
    /* 4F6FD8 80356BC8 3C018038 */  lui        $at, %hi(D_80382C70_523080)
    /* 4F6FDC 80356BCC AC222C70 */  sw         $v0, %lo(D_80382C70_523080)($at)
    /* 4F6FE0 80356BD0 AFA20040 */  sw         $v0, 0x40($sp)
    /* 4F6FE4 80356BD4 24440010 */  addiu      $a0, $v0, 0x10
    /* 4F6FE8 80356BD8 00002825 */  or         $a1, $zero, $zero
    /* 4F6FEC 80356BDC 0C009862 */  jal        spX2Move
    /* 4F6FF0 80356BE0 00003025 */   or        $a2, $zero, $zero
    /* 4F6FF4 80356BE4 8FA40040 */  lw         $a0, 0x40($sp)
    /* 4F6FF8 80356BE8 24050004 */  addiu      $a1, $zero, 0x4
    /* 4F6FFC 80356BEC 0C00985C */  jal        spSetAttribute
    /* 4F7000 80356BF0 24840010 */   addiu     $a0, $a0, 0x10
    /* 4F7004 80356BF4 3C014200 */  lui        $at, (0x42000000 >> 16)
    /* 4F7008 80356BF8 44813000 */  mtc1       $at, $f6
    /* 4F700C 80356BFC 8FA20040 */  lw         $v0, 0x40($sp)
    /* 4F7010 80356C00 3C0141C0 */  lui        $at, (0x41C00000 >> 16)
    /* 4F7014 80356C04 44814000 */  mtc1       $at, $f8
    /* 4F7018 80356C08 3C058038 */  lui        $a1, %hi(D_8037A9A0_51ADB0)
    /* 4F701C 80356C0C E4460018 */  swc1       $f6, 0x18($v0)
    /* 4F7020 80356C10 E448001C */  swc1       $f8, 0x1C($v0)
    /* 4F7024 80356C14 8FA40048 */  lw         $a0, 0x48($sp)
    /* 4F7028 80356C18 0C00282D */  jal        omGObjAddSprite
    /* 4F702C 80356C1C 24A5A9A0 */   addiu     $a1, $a1, %lo(D_8037A9A0_51ADB0)
    /* 4F7030 80356C20 3C018038 */  lui        $at, %hi(D_80382C74_523084)
    /* 4F7034 80356C24 AC222C74 */  sw         $v0, %lo(D_80382C74_523084)($at)
    /* 4F7038 80356C28 24440010 */  addiu      $a0, $v0, 0x10
    /* 4F703C 80356C2C 0C00985C */  jal        spSetAttribute
    /* 4F7040 80356C30 24050004 */   addiu     $a1, $zero, 0x4
    /* 4F7044 80356C34 3C058038 */  lui        $a1, %hi(D_8037C468_51C878)
    /* 4F7048 80356C38 24A5C468 */  addiu      $a1, $a1, %lo(D_8037C468_51C878)
    /* 4F704C 80356C3C 0C00282D */  jal        omGObjAddSprite
    /* 4F7050 80356C40 8FA40048 */   lw        $a0, 0x48($sp)
    /* 4F7054 80356C44 3C018038 */  lui        $at, %hi(D_80382C78_523088)
    /* 4F7058 80356C48 AC222C78 */  sw         $v0, %lo(D_80382C78_523088)($at)
    /* 4F705C 80356C4C 24440010 */  addiu      $a0, $v0, 0x10
    /* 4F7060 80356C50 0C00985C */  jal        spSetAttribute
    /* 4F7064 80356C54 24050004 */   addiu     $a1, $zero, 0x4
    /* 4F7068 80356C58 3C058038 */  lui        $a1, %hi(D_8037D2A0_51D6B0)
    /* 4F706C 80356C5C 24A5D2A0 */  addiu      $a1, $a1, %lo(D_8037D2A0_51D6B0)
    /* 4F7070 80356C60 0C00282D */  jal        omGObjAddSprite
    /* 4F7074 80356C64 8FA40048 */   lw        $a0, 0x48($sp)
    /* 4F7078 80356C68 3C018038 */  lui        $at, %hi(D_80382C7C_52308C)
    /* 4F707C 80356C6C AC222C7C */  sw         $v0, %lo(D_80382C7C_52308C)($at)
    /* 4F7080 80356C70 AFA20040 */  sw         $v0, 0x40($sp)
    /* 4F7084 80356C74 24440010 */  addiu      $a0, $v0, 0x10
    /* 4F7088 80356C78 0C00985C */  jal        spSetAttribute
    /* 4F708C 80356C7C 24050004 */   addiu     $a1, $zero, 0x4
    /* 4F7090 80356C80 8FA20040 */  lw         $v0, 0x40($sp)
    /* 4F7094 80356C84 24050074 */  addiu      $a1, $zero, 0x74
    /* 4F7098 80356C88 2406009C */  addiu      $a2, $zero, 0x9C
    /* 4F709C 80356C8C 0C009862 */  jal        spX2Move
    /* 4F70A0 80356C90 24440010 */   addiu     $a0, $v0, 0x10
    /* 4F70A4 80356C94 3C058038 */  lui        $a1, %hi(D_8037E0D8_51E4E8)
    /* 4F70A8 80356C98 24A5E0D8 */  addiu      $a1, $a1, %lo(D_8037E0D8_51E4E8)
    /* 4F70AC 80356C9C 0C00282D */  jal        omGObjAddSprite
    /* 4F70B0 80356CA0 8FA40048 */   lw        $a0, 0x48($sp)
    /* 4F70B4 80356CA4 3C018038 */  lui        $at, %hi(D_80382C80_523090)
    /* 4F70B8 80356CA8 AC222C80 */  sw         $v0, %lo(D_80382C80_523090)($at)
    /* 4F70BC 80356CAC AFA20040 */  sw         $v0, 0x40($sp)
    /* 4F70C0 80356CB0 24440010 */  addiu      $a0, $v0, 0x10
    /* 4F70C4 80356CB4 0C00985C */  jal        spSetAttribute
    /* 4F70C8 80356CB8 24050004 */   addiu     $a1, $zero, 0x4
    /* 4F70CC 80356CBC 8FA20040 */  lw         $v0, 0x40($sp)
    /* 4F70D0 80356CC0 24050074 */  addiu      $a1, $zero, 0x74
    /* 4F70D4 80356CC4 2406009C */  addiu      $a2, $zero, 0x9C
    /* 4F70D8 80356CC8 0C009862 */  jal        spX2Move
    /* 4F70DC 80356CCC 24440010 */   addiu     $a0, $v0, 0x10
    /* 4F70E0 80356CD0 3C058038 */  lui        $a1, %hi(D_8037EF10_51F320)
    /* 4F70E4 80356CD4 24A5EF10 */  addiu      $a1, $a1, %lo(D_8037EF10_51F320)
    /* 4F70E8 80356CD8 0C00282D */  jal        omGObjAddSprite
    /* 4F70EC 80356CDC 8FA40048 */   lw        $a0, 0x48($sp)
    /* 4F70F0 80356CE0 3C018038 */  lui        $at, %hi(D_80382C84_523094)
    /* 4F70F4 80356CE4 AC222C84 */  sw         $v0, %lo(D_80382C84_523094)($at)
    /* 4F70F8 80356CE8 AFA20040 */  sw         $v0, 0x40($sp)
    /* 4F70FC 80356CEC 24440010 */  addiu      $a0, $v0, 0x10
    /* 4F7100 80356CF0 0C00985C */  jal        spSetAttribute
    /* 4F7104 80356CF4 24050004 */   addiu     $a1, $zero, 0x4
    /* 4F7108 80356CF8 8FA20040 */  lw         $v0, 0x40($sp)
    /* 4F710C 80356CFC 24050074 */  addiu      $a1, $zero, 0x74
    /* 4F7110 80356D00 24060085 */  addiu      $a2, $zero, 0x85
    /* 4F7114 80356D04 0C009862 */  jal        spX2Move
    /* 4F7118 80356D08 24440010 */   addiu     $a0, $v0, 0x10
    /* 4F711C 80356D0C 3C058038 */  lui        $a1, %hi(D_8037FD48_520158)
    /* 4F7120 80356D10 24A5FD48 */  addiu      $a1, $a1, %lo(D_8037FD48_520158)
    /* 4F7124 80356D14 0C00282D */  jal        omGObjAddSprite
    /* 4F7128 80356D18 8FA40048 */   lw        $a0, 0x48($sp)
    /* 4F712C 80356D1C 3C018038 */  lui        $at, %hi(D_80382C88_523098)
    /* 4F7130 80356D20 AC222C88 */  sw         $v0, %lo(D_80382C88_523098)($at)
    /* 4F7134 80356D24 AFA20040 */  sw         $v0, 0x40($sp)
    /* 4F7138 80356D28 24440010 */  addiu      $a0, $v0, 0x10
    /* 4F713C 80356D2C 0C00985C */  jal        spSetAttribute
    /* 4F7140 80356D30 24050004 */   addiu     $a1, $zero, 0x4
    /* 4F7144 80356D34 8FA20040 */  lw         $v0, 0x40($sp)
    /* 4F7148 80356D38 24050074 */  addiu      $a1, $zero, 0x74
    /* 4F714C 80356D3C 24060085 */  addiu      $a2, $zero, 0x85
    /* 4F7150 80356D40 0C009862 */  jal        spX2Move
    /* 4F7154 80356D44 24440010 */   addiu     $a0, $v0, 0x10
    /* 4F7158 80356D48 3C058038 */  lui        $a1, %hi(D_80380B80_520F90)
    /* 4F715C 80356D4C 24A50B80 */  addiu      $a1, $a1, %lo(D_80380B80_520F90)
    /* 4F7160 80356D50 0C00282D */  jal        omGObjAddSprite
    /* 4F7164 80356D54 8FA40048 */   lw        $a0, 0x48($sp)
    /* 4F7168 80356D58 3C018038 */  lui        $at, %hi(D_80382C8C_52309C)
    /* 4F716C 80356D5C AC222C8C */  sw         $v0, %lo(D_80382C8C_52309C)($at)
    /* 4F7170 80356D60 AFA20040 */  sw         $v0, 0x40($sp)
    /* 4F7174 80356D64 24440010 */  addiu      $a0, $v0, 0x10
    /* 4F7178 80356D68 0C00985C */  jal        spSetAttribute
    /* 4F717C 80356D6C 24050004 */   addiu     $a1, $zero, 0x4
    /* 4F7180 80356D70 8FA20040 */  lw         $v0, 0x40($sp)
    /* 4F7184 80356D74 24050074 */  addiu      $a1, $zero, 0x74
    /* 4F7188 80356D78 240600B3 */  addiu      $a2, $zero, 0xB3
    /* 4F718C 80356D7C 0C009862 */  jal        spX2Move
    /* 4F7190 80356D80 24440010 */   addiu     $a0, $v0, 0x10
    /* 4F7194 80356D84 3C058038 */  lui        $a1, %hi(D_803819B8_521DC8)
    /* 4F7198 80356D88 24A519B8 */  addiu      $a1, $a1, %lo(D_803819B8_521DC8)
    /* 4F719C 80356D8C 0C00282D */  jal        omGObjAddSprite
    /* 4F71A0 80356D90 8FA40048 */   lw        $a0, 0x48($sp)
    /* 4F71A4 80356D94 3C018038 */  lui        $at, %hi(D_80382C90_5230A0)
    /* 4F71A8 80356D98 AC222C90 */  sw         $v0, %lo(D_80382C90_5230A0)($at)
    /* 4F71AC 80356D9C AFA20040 */  sw         $v0, 0x40($sp)
    /* 4F71B0 80356DA0 24440010 */  addiu      $a0, $v0, 0x10
    /* 4F71B4 80356DA4 0C00985C */  jal        spSetAttribute
    /* 4F71B8 80356DA8 24050004 */   addiu     $a1, $zero, 0x4
    /* 4F71BC 80356DAC 8FA20040 */  lw         $v0, 0x40($sp)
    /* 4F71C0 80356DB0 24050074 */  addiu      $a1, $zero, 0x74
    /* 4F71C4 80356DB4 240600B3 */  addiu      $a2, $zero, 0xB3
    /* 4F71C8 80356DB8 0C009862 */  jal        spX2Move
    /* 4F71CC 80356DBC 24440010 */   addiu     $a0, $v0, 0x10
    /* 4F71D0 80356DC0 3C19803B */  lui        $t9, %hi(gIdleScript)
    /* 4F71D4 80356DC4 8F39E518 */  lw         $t9, %lo(gIdleScript)($t9)
    /* 4F71D8 80356DC8 3C058035 */  lui        $a1, %hi(func_803549A4_4F4DB4)
    /* 4F71DC 80356DCC 24A549A4 */  addiu      $a1, $a1, %lo(func_803549A4_4F4DB4)
    /* 4F71E0 80356DD0 17200004 */  bnez       $t9, .L80356DE4_4F71F4
    /* 4F71E4 80356DD4 8FA40048 */   lw        $a0, 0x48($sp)
    /* 4F71E8 80356DD8 24060001 */  addiu      $a2, $zero, 0x1
    /* 4F71EC 80356DDC 0C00230A */  jal        omCreateProcess
    /* 4F71F0 80356DE0 24070009 */   addiu     $a3, $zero, 0x9
  .L80356DE4_4F71F4:
    /* 4F71F4 80356DE4 3C058035 */  lui        $a1, %hi(func_80353118_4F3528)
    /* 4F71F8 80356DE8 24A53118 */  addiu      $a1, $a1, %lo(func_80353118_4F3528)
    /* 4F71FC 80356DEC 8FA40048 */  lw         $a0, 0x48($sp)
    /* 4F7200 80356DF0 24060001 */  addiu      $a2, $zero, 0x1
    /* 4F7204 80356DF4 0C00230A */  jal        omCreateProcess
    /* 4F7208 80356DF8 24070009 */   addiu     $a3, $zero, 0x9
    /* 4F720C 80356DFC 0C026E60 */  jal        getLevelId
    /* 4F7210 80356E00 00000000 */   nop
    /* 4F7214 80356E04 2C410007 */  sltiu      $at, $v0, 0x7
    /* 4F7218 80356E08 10200065 */  beqz       $at, .L80356FA0_4F73B0
    /* 4F721C 80356E0C 00025080 */   sll       $t2, $v0, 2
    /* 4F7220 80356E10 3C018039 */  lui        $at, %hi(jtbl_8038A2D4_52A6E4)
    /* 4F7224 80356E14 002A0821 */  addu       $at, $at, $t2
    /* 4F7228 80356E18 8C2AA2D4 */  lw         $t2, %lo(jtbl_8038A2D4_52A6E4)($at)
    /* 4F722C 80356E1C 01400008 */  jr         $t2
    /* 4F7230 80356E20 00000000 */   nop
  .L80356E24_4F7234:
    /* 4F7234 80356E24 3C0B803B */  lui        $t3, %hi(IsTutorialEnabled)
    /* 4F7238 80356E28 816BE515 */  lb         $t3, %lo(IsTutorialEnabled)($t3)
    /* 4F723C 80356E2C 24010001 */  addiu      $at, $zero, 0x1
    /* 4F7240 80356E30 3C058035 */  lui        $a1, %hi(func_803554EC_4F58FC)
    /* 4F7244 80356E34 1561000A */  bne        $t3, $at, .L80356E60_4F7270
    /* 4F7248 80356E38 24040008 */   addiu     $a0, $zero, 0x8
    /* 4F724C 80356E3C 8FA4004C */  lw         $a0, 0x4C($sp)
    /* 4F7250 80356E40 24A554EC */  addiu      $a1, $a1, %lo(func_803554EC_4F58FC)
    /* 4F7254 80356E44 24060001 */  addiu      $a2, $zero, 0x1
    /* 4F7258 80356E48 0C00230A */  jal        omCreateProcess
    /* 4F725C 80356E4C 24070009 */   addiu     $a3, $zero, 0x9
    /* 4F7260 80356E50 240C0001 */  addiu      $t4, $zero, 0x1
    /* 4F7264 80356E54 3C018038 */  lui        $at, %hi(D_80382D0C_52311C)
    /* 4F7268 80356E58 10000003 */  b          .L80356E68_4F7278
    /* 4F726C 80356E5C AC2C2D0C */   sw        $t4, %lo(D_80382D0C_52311C)($at)
  .L80356E60_4F7270:
    /* 4F7270 80356E60 0C02FFAF */  jal        func_800BFEBC_5CD5C
    /* 4F7274 80356E64 24050001 */   addiu     $a1, $zero, 0x1
  .L80356E68_4F7278:
    /* 4F7278 80356E68 3C014000 */  lui        $at, (0x40000000 >> 16)
    /* 4F727C 80356E6C 44815000 */  mtc1       $at, $f10
    /* 4F7280 80356E70 3C018038 */  lui        $at, %hi(D_80382C5C_52306C)
    /* 4F7284 80356E74 3C058035 */  lui        $a1, %hi(func_80353BCC_4F3FDC)
    /* 4F7288 80356E78 E42A2C5C */  swc1       $f10, %lo(D_80382C5C_52306C)($at)
    /* 4F728C 80356E7C 3C0141C8 */  lui        $at, (0x41C80000 >> 16)
    /* 4F7290 80356E80 44818000 */  mtc1       $at, $f16
    /* 4F7294 80356E84 3C018038 */  lui        $at, %hi(D_80382C60_523070)
    /* 4F7298 80356E88 24A53BCC */  addiu      $a1, $a1, %lo(func_80353BCC_4F3FDC)
    /* 4F729C 80356E8C 8FA4004C */  lw         $a0, 0x4C($sp)
    /* 4F72A0 80356E90 00003025 */  or         $a2, $zero, $zero
    /* 4F72A4 80356E94 24070009 */  addiu      $a3, $zero, 0x9
    /* 4F72A8 80356E98 0C00230A */  jal        omCreateProcess
    /* 4F72AC 80356E9C E4302C60 */   swc1      $f16, %lo(D_80382C60_523070)($at)
    /* 4F72B0 80356EA0 1000003F */  b          .L80356FA0_4F73B0
    /* 4F72B4 80356EA4 00000000 */   nop
  .L80356EA8_4F72B8:
    /* 4F72B8 80356EA8 3C014220 */  lui        $at, (0x42200000 >> 16)
    /* 4F72BC 80356EAC 44819000 */  mtc1       $at, $f18
    /* 4F72C0 80356EB0 3C018038 */  lui        $at, %hi(D_80382C5C_52306C)
    /* 4F72C4 80356EB4 3C058035 */  lui        $a1, %hi(func_80353BCC_4F3FDC)
    /* 4F72C8 80356EB8 E4322C5C */  swc1       $f18, %lo(D_80382C5C_52306C)($at)
    /* 4F72CC 80356EBC 3C013FC0 */  lui        $at, (0x3FC00000 >> 16)
    /* 4F72D0 80356EC0 44812000 */  mtc1       $at, $f4
    /* 4F72D4 80356EC4 3C018038 */  lui        $at, %hi(D_80382C60_523070)
    /* 4F72D8 80356EC8 24A53BCC */  addiu      $a1, $a1, %lo(func_80353BCC_4F3FDC)
    /* 4F72DC 80356ECC 8FA4004C */  lw         $a0, 0x4C($sp)
    /* 4F72E0 80356ED0 00003025 */  or         $a2, $zero, $zero
    /* 4F72E4 80356ED4 24070009 */  addiu      $a3, $zero, 0x9
    /* 4F72E8 80356ED8 0C00230A */  jal        omCreateProcess
    /* 4F72EC 80356EDC E4242C60 */   swc1      $f4, %lo(D_80382C60_523070)($at)
    /* 4F72F0 80356EE0 1000002F */  b          .L80356FA0_4F73B0
    /* 4F72F4 80356EE4 00000000 */   nop
  .L80356EE8_4F72F8:
    /* 4F72F8 80356EE8 3C01420C */  lui        $at, (0x420C0000 >> 16)
    /* 4F72FC 80356EEC 44813000 */  mtc1       $at, $f6
    /* 4F7300 80356EF0 3C018038 */  lui        $at, %hi(D_80382C5C_52306C)
    /* 4F7304 80356EF4 3C058035 */  lui        $a1, %hi(func_80353BCC_4F3FDC)
    /* 4F7308 80356EF8 E4262C5C */  swc1       $f6, %lo(D_80382C5C_52306C)($at)
    /* 4F730C 80356EFC 3C013FC0 */  lui        $at, (0x3FC00000 >> 16)
    /* 4F7310 80356F00 44814000 */  mtc1       $at, $f8
    /* 4F7314 80356F04 3C018038 */  lui        $at, %hi(D_80382C60_523070)
    /* 4F7318 80356F08 24A53BCC */  addiu      $a1, $a1, %lo(func_80353BCC_4F3FDC)
    /* 4F731C 80356F0C 8FA4004C */  lw         $a0, 0x4C($sp)
    /* 4F7320 80356F10 00003025 */  or         $a2, $zero, $zero
    /* 4F7324 80356F14 24070009 */  addiu      $a3, $zero, 0x9
    /* 4F7328 80356F18 0C00230A */  jal        omCreateProcess
    /* 4F732C 80356F1C E4282C60 */   swc1      $f8, %lo(D_80382C60_523070)($at)
    /* 4F7330 80356F20 1000001F */  b          .L80356FA0_4F73B0
    /* 4F7334 80356F24 00000000 */   nop
  .L80356F28_4F7338:
    /* 4F7338 80356F28 3C014120 */  lui        $at, (0x41200000 >> 16)
    /* 4F733C 80356F2C 44815000 */  mtc1       $at, $f10
    /* 4F7340 80356F30 3C018038 */  lui        $at, %hi(D_80382C5C_52306C)
    /* 4F7344 80356F34 3C058035 */  lui        $a1, %hi(func_80353BCC_4F3FDC)
    /* 4F7348 80356F38 E42A2C5C */  swc1       $f10, %lo(D_80382C5C_52306C)($at)
    /* 4F734C 80356F3C 3C014000 */  lui        $at, (0x40000000 >> 16)
    /* 4F7350 80356F40 44818000 */  mtc1       $at, $f16
    /* 4F7354 80356F44 3C018038 */  lui        $at, %hi(D_80382C60_523070)
    /* 4F7358 80356F48 24A53BCC */  addiu      $a1, $a1, %lo(func_80353BCC_4F3FDC)
    /* 4F735C 80356F4C 8FA4004C */  lw         $a0, 0x4C($sp)
    /* 4F7360 80356F50 00003025 */  or         $a2, $zero, $zero
    /* 4F7364 80356F54 24070009 */  addiu      $a3, $zero, 0x9
    /* 4F7368 80356F58 0C00230A */  jal        omCreateProcess
    /* 4F736C 80356F5C E4302C60 */   swc1      $f16, %lo(D_80382C60_523070)($at)
    /* 4F7370 80356F60 1000000F */  b          .L80356FA0_4F73B0
    /* 4F7374 80356F64 00000000 */   nop
  .L80356F68_4F7378:
    /* 4F7378 80356F68 3C014170 */  lui        $at, (0x41700000 >> 16)
    /* 4F737C 80356F6C 44819000 */  mtc1       $at, $f18
    /* 4F7380 80356F70 3C018038 */  lui        $at, %hi(D_80382C5C_52306C)
    /* 4F7384 80356F74 3C058035 */  lui        $a1, %hi(func_80353BCC_4F3FDC)
    /* 4F7388 80356F78 E4322C5C */  swc1       $f18, %lo(D_80382C5C_52306C)($at)
    /* 4F738C 80356F7C 3C013FC0 */  lui        $at, (0x3FC00000 >> 16)
    /* 4F7390 80356F80 44812000 */  mtc1       $at, $f4
    /* 4F7394 80356F84 3C018038 */  lui        $at, %hi(D_80382C60_523070)
    /* 4F7398 80356F88 24A53BCC */  addiu      $a1, $a1, %lo(func_80353BCC_4F3FDC)
    /* 4F739C 80356F8C 8FA4004C */  lw         $a0, 0x4C($sp)
    /* 4F73A0 80356F90 00003025 */  or         $a2, $zero, $zero
    /* 4F73A4 80356F94 24070009 */  addiu      $a3, $zero, 0x9
    /* 4F73A8 80356F98 0C00230A */  jal        omCreateProcess
    /* 4F73AC 80356F9C E4242C60 */   swc1      $f4, %lo(D_80382C60_523070)($at)
  .L80356FA0_4F73B0:
    /* 4F73B0 80356FA0 0C0D96C9 */  jal        func_80365B24_505F34
    /* 4F73B4 80356FA4 00000000 */   nop
    /* 4F73B8 80356FA8 8FBF0034 */  lw         $ra, 0x34($sp)
    /* 4F73BC 80356FAC 8FA2004C */  lw         $v0, 0x4C($sp)
    /* 4F73C0 80356FB0 27BD0050 */  addiu      $sp, $sp, 0x50
    /* 4F73C4 80356FB4 03E00008 */  jr         $ra
    /* 4F73C8 80356FB8 00000000 */   nop
endlabel initUI
