.section .rodata
.align 2
nonmatching D_8038A0E0_52A4F0

dlabel D_8038A0E0_52A4F0
    /* 52A4F0 8038A0E0 */ .asciz "You're out of film!"
    /* 596F75277265206F7574206F662066696C6D2100 */
.align 2
enddlabel D_8038A0E0_52A4F0


.section .text
/* Generated by spimdisasm 1.42.0 */

nonmatching processOutOfFilm, 0x2C4

glabel processOutOfFilm
    /* 4F5C70 80355860 27BDFF98 */  addiu      $sp, $sp, -0x68
    /* 4F5C74 80355864 240E0001 */  addiu      $t6, $zero, 0x1
    /* 4F5C78 80355868 3C018038 */  lui        $at, %hi(D_80382D44_523154)
    /* 4F5C7C 8035586C A02E2D44 */  sb         $t6, %lo(D_80382D44_523154)($at)
    /* 4F5C80 80355870 AFBF003C */  sw         $ra, 0x3C($sp)
    /* 4F5C84 80355874 AFB20038 */  sw         $s2, 0x38($sp)
    /* 4F5C88 80355878 3C01803B */  lui        $at, %hi(D_803AE516_54E926)
    /* 4F5C8C 8035587C 240F0001 */  addiu      $t7, $zero, 0x1
    /* 4F5C90 80355880 AFB10034 */  sw         $s1, 0x34($sp)
    /* 4F5C94 80355884 AFB00030 */  sw         $s0, 0x30($sp)
    /* 4F5C98 80355888 AFA40068 */  sw         $a0, 0x68($sp)
    /* 4F5C9C 8035588C 00009025 */  or         $s2, $zero, $zero
    /* 4F5CA0 80355890 0C0D40E3 */  jal        stopLevelProcesses
    /* 4F5CA4 80355894 A02FE516 */   sb        $t7, %lo(D_803AE516_54E926)($at)
    /* 4F5CA8 80355898 3C048038 */  lui        $a0, %hi(gObjPlayer)
    /* 4F5CAC 8035589C 3C058035 */  lui        $a1, %hi(func_80355228_4F5638)
    /* 4F5CB0 803558A0 24A55228 */  addiu      $a1, $a1, %lo(func_80355228_4F5638)
    /* 4F5CB4 803558A4 0C002F77 */  jal        ohPauseProcessByFunction
    /* 4F5CB8 803558A8 8C842C00 */   lw        $a0, %lo(gObjPlayer)($a0)
    /* 4F5CBC 803558AC 0C0D5C48 */  jal        func_80357120_4F7530
    /* 4F5CC0 803558B0 00002025 */   or        $a0, $zero, $zero
    /* 4F5CC4 803558B4 00002025 */  or         $a0, $zero, $zero
    /* 4F5CC8 803558B8 00002825 */  or         $a1, $zero, $zero
    /* 4F5CCC 803558BC 0C0D556C */  jal        func_803555B0_4F59C0
    /* 4F5CD0 803558C0 240600FF */   addiu     $a2, $zero, 0xFF
    /* 4F5CD4 803558C4 0C000A75 */  jal        scRemovePostProcessFunc
    /* 4F5CD8 803558C8 00000000 */   nop
    /* 4F5CDC 803558CC 0C0D4456 */  jal        playDashEngineSounds
    /* 4F5CE0 803558D0 00002025 */   or        $a0, $zero, $zero
    /* 4F5CE4 803558D4 0C0D7594 */  jal        Icons_SetDashEngineEnabled
    /* 4F5CE8 803558D8 00002025 */   or        $a0, $zero, $zero
    /* 4F5CEC 803558DC 3C118038 */  lui        $s1, %hi(ObjectPauseMenu)
    /* 4F5CF0 803558E0 26312C6C */  addiu      $s1, $s1, %lo(ObjectPauseMenu)
    /* 4F5CF4 803558E4 3C058039 */  lui        $a1, %hi(D_80388E00_529210)
    /* 4F5CF8 803558E8 24A58E00 */  addiu      $a1, $a1, %lo(D_80388E00_529210)
    /* 4F5CFC 803558EC 0C00282D */  jal        omGObjAddSprite
    /* 4F5D00 803558F0 8E240000 */   lw        $a0, 0x0($s1)
    /* 4F5D04 803558F4 00408025 */  or         $s0, $v0, $zero
    /* 4F5D08 803558F8 24440010 */  addiu      $a0, $v0, 0x10
    /* 4F5D0C 803558FC 2405007D */  addiu      $a1, $zero, 0x7D
    /* 4F5D10 80355900 0C009862 */  jal        spX2Move
    /* 4F5D14 80355904 24060061 */   addiu     $a2, $zero, 0x61
    /* 4F5D18 80355908 26040010 */  addiu      $a0, $s0, 0x10
    /* 4F5D1C 8035590C AFA40048 */  sw         $a0, 0x48($sp)
    /* 4F5D20 80355910 240500FF */  addiu      $a1, $zero, 0xFF
    /* 4F5D24 80355914 240600FF */  addiu      $a2, $zero, 0xFF
    /* 4F5D28 80355918 240700FF */  addiu      $a3, $zero, 0xFF
    /* 4F5D2C 8035591C 0C009850 */  jal        spColor
    /* 4F5D30 80355920 AFA00010 */   sw        $zero, 0x10($sp)
    /* 4F5D34 80355924 3C058038 */  lui        $a1, %hi(D_80381B58_521F68)
    /* 4F5D38 80355928 24A51B58 */  addiu      $a1, $a1, %lo(D_80381B58_521F68)
    /* 4F5D3C 8035592C 0C00282D */  jal        omGObjAddSprite
    /* 4F5D40 80355930 8E240000 */   lw        $a0, 0x0($s1)
    /* 4F5D44 80355934 00408025 */  or         $s0, $v0, $zero
    /* 4F5D48 80355938 24440010 */  addiu      $a0, $v0, 0x10
    /* 4F5D4C 8035593C 24050095 */  addiu      $a1, $zero, 0x95
    /* 4F5D50 80355940 0C009862 */  jal        spX2Move
    /* 4F5D54 80355944 24060067 */   addiu     $a2, $zero, 0x67
    /* 4F5D58 80355948 26040010 */  addiu      $a0, $s0, 0x10
    /* 4F5D5C 8035594C AFA40040 */  sw         $a0, 0x40($sp)
    /* 4F5D60 80355950 240500FF */  addiu      $a1, $zero, 0xFF
    /* 4F5D64 80355954 240600FF */  addiu      $a2, $zero, 0xFF
    /* 4F5D68 80355958 240700FF */  addiu      $a3, $zero, 0xFF
    /* 4F5D6C 8035595C 0C009850 */  jal        spColor
    /* 4F5D70 80355960 AFA00010 */   sw        $zero, 0x10($sp)
    /* 4F5D74 80355964 2410003B */  addiu      $s0, $zero, 0x3B
    /* 4F5D78 80355968 2652000A */  addiu      $s2, $s2, 0xA
  .L8035596C_4F5D7C:
    /* 4F5D7C 8035596C 2A410100 */  slti       $at, $s2, 0x100
    /* 4F5D80 80355970 14200002 */  bnez       $at, .L8035597C_4F5D8C
    /* 4F5D84 80355974 8FA40048 */   lw        $a0, 0x48($sp)
    /* 4F5D88 80355978 241200FF */  addiu      $s2, $zero, 0xFF
  .L8035597C_4F5D8C:
    /* 4F5D8C 8035597C 325100FF */  andi       $s1, $s2, 0xFF
    /* 4F5D90 80355980 AFB10010 */  sw         $s1, 0x10($sp)
    /* 4F5D94 80355984 240500FF */  addiu      $a1, $zero, 0xFF
    /* 4F5D98 80355988 240600FF */  addiu      $a2, $zero, 0xFF
    /* 4F5D9C 8035598C 0C009850 */  jal        spColor
    /* 4F5DA0 80355990 240700FF */   addiu     $a3, $zero, 0xFF
    /* 4F5DA4 80355994 8FA40040 */  lw         $a0, 0x40($sp)
    /* 4F5DA8 80355998 240500FF */  addiu      $a1, $zero, 0xFF
    /* 4F5DAC 8035599C 240600FF */  addiu      $a2, $zero, 0xFF
    /* 4F5DB0 803559A0 240700FF */  addiu      $a3, $zero, 0xFF
    /* 4F5DB4 803559A4 0C009850 */  jal        spColor
    /* 4F5DB8 803559A8 AFB10010 */   sw        $s1, 0x10($sp)
    /* 4F5DBC 803559AC 0C002F2A */  jal        ohWait
    /* 4F5DC0 803559B0 24040001 */   addiu     $a0, $zero, 0x1
    /* 4F5DC4 803559B4 2610FFFF */  addiu      $s0, $s0, -0x1
    /* 4F5DC8 803559B8 5600FFEC */  bnel       $s0, $zero, .L8035596C_4F5D7C
    /* 4F5DCC 803559BC 2652000A */   addiu     $s2, $s2, 0xA
    /* 4F5DD0 803559C0 3C048039 */  lui        $a0, %hi(D_8038A0E0_52A4F0)
    /* 4F5DD4 803559C4 241800FF */  addiu      $t8, $zero, 0xFF
    /* 4F5DD8 803559C8 241900FF */  addiu      $t9, $zero, 0xFF
    /* 4F5DDC 803559CC 240800FF */  addiu      $t0, $zero, 0xFF
    /* 4F5DE0 803559D0 24090005 */  addiu      $t1, $zero, 0x5
    /* 4F5DE4 803559D4 240A0002 */  addiu      $t2, $zero, 0x2
    /* 4F5DE8 803559D8 AFAA0020 */  sw         $t2, 0x20($sp)
    /* 4F5DEC 803559DC AFA9001C */  sw         $t1, 0x1C($sp)
    /* 4F5DF0 803559E0 AFA80018 */  sw         $t0, 0x18($sp)
    /* 4F5DF4 803559E4 AFB90014 */  sw         $t9, 0x14($sp)
    /* 4F5DF8 803559E8 AFB80010 */  sw         $t8, 0x10($sp)
    /* 4F5DFC 803559EC 2484A0E0 */  addiu      $a0, $a0, %lo(D_8038A0E0_52A4F0)
    /* 4F5E00 803559F0 240500A0 */  addiu      $a1, $zero, 0xA0
    /* 4F5E04 803559F4 24060082 */  addiu      $a2, $zero, 0x82
    /* 4F5E08 803559F8 0C0D96EC */  jal        Msg_ShowMessage
    /* 4F5E0C 803559FC 240700FF */   addiu     $a3, $zero, 0xFF
    /* 4F5E10 80355A00 0C0088CD */  jal        auStopBGM
    /* 4F5E14 80355A04 00000000 */   nop
    /* 4F5E18 80355A08 0C008AC5 */  jal        auStopAllSounds
    /* 4F5E1C 80355A0C 00000000 */   nop
    /* 4F5E20 80355A10 00008025 */  or         $s0, $zero, $zero
    /* 4F5E24 80355A14 24110010 */  addiu      $s1, $zero, 0x10
    /* 4F5E28 80355A18 00002025 */  or         $a0, $zero, $zero
  .L80355A1C_4F5E2C:
    /* 4F5E2C 80355A1C 320500FF */  andi       $a1, $s0, 0xFF
    /* 4F5E30 80355A20 0C0089BD */  jal        auSetBGMChannelVolume
    /* 4F5E34 80355A24 2406007F */   addiu     $a2, $zero, 0x7F
    /* 4F5E38 80355A28 26100001 */  addiu      $s0, $s0, 0x1
    /* 4F5E3C 80355A2C 5611FFFB */  bnel       $s0, $s1, .L80355A1C_4F5E2C
    /* 4F5E40 80355A30 00002025 */   or        $a0, $zero, $zero
    /* 4F5E44 80355A34 00002025 */  or         $a0, $zero, $zero
    /* 4F5E48 80355A38 0C0088DD */  jal        auPlaySong
    /* 4F5E4C 80355A3C 24050011 */   addiu     $a1, $zero, 0x11
    /* 4F5E50 80355A40 0C0D979C */  jal        Msg_IsMessagePrinted
    /* 4F5E54 80355A44 00000000 */   nop
    /* 4F5E58 80355A48 14400007 */  bnez       $v0, .L80355A68_4F5E78
    /* 4F5E5C 80355A4C 00000000 */   nop
  .L80355A50_4F5E60:
    /* 4F5E60 80355A50 0C002F2A */  jal        ohWait
    /* 4F5E64 80355A54 24040001 */   addiu     $a0, $zero, 0x1
    /* 4F5E68 80355A58 0C0D979C */  jal        Msg_IsMessagePrinted
    /* 4F5E6C 80355A5C 00000000 */   nop
    /* 4F5E70 80355A60 1040FFFB */  beqz       $v0, .L80355A50_4F5E60
    /* 4F5E74 80355A64 00000000 */   nop
  .L80355A68_4F5E78:
    /* 4F5E78 80355A68 3C118005 */  lui        $s1, %hi(gContInputPressedButtons)
    /* 4F5E7C 80355A6C 26319752 */  addiu      $s1, $s1, %lo(gContInputPressedButtons)
    /* 4F5E80 80355A70 241000B4 */  addiu      $s0, $zero, 0xB4
    /* 4F5E84 80355A74 962B0000 */  lhu        $t3, 0x0($s1)
  .L80355A78_4F5E88:
    /* 4F5E88 80355A78 316C8000 */  andi       $t4, $t3, 0x8000
    /* 4F5E8C 80355A7C 55800007 */  bnel       $t4, $zero, .L80355A9C_4F5EAC
    /* 4F5E90 80355A80 2404000A */   addiu     $a0, $zero, 0xA
    /* 4F5E94 80355A84 0C002F2A */  jal        ohWait
    /* 4F5E98 80355A88 24040001 */   addiu     $a0, $zero, 0x1
    /* 4F5E9C 80355A8C 2610FFFF */  addiu      $s0, $s0, -0x1
    /* 4F5EA0 80355A90 5600FFF9 */  bnel       $s0, $zero, .L80355A78_4F5E88
    /* 4F5EA4 80355A94 962B0000 */   lhu       $t3, 0x0($s1)
    /* 4F5EA8 80355A98 2404000A */  addiu      $a0, $zero, 0xA
  .L80355A9C_4F5EAC:
    /* 4F5EAC 80355A9C 0C0D4116 */  jal        func_80350458_4F0868
    /* 4F5EB0 80355AA0 24050001 */   addiu     $a1, $zero, 0x1
    /* 4F5EB4 80355AA4 44806000 */  mtc1       $zero, $f12
    /* 4F5EB8 80355AA8 00003025 */  or         $a2, $zero, $zero
    /* 4F5EBC 80355AAC 3C074000 */  lui        $a3, (0x40000000 >> 16)
    /* 4F5EC0 80355AB0 0C029FD0 */  jal        func_800A7F40
    /* 4F5EC4 80355AB4 46006386 */   mov.s     $f14, $f12
    /* 4F5EC8 80355AB8 0C002F2A */  jal        ohWait
    /* 4F5ECC 80355ABC 24040001 */   addiu     $a0, $zero, 0x1
    /* 4F5ED0 80355AC0 0C029D18 */  jal        func_800A7460
    /* 4F5ED4 80355AC4 00000000 */   nop
    /* 4F5ED8 80355AC8 24010001 */  addiu      $at, $zero, 0x1
    /* 4F5EDC 80355ACC 14410008 */  bne        $v0, $at, .L80355AF0_4F5F00
    /* 4F5EE0 80355AD0 00000000 */   nop
  .L80355AD4_4F5EE4:
    /* 4F5EE4 80355AD4 0C002F2A */  jal        ohWait
    /* 4F5EE8 80355AD8 24040001 */   addiu     $a0, $zero, 0x1
    /* 4F5EEC 80355ADC 0C029D18 */  jal        func_800A7460
    /* 4F5EF0 80355AE0 00000000 */   nop
    /* 4F5EF4 80355AE4 24010001 */  addiu      $at, $zero, 0x1
    /* 4F5EF8 80355AE8 1041FFFA */  beq        $v0, $at, .L80355AD4_4F5EE4
    /* 4F5EFC 80355AEC 00000000 */   nop
  .L80355AF0_4F5F00:
    /* 4F5F00 80355AF0 3C198038 */  lui        $t9, %hi(EndLevelCb)
    /* 4F5F04 80355AF4 8F392D18 */  lw         $t9, %lo(EndLevelCb)($t9)
    /* 4F5F08 80355AF8 24040004 */  addiu      $a0, $zero, 0x4
    /* 4F5F0C 80355AFC 0320F809 */  jalr       $t9
    /* 4F5F10 80355B00 00000000 */   nop
    /* 4F5F14 80355B04 0C0023CB */  jal        omEndProcess
    /* 4F5F18 80355B08 00002025 */   or        $a0, $zero, $zero
    /* 4F5F1C 80355B0C 8FBF003C */  lw         $ra, 0x3C($sp)
    /* 4F5F20 80355B10 8FB00030 */  lw         $s0, 0x30($sp)
    /* 4F5F24 80355B14 8FB10034 */  lw         $s1, 0x34($sp)
    /* 4F5F28 80355B18 8FB20038 */  lw         $s2, 0x38($sp)
    /* 4F5F2C 80355B1C 03E00008 */  jr         $ra
    /* 4F5F30 80355B20 27BD0068 */   addiu     $sp, $sp, 0x68
endlabel processOutOfFilm
