.section .late_rodata
nonmatching D_80043DA4

dlabel D_80043DA4
    /* 449A4 80043DA4 3C8EFA35 */ .float 0.01745329238
enddlabel D_80043DA4


.section .text
/* Generated by spimdisasm 1.42.0 */

nonmatching hal_perspective_f, 0x1C8

glabel hal_perspective_f
    /* 1D54C 8001C94C 3C018004 */  lui        $at, %hi(D_80043DA4)
    /* 1D550 8001C950 44867000 */  mtc1       $a2, $f14
    /* 1D554 8001C954 C4243DA4 */  lwc1       $f4, %lo(D_80043DA4)($at)
    /* 1D558 8001C958 3C014000 */  lui        $at, (0x40000000 >> 16)
    /* 1D55C 8001C95C 44813000 */  mtc1       $at, $f6
    /* 1D560 8001C960 46047382 */  mul.s      $f14, $f14, $f4
    /* 1D564 8001C964 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* 1D568 8001C968 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 1D56C 8001C96C AFA7003C */  sw         $a3, 0x3C($sp)
    /* 1D570 8001C970 AFA40030 */  sw         $a0, 0x30($sp)
    /* 1D574 8001C974 AFA50034 */  sw         $a1, 0x34($sp)
    /* 1D578 8001C978 46067303 */  div.s      $f12, $f14, $f6
    /* 1D57C 8001C97C 0C00E378 */  jal        __cosf
    /* 1D580 8001C980 E7AC0018 */   swc1      $f12, 0x18($sp)
    /* 1D584 8001C984 C7AC0018 */  lwc1       $f12, 0x18($sp)
    /* 1D588 8001C988 0C00CA88 */  jal        __sinf
    /* 1D58C 8001C98C E7A00020 */   swc1      $f0, 0x20($sp)
    /* 1D590 8001C990 C7A80020 */  lwc1       $f8, 0x20($sp)
    /* 1D594 8001C994 C7AA003C */  lwc1       $f10, 0x3C($sp)
    /* 1D598 8001C998 C7A20048 */  lwc1       $f2, 0x48($sp)
    /* 1D59C 8001C99C 46004303 */  div.s      $f12, $f8, $f0
    /* 1D5A0 8001C9A0 C7AE0040 */  lwc1       $f14, 0x40($sp)
    /* 1D5A4 8001C9A4 C7B20044 */  lwc1       $f18, 0x44($sp)
    /* 1D5A8 8001C9A8 8FA40030 */  lw         $a0, 0x30($sp)
    /* 1D5AC 8001C9AC 8FA50034 */  lw         $a1, 0x34($sp)
    /* 1D5B0 8001C9B0 46127401 */  sub.s      $f16, $f14, $f18
    /* 1D5B4 8001C9B4 44800000 */  mtc1       $zero, $f0
    /* 1D5B8 8001C9B8 3C014000 */  lui        $at, (0x40000000 >> 16)
    /* 1D5BC 8001C9BC 460A6103 */  div.s      $f4, $f12, $f10
    /* 1D5C0 8001C9C0 46127280 */  add.s      $f10, $f14, $f18
    /* 1D5C4 8001C9C4 46022182 */  mul.s      $f6, $f4, $f2
    /* 1D5C8 8001C9C8 00000000 */  nop
    /* 1D5CC 8001C9CC 46026202 */  mul.s      $f8, $f12, $f2
    /* 1D5D0 8001C9D0 E4860000 */  swc1       $f6, 0x0($a0)
    /* 1D5D4 8001C9D4 E4880014 */  swc1       $f8, 0x14($a0)
    /* 1D5D8 8001C9D8 E7AA0018 */  swc1       $f10, 0x18($sp)
    /* 1D5DC 8001C9DC C7A40018 */  lwc1       $f4, 0x18($sp)
    /* 1D5E0 8001C9E0 46001287 */  neg.s      $f10, $f2
    /* 1D5E4 8001C9E4 E4800004 */  swc1       $f0, 0x4($a0)
    /* 1D5E8 8001C9E8 46022182 */  mul.s      $f6, $f4, $f2
    /* 1D5EC 8001C9EC 460E7100 */  add.s      $f4, $f14, $f14
    /* 1D5F0 8001C9F0 E48A002C */  swc1       $f10, 0x2C($a0)
    /* 1D5F4 8001C9F4 E4800008 */  swc1       $f0, 0x8($a0)
    /* 1D5F8 8001C9F8 E480000C */  swc1       $f0, 0xC($a0)
    /* 1D5FC 8001C9FC E4800010 */  swc1       $f0, 0x10($a0)
    /* 1D600 8001CA00 E4800018 */  swc1       $f0, 0x18($a0)
    /* 1D604 8001CA04 46103203 */  div.s      $f8, $f6, $f16
    /* 1D608 8001CA08 E480001C */  swc1       $f0, 0x1C($a0)
    /* 1D60C 8001CA0C E4800020 */  swc1       $f0, 0x20($a0)
    /* 1D610 8001CA10 E4800024 */  swc1       $f0, 0x24($a0)
    /* 1D614 8001CA14 46122182 */  mul.s      $f6, $f4, $f18
    /* 1D618 8001CA18 44802000 */  mtc1       $zero, $f4
    /* 1D61C 8001CA1C E4800030 */  swc1       $f0, 0x30($a0)
    /* 1D620 8001CA20 E4800034 */  swc1       $f0, 0x34($a0)
    /* 1D624 8001CA24 E484003C */  swc1       $f4, 0x3C($a0)
    /* 1D628 8001CA28 E4880028 */  swc1       $f8, 0x28($a0)
    /* 1D62C 8001CA2C 46023202 */  mul.s      $f8, $f6, $f2
    /* 1D630 8001CA30 46104283 */  div.s      $f10, $f8, $f16
    /* 1D634 8001CA34 10A00033 */  beqz       $a1, .L8001CB04
    /* 1D638 8001CA38 E48A0038 */   swc1      $f10, 0x38($a0)
    /* 1D63C 8001CA3C 44813000 */  mtc1       $at, $f6
    /* 1D640 8001CA40 C7A80018 */  lwc1       $f8, 0x18($sp)
    /* 1D644 8001CA44 340EFFFF */  ori        $t6, $zero, 0xFFFF
    /* 1D648 8001CA48 3C014800 */  lui        $at, (0x48000000 >> 16)
    /* 1D64C 8001CA4C 4606403E */  c.le.s     $f8, $f6
    /* 1D650 8001CA50 C7A40018 */  lwc1       $f4, 0x18($sp)
    /* 1D654 8001CA54 45020004 */  bc1fl      .L8001CA68
    /* 1D658 8001CA58 44815000 */   mtc1      $at, $f10
    /* 1D65C 8001CA5C 10000029 */  b          .L8001CB04
    /* 1D660 8001CA60 A4AE0000 */   sh        $t6, 0x0($a1)
    /* 1D664 8001CA64 44815000 */  mtc1       $at, $f10
  .L8001CA68:
    /* 1D668 8001CA68 24180001 */  addiu      $t8, $zero, 0x1
    /* 1D66C 8001CA6C 3C014F00 */  lui        $at, (0x4F000000 >> 16)
    /* 1D670 8001CA70 46045183 */  div.s      $f6, $f10, $f4
    /* 1D674 8001CA74 24080001 */  addiu      $t0, $zero, 0x1
    /* 1D678 8001CA78 444FF800 */  cfc1       $t7, $31
    /* 1D67C 8001CA7C 44D8F800 */  ctc1       $t8, $31
    /* 1D680 8001CA80 00000000 */  nop
    /* 1D684 8001CA84 46003224 */  cvt.w.s    $f8, $f6
    /* 1D688 8001CA88 4458F800 */  cfc1       $t8, $31
    /* 1D68C 8001CA8C 00000000 */  nop
    /* 1D690 8001CA90 33180078 */  andi       $t8, $t8, 0x78
    /* 1D694 8001CA94 53000013 */  beql       $t8, $zero, .L8001CAE4
    /* 1D698 8001CA98 44184000 */   mfc1      $t8, $f8
    /* 1D69C 8001CA9C 44814000 */  mtc1       $at, $f8
    /* 1D6A0 8001CAA0 24180001 */  addiu      $t8, $zero, 0x1
    /* 1D6A4 8001CAA4 46083201 */  sub.s      $f8, $f6, $f8
    /* 1D6A8 8001CAA8 44D8F800 */  ctc1       $t8, $31
    /* 1D6AC 8001CAAC 00000000 */  nop
    /* 1D6B0 8001CAB0 46004224 */  cvt.w.s    $f8, $f8
    /* 1D6B4 8001CAB4 4458F800 */  cfc1       $t8, $31
    /* 1D6B8 8001CAB8 00000000 */  nop
    /* 1D6BC 8001CABC 33180078 */  andi       $t8, $t8, 0x78
    /* 1D6C0 8001CAC0 17000005 */  bnez       $t8, .L8001CAD8
    /* 1D6C4 8001CAC4 00000000 */   nop
    /* 1D6C8 8001CAC8 44184000 */  mfc1       $t8, $f8
    /* 1D6CC 8001CACC 3C018000 */  lui        $at, (0x80000000 >> 16)
    /* 1D6D0 8001CAD0 10000007 */  b          .L8001CAF0
    /* 1D6D4 8001CAD4 0301C025 */   or        $t8, $t8, $at
  .L8001CAD8:
    /* 1D6D8 8001CAD8 10000005 */  b          .L8001CAF0
    /* 1D6DC 8001CADC 2418FFFF */   addiu     $t8, $zero, -0x1
    /* 1D6E0 8001CAE0 44184000 */  mfc1       $t8, $f8
  .L8001CAE4:
    /* 1D6E4 8001CAE4 00000000 */  nop
    /* 1D6E8 8001CAE8 0700FFFB */  bltz       $t8, .L8001CAD8
    /* 1D6EC 8001CAEC 00000000 */   nop
  .L8001CAF0:
    /* 1D6F0 8001CAF0 44CFF800 */  ctc1       $t7, $31
    /* 1D6F4 8001CAF4 3319FFFF */  andi       $t9, $t8, 0xFFFF
    /* 1D6F8 8001CAF8 1F200002 */  bgtz       $t9, .L8001CB04
    /* 1D6FC 8001CAFC A4B80000 */   sh        $t8, 0x0($a1)
    /* 1D700 8001CB00 A4A80000 */  sh         $t0, 0x0($a1)
  .L8001CB04:
    /* 1D704 8001CB04 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 1D708 8001CB08 27BD0030 */  addiu      $sp, $sp, 0x30
    /* 1D70C 8001CB0C 03E00008 */  jr         $ra
    /* 1D710 8001CB10 00000000 */   nop
endlabel hal_perspective_f
