.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.42.0 */

nonmatching D_8033E130_6C05E0, 0x8

dlabel D_8033E130_6C05E0
    /* 8033E130 */ .space 0x08

nonmatching D_8033E138_6C05E8, 0x10

dlabel D_8033E138_6C05E8
    /* 8033E138 */ .space 0x10

nonmatching D_8033E148_6C05F8, 0x1550

dlabel D_8033E148_6C05F8
    /* 8033E148 */ .space 0x1550

nonmatching D_8033F698_6C1B48, 0x1

dlabel D_8033F698_6C1B48
    /* 8033F698 */ .space 0x01

nonmatching D_8033F699_6C1B49, 0x1

dlabel D_8033F699_6C1B49
    /* 8033F699 */ .space 0x01

nonmatching D_8033F69A_6C1B4A, 0x16

dlabel D_8033F69A_6C1B4A
    /* 8033F69A */ .space 0x16
