.section .late_rodata
.align 3
nonmatching D_802E3920_734B20

dlabel D_802E3920_734B20
    /* 734B20 802E3920 3FAEB851EB851EB8 */ .double 0.0599999999999999978
    /* 734B28 802E3928 0000000000000000 */ .double 0
enddlabel D_802E3920_734B20


.section .text
/* Generated by spimdisasm 1.42.1 */

nonmatching func_802DD7F0_72E9F0, 0x108

glabel func_802DD7F0_72E9F0
    /* 72E9F0 802DD7F0 27BDFFB8 */  addiu      $sp, $sp, -0x48
    /* 72E9F4 802DD7F4 AFBF002C */  sw         $ra, 0x2C($sp)
    /* 72E9F8 802DD7F8 AFB30028 */  sw         $s3, 0x28($sp)
    /* 72E9FC 802DD7FC AFB20024 */  sw         $s2, 0x24($sp)
    /* 72EA00 802DD800 AFB10020 */  sw         $s1, 0x20($sp)
    /* 72EA04 802DD804 AFB0001C */  sw         $s0, 0x1C($sp)
    /* 72EA08 802DD808 F7B40010 */  sdc1       $f20, 0x10($sp)
    /* 72EA0C 802DD80C 8C820058 */  lw         $v0, 0x58($a0)
    /* 72EA10 802DD810 3C01802E */  lui        $at, %hi(D_802E3920_734B20)
    /* 72EA14 802DD814 00809825 */  or         $s3, $a0, $zero
    /* 72EA18 802DD818 AC400010 */  sw         $zero, 0x10($v0)
    /* 72EA1C 802DD81C 8C8E0050 */  lw         $t6, 0x50($a0)
    /* 72EA20 802DD820 27B00034 */  addiu      $s0, $sp, 0x34
    /* 72EA24 802DD824 27B10030 */  addiu      $s1, $sp, 0x30
    /* 72EA28 802DD828 35CF0003 */  ori        $t7, $t6, 0x3
    /* 72EA2C 802DD82C AC8F0050 */  sw         $t7, 0x50($a0)
    /* 72EA30 802DD830 D4343920 */  ldc1       $f20, %lo(D_802E3920_734B20)($at)
    /* 72EA34 802DD834 24120005 */  addiu      $s2, $zero, 0x5
    /* 72EA38 802DD838 AFA20038 */  sw         $v0, 0x38($sp)
    /* 72EA3C 802DD83C 02002025 */  or         $a0, $s0, $zero
  .L802DD840_72EA40:
    /* 72EA40 802DD840 0C0D5CE1 */  jal        getLevelProgress
    /* 72EA44 802DD844 02202825 */   or        $a1, $s1, $zero
    /* 72EA48 802DD848 8FA20034 */  lw         $v0, 0x34($sp)
    /* 72EA4C 802DD84C C7A40030 */  lwc1       $f4, 0x30($sp)
    /* 72EA50 802DD850 28410006 */  slti       $at, $v0, 0x6
    /* 72EA54 802DD854 5020000D */  beql       $at, $zero, .L802DD88C_72EA8C
    /* 72EA58 802DD858 8FB90038 */   lw        $t9, 0x38($sp)
    /* 72EA5C 802DD85C 14520006 */  bne        $v0, $s2, .L802DD878_72EA78
    /* 72EA60 802DD860 00000000 */   nop
    /* 72EA64 802DD864 460021A1 */  cvt.d.s    $f6, $f4
    /* 72EA68 802DD868 4626A03E */  c.le.d     $f20, $f6
    /* 72EA6C 802DD86C 00000000 */  nop
    /* 72EA70 802DD870 45030006 */  bc1tl      .L802DD88C_72EA8C
    /* 72EA74 802DD874 8FB90038 */   lw        $t9, 0x38($sp)
  .L802DD878_72EA78:
    /* 72EA78 802DD878 0C002F2A */  jal        ohWait
    /* 72EA7C 802DD87C 24040001 */   addiu     $a0, $zero, 0x1
    /* 72EA80 802DD880 1000FFEF */  b          .L802DD840_72EA40
    /* 72EA84 802DD884 02002025 */   or        $a0, $s0, $zero
    /* 72EA88 802DD888 8FB90038 */  lw         $t9, 0x38($sp)
  .L802DD88C_72EA8C:
    /* 72EA8C 802DD88C 24180001 */  addiu      $t8, $zero, 0x1
    /* 72EA90 802DD890 3C05802D */  lui        $a1, %hi(func_802D6B64_727D64)
    /* 72EA94 802DD894 AF380010 */  sw         $t8, 0x10($t9)
    /* 72EA98 802DD898 AE600050 */  sw         $zero, 0x50($s3)
    /* 72EA9C 802DD89C 8FA80038 */  lw         $t0, 0x38($sp)
    /* 72EAA0 802DD8A0 24A56B64 */  addiu      $a1, $a1, %lo(func_802D6B64_727D64)
    /* 72EAA4 802DD8A4 02602025 */  or         $a0, $s3, $zero
    /* 72EAA8 802DD8A8 24060001 */  addiu      $a2, $zero, 0x1
    /* 72EAAC 802DD8AC 24070001 */  addiu      $a3, $zero, 0x1
    /* 72EAB0 802DD8B0 0C00230A */  jal        omCreateProcess
    /* 72EAB4 802DD8B4 AD0000B0 */   sw        $zero, 0xB0($t0)
    /* 72EAB8 802DD8B8 3C05802E */  lui        $a1, %hi(func_802DDA0C_72EC0C)
    /* 72EABC 802DD8BC 24A5DA0C */  addiu      $a1, $a1, %lo(func_802DDA0C_72EC0C)
    /* 72EAC0 802DD8C0 0C0D7B7E */  jal        Pokemon_StartPathProc
    /* 72EAC4 802DD8C4 02602025 */   or        $a0, $s3, $zero
    /* 72EAC8 802DD8C8 3C05802E */  lui        $a1, %hi(func_802DD8F8_72EAF8)
    /* 72EACC 802DD8CC 24A5D8F8 */  addiu      $a1, $a1, %lo(func_802DD8F8_72EAF8)
    /* 72EAD0 802DD8D0 0C0D7B16 */  jal        Pokemon_SetState
    /* 72EAD4 802DD8D4 02602025 */   or        $a0, $s3, $zero
    /* 72EAD8 802DD8D8 8FBF002C */  lw         $ra, 0x2C($sp)
    /* 72EADC 802DD8DC D7B40010 */  ldc1       $f20, 0x10($sp)
    /* 72EAE0 802DD8E0 8FB0001C */  lw         $s0, 0x1C($sp)
    /* 72EAE4 802DD8E4 8FB10020 */  lw         $s1, 0x20($sp)
    /* 72EAE8 802DD8E8 8FB20024 */  lw         $s2, 0x24($sp)
    /* 72EAEC 802DD8EC 8FB30028 */  lw         $s3, 0x28($sp)
    /* 72EAF0 802DD8F0 03E00008 */  jr         $ra
    /* 72EAF4 802DD8F4 27BD0048 */   addiu     $sp, $sp, 0x48
endlabel func_802DD7F0_72E9F0
