.section .late_rodata
nonmatching jtbl_80043700

dlabel jtbl_80043700
    /* 44300 80043700 8000B92C */ .word .L8000B92C
    /* 44304 80043704 8000B918 */ .word .L8000B918
    /* 44308 80043708 8000B908 */ .word .L8000B908
    /* 4430C 8004370C 8000B8F8 */ .word .L8000B8F8
    /* 44310 80043710 8000B8E8 */ .word .L8000B8E8
    /* 44314 80043714 00000000 */ .word 0x00000000
    /* 44318 80043718 00000000 */ .word 0x00000000
    /* 4431C 8004371C 00000000 */ .word 0x00000000
enddlabel jtbl_80043700


.section .text
/* Generated by spimdisasm 1.42.2 */

nonmatching cmdProcessCommands, 0x118

glabel cmdProcessCommands
    /* C480 8000B880 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* C484 8000B884 AFB2001C */  sw         $s2, 0x1C($sp)
    /* C488 8000B888 3C128005 */  lui        $s2, %hi(omCurrentObject)
    /* C48C 8000B88C 2652AC44 */  addiu      $s2, $s2, %lo(omCurrentObject)
    /* C490 8000B890 8E4E0000 */  lw         $t6, 0x0($s2)
    /* C494 8000B894 AFBF0024 */  sw         $ra, 0x24($sp)
    /* C498 8000B898 AFB30020 */  sw         $s3, 0x20($sp)
    /* C49C 8000B89C 25CF003C */  addiu      $t7, $t6, 0x3C
    /* C4A0 8000B8A0 AFB10018 */  sw         $s1, 0x18($sp)
    /* C4A4 8000B8A4 AFB00014 */  sw         $s0, 0x14($sp)
    /* C4A8 8000B8A8 AFAF002C */  sw         $t7, 0x2C($sp)
    /* C4AC 8000B8AC 8DF00000 */  lw         $s0, 0x0($t7)
    /* C4B0 8000B8B0 00808825 */  or         $s1, $a0, $zero
    /* C4B4 8000B8B4 2413FFFE */  addiu      $s3, $zero, -0x2
    /* C4B8 8000B8B8 1200002B */  beqz       $s0, .L8000B968
    /* C4BC 8000B8BC 00000000 */   nop
    /* C4C0 8000B8C0 8E190008 */  lw         $t9, 0x8($s0)
  .L8000B8C4:
    /* C4C4 8000B8C4 27280005 */  addiu      $t0, $t9, 0x5
    /* C4C8 8000B8C8 2D010005 */  sltiu      $at, $t0, 0x5
    /* C4CC 8000B8CC 1020001C */  beqz       $at, .L8000B940
    /* C4D0 8000B8D0 00084080 */   sll       $t0, $t0, 2
    /* C4D4 8000B8D4 3C018004 */  lui        $at, %hi(jtbl_80043700)
    /* C4D8 8000B8D8 00280821 */  addu       $at, $at, $t0
    /* C4DC 8000B8DC 8C283700 */  lw         $t0, %lo(jtbl_80043700)($at)
    /* C4E0 8000B8E0 01000008 */  jr         $t0
    /* C4E4 8000B8E4 00000000 */   nop
  .L8000B8E8:
    /* C4E8 8000B8E8 0C00294B */  jal        omDeleteGObj
    /* C4EC 8000B8EC 00002025 */   or        $a0, $zero, $zero
    /* C4F0 8000B8F0 10000022 */  b          .L8000B97C
    /* C4F4 8000B8F4 24020001 */   addiu     $v0, $zero, 0x1
  .L8000B8F8:
    /* C4F8 8000B8F8 0C002F51 */  jal        ohPauseObjectProcesses
    /* C4FC 8000B8FC 00002025 */   or        $a0, $zero, $zero
    /* C500 8000B900 10000017 */  b          .L8000B960
    /* C504 8000B904 8E100000 */   lw        $s0, 0x0($s0)
  .L8000B908:
    /* C508 8000B908 0C002F5E */  jal        ohResumeObjectProcesses
    /* C50C 8000B90C 00002025 */   or        $a0, $zero, $zero
    /* C510 8000B910 10000013 */  b          .L8000B960
    /* C514 8000B914 8E100000 */   lw        $s0, 0x0($s0)
  .L8000B918:
    /* C518 8000B918 8E420000 */  lw         $v0, 0x0($s2)
    /* C51C 8000B91C 8C490050 */  lw         $t1, 0x50($v0)
    /* C520 8000B920 352A0001 */  ori        $t2, $t1, 0x1
    /* C524 8000B924 1000000D */  b          .L8000B95C
    /* C528 8000B928 AC4A0050 */   sw        $t2, 0x50($v0)
  .L8000B92C:
    /* C52C 8000B92C 8E420000 */  lw         $v0, 0x0($s2)
    /* C530 8000B930 8C4B0050 */  lw         $t3, 0x50($v0)
    /* C534 8000B934 01736024 */  and        $t4, $t3, $s3
    /* C538 8000B938 10000008 */  b          .L8000B95C
    /* C53C 8000B93C AC4C0050 */   sw        $t4, 0x50($v0)
  .L8000B940:
    /* C540 8000B940 52200007 */  beql       $s1, $zero, .L8000B960
    /* C544 8000B944 8E100000 */   lw        $s0, 0x0($s0)
    /* C548 8000B948 8E040004 */  lw         $a0, 0x4($s0)
    /* C54C 8000B94C AFA40000 */  sw         $a0, 0x0($sp)
    /* C550 8000B950 8E050008 */  lw         $a1, 0x8($s0)
    /* C554 8000B954 0220F809 */  jalr       $s1
    /* C558 8000B958 AFA50004 */   sw        $a1, 0x4($sp)
  .L8000B95C:
    /* C55C 8000B95C 8E100000 */  lw         $s0, 0x0($s0)
  .L8000B960:
    /* C560 8000B960 5600FFD8 */  bnel       $s0, $zero, .L8000B8C4
    /* C564 8000B964 8E190008 */   lw        $t9, 0x8($s0)
  .L8000B968:
    /* C568 8000B968 0C002DD0 */  jal        cmdFreeObjCmd
    /* C56C 8000B96C 8FA4002C */   lw        $a0, 0x2C($sp)
    /* C570 8000B970 8FAF002C */  lw         $t7, 0x2C($sp)
    /* C574 8000B974 00001025 */  or         $v0, $zero, $zero
    /* C578 8000B978 ADE00008 */  sw         $zero, 0x8($t7)
  .L8000B97C:
    /* C57C 8000B97C 8FBF0024 */  lw         $ra, 0x24($sp)
    /* C580 8000B980 8FB00014 */  lw         $s0, 0x14($sp)
    /* C584 8000B984 8FB10018 */  lw         $s1, 0x18($sp)
    /* C588 8000B988 8FB2001C */  lw         $s2, 0x1C($sp)
    /* C58C 8000B98C 8FB30020 */  lw         $s3, 0x20($sp)
    /* C590 8000B990 03E00008 */  jr         $ra
    /* C594 8000B994 27BD0030 */   addiu     $sp, $sp, 0x30
endlabel cmdProcessCommands
