.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.2 */

nonmatching D_802E4C50_6CCA30

dlabel D_802E4C50_6CCA30
    /* 6CCA30 802E4C50 40490FDB */ .float 3.141592741
    /* 6CCA34 802E4C54 00000000 */ .float 0
    /* 6CCA38 802E4C58 00000000 */ .float 0
    /* 6CCA3C 802E4C5C 00000000 */ .float 0
enddlabel D_802E4C50_6CCA30
