.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.2 */

.align 3
nonmatching D_802E4C80_6CCA60

dlabel D_802E4C80_6CCA60
    /* 6CCA60 802E4C80 3FE6666666666666 */ .double 0.699999999999999956
    /* 6CCA68 802E4C88 0000000000000000 */ .double 0
enddlabel D_802E4C80_6CCA60
