.section .late_rodata
.align 3
nonmatching D_80393920_533D30

dlabel D_80393920_533D30
    /* 533D30 80393920 3FA0E5604189374C */ .double 0.0330000000000000016
enddlabel D_80393920_533D30


.section .text
/* Generated by spimdisasm 1.42.2 */

nonmatching Pokemon_StepWalkInDirectionFacing, 0xAC

glabel Pokemon_StepWalkInDirectionFacing
    /* 50132C 80360F1C 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* 501330 80360F20 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 501334 80360F24 AFA50034 */  sw         $a1, 0x34($sp)
    /* 501338 80360F28 8C820058 */  lw         $v0, 0x58($a0)
    /* 50133C 80360F2C 8C830048 */  lw         $v1, 0x48($a0)
    /* 501340 80360F30 8C4E008C */  lw         $t6, 0x8C($v0)
    /* 501344 80360F34 31CF0020 */  andi       $t7, $t6, 0x20
    /* 501348 80360F38 55E0001F */  bnel       $t7, $zero, .L80360FB8_5013C8
    /* 50134C 80360F3C 00001025 */   or        $v0, $zero, $zero
    /* 501350 80360F40 C4440098 */  lwc1       $f4, 0x98($v0)
    /* 501354 80360F44 3C018039 */  lui        $at, %hi(D_80393920_533D30)
    /* 501358 80360F48 D4283920 */  ldc1       $f8, %lo(D_80393920_533D30)($at)
    /* 50135C 80360F4C 460021A1 */  cvt.d.s    $f6, $f4
    /* 501360 80360F50 46283282 */  mul.d      $f10, $f6, $f8
    /* 501364 80360F54 46205420 */  cvt.s.d    $f16, $f10
    /* 501368 80360F58 E7B00024 */  swc1       $f16, 0x24($sp)
    /* 50136C 80360F5C 8C78004C */  lw         $t8, 0x4C($v1)
    /* 501370 80360F60 C70C0020 */  lwc1       $f12, 0x20($t8)
    /* 501374 80360F64 AFA40030 */  sw         $a0, 0x30($sp)
    /* 501378 80360F68 0C00CA88 */  jal        __sinf
    /* 50137C 80360F6C E7AC0020 */   swc1      $f12, 0x20($sp)
    /* 501380 80360F70 C7B20024 */  lwc1       $f18, 0x24($sp)
    /* 501384 80360F74 C7AC0020 */  lwc1       $f12, 0x20($sp)
    /* 501388 80360F78 46120102 */  mul.s      $f4, $f0, $f18
    /* 50138C 80360F7C 0C00E378 */  jal        __cosf
    /* 501390 80360F80 E7A4001C */   swc1      $f4, 0x1C($sp)
    /* 501394 80360F84 C7A60024 */  lwc1       $f6, 0x24($sp)
    /* 501398 80360F88 8FA40030 */  lw         $a0, 0x30($sp)
    /* 50139C 80360F8C 8FA5001C */  lw         $a1, 0x1C($sp)
    /* 5013A0 80360F90 46060202 */  mul.s      $f8, $f0, $f6
    /* 5013A4 80360F94 8FA70034 */  lw         $a3, 0x34($sp)
    /* 5013A8 80360F98 44064000 */  mfc1       $a2, $f8
    /* 5013AC 80360F9C 0C0D8346 */  jal        func_80360D18_501128
    /* 5013B0 80360FA0 00000000 */   nop
    /* 5013B4 80360FA4 50400004 */  beql       $v0, $zero, .L80360FB8_5013C8
    /* 5013B8 80360FA8 00001025 */   or        $v0, $zero, $zero
    /* 5013BC 80360FAC 10000002 */  b          .L80360FB8_5013C8
    /* 5013C0 80360FB0 24020001 */   addiu     $v0, $zero, 0x1
    /* 5013C4 80360FB4 00001025 */  or         $v0, $zero, $zero
  .L80360FB8_5013C8:
    /* 5013C8 80360FB8 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 5013CC 80360FBC 27BD0030 */  addiu      $sp, $sp, 0x30
    /* 5013D0 80360FC0 03E00008 */  jr         $ra
    /* 5013D4 80360FC4 00000000 */   nop
endlabel Pokemon_StepWalkInDirectionFacing
