.section .rodata
.align 2
nonmatching D_80208ED0_9D3120

dlabel D_80208ED0_9D3120
    /* 9D3120 80208ED0 */ .asciz "\\i%2d \\gTaken"
    /* 5C69253264205C6754616B656E000000 */
.align 2
enddlabel D_80208ED0_9D3120

.align 2
nonmatching D_80208EE0_9D3130

dlabel D_80208EE0_9D3130
    /* 9D3130 80208EE0 */ .asciz "\\i%2d \\gLeft"
    /* 5C69253264205C674C65667400000000 */
.align 2
enddlabel D_80208EE0_9D3130


.section .text
/* Generated by spimdisasm 1.42.2 */

nonmatching func_801E1598_9AB7E8, 0x2C0

glabel func_801E1598_9AB7E8
    /* 9AB7E8 801E1598 27BDFF88 */  addiu      $sp, $sp, -0x78
    /* 9AB7EC 801E159C AFBF0024 */  sw         $ra, 0x24($sp)
    /* 9AB7F0 801E15A0 AFA40078 */  sw         $a0, 0x78($sp)
    /* 9AB7F4 801E15A4 AFB00020 */  sw         $s0, 0x20($sp)
    /* 9AB7F8 801E15A8 240E0001 */  addiu      $t6, $zero, 0x1
    /* 9AB7FC 801E15AC AFAE005C */  sw         $t6, 0x5C($sp)
    /* 9AB800 801E15B0 0C0DC5FA */  jal        func_803717E8
    /* 9AB804 801E15B4 00000000 */   nop
    /* 9AB808 801E15B8 0C0DC10A */  jal        func_80370428
    /* 9AB80C 801E15BC 00000000 */   nop
    /* 9AB810 801E15C0 0C079021 */  jal        func_801E4084_9AE2D4
    /* 9AB814 801E15C4 00000000 */   nop
    /* 9AB818 801E15C8 0C0DC029 */  jal        func_803700A4
    /* 9AB81C 801E15CC 00002025 */   or        $a0, $zero, $zero
    /* 9AB820 801E15D0 0C0779DA */  jal        func_801DE768_9A89B8
    /* 9AB824 801E15D4 00000000 */   nop
    /* 9AB828 801E15D8 0C077A0C */  jal        func_801DE830_9A8A80
    /* 9AB82C 801E15DC 00000000 */   nop
    /* 9AB830 801E15E0 0C077B3A */  jal        func_801DECE8_9A8F38
    /* 9AB834 801E15E4 00000000 */   nop
    /* 9AB838 801E15E8 0C078434 */  jal        func_801E10D0_9AB320
    /* 9AB83C 801E15EC 00000000 */   nop
    /* 9AB840 801E15F0 0C077645 */  jal        func_801DD914_9A7B64
    /* 9AB844 801E15F4 00000000 */   nop
    /* 9AB848 801E15F8 0C07771C */  jal        func_801DDC70_9A7EC0
    /* 9AB84C 801E15FC 00002025 */   or        $a0, $zero, $zero
    /* 9AB850 801E1600 0C077540 */  jal        func_801DD500_9A7750
    /* 9AB854 801E1604 00002025 */   or        $a0, $zero, $zero
    /* 9AB858 801E1608 0C077832 */  jal        func_801DE0C8_9A8318
    /* 9AB85C 801E160C 00000000 */   nop
    /* 9AB860 801E1610 0C0778F7 */  jal        func_801DE3DC_9A862C
    /* 9AB864 801E1614 00000000 */   nop
    /* 9AB868 801E1618 0C077799 */  jal        func_801DDE64_9A80B4
    /* 9AB86C 801E161C 00000000 */   nop
    /* 9AB870 801E1620 0C07780F */  jal        func_801DE03C_9A828C
    /* 9AB874 801E1624 00002025 */   or        $a0, $zero, $zero
    /* 9AB878 801E1628 240F0400 */  addiu      $t7, $zero, 0x400
    /* 9AB87C 801E162C AFAF0010 */  sw         $t7, 0x10($sp)
    /* 9AB880 801E1630 2404007C */  addiu      $a0, $zero, 0x7C
    /* 9AB884 801E1634 24050083 */  addiu      $a1, $zero, 0x83
    /* 9AB888 801E1638 2406003C */  addiu      $a2, $zero, 0x3C
    /* 9AB88C 801E163C 0C0DAB1B */  jal        func_8036AC6C
    /* 9AB890 801E1640 24070012 */   addiu     $a3, $zero, 0x12
    /* 9AB894 801E1644 AFA20064 */  sw         $v0, 0x64($sp)
    /* 9AB898 801E1648 241800FF */  addiu      $t8, $zero, 0xFF
    /* 9AB89C 801E164C 241900FF */  addiu      $t9, $zero, 0xFF
    /* 9AB8A0 801E1650 AFB90014 */  sw         $t9, 0x14($sp)
    /* 9AB8A4 801E1654 AFB80010 */  sw         $t8, 0x10($sp)
    /* 9AB8A8 801E1658 8FA40064 */  lw         $a0, 0x64($sp)
    /* 9AB8AC 801E165C 24050001 */  addiu      $a1, $zero, 0x1
    /* 9AB8B0 801E1660 240600FF */  addiu      $a2, $zero, 0xFF
    /* 9AB8B4 801E1664 0C0DAE1C */  jal        func_8036B870
    /* 9AB8B8 801E1668 240700FF */   addiu     $a3, $zero, 0xFF
    /* 9AB8BC 801E166C 8FA40064 */  lw         $a0, 0x64($sp)
    /* 9AB8C0 801E1670 00002825 */  or         $a1, $zero, $zero
    /* 9AB8C4 801E1674 00003025 */  or         $a2, $zero, $zero
    /* 9AB8C8 801E1678 00003825 */  or         $a3, $zero, $zero
    /* 9AB8CC 801E167C AFA00010 */  sw         $zero, 0x10($sp)
    /* 9AB8D0 801E1680 0C0DAE1C */  jal        func_8036B870
    /* 9AB8D4 801E1684 AFA00014 */   sw        $zero, 0x14($sp)
    /* 9AB8D8 801E1688 0C0DB512 */  jal        func_8036D448
    /* 9AB8DC 801E168C 00002025 */   or        $a0, $zero, $zero
    /* 9AB8E0 801E1690 00002025 */  or         $a0, $zero, $zero
    /* 9AB8E4 801E1694 0C0DB4FA */  jal        func_8036D3E8
    /* 9AB8E8 801E1698 24050004 */   addiu     $a1, $zero, 0x4
    /* 9AB8EC 801E169C 0C0DADCD */  jal        func_8036B734
    /* 9AB8F0 801E16A0 8FA40064 */   lw        $a0, 0x64($sp)
    /* 9AB8F4 801E16A4 8FA40064 */  lw         $a0, 0x64($sp)
    /* 9AB8F8 801E16A8 0C0DB2D6 */  jal        func_8036CB58
    /* 9AB8FC 801E16AC 24050008 */   addiu     $a1, $zero, 0x8
    /* 9AB900 801E16B0 8FA40064 */  lw         $a0, 0x64($sp)
    /* 9AB904 801E16B4 2405000A */  addiu      $a1, $zero, 0xA
    /* 9AB908 801E16B8 0C0DAE7B */  jal        func_8036B9EC
    /* 9AB90C 801E16BC 00003025 */   or        $a2, $zero, $zero
    /* 9AB910 801E16C0 0C078EAE */  jal        func_801E3AB8_9ADD08
    /* 9AB914 801E16C4 00000000 */   nop
    /* 9AB918 801E16C8 00408025 */  or         $s0, $v0, $zero
    /* 9AB91C 801E16CC 3C058021 */  lui        $a1, %hi(D_80208ED0_9D3120)
    /* 9AB920 801E16D0 24A58ED0 */  addiu      $a1, $a1, %lo(D_80208ED0_9D3120)
    /* 9AB924 801E16D4 02003025 */  or         $a2, $s0, $zero
    /* 9AB928 801E16D8 0C0DD467 */  jal        func_8037519C
    /* 9AB92C 801E16DC 8FA40064 */   lw        $a0, 0x64($sp)
    /* 9AB930 801E16E0 8FA40064 */  lw         $a0, 0x64($sp)
    /* 9AB934 801E16E4 2405000A */  addiu      $a1, $zero, 0xA
    /* 9AB938 801E16E8 0C0DAE7B */  jal        func_8036B9EC
    /* 9AB93C 801E16EC 24060009 */   addiu     $a2, $zero, 0x9
    /* 9AB940 801E16F0 0C078EAE */  jal        func_801E3AB8_9ADD08
    /* 9AB944 801E16F4 00000000 */   nop
    /* 9AB948 801E16F8 00408025 */  or         $s0, $v0, $zero
    /* 9AB94C 801E16FC 3C058021 */  lui        $a1, %hi(D_80208EE0_9D3130)
    /* 9AB950 801E1700 2408003C */  addiu      $t0, $zero, 0x3C
    /* 9AB954 801E1704 01103023 */  subu       $a2, $t0, $s0
    /* 9AB958 801E1708 24A58EE0 */  addiu      $a1, $a1, %lo(D_80208EE0_9D3130)
    /* 9AB95C 801E170C 0C0DD467 */  jal        func_8037519C
    /* 9AB960 801E1710 8FA40064 */   lw        $a0, 0x64($sp)
    /* 9AB964 801E1714 8FA40064 */  lw         $a0, 0x64($sp)
    /* 9AB968 801E1718 0C0DB469 */  jal        func_8036D1A4
    /* 9AB96C 801E171C 24050001 */   addiu     $a1, $zero, 0x1
    /* 9AB970 801E1720 0C002F2A */  jal        ohWait
    /* 9AB974 801E1724 24040001 */   addiu     $a0, $zero, 0x1
    /* 9AB978 801E1728 8FA90064 */  lw         $t1, 0x64($sp)
    /* 9AB97C 801E172C 3C018025 */  lui        $at, %hi(D_8024FFF4_A1A244)
    /* 9AB980 801E1730 AC29FFF4 */  sw         $t1, %lo(D_8024FFF4_A1A244)($at)
    /* 9AB984 801E1734 3C048025 */  lui        $a0, %hi(D_8024FFF4_A1A244)
    /* 9AB988 801E1738 8C84FFF4 */  lw         $a0, %lo(D_8024FFF4_A1A244)($a0)
    /* 9AB98C 801E173C 0C0DB469 */  jal        func_8036D1A4
    /* 9AB990 801E1740 00002825 */   or        $a1, $zero, $zero
    /* 9AB994 801E1744 AFA0006C */  sw         $zero, 0x6C($sp)
  .L801E1748_9AB998:
    /* 9AB998 801E1748 8FA5006C */  lw         $a1, 0x6C($sp)
    /* 9AB99C 801E174C 3C048025 */  lui        $a0, %hi(D_8024FFF4_A1A244)
    /* 9AB9A0 801E1750 8C84FFF4 */  lw         $a0, %lo(D_8024FFF4_A1A244)($a0)
    /* 9AB9A4 801E1754 00A00821 */  addu       $at, $a1, $zero
    /* 9AB9A8 801E1758 00012A00 */  sll        $a1, $at, 8
    /* 9AB9AC 801E175C 00A12823 */  subu       $a1, $a1, $at
    /* 9AB9B0 801E1760 2401003C */  addiu      $at, $zero, 0x3C
    /* 9AB9B4 801E1764 00A1001A */  div        $zero, $a1, $at
    /* 9AB9B8 801E1768 00002812 */  mflo       $a1
    /* 9AB9BC 801E176C 0C0775A1 */  jal        func_801DD684_9A78D4
    /* 9AB9C0 801E1770 00000000 */   nop
    /* 9AB9C4 801E1774 8FA4006C */  lw         $a0, 0x6C($sp)
    /* 9AB9C8 801E1778 00800821 */  addu       $at, $a0, $zero
    /* 9AB9CC 801E177C 00012200 */  sll        $a0, $at, 8
    /* 9AB9D0 801E1780 00812023 */  subu       $a0, $a0, $at
    /* 9AB9D4 801E1784 2401003C */  addiu      $at, $zero, 0x3C
    /* 9AB9D8 801E1788 0081001A */  div        $zero, $a0, $at
    /* 9AB9DC 801E178C 00002012 */  mflo       $a0
    /* 9AB9E0 801E1790 0C077501 */  jal        func_801DD404_9A7654
    /* 9AB9E4 801E1794 00000000 */   nop
    /* 9AB9E8 801E1798 0C002F2A */  jal        ohWait
    /* 9AB9EC 801E179C 24040001 */   addiu     $a0, $zero, 0x1
    /* 9AB9F0 801E17A0 8FAA006C */  lw         $t2, 0x6C($sp)
    /* 9AB9F4 801E17A4 254B0001 */  addiu      $t3, $t2, 0x1
    /* 9AB9F8 801E17A8 2961003C */  slti       $at, $t3, 0x3C
    /* 9AB9FC 801E17AC 1420FFE6 */  bnez       $at, .L801E1748_9AB998
    /* 9ABA00 801E17B0 AFAB006C */   sw        $t3, 0x6C($sp)
    /* 9ABA04 801E17B4 0C077501 */  jal        func_801DD404_9A7654
    /* 9ABA08 801E17B8 240400FF */   addiu     $a0, $zero, 0xFF
    /* 9ABA0C 801E17BC 0C0DC5CB */  jal        func_8037172C
    /* 9ABA10 801E17C0 24040001 */   addiu     $a0, $zero, 0x1
    /* 9ABA14 801E17C4 0C0DC4F2 */  jal        func_803713C8
    /* 9ABA18 801E17C8 00002025 */   or        $a0, $zero, $zero
    /* 9ABA1C 801E17CC 0C002F2A */  jal        ohWait
    /* 9ABA20 801E17D0 2404001E */   addiu     $a0, $zero, 0x1E
    /* 9ABA24 801E17D4 0C078640 */  jal        func_801E1900_9ABB50
    /* 9ABA28 801E17D8 00000000 */   nop
    /* 9ABA2C 801E17DC 00408025 */  or         $s0, $v0, $zero
    /* 9ABA30 801E17E0 0C0DC30D */  jal        func_80370C34
    /* 9ABA34 801E17E4 02002025 */   or        $a0, $s0, $zero
    /* 9ABA38 801E17E8 0C0DC169 */  jal        func_803705A4
    /* 9ABA3C 801E17EC 00000000 */   nop
    /* 9ABA40 801E17F0 0C0DC029 */  jal        func_803700A4
    /* 9ABA44 801E17F4 24040001 */   addiu     $a0, $zero, 0x1
    /* 9ABA48 801E17F8 00008025 */  or         $s0, $zero, $zero
    /* 9ABA4C 801E17FC 0C0DB528 */  jal        func_8036D4A0
    /* 9ABA50 801E1800 02002025 */   or        $a0, $s0, $zero
  .L801E1804_9ABA54:
    /* 9ABA54 801E1804 0C078DE8 */  jal        func_801E37A0_9AD9F0
    /* 9ABA58 801E1808 00000000 */   nop
    /* 9ABA5C 801E180C 0C0DC5CB */  jal        func_8037172C
    /* 9ABA60 801E1810 00002025 */   or        $a0, $zero, $zero
    /* 9ABA64 801E1814 0C0DD348 */  jal        func_80374D20
    /* 9ABA68 801E1818 00000000 */   nop
    /* 9ABA6C 801E181C 3C018021 */  lui        $at, %hi(D_80208B74_9D2DC4)
    /* 9ABA70 801E1820 AC208B74 */  sw         $zero, %lo(D_80208B74_9D2DC4)($at)
    /* 9ABA74 801E1824 0C02AB7C */  jal        func_800AADF0
    /* 9ABA78 801E1828 2404000D */   addiu     $a0, $zero, 0xD
    /* 9ABA7C 801E182C 0C002F2A */  jal        ohWait
    /* 9ABA80 801E1830 24040001 */   addiu     $a0, $zero, 0x1
    /* 9ABA84 801E1834 1000FFF3 */  b          .L801E1804_9ABA54
    /* 9ABA88 801E1838 00000000 */   nop
    /* 9ABA8C 801E183C 10000001 */  b          .L801E1844_9ABA94
    /* 9ABA90 801E1840 00000000 */   nop
  .L801E1844_9ABA94:
    /* 9ABA94 801E1844 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 9ABA98 801E1848 8FB00020 */  lw         $s0, 0x20($sp)
    /* 9ABA9C 801E184C 27BD0078 */  addiu      $sp, $sp, 0x78
    /* 9ABAA0 801E1850 03E00008 */  jr         $ra
    /* 9ABAA4 801E1854 00000000 */   nop
endlabel func_801E1598_9AB7E8
