.section .rodata
.align 2
nonmatching D_80208EA8_9D30F8

dlabel D_80208EA8_9D30F8
    /* 9D30F8 80208EA8 */ .asciz "Delete this picture?\n\n"
    /* 44656C657465207468697320706963747572653F0A0A0000 */
.align 2
enddlabel D_80208EA8_9D30F8

.align 2
nonmatching D_80208EC0_9D3110

dlabel D_80208EC0_9D3110
    /* 9D3110 80208EC0 */ .asciz "\\a Yes   \\b No"
    /* 5C61205965732020205C62204E6F0000 */
.align 2
enddlabel D_80208EC0_9D3110


.section .text
/* Generated by spimdisasm 1.42.0 */

nonmatching func_801E1168_9AB3B8, 0x1B8

glabel func_801E1168_9AB3B8
    /* 9AB3B8 801E1168 27BDFFC0 */  addiu      $sp, $sp, -0x40
    /* 9AB3BC 801E116C AFBF0024 */  sw         $ra, 0x24($sp)
    /* 9AB3C0 801E1170 AFA40040 */  sw         $a0, 0x40($sp)
    /* 9AB3C4 801E1174 AFB00020 */  sw         $s0, 0x20($sp)
    /* 9AB3C8 801E1178 8FAE0040 */  lw         $t6, 0x40($sp)
    /* 9AB3CC 801E117C 11C00056 */  beqz       $t6, .L801E12D8_9AB528
    /* 9AB3D0 801E1180 00000000 */   nop
    /* 9AB3D4 801E1184 0C0DBDE3 */  jal        UIFrame_Create
    /* 9AB3D8 801E1188 00000000 */   nop
    /* 9AB3DC 801E118C AFA20034 */  sw         $v0, 0x34($sp)
    /* 9AB3E0 801E1190 8FAF0034 */  lw         $t7, 0x34($sp)
    /* 9AB3E4 801E1194 3C018025 */  lui        $at, %hi(D_8025005C_A1A2AC)
    /* 9AB3E8 801E1198 AC2F005C */  sw         $t7, %lo(D_8025005C_A1A2AC)($at)
    /* 9AB3EC 801E119C 8FA40034 */  lw         $a0, 0x34($sp)
    /* 9AB3F0 801E11A0 240500B8 */  addiu      $a1, $zero, 0xB8
    /* 9AB3F4 801E11A4 0C0DBC7D */  jal        func_8036F1F4
    /* 9AB3F8 801E11A8 24060140 */   addiu     $a2, $zero, 0x140
    /* 9AB3FC 801E11AC 8FA40034 */  lw         $a0, 0x34($sp)
    /* 9AB400 801E11B0 0C0DBC37 */  jal        func_8036F0DC
    /* 9AB404 801E11B4 00002825 */   or        $a1, $zero, $zero
    /* 9AB408 801E11B8 24040068 */  addiu      $a0, $zero, 0x68
    /* 9AB40C 801E11BC 240500AD */  addiu      $a1, $zero, 0xAD
    /* 9AB410 801E11C0 240600C0 */  addiu      $a2, $zero, 0xC0
    /* 9AB414 801E11C4 2407002F */  addiu      $a3, $zero, 0x2F
    /* 9AB418 801E11C8 0C0DAB1B */  jal        func_8036AC6C
    /* 9AB41C 801E11CC AFA00010 */   sw        $zero, 0x10($sp)
    /* 9AB420 801E11D0 AFA20030 */  sw         $v0, 0x30($sp)
    /* 9AB424 801E11D4 8FB80030 */  lw         $t8, 0x30($sp)
    /* 9AB428 801E11D8 3C018025 */  lui        $at, %hi(D_80250000_A1A250)
    /* 9AB42C 801E11DC AC380000 */  sw         $t8, %lo(D_80250000_A1A250)($at)
    /* 9AB430 801E11E0 241900FF */  addiu      $t9, $zero, 0xFF
    /* 9AB434 801E11E4 240800FF */  addiu      $t0, $zero, 0xFF
    /* 9AB438 801E11E8 AFA80014 */  sw         $t0, 0x14($sp)
    /* 9AB43C 801E11EC AFB90010 */  sw         $t9, 0x10($sp)
    /* 9AB440 801E11F0 8FA40030 */  lw         $a0, 0x30($sp)
    /* 9AB444 801E11F4 24050001 */  addiu      $a1, $zero, 0x1
    /* 9AB448 801E11F8 240600FF */  addiu      $a2, $zero, 0xFF
    /* 9AB44C 801E11FC 0C0DAE1C */  jal        func_8036B870
    /* 9AB450 801E1200 240700FF */   addiu     $a3, $zero, 0xFF
    /* 9AB454 801E1204 24090046 */  addiu      $t1, $zero, 0x46
    /* 9AB458 801E1208 240A00FF */  addiu      $t2, $zero, 0xFF
    /* 9AB45C 801E120C AFAA0014 */  sw         $t2, 0x14($sp)
    /* 9AB460 801E1210 AFA90010 */  sw         $t1, 0x10($sp)
    /* 9AB464 801E1214 8FA40030 */  lw         $a0, 0x30($sp)
    /* 9AB468 801E1218 00002825 */  or         $a1, $zero, $zero
    /* 9AB46C 801E121C 240600A3 */  addiu      $a2, $zero, 0xA3
    /* 9AB470 801E1220 0C0DAE1C */  jal        func_8036B870
    /* 9AB474 801E1224 24070046 */   addiu     $a3, $zero, 0x46
    /* 9AB478 801E1228 0C0DADCD */  jal        func_8036B734
    /* 9AB47C 801E122C 8FA40030 */   lw        $a0, 0x30($sp)
    /* 9AB480 801E1230 8FA40030 */  lw         $a0, 0x30($sp)
    /* 9AB484 801E1234 0C0DB469 */  jal        func_8036D1A4
    /* 9AB488 801E1238 24050001 */   addiu     $a1, $zero, 0x1
    /* 9AB48C 801E123C 0C002F2A */  jal        ohWait
    /* 9AB490 801E1240 24040001 */   addiu     $a0, $zero, 0x1
    /* 9AB494 801E1244 8FA40030 */  lw         $a0, 0x30($sp)
    /* 9AB498 801E1248 0C0DB2D6 */  jal        func_8036CB58
    /* 9AB49C 801E124C 2405000C */   addiu     $a1, $zero, 0xC
    /* 9AB4A0 801E1250 0C0DB512 */  jal        func_8036D448
    /* 9AB4A4 801E1254 24040001 */   addiu     $a0, $zero, 0x1
    /* 9AB4A8 801E1258 2404FFFF */  addiu      $a0, $zero, -0x1
    /* 9AB4AC 801E125C 0C0DB4FA */  jal        func_8036D3E8
    /* 9AB4B0 801E1260 24050003 */   addiu     $a1, $zero, 0x3
    /* 9AB4B4 801E1264 8FA40030 */  lw         $a0, 0x30($sp)
    /* 9AB4B8 801E1268 00002825 */  or         $a1, $zero, $zero
    /* 9AB4BC 801E126C 0C0DAE7B */  jal        func_8036B9EC
    /* 9AB4C0 801E1270 00003025 */   or        $a2, $zero, $zero
    /* 9AB4C4 801E1274 3C058021 */  lui        $a1, %hi(D_80208EA8_9D30F8)
    /* 9AB4C8 801E1278 24A58EA8 */  addiu      $a1, $a1, %lo(D_80208EA8_9D30F8)
    /* 9AB4CC 801E127C 0C0DB226 */  jal        func_8036C898
    /* 9AB4D0 801E1280 8FA40030 */   lw        $a0, 0x30($sp)
    /* 9AB4D4 801E1284 0C002F2A */  jal        ohWait
    /* 9AB4D8 801E1288 24040001 */   addiu     $a0, $zero, 0x1
    /* 9AB4DC 801E128C 8FA40034 */  lw         $a0, 0x34($sp)
    /* 9AB4E0 801E1290 0C0DBF95 */  jal        func_8036FE54
    /* 9AB4E4 801E1294 00002825 */   or        $a1, $zero, $zero
    /* 9AB4E8 801E1298 8FA40030 */  lw         $a0, 0x30($sp)
    /* 9AB4EC 801E129C 0C0DB469 */  jal        func_8036D1A4
    /* 9AB4F0 801E12A0 00002825 */   or        $a1, $zero, $zero
    /* 9AB4F4 801E12A4 00008025 */  or         $s0, $zero, $zero
    /* 9AB4F8 801E12A8 0C0DB528 */  jal        func_8036D4A0
    /* 9AB4FC 801E12AC 02002025 */   or        $a0, $s0, $zero
    /* 9AB500 801E12B0 8FA40030 */  lw         $a0, 0x30($sp)
    /* 9AB504 801E12B4 00002825 */  or         $a1, $zero, $zero
    /* 9AB508 801E12B8 0C0DAE7B */  jal        func_8036B9EC
    /* 9AB50C 801E12BC 24060020 */   addiu     $a2, $zero, 0x20
    /* 9AB510 801E12C0 3C058021 */  lui        $a1, %hi(D_80208EC0_9D3110)
    /* 9AB514 801E12C4 24A58EC0 */  addiu      $a1, $a1, %lo(D_80208EC0_9D3110)
    /* 9AB518 801E12C8 0C0DB226 */  jal        func_8036C898
    /* 9AB51C 801E12CC 8FA40030 */   lw        $a0, 0x30($sp)
    /* 9AB520 801E12D0 1000000C */  b          .L801E1304_9AB554
    /* 9AB524 801E12D4 00000000 */   nop
  .L801E12D8_9AB528:
    /* 9AB528 801E12D8 3C048025 */  lui        $a0, %hi(D_80250000_A1A250)
    /* 9AB52C 801E12DC 0C0DAA39 */  jal        func_8036A8E4
    /* 9AB530 801E12E0 8C840000 */   lw        $a0, %lo(D_80250000_A1A250)($a0)
    /* 9AB534 801E12E4 3C048025 */  lui        $a0, %hi(D_80250000_A1A250)
    /* 9AB538 801E12E8 0C0DAD7C */  jal        func_8036B5F0
    /* 9AB53C 801E12EC 8C840000 */   lw        $a0, %lo(D_80250000_A1A250)($a0)
    /* 9AB540 801E12F0 3C048025 */  lui        $a0, %hi(D_8025005C_A1A2AC)
    /* 9AB544 801E12F4 0C0DBFC8 */  jal        func_8036FF20
    /* 9AB548 801E12F8 8C84005C */   lw        $a0, %lo(D_8025005C_A1A2AC)($a0)
    /* 9AB54C 801E12FC 0C002F2A */  jal        ohWait
    /* 9AB550 801E1300 24040015 */   addiu     $a0, $zero, 0x15
  .L801E1304_9AB554:
    /* 9AB554 801E1304 10000001 */  b          .L801E130C_9AB55C
    /* 9AB558 801E1308 00000000 */   nop
  .L801E130C_9AB55C:
    /* 9AB55C 801E130C 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 9AB560 801E1310 8FB00020 */  lw         $s0, 0x20($sp)
    /* 9AB564 801E1314 27BD0040 */  addiu      $sp, $sp, 0x40
    /* 9AB568 801E1318 03E00008 */  jr         $ra
    /* 9AB56C 801E131C 00000000 */   nop
endlabel func_801E1168_9AB3B8
