.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.42.1 */

nonmatching growlithe_spawner_modelanim

dlabel growlithe_spawner_modelanim
    /* 33A5E0 80113960 00000000 */ .word 0x00000000
    /* 33A5E4 80113964 80113968 */ .word D_80113968_33A5E8
enddlabel growlithe_spawner_modelanim

nonmatching D_80113968_33A5E8

dlabel D_80113968_33A5E8
    /* 33A5E8 80113968 06100000 */ .word 0x06100000
    /* 33A5EC 8011396C 00000000 */ .word 0x00000000
    /* 33A5F0 80113970 06100032 */ .word 0x06100032
    /* 33A5F4 80113974 41D22A68 */ .word 0x41D22A68
    /* 33A5F8 80113978 06100032 */ .word 0x06100032
    /* 33A5FC 8011397C 00000000 */ .word 0x00000000
    /* 33A600 80113980 1C000000 */ .word 0x1C000000
    /* 33A604 80113984 80113968 */ .word D_80113968_33A5E8
    /* 33A608 80113988 00000000 */ .word 0x00000000
    /* 33A60C 8011398C 00000000 */ .word 0x00000000
enddlabel D_80113968_33A5E8
