.section .late_rodata
nonmatching D_8034B680_82ADF0

dlabel D_8034B680_82ADF0
    /* 82ADF0 8034B680 40C90FDB */ .float 6.283185482
enddlabel D_8034B680_82ADF0

nonmatching D_8034B684_82ADF4

dlabel D_8034B684_82ADF4
    /* 82ADF4 8034B684 40490FDB */ .float 3.141592741
enddlabel D_8034B684_82ADF4


.section .text
/* Generated by spimdisasm 1.42.2 */

nonmatching func_803471D4_826944, 0x160

glabel func_803471D4_826944
    /* 826944 803471D4 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 826948 803471D8 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 82694C 803471DC AFB10018 */  sw         $s1, 0x18($sp)
    /* 826950 803471E0 AFB00014 */  sw         $s0, 0x14($sp)
    /* 826954 803471E4 8C900058 */  lw         $s0, 0x58($a0)
    /* 826958 803471E8 2401FFFB */  addiu      $at, $zero, -0x5
    /* 82695C 803471EC 3C098035 */  lui        $t1, %hi(D_8034AE10_82A580)
    /* 826960 803471F0 AE000010 */  sw         $zero, 0x10($s0)
    /* 826964 803471F4 8C8E0050 */  lw         $t6, 0x50($a0)
    /* 826968 803471F8 241800B4 */  addiu      $t8, $zero, 0xB4
    /* 82696C 803471FC 2529AE10 */  addiu      $t1, $t1, %lo(D_8034AE10_82A580)
    /* 826970 80347200 35CF0003 */  ori        $t7, $t6, 0x3
    /* 826974 80347204 AC8F0050 */  sw         $t7, 0x50($a0)
    /* 826978 80347208 8E19008C */  lw         $t9, 0x8C($s0)
    /* 82697C 8034720C 00808825 */  or         $s1, $a0, $zero
    /* 826980 80347210 24050004 */  addiu      $a1, $zero, 0x4
    /* 826984 80347214 03214024 */  and        $t0, $t9, $at
    /* 826988 80347218 AE08008C */  sw         $t0, 0x8C($s0)
    /* 82698C 8034721C AE180090 */  sw         $t8, 0x90($s0)
    /* 826990 80347220 0C0D7EFC */  jal        Pokemon_WaitForFlag
    /* 826994 80347224 AE0900AC */   sw        $t1, 0xAC($s0)
    /* 826998 80347228 0C006785 */  jal        randRange
    /* 82699C 8034722C 24040168 */   addiu     $a0, $zero, 0x168
    /* 8269A0 80347230 44822000 */  mtc1       $v0, $f4
    /* 8269A4 80347234 3C018035 */  lui        $at, %hi(D_8034B680_82ADF0)
    /* 8269A8 80347238 C428B680 */  lwc1       $f8, %lo(D_8034B680_82ADF0)($at)
    /* 8269AC 8034723C 468021A0 */  cvt.s.w    $f6, $f4
    /* 8269B0 80347240 3C0143B4 */  lui        $at, (0x43B40000 >> 16)
    /* 8269B4 80347244 44818000 */  mtc1       $at, $f16
    /* 8269B8 80347248 3C018035 */  lui        $at, %hi(D_8034AE50_82A5C0)
    /* 8269BC 8034724C 240400B4 */  addiu      $a0, $zero, 0xB4
    /* 8269C0 80347250 46083282 */  mul.s      $f10, $f6, $f8
    /* 8269C4 80347254 46105483 */  div.s      $f18, $f10, $f16
    /* 8269C8 80347258 0C006785 */  jal        randRange
    /* 8269CC 8034725C E432AE50 */   swc1      $f18, %lo(D_8034AE50_82A5C0)($at)
    /* 8269D0 80347260 44822000 */  mtc1       $v0, $f4
    /* 8269D4 80347264 3C018035 */  lui        $at, %hi(D_8034B684_82ADF4)
    /* 8269D8 80347268 C428B684 */  lwc1       $f8, %lo(D_8034B684_82ADF4)($at)
    /* 8269DC 8034726C 468021A0 */  cvt.s.w    $f6, $f4
    /* 8269E0 80347270 3C014334 */  lui        $at, (0x43340000 >> 16)
    /* 8269E4 80347274 44818000 */  mtc1       $at, $f16
    /* 8269E8 80347278 3C018035 */  lui        $at, %hi(D_8034AE58_82A5C8)
    /* 8269EC 8034727C 3C048035 */  lui        $a0, %hi(D_8034AB98_82A308)
    /* 8269F0 80347280 8C84AB98 */  lw         $a0, %lo(D_8034AB98_82A308)($a0)
    /* 8269F4 80347284 46083282 */  mul.s      $f10, $f6, $f8
    /* 8269F8 80347288 2405001E */  addiu      $a1, $zero, 0x1E
    /* 8269FC 8034728C 02203025 */  or         $a2, $s1, $zero
    /* 826A00 80347290 46105483 */  div.s      $f18, $f10, $f16
    /* 826A04 80347294 0C002DDD */  jal        cmdSendCommand
    /* 826A08 80347298 E432AE58 */   swc1      $f18, %lo(D_8034AE58_82A5C8)($at)
    /* 826A0C 8034729C 3C058034 */  lui        $a1, %hi(func_80347398_826B08)
    /* 826A10 803472A0 24A57398 */  addiu      $a1, $a1, %lo(func_80347398_826B08)
    /* 826A14 803472A4 0C0D7B7E */  jal        Pokemon_StartPathProc
    /* 826A18 803472A8 02202025 */   or        $a0, $s1, $zero
    /* 826A1C 803472AC 8E0B008C */  lw         $t3, 0x8C($s0)
    /* 826A20 803472B0 2401FFFB */  addiu      $at, $zero, -0x5
    /* 826A24 803472B4 3C0D8035 */  lui        $t5, %hi(D_8034AE10_82A580)
    /* 826A28 803472B8 240A0001 */  addiu      $t2, $zero, 0x1
    /* 826A2C 803472BC 25ADAE10 */  addiu      $t5, $t5, %lo(D_8034AE10_82A580)
    /* 826A30 803472C0 01616024 */  and        $t4, $t3, $at
    /* 826A34 803472C4 AE0C008C */  sw         $t4, 0x8C($s0)
    /* 826A38 803472C8 AE0A0090 */  sw         $t2, 0x90($s0)
    /* 826A3C 803472CC AE0D00AC */  sw         $t5, 0xAC($s0)
    /* 826A40 803472D0 02202025 */  or         $a0, $s1, $zero
    /* 826A44 803472D4 0C0D7EFC */  jal        Pokemon_WaitForFlag
    /* 826A48 803472D8 24050004 */   addiu     $a1, $zero, 0x4
    /* 826A4C 803472DC 240E0001 */  addiu      $t6, $zero, 0x1
    /* 826A50 803472E0 AE0E0010 */  sw         $t6, 0x10($s0)
    /* 826A54 803472E4 3C058035 */  lui        $a1, %hi(D_8034ACD8_82A448)
    /* 826A58 803472E8 AE200050 */  sw         $zero, 0x50($s1)
    /* 826A5C 803472EC 24A5ACD8 */  addiu      $a1, $a1, %lo(D_8034ACD8_82A448)
    /* 826A60 803472F0 0C0D7C57 */  jal        Pokemon_ForceAnimation
    /* 826A64 803472F4 02202025 */   or        $a0, $s1, $zero
    /* 826A68 803472F8 3C0F8035 */  lui        $t7, %hi(D_8034AD50_82A4C0)
    /* 826A6C 803472FC 25EFAD50 */  addiu      $t7, $t7, %lo(D_8034AD50_82A4C0)
    /* 826A70 80347300 AE0F00AC */  sw         $t7, 0xAC($s0)
    /* 826A74 80347304 02202025 */  or         $a0, $s1, $zero
    /* 826A78 80347308 0C0D7EFC */  jal        Pokemon_WaitForFlag
    /* 826A7C 8034730C 24050001 */   addiu     $a1, $zero, 0x1
    /* 826A80 80347310 3C058034 */  lui        $a1, %hi(func_80347334_826AA4)
    /* 826A84 80347314 24A57334 */  addiu      $a1, $a1, %lo(func_80347334_826AA4)
    /* 826A88 80347318 0C0D7B16 */  jal        Pokemon_SetState
    /* 826A8C 8034731C 02202025 */   or        $a0, $s1, $zero
    /* 826A90 80347320 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 826A94 80347324 8FB00014 */  lw         $s0, 0x14($sp)
    /* 826A98 80347328 8FB10018 */  lw         $s1, 0x18($sp)
    /* 826A9C 8034732C 03E00008 */  jr         $ra
    /* 826AA0 80347330 27BD0020 */   addiu     $sp, $sp, 0x20
endlabel func_803471D4_826944
