.section .late_rodata
nonmatching D_802F0360_5ED430

dlabel D_802F0360_5ED430
    /* 5ED430 802F0360 3EB33333 */ .float 0.349999994
    /* 5ED434 802F0364 00000000 */ .float 0
    /* 5ED438 802F0368 00000000 */ .float 0
    /* 5ED43C 802F036C 00000000 */ .float 0
enddlabel D_802F0360_5ED430


.section .text
/* Generated by spimdisasm 1.42.2 */

nonmatching func_802E58B0_5E2980, 0xB8

glabel func_802E58B0_5E2980
    /* 5E2980 802E58B0 27BDFFB8 */  addiu      $sp, $sp, -0x48
    /* 5E2984 802E58B4 AFBF002C */  sw         $ra, 0x2C($sp)
    /* 5E2988 802E58B8 AFB20028 */  sw         $s2, 0x28($sp)
    /* 5E298C 802E58BC AFB10024 */  sw         $s1, 0x24($sp)
    /* 5E2990 802E58C0 AFB00020 */  sw         $s0, 0x20($sp)
    /* 5E2994 802E58C4 F7B40018 */  sdc1       $f20, 0x18($sp)
    /* 5E2998 802E58C8 8C8E0058 */  lw         $t6, 0x58($a0)
    /* 5E299C 802E58CC 3C01802F */  lui        $at, %hi(D_802F0360_5ED430)
    /* 5E29A0 802E58D0 C4340360 */  lwc1       $f20, %lo(D_802F0360_5ED430)($at)
    /* 5E29A4 802E58D4 27B00034 */  addiu      $s0, $sp, 0x34
    /* 5E29A8 802E58D8 27B10030 */  addiu      $s1, $sp, 0x30
    /* 5E29AC 802E58DC 24120005 */  addiu      $s2, $zero, 0x5
    /* 5E29B0 802E58E0 AFAE0038 */  sw         $t6, 0x38($sp)
    /* 5E29B4 802E58E4 02002025 */  or         $a0, $s0, $zero
  .L802E58E8_5E29B8:
    /* 5E29B8 802E58E8 0C0D5CE1 */  jal        getLevelProgress
    /* 5E29BC 802E58EC 02202825 */   or        $a1, $s1, $zero
    /* 5E29C0 802E58F0 8FA20034 */  lw         $v0, 0x34($sp)
    /* 5E29C4 802E58F4 C7A40030 */  lwc1       $f4, 0x30($sp)
    /* 5E29C8 802E58F8 28410006 */  slti       $at, $v0, 0x6
    /* 5E29CC 802E58FC 5020000C */  beql       $at, $zero, .L802E5930_5E2A00
    /* 5E29D0 802E5900 8FAF0038 */   lw        $t7, 0x38($sp)
    /* 5E29D4 802E5904 14520005 */  bne        $v0, $s2, .L802E591C_5E29EC
    /* 5E29D8 802E5908 00000000 */   nop
    /* 5E29DC 802E590C 4604A03E */  c.le.s     $f20, $f4
    /* 5E29E0 802E5910 00000000 */  nop
    /* 5E29E4 802E5914 45030006 */  bc1tl      .L802E5930_5E2A00
    /* 5E29E8 802E5918 8FAF0038 */   lw        $t7, 0x38($sp)
  .L802E591C_5E29EC:
    /* 5E29EC 802E591C 0C002F2A */  jal        ohWait
    /* 5E29F0 802E5920 24040001 */   addiu     $a0, $zero, 0x1
    /* 5E29F4 802E5924 1000FFF0 */  b          .L802E58E8_5E29B8
    /* 5E29F8 802E5928 02002025 */   or        $a0, $s0, $zero
    /* 5E29FC 802E592C 8FAF0038 */  lw         $t7, 0x38($sp)
  .L802E5930_5E2A00:
    /* 5E2A00 802E5930 00002025 */  or         $a0, $zero, $zero
    /* 5E2A04 802E5934 8DF8008C */  lw         $t8, 0x8C($t7)
    /* 5E2A08 802E5938 37190002 */  ori        $t9, $t8, 0x2
    /* 5E2A0C 802E593C ADF9008C */  sw         $t9, 0x8C($t7)
    /* 5E2A10 802E5940 8FA80038 */  lw         $t0, 0x38($sp)
    /* 5E2A14 802E5944 0C0023CB */  jal        omEndProcess
    /* 5E2A18 802E5948 AD000094 */   sw        $zero, 0x94($t0)
    /* 5E2A1C 802E594C 8FBF002C */  lw         $ra, 0x2C($sp)
    /* 5E2A20 802E5950 D7B40018 */  ldc1       $f20, 0x18($sp)
    /* 5E2A24 802E5954 8FB00020 */  lw         $s0, 0x20($sp)
    /* 5E2A28 802E5958 8FB10024 */  lw         $s1, 0x24($sp)
    /* 5E2A2C 802E595C 8FB20028 */  lw         $s2, 0x28($sp)
    /* 5E2A30 802E5960 03E00008 */  jr         $ra
    /* 5E2A34 802E5964 27BD0048 */   addiu     $sp, $sp, 0x48
endlabel func_802E58B0_5E2980
