#include "common.h"

Gfx moltres_hd_part13_draw[] = {
    gsDPPipeSync(),
    gsDPSetAlphaCompare(G_AC_THRESHOLD),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_TEX_EDGE2),
    gsDPSetTile(G_IM_FMT_CI, G_IM_SIZ_16b, 0, 0x0000, G_TX_LOADTILE, 0, G_TX_NOMIRROR | G_TX_WRAP, 5, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_WRAP, 5, G_TX_NOLOD),
    gsDPSetTile(G_IM_FMT_CI, G_IM_SIZ_4b, 2, 0x0000, G_TX_RENDERTILE, 0, G_TX_NOMIRROR | G_TX_CLAMP, 5, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_CLAMP, 5, G_TX_NOLOD),
    gsDPSetTextureImage(G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, moltres_tex_flame_frame0_pal),
    gsDPLoadSync(),
    gsDPLoadTLUTCmd(5, 15),
    gsDPPipeSync(),
    gsDPSetTileSize(G_TX_RENDERTILE, 0, 0, 0x01FC, 0x007C),
    gsSPDisplayList(D_0E000000),
    gsDPLoadSync(),
    gsDPLoadBlock(G_TX_LOADTILE, 0, 0, 255, 1024),
    gsDPPipeSync(),
    gsSPModifyVertex(30, G_MWO_POINT_ST, 0x06DA0000),
    gsSPModifyVertex(31, G_MWO_POINT_ST, 0x06DA03FE),
    gsSPVertex(&moltres_hd_vtx[279], 8, 0),
    gsSP2Triangles(30, 31, 7, 0, 6, 30, 7, 0),
    gsSP2Triangles(6, 7, 5, 0, 4, 6, 5, 0),
    gsSP2Triangles(4, 5, 3, 0, 5, 2, 3, 0),
    gsSP2Triangles(3, 2, 1, 0, 2, 0, 1, 0),
    gsDPPipeSync(),
    gsDPSetAlphaCompare(G_AC_NONE),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_OPA_SURF2),
    gsDPSetTile(G_IM_FMT_CI, G_IM_SIZ_16b, 0, 0x0000, G_TX_LOADTILE, 0, G_TX_NOMIRROR | G_TX_WRAP, 3, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_WRAP, 5, G_TX_NOLOD),
    gsDPSetTile(G_IM_FMT_CI, G_IM_SIZ_4b, 2, 0x0000, G_TX_RENDERTILE, 0, G_TX_NOMIRROR | G_TX_CLAMP, 3, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_CLAMP, 5, G_TX_NOLOD),
    gsDPSetTextureImage(G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, moltres_tex_skin_pal),
    gsDPLoadSync(),
    gsDPLoadTLUTCmd(5, 5),
    gsDPPipeSync(),
    gsDPSetTileSize(G_TX_RENDERTILE, 0, 0, 0x007C, 0x001C),
    gsDPSetTextureImage(G_IM_FMT_CI, G_IM_SIZ_16b, 1, moltres_tex_skin_png),
    gsDPLoadSync(),
    gsDPLoadBlock(G_TX_LOADTILE, 0, 0, 63, 1024),
    gsDPPipeSync(),
    gsSPSetGeometryMode(G_CULL_BACK),
    gsSPModifyVertex(28, G_MWO_POINT_ST, 0x02AB00A4),
    gsSPModifyVertex(29, G_MWO_POINT_ST, 0x02A60151),
    gsSPModifyVertex(31, G_MWO_POINT_ST, 0x02B1FFFD),
    gsSPVertex(&moltres_hd_vtx[287], 5, 0),
    gsSP2Triangles(4, 29, 31, 0, 3, 4, 31, 0),
    gsSP2Triangles(2, 28, 4, 0, 28, 29, 4, 0),
    gsSP2Triangles(4, 3, 1, 0, 0, 1, 2, 0),
    gsSP1Triangle(0, 4, 1, 0),
    gsDPPipeSync(),
    gsSPClearGeometryMode(G_CULL_BACK),
    gsSPModifyVertex(28, G_MWO_POINT_ST, 0x02AB00A4),
    gsSPModifyVertex(31, G_MWO_POINT_ST, 0x02B1FFFD),
    gsSPVertex(&moltres_hd_vtx[287], 5, 0),
    gsSP2Triangles(31, 28, 2, 0, 3, 31, 2, 0),
    gsSP2Triangles(1, 3, 2, 0, 2, 4, 0, 0),
    gsSPEndDisplayList(),
};
