.section .late_rodata
nonmatching D_802ECCB0_7C6240

dlabel D_802ECCB0_7C6240
    /* 7C6240 802ECCB0 3FC90FDB */ .float 1.570796371
enddlabel D_802ECCB0_7C6240


.section .text
/* Generated by spimdisasm 1.42.2 */

nonmatching func_802C8D30_7A22C0, 0x124

glabel func_802C8D30_7A22C0
    /* 7A22C0 802C8D30 27BDFFB8 */  addiu      $sp, $sp, -0x48
    /* 7A22C4 802C8D34 AFB2001C */  sw         $s2, 0x1C($sp)
    /* 7A22C8 802C8D38 00809025 */  or         $s2, $a0, $zero
    /* 7A22CC 802C8D3C AFBF0024 */  sw         $ra, 0x24($sp)
    /* 7A22D0 802C8D40 AFB30020 */  sw         $s3, 0x20($sp)
    /* 7A22D4 802C8D44 AFB10018 */  sw         $s1, 0x18($sp)
    /* 7A22D8 802C8D48 AFB00014 */  sw         $s0, 0x14($sp)
    /* 7A22DC 802C8D4C 8E530058 */  lw         $s3, 0x58($s2)
    /* 7A22E0 802C8D50 3C0E802D */  lui        $t6, %hi(D_802D2C0C_7AC19C)
    /* 7A22E4 802C8D54 8C840048 */  lw         $a0, 0x48($a0)
    /* 7A22E8 802C8D58 25CE2C0C */  addiu      $t6, $t6, %lo(D_802D2C0C_7AC19C)
    /* 7A22EC 802C8D5C 3C018035 */  lui        $at, %hi(D_8034C8D8_825E68)
    /* 7A22F0 802C8D60 AE6E00CC */  sw         $t6, 0xCC($s3)
    /* 7A22F4 802C8D64 C424C8D8 */  lwc1       $f4, %lo(D_8034C8D8_825E68)($at)
    /* 7A22F8 802C8D68 3C018035 */  lui        $at, %hi(D_8034C8DC_825E6C)
    /* 7A22FC 802C8D6C 27A6002C */  addiu      $a2, $sp, 0x2C
    /* 7A2300 802C8D70 E664001C */  swc1       $f4, 0x1C($s3)
    /* 7A2304 802C8D74 C426C8DC */  lwc1       $f6, %lo(D_8034C8DC_825E6C)($at)
    /* 7A2308 802C8D78 02602825 */  or         $a1, $s3, $zero
    /* 7A230C 802C8D7C 0C0B2293 */  jal        func_802C8A4C_7A1FDC
    /* 7A2310 802C8D80 E6660024 */   swc1      $f6, 0x24($s3)
    /* 7A2314 802C8D84 02402025 */  or         $a0, $s2, $zero
    /* 7A2318 802C8D88 8FA5002C */  lw         $a1, 0x2C($sp)
    /* 7A231C 802C8D8C 0C0D86D4 */  jal        Pokemon_SetTargetPos
    /* 7A2320 802C8D90 8FA60034 */   lw        $a2, 0x34($sp)
    /* 7A2324 802C8D94 3C05802D */  lui        $a1, %hi(D_802D2B24_7AC0B4)
    /* 7A2328 802C8D98 24A52B24 */  addiu      $a1, $a1, %lo(D_802D2B24_7AC0B4)
    /* 7A232C 802C8D9C 0C0D7C4E */  jal        Pokemon_SetAnimation
    /* 7A2330 802C8DA0 02402025 */   or        $a0, $s2, $zero
    /* 7A2334 802C8DA4 3C05802D */  lui        $a1, %hi(func_802C8E54_7A23E4)
    /* 7A2338 802C8DA8 24A58E54 */  addiu      $a1, $a1, %lo(func_802C8E54_7A23E4)
    /* 7A233C 802C8DAC 0C0D7B7E */  jal        Pokemon_StartPathProc
    /* 7A2340 802C8DB0 02402025 */   or        $a0, $s2, $zero
    /* 7A2344 802C8DB4 AE6000AC */  sw         $zero, 0xAC($s3)
    /* 7A2348 802C8DB8 02402025 */  or         $a0, $s2, $zero
    /* 7A234C 802C8DBC 0C0D7EFC */  jal        Pokemon_WaitForFlag
    /* 7A2350 802C8DC0 24050002 */   addiu     $a1, $zero, 0x2
    /* 7A2354 802C8DC4 8E6F0088 */  lw         $t7, 0x88($s3)
    /* 7A2358 802C8DC8 24010002 */  addiu      $at, $zero, 0x2
    /* 7A235C 802C8DCC 02402025 */  or         $a0, $s2, $zero
    /* 7A2360 802C8DD0 15E10007 */  bne        $t7, $at, .L802C8DF0_7A2380
    /* 7A2364 802C8DD4 3C05802D */   lui       $a1, %hi(func_802C94A4_7A2A34)
    /* 7A2368 802C8DD8 3C01802F */  lui        $at, %hi(D_802ECCB0_7C6240)
    /* 7A236C 802C8DDC C428CCB0 */  lwc1       $f8, %lo(D_802ECCB0_7C6240)($at)
    /* 7A2370 802C8DE0 3C01802D */  lui        $at, %hi(D_802D2BF8_7AC188)
    /* 7A2374 802C8DE4 24A594A4 */  addiu      $a1, $a1, %lo(func_802C94A4_7A2A34)
    /* 7A2378 802C8DE8 0C0D7B64 */  jal        Pokemon_StartAuxProc
    /* 7A237C 802C8DEC E4282BF8 */   swc1      $f8, %lo(D_802D2BF8_7AC188)($at)
  .L802C8DF0_7A2380:
    /* 7A2380 802C8DF0 3C10802D */  lui        $s0, %hi(D_802D2C08_7AC198)
    /* 7A2384 802C8DF4 26102C08 */  addiu      $s0, $s0, %lo(D_802D2C08_7AC198)
    /* 7A2388 802C8DF8 8E180000 */  lw         $t8, 0x0($s0)
    /* 7A238C 802C8DFC 24110003 */  addiu      $s1, $zero, 0x3
    /* 7A2390 802C8E00 27190001 */  addiu      $t9, $t8, 0x1
    /* 7A2394 802C8E04 12390006 */  beq        $s1, $t9, .L802C8E20_7A23B0
    /* 7A2398 802C8E08 AE190000 */   sw        $t9, 0x0($s0)
  .L802C8E0C_7A239C:
    /* 7A239C 802C8E0C 0C002F2A */  jal        ohWait
    /* 7A23A0 802C8E10 24040001 */   addiu     $a0, $zero, 0x1
    /* 7A23A4 802C8E14 8E090000 */  lw         $t1, 0x0($s0)
    /* 7A23A8 802C8E18 1629FFFC */  bne        $s1, $t1, .L802C8E0C_7A239C
    /* 7A23AC 802C8E1C 00000000 */   nop
  .L802C8E20_7A23B0:
    /* 7A23B0 802C8E20 240A0009 */  addiu      $t2, $zero, 0x9
    /* 7A23B4 802C8E24 3C05802D */  lui        $a1, %hi(func_802C8EA8_7A2438)
    /* 7A23B8 802C8E28 A66A010E */  sh         $t2, 0x10E($s3)
    /* 7A23BC 802C8E2C 24A58EA8 */  addiu      $a1, $a1, %lo(func_802C8EA8_7A2438)
    /* 7A23C0 802C8E30 0C0D7B16 */  jal        Pokemon_SetState
    /* 7A23C4 802C8E34 02402025 */   or        $a0, $s2, $zero
    /* 7A23C8 802C8E38 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 7A23CC 802C8E3C 8FB00014 */  lw         $s0, 0x14($sp)
    /* 7A23D0 802C8E40 8FB10018 */  lw         $s1, 0x18($sp)
    /* 7A23D4 802C8E44 8FB2001C */  lw         $s2, 0x1C($sp)
    /* 7A23D8 802C8E48 8FB30020 */  lw         $s3, 0x20($sp)
    /* 7A23DC 802C8E4C 03E00008 */  jr         $ra
    /* 7A23E0 802C8E50 27BD0048 */   addiu     $sp, $sp, 0x48
endlabel func_802C8D30_7A22C0
