.section .late_rodata
nonmatching D_800439F0

dlabel D_800439F0
    /* 445F0 800439F0 FEFFFFFF */ .float -1.701411733e+38
enddlabel D_800439F0


.section .text
/* Generated by spimdisasm 1.42.2 */

nonmatching animSetCameraAnimation, 0x38

glabel animSetCameraAnimation
    /* 1114C 8001054C 8C82006C */  lw         $v0, 0x6C($a0)
    /* 11150 80010550 44866000 */  mtc1       $a2, $f12
    /* 11154 80010554 3C018004 */  lui        $at, %hi(D_800439F0)
    /* 11158 80010558 50400006 */  beql       $v0, $zero, .L80010574
    /* 1115C 8001055C AC850070 */   sw        $a1, 0x70($a0)
    /* 11160 80010560 A0400005 */  sb         $zero, 0x5($v0)
  .L80010564:
    /* 11164 80010564 8C420000 */  lw         $v0, 0x0($v0)
    /* 11168 80010568 5440FFFE */  bnel       $v0, $zero, .L80010564
    /* 1116C 8001056C A0400005 */   sb        $zero, 0x5($v0)
    /* 11170 80010570 AC850070 */  sw         $a1, 0x70($a0)
  .L80010574:
    /* 11174 80010574 C42439F0 */  lwc1       $f4, %lo(D_800439F0)($at)
    /* 11178 80010578 E48C007C */  swc1       $f12, 0x7C($a0)
    /* 1117C 8001057C 03E00008 */  jr         $ra
    /* 11180 80010580 E4840074 */   swc1      $f4, 0x74($a0)
endlabel animSetCameraAnimation
