.section .late_rodata
nonmatching D_8004375C

dlabel D_8004375C
    /* 4435C 8004375C FF7FFFFF */ .float -3.402823466e+38
enddlabel D_8004375C


.section .text
/* Generated by spimdisasm 1.42.1 */

nonmatching func_8000C988, 0x110

glabel func_8000C988
    /* D588 8000C988 27BDFFC0 */  addiu      $sp, $sp, -0x40
    /* D58C 8000C98C AFBF003C */  sw         $ra, 0x3C($sp)
    /* D590 8000C990 AFB50038 */  sw         $s5, 0x38($sp)
    /* D594 8000C994 AFB40034 */  sw         $s4, 0x34($sp)
    /* D598 8000C998 AFB30030 */  sw         $s3, 0x30($sp)
    /* D59C 8000C99C AFB2002C */  sw         $s2, 0x2C($sp)
    /* D5A0 8000C9A0 AFB10028 */  sw         $s1, 0x28($sp)
    /* D5A4 8000C9A4 AFB00024 */  sw         $s0, 0x24($sp)
    /* D5A8 8000C9A8 F7B60018 */  sdc1       $f22, 0x18($sp)
    /* D5AC 8000C9AC F7B40010 */  sdc1       $f20, 0x10($sp)
    /* D5B0 8000C9B0 8C920048 */  lw         $s2, 0x48($a0)
    /* D5B4 8000C9B4 4487A000 */  mtc1       $a3, $f20
    /* D5B8 8000C9B8 00A09825 */  or         $s3, $a1, $zero
    /* D5BC 8000C9BC 00C0A025 */  or         $s4, $a2, $zero
    /* D5C0 8000C9C0 24150001 */  addiu      $s5, $zero, 0x1
    /* D5C4 8000C9C4 12400029 */  beqz       $s2, .L8000CA6C
    /* D5C8 8000C9C8 E494004C */   swc1      $f20, 0x4C($a0)
    /* D5CC 8000C9CC 3C018004 */  lui        $at, %hi(D_8004375C)
    /* D5D0 8000C9D0 C436375C */  lwc1       $f22, %lo(D_8004375C)($at)
  .L8000C9D4:
    /* D5D4 8000C9D4 1260000D */  beqz       $s3, .L8000CA0C
    /* D5D8 8000C9D8 00000000 */   nop
    /* D5DC 8000C9DC 8E650000 */  lw         $a1, 0x0($s3)
    /* D5E0 8000C9E0 50A00008 */  beql       $a1, $zero, .L8000CA04
    /* D5E4 8000C9E4 E6560074 */   swc1      $f22, 0x74($s2)
    /* D5E8 8000C9E8 4406A000 */  mfc1       $a2, $f20
    /* D5EC 8000C9EC 0C0031F3 */  jal        animSetModelAnimation
    /* D5F0 8000C9F0 02402025 */   or        $a0, $s2, $zero
    /* D5F4 8000C9F4 A2550055 */  sb         $s5, 0x55($s2)
    /* D5F8 8000C9F8 10000003 */  b          .L8000CA08
    /* D5FC 8000C9FC 0000A825 */   or        $s5, $zero, $zero
    /* D600 8000CA00 E6560074 */  swc1       $f22, 0x74($s2)
  .L8000CA04:
    /* D604 8000CA04 A2400055 */  sb         $zero, 0x55($s2)
  .L8000CA08:
    /* D608 8000CA08 26730004 */  addiu      $s3, $s3, 0x4
  .L8000CA0C:
    /* D60C 8000CA0C 12800013 */  beqz       $s4, .L8000CA5C
    /* D610 8000CA10 00000000 */   nop
    /* D614 8000CA14 8E820000 */  lw         $v0, 0x0($s4)
    /* D618 8000CA18 50400010 */  beql       $v0, $zero, .L8000CA5C
    /* D61C 8000CA1C 26940004 */   addiu     $s4, $s4, 0x4
    /* D620 8000CA20 8E500080 */  lw         $s0, 0x80($s2)
    /* D624 8000CA24 00408825 */  or         $s1, $v0, $zero
    /* D628 8000CA28 5200000C */  beql       $s0, $zero, .L8000CA5C
    /* D62C 8000CA2C 26940004 */   addiu     $s4, $s4, 0x4
    /* D630 8000CA30 8E250000 */  lw         $a1, 0x0($s1)
  .L8000CA34:
    /* D634 8000CA34 50A00005 */  beql       $a1, $zero, .L8000CA4C
    /* D638 8000CA38 8E100000 */   lw        $s0, 0x0($s0)
    /* D63C 8000CA3C 4406A000 */  mfc1       $a2, $f20
    /* D640 8000CA40 0C003201 */  jal        func_8000C804
    /* D644 8000CA44 02002025 */   or        $a0, $s0, $zero
    /* D648 8000CA48 8E100000 */  lw         $s0, 0x0($s0)
  .L8000CA4C:
    /* D64C 8000CA4C 26310004 */  addiu      $s1, $s1, 0x4
    /* D650 8000CA50 5600FFF8 */  bnel       $s0, $zero, .L8000CA34
    /* D654 8000CA54 8E250000 */   lw        $a1, 0x0($s1)
    /* D658 8000CA58 26940004 */  addiu      $s4, $s4, 0x4
  .L8000CA5C:
    /* D65C 8000CA5C 0C003154 */  jal        animModelTreeNextNode
    /* D660 8000CA60 02402025 */   or        $a0, $s2, $zero
    /* D664 8000CA64 1440FFDB */  bnez       $v0, .L8000C9D4
    /* D668 8000CA68 00409025 */   or        $s2, $v0, $zero
  .L8000CA6C:
    /* D66C 8000CA6C 8FBF003C */  lw         $ra, 0x3C($sp)
    /* D670 8000CA70 D7B40010 */  ldc1       $f20, 0x10($sp)
    /* D674 8000CA74 D7B60018 */  ldc1       $f22, 0x18($sp)
    /* D678 8000CA78 8FB00024 */  lw         $s0, 0x24($sp)
    /* D67C 8000CA7C 8FB10028 */  lw         $s1, 0x28($sp)
    /* D680 8000CA80 8FB2002C */  lw         $s2, 0x2C($sp)
    /* D684 8000CA84 8FB30030 */  lw         $s3, 0x30($sp)
    /* D688 8000CA88 8FB40034 */  lw         $s4, 0x34($sp)
    /* D68C 8000CA8C 8FB50038 */  lw         $s5, 0x38($sp)
    /* D690 8000CA90 03E00008 */  jr         $ra
    /* D694 8000CA94 27BD0040 */   addiu     $sp, $sp, 0x40
endlabel func_8000C988
