#include "common.h"

Gfx rapidash_part14_draw_near[] = {
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_OPA_SURF2),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsDPSetTile(G_IM_FMT_CI, G_IM_SIZ_16b, 0, 0x0000, G_TX_LOADTILE, 0, G_TX_NOMIRROR | G_TX_WRAP, 4, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_WRAP, 4, G_TX_NOLOD),
    gsDPSetTile(G_IM_FMT_CI, G_IM_SIZ_4b, 1, 0x0000, G_TX_RENDERTILE, 0, G_TX_NOMIRROR | G_TX_CLAMP, 4, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_CLAMP, 4, G_TX_NOLOD),
    gsDPSetTextureImage(G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, rapidash_tex_hoof_pal),
    gsDPLoadSync(),
    gsDPLoadTLUTCmd(5, 6),
    gsDPPipeSync(),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetTileSize(G_TX_RENDERTILE, 0, 0, 0x003C, 0x003C),
    gsDPSetTextureImage(G_IM_FMT_CI, G_IM_SIZ_16b, 1, rapidash_tex_hoof_png),
    gsDPLoadSync(),
    gsDPLoadBlock(G_TX_LOADTILE, 0, 0, 63, 2048),
    gsDPPipeSync(),
    gsSPVertex(&rapidash_vtx[234], 4, 3),
    gsSP2Triangles(6, 5, 4, 0, 3, 6, 4, 0),
    gsDPPipeSync(),
    gsDPSetTextureImage(G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, rapidash_tex_skin_pal),
    gsDPLoadSync(),
    gsDPLoadTLUTCmd(5, 9),
    gsDPPipeSync(),
    gsDPSetTextureImage(G_IM_FMT_CI, G_IM_SIZ_16b, 1, rapidash_tex_skin_png),
    gsDPLoadSync(),
    gsDPLoadBlock(G_TX_LOADTILE, 0, 0, 63, 2048),
    gsDPPipeSync(),
    gsSPModifyVertex(0, G_MWO_POINT_ST, 0x00C301FF),
    gsSPModifyVertex(1, G_MWO_POINT_ST, 0x000001DD),
    gsSPModifyVertex(2, G_MWO_POINT_ST, 0x00C301FF),
    gsSPVertex(&rapidash_vtx[169], 2, 3),
    gsSPVertex(&rapidash_vtx[238], 4, 5),
    gsSP1Triangle(8, 2, 1, 0),
    gsSPModifyVertex(2, G_MWO_POINT_ST, 0x016A01DA),
    gsSP2Triangles(8, 1, 7, 0, 6, 7, 1, 0),
    gsSP2Triangles(7, 4, 8, 0, 8, 4, 3, 0),
    gsSP2Triangles(5, 3, 6, 0, 1, 0, 5, 0),
    gsSP2Triangles(5, 0, 8, 0, 5, 6, 1, 0),
    gsSP2Triangles(5, 8, 3, 0, 0, 2, 8, 0),
    gsSPEndDisplayList(),
};
