.section .late_rodata
nonmatching D_800B0560

dlabel D_800B0560
    /* 5BF10 800B0560 3F7FF972 */ .float 0.9998999834
    /* 5BF14 800B0564 00000000 */ .float 0
    /* 5BF18 800B0568 00000000 */ .float 0
    /* 5BF1C 800B056C 00000000 */ .float 0
enddlabel D_800B0560


.section .text
/* Generated by spimdisasm 1.42.2 */

nonmatching func_800AB138, 0xC0

glabel func_800AB138
    /* 56AE8 800AB138 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 56AEC 800AB13C AFBF001C */  sw         $ra, 0x1C($sp)
    /* 56AF0 800AB140 AFA50024 */  sw         $a1, 0x24($sp)
    /* 56AF4 800AB144 C4800010 */  lwc1       $f0, 0x10($a0)
    /* 56AF8 800AB148 8C8F0004 */  lw         $t7, 0x4($a0)
    /* 56AFC 800AB14C 8C860000 */  lw         $a2, 0x0($a0)
    /* 56B00 800AB150 4600010D */  trunc.w.s  $f4, $f0
    /* 56B04 800AB154 8C850008 */  lw         $a1, 0x8($a0)
    /* 56B08 800AB158 44022000 */  mfc1       $v0, $f4
    /* 56B0C 800AB15C 00000000 */  nop
    /* 56B10 800AB160 44823000 */  mtc1       $v0, $f6
    /* 56B14 800AB164 0002C080 */  sll        $t8, $v0, 2
    /* 56B18 800AB168 01F81821 */  addu       $v1, $t7, $t8
    /* 56B1C 800AB16C 46803220 */  cvt.s.w    $f8, $f6
    /* 56B20 800AB170 8C680004 */  lw         $t0, 0x4($v1)
    /* 56B24 800AB174 8C670000 */  lw         $a3, 0x0($v1)
    /* 56B28 800AB178 AFA40020 */  sw         $a0, 0x20($sp)
    /* 56B2C 800AB17C AFA80010 */  sw         $t0, 0x10($sp)
    /* 56B30 800AB180 0C02AC14 */  jal        func_800AB050
    /* 56B34 800AB184 46080301 */   sub.s     $f12, $f0, $f8
    /* 56B38 800AB188 8FA40020 */  lw         $a0, 0x20($sp)
    /* 56B3C 800AB18C C7B00024 */  lwc1       $f16, 0x24($sp)
    /* 56B40 800AB190 24020001 */  addiu      $v0, $zero, 0x1
    /* 56B44 800AB194 C48A0010 */  lwc1       $f10, 0x10($a0)
    /* 56B48 800AB198 8C83000C */  lw         $v1, 0xC($a0)
    /* 56B4C 800AB19C 46105480 */  add.s      $f18, $f10, $f16
    /* 56B50 800AB1A0 246AFFFF */  addiu      $t2, $v1, -0x1
    /* 56B54 800AB1A4 246BFFFE */  addiu      $t3, $v1, -0x2
    /* 56B58 800AB1A8 E4920010 */  swc1       $f18, 0x10($a0)
    /* 56B5C 800AB1AC C4840010 */  lwc1       $f4, 0x10($a0)
    /* 56B60 800AB1B0 4600218D */  trunc.w.s  $f6, $f4
    /* 56B64 800AB1B4 44093000 */  mfc1       $t1, $f6
    /* 56B68 800AB1B8 00000000 */  nop
    /* 56B6C 800AB1BC 012A082A */  slt        $at, $t1, $t2
    /* 56B70 800AB1C0 14200009 */  bnez       $at, .L800AB1E8
    /* 56B74 800AB1C4 00000000 */   nop
    /* 56B78 800AB1C8 448B4000 */  mtc1       $t3, $f8
    /* 56B7C 800AB1CC 3C01800B */  lui        $at, %hi(D_800B0560)
    /* 56B80 800AB1D0 C4300560 */  lwc1       $f16, %lo(D_800B0560)($at)
    /* 56B84 800AB1D4 468042A0 */  cvt.s.w    $f10, $f8
    /* 56B88 800AB1D8 00001025 */  or         $v0, $zero, $zero
    /* 56B8C 800AB1DC 46105480 */  add.s      $f18, $f10, $f16
    /* 56B90 800AB1E0 10000001 */  b          .L800AB1E8
    /* 56B94 800AB1E4 E4920010 */   swc1      $f18, 0x10($a0)
  .L800AB1E8:
    /* 56B98 800AB1E8 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 56B9C 800AB1EC 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 56BA0 800AB1F0 03E00008 */  jr         $ra
    /* 56BA4 800AB1F4 00000000 */   nop
endlabel func_800AB138
