.section .late_rodata
nonmatching D_802ECD18_7C62A8

dlabel D_802ECD18_7C62A8
    /* 7C62A8 802ECD18 3DCCCCCD */ .float 0.1000000015
    /* 7C62AC 802ECD1C 00000000 */ .float 0
enddlabel D_802ECD18_7C62A8


.section .text
/* Generated by spimdisasm 1.42.0 */

nonmatching func_802CAF04_7A4494, 0x50

glabel func_802CAF04_7A4494
    /* 7A4494 802CAF04 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 7A4498 802CAF08 AFB00020 */  sw         $s0, 0x20($sp)
    /* 7A449C 802CAF0C F7B40018 */  sdc1       $f20, 0x18($sp)
    /* 7A44A0 802CAF10 3C01802F */  lui        $at, %hi(D_802ECD18_7C62A8)
    /* 7A44A4 802CAF14 00808025 */  or         $s0, $a0, $zero
    /* 7A44A8 802CAF18 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 7A44AC 802CAF1C C434CD18 */  lwc1       $f20, %lo(D_802ECD18_7C62A8)($at)
    /* 7A44B0 802CAF20 4405A000 */  mfc1       $a1, $f20
  .L802CAF24_7A44B4:
    /* 7A44B4 802CAF24 02002025 */  or         $a0, $s0, $zero
    /* 7A44B8 802CAF28 0C0D8523 */  jal        Pokemon_TurnToTarget
    /* 7A44BC 802CAF2C 00003025 */   or        $a2, $zero, $zero
    /* 7A44C0 802CAF30 0C002F2A */  jal        ohWait
    /* 7A44C4 802CAF34 24040001 */   addiu     $a0, $zero, 0x1
    /* 7A44C8 802CAF38 1000FFFA */  b          .L802CAF24_7A44B4
    /* 7A44CC 802CAF3C 4405A000 */   mfc1      $a1, $f20
    /* 7A44D0 802CAF40 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 7A44D4 802CAF44 D7B40018 */  ldc1       $f20, 0x18($sp)
    /* 7A44D8 802CAF48 8FB00020 */  lw         $s0, 0x20($sp)
    /* 7A44DC 802CAF4C 03E00008 */  jr         $ra
    /* 7A44E0 802CAF50 27BD0028 */   addiu     $sp, $sp, 0x28
endlabel func_802CAF04_7A4494
