.section .late_rodata
nonmatching D_802E4C10_6CC9F0

dlabel D_802E4C10_6CC9F0
    /* 6CC9F0 802E4C10 40490FDB */ .float 3.141592741
enddlabel D_802E4C10_6CC9F0


.section .text
/* Generated by spimdisasm 1.42.1 */

nonmatching func_802DB1C4_6C2FA4, 0xAC

glabel func_802DB1C4_6C2FA4
    /* 6C2FA4 802DB1C4 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* 6C2FA8 802DB1C8 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 6C2FAC 802DB1CC AFB00018 */  sw         $s0, 0x18($sp)
    /* 6C2FB0 802DB1D0 8C820048 */  lw         $v0, 0x48($a0)
    /* 6C2FB4 802DB1D4 00808025 */  or         $s0, $a0, $zero
    /* 6C2FB8 802DB1D8 8C4E004C */  lw         $t6, 0x4C($v0)
    /* 6C2FBC 802DB1DC 25CF0014 */  addiu      $t7, $t6, 0x14
    /* 6C2FC0 802DB1E0 AFAF0024 */  sw         $t7, 0x24($sp)
    /* 6C2FC4 802DB1E4 8C980058 */  lw         $t8, 0x58($a0)
    /* 6C2FC8 802DB1E8 24040168 */  addiu      $a0, $zero, 0x168
    /* 6C2FCC 802DB1EC 0C006785 */  jal        randRange
    /* 6C2FD0 802DB1F0 AFB80020 */   sw        $t8, 0x20($sp)
    /* 6C2FD4 802DB1F4 44822000 */  mtc1       $v0, $f4
    /* 6C2FD8 802DB1F8 3C01802E */  lui        $at, %hi(D_802E4C10_6CC9F0)
    /* 6C2FDC 802DB1FC C4284C10 */  lwc1       $f8, %lo(D_802E4C10_6CC9F0)($at)
    /* 6C2FE0 802DB200 468021A0 */  cvt.s.w    $f6, $f4
    /* 6C2FE4 802DB204 3C014334 */  lui        $at, (0x43340000 >> 16)
    /* 6C2FE8 802DB208 44818000 */  mtc1       $at, $f16
    /* 6C2FEC 802DB20C 8FB90024 */  lw         $t9, 0x24($sp)
    /* 6C2FF0 802DB210 3C05802E */  lui        $a1, %hi(func_802DB270_6C3050)
    /* 6C2FF4 802DB214 24A5B270 */  addiu      $a1, $a1, %lo(func_802DB270_6C3050)
    /* 6C2FF8 802DB218 46083282 */  mul.s      $f10, $f6, $f8
    /* 6C2FFC 802DB21C 02002025 */  or         $a0, $s0, $zero
    /* 6C3000 802DB220 46105483 */  div.s      $f18, $f10, $f16
    /* 6C3004 802DB224 0C0D7B7E */  jal        Pokemon_StartPathProc
    /* 6C3008 802DB228 E732000C */   swc1      $f18, 0xC($t9)
    /* 6C300C 802DB22C 8FA80020 */  lw         $t0, 0x20($sp)
    /* 6C3010 802DB230 02002025 */  or         $a0, $s0, $zero
    /* 6C3014 802DB234 24050001 */  addiu      $a1, $zero, 0x1
    /* 6C3018 802DB238 0C0D7EFC */  jal        Pokemon_WaitForFlag
    /* 6C301C 802DB23C AD0000AC */   sw        $zero, 0xAC($t0)
    /* 6C3020 802DB240 3C01802E */  lui        $at, %hi(D_802E28AC_6CA68C)
    /* 6C3024 802DB244 A42028AC */  sh         $zero, %lo(D_802E28AC_6CA68C)($at)
    /* 6C3028 802DB248 0C0D7F5C */  jal        Pokemon_RunCleanup
    /* 6C302C 802DB24C 02002025 */   or        $a0, $s0, $zero
    /* 6C3030 802DB250 02002025 */  or         $a0, $s0, $zero
    /* 6C3034 802DB254 0C0D7B16 */  jal        Pokemon_SetState
    /* 6C3038 802DB258 00002825 */   or        $a1, $zero, $zero
    /* 6C303C 802DB25C 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 6C3040 802DB260 8FB00018 */  lw         $s0, 0x18($sp)
    /* 6C3044 802DB264 27BD0030 */  addiu      $sp, $sp, 0x30
    /* 6C3048 802DB268 03E00008 */  jr         $ra
    /* 6C304C 802DB26C 00000000 */   nop
endlabel func_802DB1C4_6C2FA4
