#include "common.h"

Gfx koffing_part1_pre_near[] = {
    gsDPPipeSync(),
    gsDPSetCombineLERP(PRIMITIVE, 0, SHADE, 0, 0, 0, 0, PRIMITIVE, 0, 0, 0, COMBINED, 0, 0, 0, COMBINED),
    gsSPTexture(0x01C0, 0x01C0, 0, G_TX_RENDERTILE, G_ON),
    gsSPVertex(&koffing_vtx[123], 1, 0),
    gsSPVertex(&koffing_vtx[117], 1, 1),
    gsSPVertex(&koffing_vtx[122], 1, 3),
    gsSPVertex(&koffing_vtx[109], 1, 4),
    gsSPVertex(&koffing_vtx[60], 1, 5),
    gsSPVertex(&koffing_vtx[68], 1, 6),
    gsSPVertex(&koffing_vtx[55], 1, 7),
    gsSPVertex(&koffing_vtx[69], 1, 8),
    gsSPVertex(&koffing_vtx[93], 1, 9),
    gsSPVertex(&koffing_vtx[78], 1, 10),
    gsSPVertex(&koffing_vtx[91], 1, 11),
    gsSPVertex(&koffing_vtx[75], 1, 12),
    gsSPVertex(&koffing_vtx[84], 1, 14),
    gsSPVertex(&koffing_vtx[83], 1, 16),
    gsSPVertex(&koffing_vtx[52], 1, 17),
    gsSPVertex(&koffing_vtx[49], 1, 18),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsSPTexture(0x0FC0, 0x07C0, 0, G_TX_RENDERTILE, G_ON),
    gsSPVertex(&koffing_vtx[13], 1, 2),
    gsDPPipeSync(),
    gsSPTexture(0x07C0, 0x0FC0, 0, G_TX_RENDERTILE, G_ON),
    gsSPVertex(&koffing_vtx[26], 1, 13),
    gsSPVertex(&koffing_vtx[34], 1, 15),
    gsSPEndDisplayList(),
};
