#include "common.h"

Gfx koffing_part2_pre_near[] = {
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPSetCombineLERP(PRIMITIVE, 0, SHADE, 0, 0, 0, 0, PRIMITIVE, 0, 0, 0, COMBINED, 0, 0, 0, COMBINED),
    gsSPTexture(0x01C0, 0x01C0, 0, G_TX_RENDERTILE, G_ON),
    gsSPVertex(&koffing_vtx[59], 1, 0),
    gsSPVertex(&koffing_vtx[47], 1, 1),
    gsSPVertex(&koffing_vtx[76], 1, 2),
    gsSPVertex(&koffing_vtx[57], 1, 3),
    gsSPVertex(&koffing_vtx[94], 1, 4),
    gsSPVertex(&koffing_vtx[64], 1, 5),
    gsSPVertex(&koffing_vtx[63], 1, 6),
    gsSPVertex(&koffing_vtx[61], 1, 7),
    gsSPVertex(&koffing_vtx[118], 1, 8),
    gsSPVertex(&koffing_vtx[97], 1, 9),
    gsSPVertex(&koffing_vtx[99], 1, 12),
    gsSPVertex(&koffing_vtx[95], 1, 13),
    gsSPVertex(&koffing_vtx[110], 1, 16),
    gsSPVertex(&koffing_vtx[81], 1, 17),
    gsSPVertex(&koffing_vtx[90], 1, 18),
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsSPTexture(0x0FC0, 0x07C0, 0, G_TX_RENDERTILE, G_ON),
    gsSPVertex(&koffing_vtx[18], 1, 10),
    gsSPVertex(&koffing_vtx[17], 1, 11),
    gsDPPipeSync(),
    gsSPTexture(0x07C0, 0x0FC0, 0, G_TX_RENDERTILE, G_ON),
    gsSPVertex(&koffing_vtx[30], 1, 14),
    gsSPVertex(&koffing_vtx[29], 1, 15),
    gsSPEndDisplayList(),
};
