.section .late_rodata
nonmatching D_802F0350_5ED420

dlabel D_802F0350_5ED420
    /* 5ED420 802F0350 3DCCCCCD */ .float 0.1000000015
enddlabel D_802F0350_5ED420


.section .text
/* Generated by spimdisasm 1.42.2 */

nonmatching func_802E44DC_5E15AC, 0xD8

glabel func_802E44DC_5E15AC
    /* 5E15AC 802E44DC 27BDFFA8 */  addiu      $sp, $sp, -0x58
    /* 5E15B0 802E44E0 AFBF0034 */  sw         $ra, 0x34($sp)
    /* 5E15B4 802E44E4 AFB20030 */  sw         $s2, 0x30($sp)
    /* 5E15B8 802E44E8 AFB1002C */  sw         $s1, 0x2C($sp)
    /* 5E15BC 802E44EC AFB00028 */  sw         $s0, 0x28($sp)
    /* 5E15C0 802E44F0 F7B60020 */  sdc1       $f22, 0x20($sp)
    /* 5E15C4 802E44F4 F7B40018 */  sdc1       $f20, 0x18($sp)
    /* 5E15C8 802E44F8 8C820048 */  lw         $v0, 0x48($a0)
    /* 5E15CC 802E44FC 3C01802F */  lui        $at, %hi(D_802F0350_5ED420)
    /* 5E15D0 802E4500 C4360350 */  lwc1       $f22, %lo(D_802F0350_5ED420)($at)
    /* 5E15D4 802E4504 8C4E004C */  lw         $t6, 0x4C($v0)
    /* 5E15D8 802E4508 3C0143A0 */  lui        $at, (0x43A00000 >> 16)
    /* 5E15DC 802E450C 4481A000 */  mtc1       $at, $f20
    /* 5E15E0 802E4510 25CF0004 */  addiu      $t7, $t6, 0x4
    /* 5E15E4 802E4514 AFAF0050 */  sw         $t7, 0x50($sp)
    /* 5E15E8 802E4518 8C900058 */  lw         $s0, 0x58($a0)
    /* 5E15EC 802E451C 00808825 */  or         $s1, $a0, $zero
    /* 5E15F0 802E4520 27B2003C */  addiu      $s2, $sp, 0x3C
  .L802E4524_5E15F4:
    /* 5E15F4 802E4524 0C002F2A */  jal        ohWait
    /* 5E15F8 802E4528 24040001 */   addiu     $a0, $zero, 0x1
    /* 5E15FC 802E452C E6140098 */  swc1       $f20, 0x98($s0)
    /* 5E1600 802E4530 8E0400B0 */  lw         $a0, 0xB0($s0)
    /* 5E1604 802E4534 0C0B90EC */  jal        func_802E43B0_5E1480
    /* 5E1608 802E4538 02402825 */   or        $a1, $s2, $zero
    /* 5E160C 802E453C 02202025 */  or         $a0, $s1, $zero
    /* 5E1610 802E4540 8FA5003C */  lw         $a1, 0x3C($sp)
    /* 5E1614 802E4544 0C0D86D4 */  jal        Pokemon_SetTargetPos
    /* 5E1618 802E4548 8FA60044 */   lw        $a2, 0x44($sp)
    /* 5E161C 802E454C 4405B000 */  mfc1       $a1, $f22
    /* 5E1620 802E4550 02202025 */  or         $a0, $s1, $zero
    /* 5E1624 802E4554 0C0D86DA */  jal        Pokemon_StepToTargetPos
    /* 5E1628 802E4558 24060001 */   addiu     $a2, $zero, 0x1
    /* 5E162C 802E455C 1040FFF1 */  beqz       $v0, .L802E4524_5E15F4
    /* 5E1630 802E4560 00000000 */   nop
    /* 5E1634 802E4564 C7A4003C */  lwc1       $f4, 0x3C($sp)
    /* 5E1638 802E4568 8FB80050 */  lw         $t8, 0x50($sp)
    /* 5E163C 802E456C 00002025 */  or         $a0, $zero, $zero
    /* 5E1640 802E4570 E7040004 */  swc1       $f4, 0x4($t8)
    /* 5E1644 802E4574 8FB90050 */  lw         $t9, 0x50($sp)
    /* 5E1648 802E4578 C7A60044 */  lwc1       $f6, 0x44($sp)
    /* 5E164C 802E457C E726000C */  swc1       $f6, 0xC($t9)
    /* 5E1650 802E4580 8E08008C */  lw         $t0, 0x8C($s0)
    /* 5E1654 802E4584 AE000094 */  sw         $zero, 0x94($s0)
    /* 5E1658 802E4588 35090002 */  ori        $t1, $t0, 0x2
    /* 5E165C 802E458C 0C0023CB */  jal        omEndProcess
    /* 5E1660 802E4590 AE09008C */   sw        $t1, 0x8C($s0)
    /* 5E1664 802E4594 8FBF0034 */  lw         $ra, 0x34($sp)
    /* 5E1668 802E4598 D7B40018 */  ldc1       $f20, 0x18($sp)
    /* 5E166C 802E459C D7B60020 */  ldc1       $f22, 0x20($sp)
    /* 5E1670 802E45A0 8FB00028 */  lw         $s0, 0x28($sp)
    /* 5E1674 802E45A4 8FB1002C */  lw         $s1, 0x2C($sp)
    /* 5E1678 802E45A8 8FB20030 */  lw         $s2, 0x30($sp)
    /* 5E167C 802E45AC 03E00008 */  jr         $ra
    /* 5E1680 802E45B0 27BD0058 */   addiu     $sp, $sp, 0x58
endlabel func_802E44DC_5E15AC
