.section .late_rodata
nonmatching D_802F038C_5ED45C

dlabel D_802F038C_5ED45C
    /* 5ED45C 802F038C 3DCCCCCD */ .float 0.1000000015
enddlabel D_802F038C_5ED45C


.section .text
/* Generated by spimdisasm 1.42.0 */

nonmatching func_802E8B1C_5E5BEC, 0x178

glabel func_802E8B1C_5E5BEC
    /* 5E5BEC 802E8B1C 27BDFFB0 */  addiu      $sp, $sp, -0x50
    /* 5E5BF0 802E8B20 3C0E802F */  lui        $t6, %hi(D_802EE8AC_5EB97C)
    /* 5E5BF4 802E8B24 8DCEE8AC */  lw         $t6, %lo(D_802EE8AC_5EB97C)($t6)
    /* 5E5BF8 802E8B28 F7BC0030 */  sdc1       $f28, 0x30($sp)
    /* 5E5BFC 802E8B2C AFBF004C */  sw         $ra, 0x4C($sp)
    /* 5E5C00 802E8B30 AFB30048 */  sw         $s3, 0x48($sp)
    /* 5E5C04 802E8B34 AFB20044 */  sw         $s2, 0x44($sp)
    /* 5E5C08 802E8B38 AFB10040 */  sw         $s1, 0x40($sp)
    /* 5E5C0C 802E8B3C AFB0003C */  sw         $s0, 0x3C($sp)
    /* 5E5C10 802E8B40 F7BA0028 */  sdc1       $f26, 0x28($sp)
    /* 5E5C14 802E8B44 F7B80020 */  sdc1       $f24, 0x20($sp)
    /* 5E5C18 802E8B48 F7B60018 */  sdc1       $f22, 0x18($sp)
    /* 5E5C1C 802E8B4C F7B40010 */  sdc1       $f20, 0x10($sp)
    /* 5E5C20 802E8B50 3C01802F */  lui        $at, %hi(D_802F038C_5ED45C)
    /* 5E5C24 802E8B54 C43C038C */  lwc1       $f28, %lo(D_802F038C_5ED45C)($at)
    /* 5E5C28 802E8B58 8C820048 */  lw         $v0, 0x48($a0)
    /* 5E5C2C 802E8B5C 8DCF0048 */  lw         $t7, 0x48($t6)
    /* 5E5C30 802E8B60 3C0143A0 */  lui        $at, (0x43A00000 >> 16)
    /* 5E5C34 802E8B64 4481D000 */  mtc1       $at, $f26
    /* 5E5C38 802E8B68 3C014316 */  lui        $at, (0x43160000 >> 16)
    /* 5E5C3C 802E8B6C 8C50004C */  lw         $s0, 0x4C($v0)
    /* 5E5C40 802E8B70 8DF1004C */  lw         $s1, 0x4C($t7)
    /* 5E5C44 802E8B74 4481C000 */  mtc1       $at, $f24
    /* 5E5C48 802E8B78 3C0141F0 */  lui        $at, (0x41F00000 >> 16)
    /* 5E5C4C 802E8B7C 4481A000 */  mtc1       $at, $f20
    /* 5E5C50 802E8B80 4480B000 */  mtc1       $zero, $f22
    /* 5E5C54 802E8B84 8C930058 */  lw         $s3, 0x58($a0)
    /* 5E5C58 802E8B88 00809025 */  or         $s2, $a0, $zero
    /* 5E5C5C 802E8B8C 26100004 */  addiu      $s0, $s0, 0x4
    /* 5E5C60 802E8B90 26310004 */  addiu      $s1, $s1, 0x4
  .L802E8B94_5E5C64:
    /* 5E5C64 802E8B94 0C002F2A */  jal        ohWait
    /* 5E5C68 802E8B98 24040001 */   addiu     $a0, $zero, 0x1
    /* 5E5C6C 802E8B9C C6240008 */  lwc1       $f4, 0x8($s1)
    /* 5E5C70 802E8BA0 C60E0008 */  lwc1       $f14, 0x8($s0)
    /* 5E5C74 802E8BA4 02402025 */  or         $a0, $s2, $zero
    /* 5E5C78 802E8BA8 46182080 */  add.s      $f2, $f4, $f24
    /* 5E5C7C 802E8BAC 460E1001 */  sub.s      $f0, $f2, $f14
    /* 5E5C80 802E8BB0 4616003C */  c.lt.s     $f0, $f22
    /* 5E5C84 802E8BB4 00000000 */  nop
    /* 5E5C88 802E8BB8 45020004 */  bc1fl      .L802E8BCC_5E5C9C
    /* 5E5C8C 802E8BBC 46000306 */   mov.s     $f12, $f0
    /* 5E5C90 802E8BC0 10000002 */  b          .L802E8BCC_5E5C9C
    /* 5E5C94 802E8BC4 46000307 */   neg.s     $f12, $f0
    /* 5E5C98 802E8BC8 46000306 */  mov.s      $f12, $f0
  .L802E8BCC_5E5C9C:
    /* 5E5C9C 802E8BCC 4614603C */  c.lt.s     $f12, $f20
    /* 5E5CA0 802E8BD0 00000000 */  nop
    /* 5E5CA4 802E8BD4 45020004 */  bc1fl      .L802E8BE8_5E5CB8
    /* 5E5CA8 802E8BD8 4600B03C */   c.lt.s    $f22, $f0
    /* 5E5CAC 802E8BDC 1000000A */  b          .L802E8C08_5E5CD8
    /* 5E5CB0 802E8BE0 E6020008 */   swc1      $f2, 0x8($s0)
    /* 5E5CB4 802E8BE4 4600B03C */  c.lt.s     $f22, $f0
  .L802E8BE8_5E5CB8:
    /* 5E5CB8 802E8BE8 00000000 */  nop
    /* 5E5CBC 802E8BEC 45020005 */  bc1fl      .L802E8C04_5E5CD4
    /* 5E5CC0 802E8BF0 46147201 */   sub.s     $f8, $f14, $f20
    /* 5E5CC4 802E8BF4 46147180 */  add.s      $f6, $f14, $f20
    /* 5E5CC8 802E8BF8 10000003 */  b          .L802E8C08_5E5CD8
    /* 5E5CCC 802E8BFC E6060008 */   swc1      $f6, 0x8($s0)
    /* 5E5CD0 802E8C00 46147201 */  sub.s      $f8, $f14, $f20
  .L802E8C04_5E5CD4:
    /* 5E5CD4 802E8C04 E6080008 */  swc1       $f8, 0x8($s0)
  .L802E8C08_5E5CD8:
    /* 5E5CD8 802E8C08 E67A0098 */  swc1       $f26, 0x98($s3)
    /* 5E5CDC 802E8C0C 8E26000C */  lw         $a2, 0xC($s1)
    /* 5E5CE0 802E8C10 0C0D86D4 */  jal        Pokemon_SetTargetPos
    /* 5E5CE4 802E8C14 8E250004 */   lw        $a1, 0x4($s1)
    /* 5E5CE8 802E8C18 4405E000 */  mfc1       $a1, $f28
    /* 5E5CEC 802E8C1C 02402025 */  or         $a0, $s2, $zero
    /* 5E5CF0 802E8C20 0C0D86DA */  jal        Pokemon_StepToTargetPos
    /* 5E5CF4 802E8C24 00003025 */   or        $a2, $zero, $zero
    /* 5E5CF8 802E8C28 1040FFDA */  beqz       $v0, .L802E8B94_5E5C64
    /* 5E5CFC 802E8C2C 00000000 */   nop
    /* 5E5D00 802E8C30 C62A0004 */  lwc1       $f10, 0x4($s1)
    /* 5E5D04 802E8C34 00002025 */  or         $a0, $zero, $zero
    /* 5E5D08 802E8C38 E60A0004 */  swc1       $f10, 0x4($s0)
    /* 5E5D0C 802E8C3C C630000C */  lwc1       $f16, 0xC($s1)
    /* 5E5D10 802E8C40 E610000C */  swc1       $f16, 0xC($s0)
    /* 5E5D14 802E8C44 C6320008 */  lwc1       $f18, 0x8($s1)
    /* 5E5D18 802E8C48 46189100 */  add.s      $f4, $f18, $f24
    /* 5E5D1C 802E8C4C E6040008 */  swc1       $f4, 0x8($s0)
    /* 5E5D20 802E8C50 8E78008C */  lw         $t8, 0x8C($s3)
    /* 5E5D24 802E8C54 AE600094 */  sw         $zero, 0x94($s3)
    /* 5E5D28 802E8C58 37190002 */  ori        $t9, $t8, 0x2
    /* 5E5D2C 802E8C5C 0C0023CB */  jal        omEndProcess
    /* 5E5D30 802E8C60 AE79008C */   sw        $t9, 0x8C($s3)
    /* 5E5D34 802E8C64 8FBF004C */  lw         $ra, 0x4C($sp)
    /* 5E5D38 802E8C68 D7B40010 */  ldc1       $f20, 0x10($sp)
    /* 5E5D3C 802E8C6C D7B60018 */  ldc1       $f22, 0x18($sp)
    /* 5E5D40 802E8C70 D7B80020 */  ldc1       $f24, 0x20($sp)
    /* 5E5D44 802E8C74 D7BA0028 */  ldc1       $f26, 0x28($sp)
    /* 5E5D48 802E8C78 D7BC0030 */  ldc1       $f28, 0x30($sp)
    /* 5E5D4C 802E8C7C 8FB0003C */  lw         $s0, 0x3C($sp)
    /* 5E5D50 802E8C80 8FB10040 */  lw         $s1, 0x40($sp)
    /* 5E5D54 802E8C84 8FB20044 */  lw         $s2, 0x44($sp)
    /* 5E5D58 802E8C88 8FB30048 */  lw         $s3, 0x48($sp)
    /* 5E5D5C 802E8C8C 03E00008 */  jr         $ra
    /* 5E5D60 802E8C90 27BD0050 */   addiu     $sp, $sp, 0x50
endlabel func_802E8B1C_5E5BEC
