#include "common.h"

Gfx zubat_part6_draw_far[] = {
    gsDPPipeSync(),
    gsDPSetTextureImage(G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, zubat_tex_wing_outside_pal),
    gsDPLoadSync(),
    gsDPLoadTLUTCmd(5, 15),
    gsDPPipeSync(),
    gsDPSetTextureImage(G_IM_FMT_CI, G_IM_SIZ_16b, 1, zubat_tex_wing_outside_png),
    gsDPLoadSync(),
    gsDPLoadBlock(G_TX_LOADTILE, 0, 0, 1023, 512),
    gsDPPipeSync(),
    gsSPModifyVertex(0, G_MWO_POINT_ST, 0x061A04DB),
    gsSPModifyVertex(1, G_MWO_POINT_ST, 0x061A0300),
    gsSPVertex(&zubat_vtx[271], 1, 4),
    gsSPVertex(&zubat_vtx[272], 2, 29),
    gsSP2Triangles(1, 4, 29, 0, 0, 1, 29, 0),
    gsSP1Triangle(30, 0, 29, 0),
    gsDPPipeSync(),
    gsDPSetTextureImage(G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, zubat_tex_wing_inside_pal),
    gsDPLoadSync(),
    gsDPLoadTLUTCmd(5, 15),
    gsDPPipeSync(),
    gsDPSetTextureImage(G_IM_FMT_CI, G_IM_SIZ_16b, 1, zubat_tex_wing_inside_png),
    gsDPLoadSync(),
    gsDPLoadBlock(G_TX_LOADTILE, 0, 0, 1023, 512),
    gsDPPipeSync(),
    gsSPModifyVertex(2, G_MWO_POINT_ST, 0x061A04DB),
    gsSPModifyVertex(3, G_MWO_POINT_ST, 0x061A0300),
    gsSPVertex(&zubat_vtx[274], 1, 4),
    gsSPVertex(&zubat_vtx[275], 2, 27),
    gsSP2Triangles(27, 4, 3, 0, 27, 3, 2, 0),
    gsSP1Triangle(27, 2, 28, 0),
    gsSPEndDisplayList(),
};
