#include "common.h"

Gfx zubat_part5_draw_near[] = {
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsDPSetTile(G_IM_FMT_CI, G_IM_SIZ_16b, 0, 0x0000, G_TX_LOADTILE, 0, G_TX_NOMIRROR | G_TX_WRAP, 6, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_WRAP, 6, G_TX_NOLOD),
    gsDPSetTile(G_IM_FMT_CI, G_IM_SIZ_4b, 4, 0x0000, G_TX_RENDERTILE, 0, G_TX_NOMIRROR | G_TX_CLAMP, 6, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_CLAMP, 6, G_TX_NOLOD),
    gsDPSetTextureImage(G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, zubat_tex_wing_outside_pal),
    gsDPLoadSync(),
    gsDPLoadTLUTCmd(5, 15),
    gsDPPipeSync(),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetTileSize(G_TX_RENDERTILE, 0, 0, 0x00FC, 0x00FC),
    gsDPSetTextureImage(G_IM_FMT_CI, G_IM_SIZ_16b, 1, zubat_tex_wing_outside_png),
    gsDPLoadSync(),
    gsDPLoadBlock(G_TX_LOADTILE, 0, 0, 1023, 512),
    gsDPPipeSync(),
    gsSPModifyVertex(0, G_MWO_POINT_ST, 0x07FF04EB),
    gsSPModifyVertex(1, G_MWO_POINT_ST, 0x07FF03CB),
    gsSPModifyVertex(2, G_MWO_POINT_ST, 0x07FF0479),
    gsSPVertex(&zubat_vtx[127], 1, 26),
    gsSPVertex(&zubat_vtx[128], 2, 28),
    gsSP2Triangles(26, 2, 28, 0, 28, 2, 1, 0),
    gsSP2Triangles(26, 29, 0, 0, 26, 0, 2, 0),
    gsDPPipeSync(),
    gsDPSetTextureImage(G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, zubat_tex_wing_inside_pal),
    gsDPLoadSync(),
    gsDPLoadTLUTCmd(5, 15),
    gsDPPipeSync(),
    gsDPSetTextureImage(G_IM_FMT_CI, G_IM_SIZ_16b, 1, zubat_tex_wing_inside_png),
    gsDPLoadSync(),
    gsDPLoadBlock(G_TX_LOADTILE, 0, 0, 1023, 512),
    gsDPPipeSync(),
    gsSPModifyVertex(0, G_MWO_POINT_ST, 0x07FF04EB),
    gsSPModifyVertex(1, G_MWO_POINT_ST, 0x07FF03CB),
    gsSPVertex(&zubat_vtx[130], 1, 27),
    gsSPVertex(&zubat_vtx[131], 1, 30),
    gsSP2Triangles(1, 30, 27, 0, 1, 0, 30, 0),
    gsSPEndDisplayList(),
};
