#include "common.h"

Gfx pikachu_part15_draw_far[] = {
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPSetAlphaCompare(G_AC_NONE),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_OPA_SURF2),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsDPSetTile(G_IM_FMT_RGBA, G_IM_SIZ_16b, 0, 0x0000, G_TX_LOADTILE, 0, G_TX_NOMIRROR | G_TX_WRAP, 3, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_WRAP, 3, G_TX_NOLOD),
    gsDPSetTile(G_IM_FMT_RGBA, G_IM_SIZ_16b, 2, 0x0000, G_TX_RENDERTILE, 0, G_TX_NOMIRROR | G_TX_CLAMP, 3, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_CLAMP, 3, G_TX_NOLOD),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetTileSize(G_TX_RENDERTILE, 0, 0, 0x001C, 0x001C),
    gsDPSetTextureImage(G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, pikachu_tex_body_png),
    gsDPLoadSync(),
    gsDPLoadBlock(G_TX_LOADTILE, 0, 0, 63, 1024),
    gsDPPipeSync(),
    gsSPModifyVertex(0, G_MWO_POINT_ST, 0x003C00D9),
    gsSPModifyVertex(1, G_MWO_POINT_ST, 0x004500B6),
    gsSPModifyVertex(2, G_MWO_POINT_ST, 0x008E00A4),
    gsSPVertex(&pikachu_vtx[532], 4, 3),
    gsSPVertex(&pikachu_vtx[536], 3, 28),
    gsSP2Triangles(30, 2, 1, 0, 6, 30, 1, 0),
    gsSP1Triangle(1, 0, 5, 0),
    gsSPModifyVertex(0, G_MWO_POINT_ST, 0x00E100A8),
    gsSPModifyVertex(2, G_MWO_POINT_ST, 0x00C500BA),
    gsSP1Triangle(4, 0, 2, 0),
    gsSPModifyVertex(0, G_MWO_POINT_ST, 0x00150026),
    gsSPModifyVertex(2, G_MWO_POINT_ST, 0x00FF0000),
    gsSP2Triangles(2, 3, 4, 0, 0, 28, 29, 0),
    gsSPEndDisplayList(),
};
