.section .late_rodata
nonmatching D_800E6C50_64400

dlabel D_800E6C50_64400
    /* 64400 800E6C50 38D1B717 */ .float 9.999999747e-05
enddlabel D_800E6C50_64400

nonmatching D_800E6C54_64404

dlabel D_800E6C54_64404
    /* 64404 800E6C54 38D1B717 */ .float 9.999999747e-05
enddlabel D_800E6C54_64404

nonmatching D_800E6C58_64408

dlabel D_800E6C58_64408
    /* 64408 800E6C58 7F7FFFFF */ .float 3.402823466e+38
enddlabel D_800E6C58_64408

nonmatching D_800E6C5C_6440C

dlabel D_800E6C5C_6440C
    /* 6440C 800E6C5C 3F333333 */ .float 0.6999999881
enddlabel D_800E6C5C_6440C


.section .text
/* Generated by spimdisasm 1.42.1 */

nonmatching func_800E5AD4_63284, 0x25C

glabel func_800E5AD4_63284
    /* 63284 800E5AD4 27BDFF78 */  addiu      $sp, $sp, -0x88
    /* 63288 800E5AD8 AFA5008C */  sw         $a1, 0x8C($sp)
    /* 6328C 800E5ADC AFA70094 */  sw         $a3, 0x94($sp)
    /* 63290 800E5AE0 8FA7008C */  lw         $a3, 0x8C($sp)
    /* 63294 800E5AE4 00802825 */  or         $a1, $a0, $zero
    /* 63298 800E5AE8 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 6329C 800E5AEC AFA40088 */  sw         $a0, 0x88($sp)
    /* 632A0 800E5AF0 AFB00020 */  sw         $s0, 0x20($sp)
    /* 632A4 800E5AF4 AFA60090 */  sw         $a2, 0x90($sp)
    /* 632A8 800E5AF8 27A40070 */  addiu      $a0, $sp, 0x70
    /* 632AC 800E5AFC 0C00692B */  jal        Vec3fDiff
    /* 632B0 800E5B00 AFA7008C */   sw        $a3, 0x8C($sp)
    /* 632B4 800E5B04 8FA7008C */  lw         $a3, 0x8C($sp)
    /* 632B8 800E5B08 8FB000A0 */  lw         $s0, 0xA0($sp)
    /* 632BC 800E5B0C C4E40000 */  lwc1       $f4, 0x0($a3)
    /* 632C0 800E5B10 02002025 */  or         $a0, $s0, $zero
    /* 632C4 800E5B14 E6040000 */  swc1       $f4, 0x0($s0)
    /* 632C8 800E5B18 C4E80004 */  lwc1       $f8, 0x4($a3)
    /* 632CC 800E5B1C E6080004 */  swc1       $f8, 0x4($s0)
    /* 632D0 800E5B20 C4EA0008 */  lwc1       $f10, 0x8($a3)
    /* 632D4 800E5B24 0C0068D8 */  jal        Vec3fNormalize
    /* 632D8 800E5B28 E60A0008 */   swc1      $f10, 0x8($s0)
    /* 632DC 800E5B2C C6060000 */  lwc1       $f6, 0x0($s0)
    /* 632E0 800E5B30 46000406 */  mov.s      $f16, $f0
    /* 632E4 800E5B34 3C01800E */  lui        $at, %hi(D_800E6C50_64400)
    /* 632E8 800E5B38 E7A6007C */  swc1       $f6, 0x7C($sp)
    /* 632EC 800E5B3C C6040004 */  lwc1       $f4, 0x4($s0)
    /* 632F0 800E5B40 C7AA007C */  lwc1       $f10, 0x7C($sp)
    /* 632F4 800E5B44 E7A40080 */  swc1       $f4, 0x80($sp)
    /* 632F8 800E5B48 C6080008 */  lwc1       $f8, 0x8($s0)
    /* 632FC 800E5B4C 460A5182 */  mul.s      $f6, $f10, $f10
    /* 63300 800E5B50 E7AA0028 */  swc1       $f10, 0x28($sp)
    /* 63304 800E5B54 E7A80084 */  swc1       $f8, 0x84($sp)
    /* 63308 800E5B58 C7A40084 */  lwc1       $f4, 0x84($sp)
    /* 6330C 800E5B5C 46042202 */  mul.s      $f8, $f4, $f4
    /* 63310 800E5B60 46083180 */  add.s      $f6, $f6, $f8
    /* 63314 800E5B64 C7A80080 */  lwc1       $f8, 0x80($sp)
    /* 63318 800E5B68 46084282 */  mul.s      $f10, $f8, $f8
    /* 6331C 800E5B6C 460A3081 */  sub.s      $f2, $f6, $f10
    /* 63320 800E5B70 C7AA0070 */  lwc1       $f10, 0x70($sp)
    /* 63324 800E5B74 C7A60028 */  lwc1       $f6, 0x28($sp)
    /* 63328 800E5B78 E7A80028 */  swc1       $f8, 0x28($sp)
    /* 6332C 800E5B7C C7A80078 */  lwc1       $f8, 0x78($sp)
    /* 63330 800E5B80 460A3182 */  mul.s      $f6, $f6, $f10
    /* 63334 800E5B84 46001486 */  mov.s      $f18, $f2
    /* 63338 800E5B88 46082102 */  mul.s      $f4, $f4, $f8
    /* 6333C 800E5B8C 46043180 */  add.s      $f6, $f6, $f4
    /* 63340 800E5B90 C7A40028 */  lwc1       $f4, 0x28($sp)
    /* 63344 800E5B94 E7AA0028 */  swc1       $f10, 0x28($sp)
    /* 63348 800E5B98 C7AA0074 */  lwc1       $f10, 0x74($sp)
    /* 6334C 800E5B9C 460A2102 */  mul.s      $f4, $f4, $f10
    /* 63350 800E5BA0 46043301 */  sub.s      $f12, $f6, $f4
    /* 63354 800E5BA4 C7A60028 */  lwc1       $f6, 0x28($sp)
    /* 63358 800E5BA8 46063102 */  mul.s      $f4, $f6, $f6
    /* 6335C 800E5BAC 46006386 */  mov.s      $f14, $f12
    /* 63360 800E5BB0 46084182 */  mul.s      $f6, $f8, $f8
    /* 63364 800E5BB4 46062200 */  add.s      $f8, $f4, $f6
    /* 63368 800E5BB8 460A5102 */  mul.s      $f4, $f10, $f10
    /* 6336C 800E5BBC 44805000 */  mtc1       $zero, $f10
    /* 63370 800E5BC0 00000000 */  nop
    /* 63374 800E5BC4 460A103C */  c.lt.s     $f2, $f10
    /* 63378 800E5BC8 46044181 */  sub.s      $f6, $f8, $f4
    /* 6337C 800E5BCC E7A60034 */  swc1       $f6, 0x34($sp)
    /* 63380 800E5BD0 45000003 */  bc1f       .L800E5BE0_63390
    /* 63384 800E5BD4 E7A60058 */   swc1      $f6, 0x58($sp)
    /* 63388 800E5BD8 10000002 */  b          .L800E5BE4_63394
    /* 6338C 800E5BDC 46001007 */   neg.s     $f0, $f2
  .L800E5BE0_63390:
    /* 63390 800E5BE0 46001006 */  mov.s      $f0, $f2
  .L800E5BE4_63394:
    /* 63394 800E5BE4 C4286C50 */  lwc1       $f8, %lo(D_800E6C50_64400)($at)
    /* 63398 800E5BE8 C7A60034 */  lwc1       $f6, 0x34($sp)
    /* 6339C 800E5BEC 4608003C */  c.lt.s     $f0, $f8
    /* 633A0 800E5BF0 00000000 */  nop
    /* 633A4 800E5BF4 45030049 */  bc1tl      .L800E5D1C_634CC
    /* 633A8 800E5BF8 00001025 */   or        $v0, $zero, $zero
    /* 633AC 800E5BFC 460C6102 */  mul.s      $f4, $f12, $f12
    /* 633B0 800E5C00 00000000 */  nop
    /* 633B4 800E5C04 46061282 */  mul.s      $f10, $f2, $f6
    /* 633B8 800E5C08 C7A60058 */  lwc1       $f6, 0x58($sp)
    /* 633BC 800E5C0C 4604503E */  c.le.s     $f10, $f4
    /* 633C0 800E5C10 00000000 */  nop
    /* 633C4 800E5C14 45000040 */  bc1f       .L800E5D18_634C8
    /* 633C8 800E5C18 00000000 */   nop
    /* 633CC 800E5C1C 460E7202 */  mul.s      $f8, $f14, $f14
    /* 633D0 800E5C20 E7AE005C */  swc1       $f14, 0x5C($sp)
    /* 633D4 800E5C24 E7B00050 */  swc1       $f16, 0x50($sp)
    /* 633D8 800E5C28 46069102 */  mul.s      $f4, $f18, $f6
    /* 633DC 800E5C2C E7B20060 */  swc1       $f18, 0x60($sp)
    /* 633E0 800E5C30 0C00D824 */  jal        sqrtf
    /* 633E4 800E5C34 46044301 */   sub.s     $f12, $f8, $f4
    /* 633E8 800E5C38 C7AE005C */  lwc1       $f14, 0x5C($sp)
    /* 633EC 800E5C3C C7B20060 */  lwc1       $f18, 0x60($sp)
    /* 633F0 800E5C40 3C01800E */  lui        $at, %hi(D_800E6C54_64404)
    /* 633F4 800E5C44 46007287 */  neg.s      $f10, $f14
    /* 633F8 800E5C48 C4286C54 */  lwc1       $f8, %lo(D_800E6C54_64404)($at)
    /* 633FC 800E5C4C 46005181 */  sub.s      $f6, $f10, $f0
    /* 63400 800E5C50 C7B00050 */  lwc1       $f16, 0x50($sp)
    /* 63404 800E5C54 3C01800E */  lui        $at, %hi(D_800E6C58_64408)
    /* 63408 800E5C58 C7A4004C */  lwc1       $f4, 0x4C($sp)
    /* 6340C 800E5C5C 46123083 */  div.s      $f2, $f6, $f18
    /* 63410 800E5C60 4602403C */  c.lt.s     $f8, $f2
    /* 63414 800E5C64 00000000 */  nop
    /* 63418 800E5C68 4502002C */  bc1fl      .L800E5D1C_634CC
    /* 6341C 800E5C6C 00001025 */   or        $v0, $zero, $zero
    /* 63420 800E5C70 C42A6C58 */  lwc1       $f10, %lo(D_800E6C58_64408)($at)
    /* 63424 800E5C74 C7A60080 */  lwc1       $f6, 0x80($sp)
    /* 63428 800E5C78 460A203C */  c.lt.s     $f4, $f10
    /* 6342C 800E5C7C 00000000 */  nop
    /* 63430 800E5C80 45020026 */  bc1fl      .L800E5D1C_634CC
    /* 63434 800E5C84 00001025 */   or        $v0, $zero, $zero
    /* 63438 800E5C88 46061202 */  mul.s      $f8, $f2, $f6
    /* 6343C 800E5C8C C7A40074 */  lwc1       $f4, 0x74($sp)
    /* 63440 800E5C90 44805000 */  mtc1       $zero, $f10
    /* 63444 800E5C94 C7A60098 */  lwc1       $f6, 0x98($sp)
    /* 63448 800E5C98 46044000 */  add.s      $f0, $f8, $f4
    /* 6344C 800E5C9C 4600503E */  c.le.s     $f10, $f0
    /* 63450 800E5CA0 00000000 */  nop
    /* 63454 800E5CA4 4502001D */  bc1fl      .L800E5D1C_634CC
    /* 63458 800E5CA8 00001025 */   or        $v0, $zero, $zero
    /* 6345C 800E5CAC 4606003E */  c.le.s     $f0, $f6
    /* 63460 800E5CB0 00000000 */  nop
    /* 63464 800E5CB4 45020019 */  bc1fl      .L800E5D1C_634CC
    /* 63468 800E5CB8 00001025 */   or        $v0, $zero, $zero
    /* 6346C 800E5CBC 4610103C */  c.lt.s     $f2, $f16
    /* 63470 800E5CC0 27A40070 */  addiu      $a0, $sp, 0x70
    /* 63474 800E5CC4 27A5007C */  addiu      $a1, $sp, 0x7C
    /* 63478 800E5CC8 8FA7009C */  lw         $a3, 0x9C($sp)
    /* 6347C 800E5CCC 45020013 */  bc1fl      .L800E5D1C_634CC
    /* 63480 800E5CD0 00001025 */   or        $v0, $zero, $zero
    /* 63484 800E5CD4 44061000 */  mfc1       $a2, $f2
    /* 63488 800E5CD8 AFB00010 */  sw         $s0, 0x10($sp)
    /* 6348C 800E5CDC 0C039693 */  jal        func_800E5A4C_631FC
    /* 63490 800E5CE0 E7B00050 */   swc1      $f16, 0x50($sp)
    /* 63494 800E5CE4 3C01800E */  lui        $at, %hi(D_800E6C5C_6440C)
    /* 63498 800E5CE8 C7B00050 */  lwc1       $f16, 0x50($sp)
    /* 6349C 800E5CEC C4286C5C */  lwc1       $f8, %lo(D_800E6C5C_6440C)($at)
    /* 634A0 800E5CF0 02002025 */  or         $a0, $s0, $zero
    /* 634A4 800E5CF4 46088402 */  mul.s      $f16, $f16, $f8
    /* 634A8 800E5CF8 44058000 */  mfc1       $a1, $f16
    /* 634AC 800E5CFC 0C00694C */  jal        Vec3fScale
    /* 634B0 800E5D00 00000000 */   nop
    /* 634B4 800E5D04 8FA4009C */  lw         $a0, 0x9C($sp)
    /* 634B8 800E5D08 0C00690F */  jal        Vec3fAdd
    /* 634BC 800E5D0C 8FA50090 */   lw        $a1, 0x90($sp)
    /* 634C0 800E5D10 10000002 */  b          .L800E5D1C_634CC
    /* 634C4 800E5D14 24020001 */   addiu     $v0, $zero, 0x1
  .L800E5D18_634C8:
    /* 634C8 800E5D18 00001025 */  or         $v0, $zero, $zero
  .L800E5D1C_634CC:
    /* 634CC 800E5D1C 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 634D0 800E5D20 8FB00020 */  lw         $s0, 0x20($sp)
    /* 634D4 800E5D24 27BD0088 */  addiu      $sp, $sp, 0x88
    /* 634D8 800E5D28 03E00008 */  jr         $ra
    /* 634DC 800E5D2C 00000000 */   nop
endlabel func_800E5AD4_63284
