.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.1 */

.align 3
nonmatching D_802F03D0_5ED4A0

dlabel D_802F03D0_5ED4A0
    /* 5ED4A0 802F03D0 3FE39DB22D0E5604 */ .double 0.612999999999999989
enddlabel D_802F03D0_5ED4A0

.align 3
nonmatching D_802F03D8_5ED4A8

dlabel D_802F03D8_5ED4A8
    /* 5ED4A8 802F03D8 3FD676C8B4395810 */ .double 0.350999999999999979
enddlabel D_802F03D8_5ED4A8
