.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.1 */

.align 2
nonmatching D_803A68F0_87A0A0

dlabel D_803A68F0_87A0A0
    /* 87A0A0 803A68F0 */ .asciz "\\l"
    /* 5C6C0000 */
.align 2
.align 2
    /* 87A0A4 803A68F4 */ .asciz ""
    /* 00000000 */
.align 2
.align 2
    /* 87A0A8 803A68F8 */ .asciz ""
    /* 00000000 */
.align 2
.align 2
    /* 87A0AC 803A68FC */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_803A68F0_87A0A0
