.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.2 */

.align 3
nonmatching D_803A6840_879FF0

dlabel D_803A6840_879FF0
    /* 879FF0 803A6840 3FD3333333333333 */ .double 0.299999999999999989
    /* 879FF8 803A6848 0000000000000000 */ .double 0
enddlabel D_803A6840_879FF0
