.section .late_rodata
nonmatching D_beach_802CE190

dlabel D_beach_802CE190
    /* 566200 802CE190 40490FDB */ .float 3.141592741
    /* 566204 802CE194 00000000 */ .float 0
    /* 566208 802CE198 00000000 */ .float 0
    /* 56620C 802CE19C 00000000 */ .float 0
enddlabel D_beach_802CE190


.section .text
/* Generated by spimdisasm 1.42.1 */

nonmatching func_beach_802CAB50, 0xB8

glabel func_beach_802CAB50
    /* 562BC0 802CAB50 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* 562BC4 802CAB54 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 562BC8 802CAB58 AFB00018 */  sw         $s0, 0x18($sp)
    /* 562BCC 802CAB5C 8C820048 */  lw         $v0, 0x48($a0)
    /* 562BD0 802CAB60 3C05802D */  lui        $a1, %hi(D_beach_802CDAB4)
    /* 562BD4 802CAB64 00808025 */  or         $s0, $a0, $zero
    /* 562BD8 802CAB68 8C4E004C */  lw         $t6, 0x4C($v0)
    /* 562BDC 802CAB6C 24A5DAB4 */  addiu      $a1, $a1, %lo(D_beach_802CDAB4)
    /* 562BE0 802CAB70 25CF0014 */  addiu      $t7, $t6, 0x14
    /* 562BE4 802CAB74 AFAF0024 */  sw         $t7, 0x24($sp)
    /* 562BE8 802CAB78 8C980058 */  lw         $t8, 0x58($a0)
    /* 562BEC 802CAB7C 0C0D7C4E */  jal        Pokemon_SetAnimation
    /* 562BF0 802CAB80 AFB80020 */   sw        $t8, 0x20($sp)
    /* 562BF4 802CAB84 0C006785 */  jal        randRange
    /* 562BF8 802CAB88 24040168 */   addiu     $a0, $zero, 0x168
    /* 562BFC 802CAB8C 44822000 */  mtc1       $v0, $f4
    /* 562C00 802CAB90 3C01802D */  lui        $at, %hi(D_beach_802CE190)
    /* 562C04 802CAB94 C428E190 */  lwc1       $f8, %lo(D_beach_802CE190)($at)
    /* 562C08 802CAB98 468021A0 */  cvt.s.w    $f6, $f4
    /* 562C0C 802CAB9C 3C014334 */  lui        $at, (0x43340000 >> 16)
    /* 562C10 802CABA0 44818000 */  mtc1       $at, $f16
    /* 562C14 802CABA4 8FB90024 */  lw         $t9, 0x24($sp)
    /* 562C18 802CABA8 3C05802D */  lui        $a1, %hi(func_beach_802CAC08)
    /* 562C1C 802CABAC 24A5AC08 */  addiu      $a1, $a1, %lo(func_beach_802CAC08)
    /* 562C20 802CABB0 46083282 */  mul.s      $f10, $f6, $f8
    /* 562C24 802CABB4 02002025 */  or         $a0, $s0, $zero
    /* 562C28 802CABB8 46105483 */  div.s      $f18, $f10, $f16
    /* 562C2C 802CABBC 0C0D7B7E */  jal        Pokemon_StartPathProc
    /* 562C30 802CABC0 E732000C */   swc1      $f18, 0xC($t9)
    /* 562C34 802CABC4 8FA80020 */  lw         $t0, 0x20($sp)
    /* 562C38 802CABC8 02002025 */  or         $a0, $s0, $zero
    /* 562C3C 802CABCC 24050001 */  addiu      $a1, $zero, 0x1
    /* 562C40 802CABD0 0C0D7EFC */  jal        Pokemon_WaitForFlag
    /* 562C44 802CABD4 AD0000AC */   sw        $zero, 0xAC($t0)
    /* 562C48 802CABD8 3C01802D */  lui        $at, %hi(D_beach_802CC014)
    /* 562C4C 802CABDC A420C014 */  sh         $zero, %lo(D_beach_802CC014)($at)
    /* 562C50 802CABE0 0C0D7F5C */  jal        Pokemon_RunCleanup
    /* 562C54 802CABE4 02002025 */   or        $a0, $s0, $zero
    /* 562C58 802CABE8 02002025 */  or         $a0, $s0, $zero
    /* 562C5C 802CABEC 0C0D7B16 */  jal        Pokemon_SetState
    /* 562C60 802CABF0 00002825 */   or        $a1, $zero, $zero
    /* 562C64 802CABF4 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 562C68 802CABF8 8FB00018 */  lw         $s0, 0x18($sp)
    /* 562C6C 802CABFC 27BD0030 */  addiu      $sp, $sp, 0x30
    /* 562C70 802CAC00 03E00008 */  jr         $ra
    /* 562C74 802CAC04 00000000 */   nop
endlabel func_beach_802CAB50
