.section .late_rodata
nonmatching D_801C6AD8_98C2F8

dlabel D_801C6AD8_98C2F8
    /* 98C2F8 801C6AD8 3DCCCCCD */ .float 0.1000000015
enddlabel D_801C6AD8_98C2F8


.section .text
/* Generated by spimdisasm 1.42.1 */

nonmatching func_800E48C4_8AA0E4, 0xB0

glabel func_800E48C4_8AA0E4
    /* 8AA0E4 800E48C4 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 8AA0E8 800E48C8 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 8AA0EC 800E48CC AFB10020 */  sw         $s1, 0x20($sp)
    /* 8AA0F0 800E48D0 AFB0001C */  sw         $s0, 0x1C($sp)
    /* 8AA0F4 800E48D4 F7B40010 */  sdc1       $f20, 0x10($sp)
    /* 8AA0F8 800E48D8 0C008A39 */  jal        auPlaySound
    /* 8AA0FC 800E48DC 24040052 */   addiu     $a0, $zero, 0x52
    /* 8AA100 800E48E0 0C0DC17C */  jal        func_803705F0
    /* 8AA104 800E48E4 24040001 */   addiu     $a0, $zero, 0x1
    /* 8AA108 800E48E8 0C038C8C */  jal        func_800E3230_8A8A50
    /* 8AA10C 800E48EC 00000000 */   nop
    /* 8AA110 800E48F0 0C0DC30D */  jal        func_80370C34
    /* 8AA114 800E48F4 00402025 */   or        $a0, $v0, $zero
    /* 8AA118 800E48F8 24040001 */  addiu      $a0, $zero, 0x1
    /* 8AA11C 800E48FC 0C0DC240 */  jal        func_80370900
    /* 8AA120 800E4900 24050003 */   addiu     $a1, $zero, 0x3
    /* 8AA124 800E4904 3C01801C */  lui        $at, %hi(D_801C6AD8_98C2F8)
    /* 8AA128 800E4908 C42C6AD8 */  lwc1       $f12, %lo(D_801C6AD8_98C2F8)($at)
    /* 8AA12C 800E490C 0C0DC264 */  jal        func_80370990
    /* 8AA130 800E4910 24050003 */   addiu     $a1, $zero, 0x3
    /* 8AA134 800E4914 3C0141F0 */  lui        $at, (0x41F00000 >> 16)
    /* 8AA138 800E4918 4481A000 */  mtc1       $at, $f20
    /* 8AA13C 800E491C 24100001 */  addiu      $s0, $zero, 0x1
    /* 8AA140 800E4920 2411001E */  addiu      $s1, $zero, 0x1E
    /* 8AA144 800E4924 44902000 */  mtc1       $s0, $f4
  .L800E4928_8AA148:
    /* 8AA148 800E4928 24050003 */  addiu      $a1, $zero, 0x3
    /* 8AA14C 800E492C 468021A0 */  cvt.s.w    $f6, $f4
    /* 8AA150 800E4930 0C0DC264 */  jal        func_80370990
    /* 8AA154 800E4934 46143303 */   div.s     $f12, $f6, $f20
    /* 8AA158 800E4938 26100001 */  addiu      $s0, $s0, 0x1
    /* 8AA15C 800E493C 0C002F2A */  jal        ohWait
    /* 8AA160 800E4940 24040001 */   addiu     $a0, $zero, 0x1
    /* 8AA164 800E4944 5611FFF8 */  bnel       $s0, $s1, .L800E4928_8AA148
    /* 8AA168 800E4948 44902000 */   mtc1      $s0, $f4
    /* 8AA16C 800E494C 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 8AA170 800E4950 44816000 */  mtc1       $at, $f12
    /* 8AA174 800E4954 0C0DC264 */  jal        func_80370990
    /* 8AA178 800E4958 24050003 */   addiu     $a1, $zero, 0x3
    /* 8AA17C 800E495C 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 8AA180 800E4960 D7B40010 */  ldc1       $f20, 0x10($sp)
    /* 8AA184 800E4964 8FB0001C */  lw         $s0, 0x1C($sp)
    /* 8AA188 800E4968 8FB10020 */  lw         $s1, 0x20($sp)
    /* 8AA18C 800E496C 03E00008 */  jr         $ra
    /* 8AA190 800E4970 27BD0028 */   addiu     $sp, $sp, 0x28
endlabel func_800E48C4_8AA0E4
