.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.2 */

nonmatching D_8038A3C0_52A7D0

dlabel D_8038A3C0_52A7D0
    /* 52A7D0 8038A3C0 3E4CCCCD */ .float 0.200000003
    /* 52A7D4 8038A3C4 00000000 */ .float 0
    /* 52A7D8 8038A3C8 00000000 */ .float 0
    /* 52A7DC 8038A3CC 00000000 */ .float 0
enddlabel D_8038A3C0_52A7D0
