#include "common.h"

Gfx vulpix_part15_draw_far[] = {
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsDPSetTile(G_IM_FMT_CI, G_IM_SIZ_16b, 0, 0x0000, G_TX_LOADTILE, 0, G_TX_NOMIRROR | G_TX_WRAP, 5, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_WRAP, 6, G_TX_NOLOD),
    gsDPSetTile(G_IM_FMT_CI, G_IM_SIZ_8b, 8, 0x0000, G_TX_RENDERTILE, 0, G_TX_NOMIRROR | G_TX_CLAMP, 5, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_CLAMP, 6, G_TX_NOLOD),
    gsDPSetTextureImage(G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, vulpix_tex_paw_pal),
    gsDPLoadSync(),
    gsDPLoadTLUTCmd(5, 254),
    gsDPPipeSync(),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetTileSize(G_TX_RENDERTILE, 0, 0, 0x00FC, 0x007C),
    gsDPSetTextureImage(G_IM_FMT_CI, G_IM_SIZ_16b, 1, vulpix_tex_paw_png),
    gsDPLoadSync(),
    gsDPLoadBlock(G_TX_LOADTILE, 0, 0, 1023, 256),
    gsDPPipeSync(),
    gsSPModifyVertex(0, G_MWO_POINT_ST, 0x07DF029F),
    gsSPModifyVertex(1, G_MWO_POINT_ST, 0x07BE0239),
    gsSPModifyVertex(2, G_MWO_POINT_ST, 0x00210299),
    gsSPVertex(&vulpix_vtx[538], 6, 3),
    gsSP2Triangles(8, 2, 1, 0, 1, 7, 8, 0),
    gsSPModifyVertex(1, G_MWO_POINT_ST, 0x005E0239),
    gsSP2Triangles(1, 0, 6, 0, 6, 5, 1, 0),
    gsSP2Triangles(8, 6, 0, 0, 0, 2, 8, 0),
    gsSP1Triangle(4, 3, 8, 0),
    gsSPEndDisplayList(),
};
