.section .late_rodata
nonmatching D_802E4C74_6CCA54

dlabel D_802E4C74_6CCA54
    /* 6CCA54 802E4C74 3F666666 */ .float 0.8999999762
    /* 6CCA58 802E4C78 00000000 */ .float 0
    /* 6CCA5C 802E4C7C 00000000 */ .float 0
enddlabel D_802E4C74_6CCA54


.section .text
/* Generated by spimdisasm 1.42.2 */

nonmatching func_802DEB00_6C68E0, 0xB8

glabel func_802DEB00_6C68E0
    /* 6C68E0 802DEB00 27BDFFB8 */  addiu      $sp, $sp, -0x48
    /* 6C68E4 802DEB04 AFBF002C */  sw         $ra, 0x2C($sp)
    /* 6C68E8 802DEB08 AFB20028 */  sw         $s2, 0x28($sp)
    /* 6C68EC 802DEB0C AFB10024 */  sw         $s1, 0x24($sp)
    /* 6C68F0 802DEB10 AFB00020 */  sw         $s0, 0x20($sp)
    /* 6C68F4 802DEB14 F7B40018 */  sdc1       $f20, 0x18($sp)
    /* 6C68F8 802DEB18 8C8E0058 */  lw         $t6, 0x58($a0)
    /* 6C68FC 802DEB1C 3C01802E */  lui        $at, %hi(D_802E4C74_6CCA54)
    /* 6C6900 802DEB20 C4344C74 */  lwc1       $f20, %lo(D_802E4C74_6CCA54)($at)
    /* 6C6904 802DEB24 27B00034 */  addiu      $s0, $sp, 0x34
    /* 6C6908 802DEB28 27B10030 */  addiu      $s1, $sp, 0x30
    /* 6C690C 802DEB2C 24120002 */  addiu      $s2, $zero, 0x2
    /* 6C6910 802DEB30 AFAE0038 */  sw         $t6, 0x38($sp)
    /* 6C6914 802DEB34 02002025 */  or         $a0, $s0, $zero
  .L802DEB38_6C6918:
    /* 6C6918 802DEB38 0C0D5CE1 */  jal        getLevelProgress
    /* 6C691C 802DEB3C 02202825 */   or        $a1, $s1, $zero
    /* 6C6920 802DEB40 8FA20034 */  lw         $v0, 0x34($sp)
    /* 6C6924 802DEB44 C7A40030 */  lwc1       $f4, 0x30($sp)
    /* 6C6928 802DEB48 28410003 */  slti       $at, $v0, 0x3
    /* 6C692C 802DEB4C 5020000C */  beql       $at, $zero, .L802DEB80_6C6960
    /* 6C6930 802DEB50 8FAF0038 */   lw        $t7, 0x38($sp)
    /* 6C6934 802DEB54 14520005 */  bne        $v0, $s2, .L802DEB6C_6C694C
    /* 6C6938 802DEB58 00000000 */   nop
    /* 6C693C 802DEB5C 4604A03E */  c.le.s     $f20, $f4
    /* 6C6940 802DEB60 00000000 */  nop
    /* 6C6944 802DEB64 45030006 */  bc1tl      .L802DEB80_6C6960
    /* 6C6948 802DEB68 8FAF0038 */   lw        $t7, 0x38($sp)
  .L802DEB6C_6C694C:
    /* 6C694C 802DEB6C 0C002F2A */  jal        ohWait
    /* 6C6950 802DEB70 24040001 */   addiu     $a0, $zero, 0x1
    /* 6C6954 802DEB74 1000FFF0 */  b          .L802DEB38_6C6918
    /* 6C6958 802DEB78 02002025 */   or        $a0, $s0, $zero
    /* 6C695C 802DEB7C 8FAF0038 */  lw         $t7, 0x38($sp)
  .L802DEB80_6C6960:
    /* 6C6960 802DEB80 00002025 */  or         $a0, $zero, $zero
    /* 6C6964 802DEB84 8DF8008C */  lw         $t8, 0x8C($t7)
    /* 6C6968 802DEB88 37190002 */  ori        $t9, $t8, 0x2
    /* 6C696C 802DEB8C ADF9008C */  sw         $t9, 0x8C($t7)
    /* 6C6970 802DEB90 8FA80038 */  lw         $t0, 0x38($sp)
    /* 6C6974 802DEB94 0C0023CB */  jal        omEndProcess
    /* 6C6978 802DEB98 AD000094 */   sw        $zero, 0x94($t0)
    /* 6C697C 802DEB9C 8FBF002C */  lw         $ra, 0x2C($sp)
    /* 6C6980 802DEBA0 D7B40018 */  ldc1       $f20, 0x18($sp)
    /* 6C6984 802DEBA4 8FB00020 */  lw         $s0, 0x20($sp)
    /* 6C6988 802DEBA8 8FB10024 */  lw         $s1, 0x24($sp)
    /* 6C698C 802DEBAC 8FB20028 */  lw         $s2, 0x28($sp)
    /* 6C6990 802DEBB0 03E00008 */  jr         $ra
    /* 6C6994 802DEBB4 27BD0048 */   addiu     $sp, $sp, 0x48
endlabel func_802DEB00_6C68E0
