.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.42.2 */

nonmatching koffing_smoke_matanim_reveal

dlabel koffing_smoke_matanim_reveal
    /* 33AF40 801142C0 801142F0 */ .word D_801142F0_33AF70
    /* 33AF44 801142C4 00000000 */ .word 0x00000000
enddlabel koffing_smoke_matanim_reveal

nonmatching D_801142C8_33AF48

dlabel D_801142C8_33AF48
    /* 33AF48 801142C8 08800000 */ .word 0x08800000
    /* 33AF4C 801142CC 40800000 */ .word 0x40800000
    /* 33AF50 801142D0 160F0000 */ .word 0x160F0000
    /* 33AF54 801142D4 00000000 */ .word 0x00000000
    /* 33AF58 801142D8 00000000 */ .word 0x00000000
    /* 33AF5C 801142DC 3F800000 */ .word 0x3F800000
    /* 33AF60 801142E0 3F800000 */ .word 0x3F800000
    /* 33AF64 801142E4 06800064 */ .word 0x06800064
    /* 33AF68 801142E8 40E00000 */ .word 0x40E00000
    /* 33AF6C 801142EC 00000000 */ .word 0x00000000
enddlabel D_801142C8_33AF48

nonmatching D_801142F0_33AF70

dlabel D_801142F0_33AF70
    /* 33AF70 801142F0 801142C8 */ .word D_801142C8_33AF48
    /* 33AF74 801142F4 00000000 */ .word 0x00000000
    /* 33AF78 801142F8 00000000 */ .word 0x00000000
    /* 33AF7C 801142FC 00000000 */ .word 0x00000000
enddlabel D_801142F0_33AF70
