.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.42.1 */

nonmatching koffing_smoke_matanim_show

dlabel koffing_smoke_matanim_show
    /* 33AEC0 80114240 80114270 */ .word D_80114270_33AEF0
    /* 33AEC4 80114244 00000000 */ .word 0x00000000
enddlabel koffing_smoke_matanim_show

nonmatching D_80114248_33AEC8

dlabel D_80114248_33AEC8
    /* 33AEC8 80114248 08800000 */ .word 0x08800000
    /* 33AECC 8011424C 00000000 */ .word 0x00000000
    /* 33AED0 80114250 160F0000 */ .word 0x160F0000
    /* 33AED4 80114254 00000000 */ .word 0x00000000
    /* 33AED8 80114258 00000000 */ .word 0x00000000
    /* 33AEDC 8011425C 3F800000 */ .word 0x3F800000
    /* 33AEE0 80114260 3F800000 */ .word 0x3F800000
    /* 33AEE4 80114264 06800064 */ .word 0x06800064
    /* 33AEE8 80114268 40400000 */ .word 0x40400000
    /* 33AEEC 8011426C 00000000 */ .word 0x00000000
enddlabel D_80114248_33AEC8

nonmatching D_80114270_33AEF0

dlabel D_80114270_33AEF0
    /* 33AEF0 80114270 80114248 */ .word D_80114248_33AEC8
    /* 33AEF4 80114274 00000000 */ .word 0x00000000
    /* 33AEF8 80114278 00000000 */ .word 0x00000000
    /* 33AEFC 8011427C 00000000 */ .word 0x00000000
enddlabel D_80114270_33AEF0
