.section .late_rodata
nonmatching D_8038A318_52A728

dlabel D_8038A318_52A728
    /* 52A728 8038A318 453B8000 */ .float 3000
enddlabel D_8038A318_52A728


.section .text
/* Generated by spimdisasm 1.42.2 */

nonmatching func_8035A1B8_4FA5C8, 0xB4

glabel func_8035A1B8_4FA5C8
    /* 4FA5C8 8035A1B8 27BDFFB8 */  addiu      $sp, $sp, -0x48
    /* 4FA5CC 8035A1BC AFBF0014 */  sw         $ra, 0x14($sp)
    /* 4FA5D0 8035A1C0 AFA5004C */  sw         $a1, 0x4C($sp)
    /* 4FA5D4 8035A1C4 C484001C */  lwc1       $f4, 0x1C($a0)
    /* 4FA5D8 8035A1C8 3C028038 */  lui        $v0, %hi(gPlayerDObj)
    /* 4FA5DC 8035A1CC 8C422C04 */  lw         $v0, %lo(gPlayerDObj)($v0)
    /* 4FA5E0 8035A1D0 E7A4002C */  swc1       $f4, 0x2C($sp)
    /* 4FA5E4 8035A1D4 C4860020 */  lwc1       $f6, 0x20($a0)
    /* 4FA5E8 8035A1D8 27A50038 */  addiu      $a1, $sp, 0x38
    /* 4FA5EC 8035A1DC 27A6002C */  addiu      $a2, $sp, 0x2C
    /* 4FA5F0 8035A1E0 E7A60030 */  swc1       $f6, 0x30($sp)
    /* 4FA5F4 8035A1E4 C4880024 */  lwc1       $f8, 0x24($a0)
    /* 4FA5F8 8035A1E8 27A40020 */  addiu      $a0, $sp, 0x20
    /* 4FA5FC 8035A1EC E7A80034 */  swc1       $f8, 0x34($sp)
    /* 4FA600 8035A1F0 8C4E004C */  lw         $t6, 0x4C($v0)
    /* 4FA604 8035A1F4 C5CA0008 */  lwc1       $f10, 0x8($t6)
    /* 4FA608 8035A1F8 E7AA0038 */  swc1       $f10, 0x38($sp)
    /* 4FA60C 8035A1FC 8C4F004C */  lw         $t7, 0x4C($v0)
    /* 4FA610 8035A200 C5F0000C */  lwc1       $f16, 0xC($t7)
    /* 4FA614 8035A204 E7B0003C */  swc1       $f16, 0x3C($sp)
    /* 4FA618 8035A208 8C58004C */  lw         $t8, 0x4C($v0)
    /* 4FA61C 8035A20C C7120010 */  lwc1       $f18, 0x10($t8)
    /* 4FA620 8035A210 0C006939 */  jal        Vec3fDirection
    /* 4FA624 8035A214 E7B20040 */   swc1      $f18, 0x40($sp)
    /* 4FA628 8035A218 3C018039 */  lui        $at, %hi(D_8038A318_52A728)
    /* 4FA62C 8035A21C C42CA318 */  lwc1       $f12, %lo(D_8038A318_52A728)($at)
    /* 4FA630 8035A220 46000086 */  mov.s      $f2, $f0
    /* 4FA634 8035A224 460C003C */  c.lt.s     $f0, $f12
    /* 4FA638 8035A228 00000000 */  nop
    /* 4FA63C 8035A22C 4502000C */  bc1fl      .L8035A260_4FA670
    /* 4FA640 8035A230 8FBF0014 */   lw        $ra, 0x14($sp)
    /* 4FA644 8035A234 460C1103 */  div.s      $f4, $f2, $f12
    /* 4FA648 8035A238 3C0146F0 */  lui        $at, (0x46F00000 >> 16)
    /* 4FA64C 8035A23C 44810000 */  mtc1       $at, $f0
    /* 4FA650 8035A240 8FA4004C */  lw         $a0, 0x4C($sp)
    /* 4FA654 8035A244 46002182 */  mul.s      $f6, $f4, $f0
    /* 4FA658 8035A248 46060201 */  sub.s      $f8, $f0, $f6
    /* 4FA65C 8035A24C 4600428D */  trunc.w.s  $f10, $f8
    /* 4FA660 8035A250 44055000 */  mfc1       $a1, $f10
    /* 4FA664 8035A254 0C008CBF */  jal        auPlaySoundWithVolume
    /* 4FA668 8035A258 00000000 */   nop
    /* 4FA66C 8035A25C 8FBF0014 */  lw         $ra, 0x14($sp)
  .L8035A260_4FA670:
    /* 4FA670 8035A260 27BD0048 */  addiu      $sp, $sp, 0x48
    /* 4FA674 8035A264 03E00008 */  jr         $ra
    /* 4FA678 8035A268 00000000 */   nop
endlabel func_8035A1B8_4FA5C8
