.section .late_rodata
nonmatching D_8038A370_52A780

dlabel D_8038A370_52A780
    /* 52A780 8038A370 3E4CCCCD */ .float 0.200000003
enddlabel D_8038A370_52A780

nonmatching D_8038A374_52A784

dlabel D_8038A374_52A784
    /* 52A784 8038A374 3E4CCCCD */ .float 0.200000003
enddlabel D_8038A374_52A784

nonmatching D_8038A378_52A788

dlabel D_8038A378_52A788
    /* 52A788 8038A378 3E99999A */ .float 0.3000000119
enddlabel D_8038A378_52A788

nonmatching D_8038A37C_52A78C

dlabel D_8038A37C_52A78C
    /* 52A78C 8038A37C 3E99999A */ .float 0.3000000119
enddlabel D_8038A37C_52A78C

nonmatching D_8038A380_52A790

dlabel D_8038A380_52A790
    /* 52A790 8038A380 3E4CCCCD */ .float 0.200000003
enddlabel D_8038A380_52A790


.section .text
/* Generated by spimdisasm 1.42.2 */

nonmatching func_8035B528_4FB938, 0x410

glabel func_8035B528_4FB938
    /* 4FB938 8035B528 27BDFFC8 */  addiu      $sp, $sp, -0x38
    /* 4FB93C 8035B52C AFBF0014 */  sw         $ra, 0x14($sp)
    /* 4FB940 8035B530 AFA5003C */  sw         $a1, 0x3C($sp)
    /* 4FB944 8035B534 8C8E0048 */  lw         $t6, 0x48($a0)
    /* 4FB948 8035B538 00803025 */  or         $a2, $a0, $zero
    /* 4FB94C 8035B53C AFAE0034 */  sw         $t6, 0x34($sp)
    /* 4FB950 8035B540 8C830058 */  lw         $v1, 0x58($a0)
    /* 4FB954 8035B544 27A40024 */  addiu      $a0, $sp, 0x24
    /* 4FB958 8035B548 C4640008 */  lwc1       $f4, 0x8($v1)
    /* 4FB95C 8035B54C E7A40024 */  swc1       $f4, 0x24($sp)
    /* 4FB960 8035B550 C466000C */  lwc1       $f6, 0xC($v1)
    /* 4FB964 8035B554 E7A60028 */  swc1       $f6, 0x28($sp)
    /* 4FB968 8035B558 C4680010 */  lwc1       $f8, 0x10($v1)
    /* 4FB96C 8035B55C AFA60038 */  sw         $a2, 0x38($sp)
    /* 4FB970 8035B560 AFA30030 */  sw         $v1, 0x30($sp)
    /* 4FB974 8035B564 0C0068D8 */  jal        Vec3fNormalize
    /* 4FB978 8035B568 E7A8002C */   swc1      $f8, 0x2C($sp)
    /* 4FB97C 8035B56C 8FA30030 */  lw         $v1, 0x30($sp)
    /* 4FB980 8035B570 8FA6003C */  lw         $a2, 0x3C($sp)
    /* 4FB984 8035B574 C46C0020 */  lwc1       $f12, 0x20($v1)
    /* 4FB988 8035B578 C46E0028 */  lwc1       $f14, 0x28($v1)
    /* 4FB98C 8035B57C 0C0390D7 */  jal        func_800E435C_61B0C
    /* 4FB990 8035B580 E7A00020 */   swc1      $f0, 0x20($sp)
    /* 4FB994 8035B584 8FA30030 */  lw         $v1, 0x30($sp)
    /* 4FB998 8035B588 240100A2 */  addiu      $at, $zero, 0xA2
    /* 4FB99C 8035B58C C7A20020 */  lwc1       $f2, 0x20($sp)
    /* 4FB9A0 8035B590 906F0000 */  lbu        $t7, 0x0($v1)
    /* 4FB9A4 8035B594 8FA40034 */  lw         $a0, 0x34($sp)
    /* 4FB9A8 8035B598 2405000A */  addiu      $a1, $zero, 0xA
    /* 4FB9AC 8035B59C 15E10034 */  bne        $t7, $at, .L8035B670_4FBA80
    /* 4FB9B0 8035B5A0 8FAB003C */   lw        $t3, 0x3C($sp)
    /* 4FB9B4 8035B5A4 0C0D686E */  jal        func_8035A1B8_4FA5C8
    /* 4FB9B8 8035B5A8 AFA30030 */   sw        $v1, 0x30($sp)
    /* 4FB9BC 8035B5AC 8FB8003C */  lw         $t8, 0x3C($sp)
    /* 4FB9C0 8035B5B0 3C01004C */  lui        $at, (0x4C1900 >> 16)
    /* 4FB9C4 8035B5B4 44801000 */  mtc1       $zero, $f2
    /* 4FB9C8 8035B5B8 8F020010 */  lw         $v0, 0x10($t8)
    /* 4FB9CC 8035B5BC 34211900 */  ori        $at, $at, (0x4C1900 & 0xFFFF)
    /* 4FB9D0 8035B5C0 8FA30030 */  lw         $v1, 0x30($sp)
    /* 4FB9D4 8035B5C4 1041000D */  beq        $v0, $at, .L8035B5FC_4FBA0C
    /* 4FB9D8 8035B5C8 3C01004C */   lui       $at, (0x4C4C33 >> 16)
    /* 4FB9DC 8035B5CC 34214C33 */  ori        $at, $at, (0x4C4C33 & 0xFFFF)
    /* 4FB9E0 8035B5D0 1041000A */  beq        $v0, $at, .L8035B5FC_4FBA0C
    /* 4FB9E4 8035B5D4 3C01007F */   lui       $at, (0x7F4C00 >> 16)
    /* 4FB9E8 8035B5D8 34214C00 */  ori        $at, $at, (0x7F4C00 & 0xFFFF)
    /* 4FB9EC 8035B5DC 10410007 */  beq        $v0, $at, .L8035B5FC_4FBA0C
    /* 4FB9F0 8035B5E0 3C01007F */   lui       $at, (0x7F7F7F >> 16)
    /* 4FB9F4 8035B5E4 34217F7F */  ori        $at, $at, (0x7F7F7F & 0xFFFF)
    /* 4FB9F8 8035B5E8 10410004 */  beq        $v0, $at, .L8035B5FC_4FBA0C
    /* 4FB9FC 8035B5EC 3C0100B2 */   lui       $at, (0xB2997F >> 16)
    /* 4FBA00 8035B5F0 3421997F */  ori        $at, $at, (0xB2997F & 0xFFFF)
    /* 4FBA04 8035B5F4 54410008 */  bnel       $v0, $at, .L8035B618_4FBA28
    /* 4FBA08 8035B5F8 8FA40038 */   lw        $a0, 0x38($sp)
  .L8035B5FC_4FBA0C:
    /* 4FBA0C 8035B5FC 90790000 */  lbu        $t9, 0x0($v1)
    /* 4FBA10 8035B600 240100A2 */  addiu      $at, $zero, 0xA2
    /* 4FBA14 8035B604 24080002 */  addiu      $t0, $zero, 0x2
    /* 4FBA18 8035B608 57210003 */  bnel       $t9, $at, .L8035B618_4FBA28
    /* 4FBA1C 8035B60C 8FA40038 */   lw        $a0, 0x38($sp)
    /* 4FBA20 8035B610 A0680001 */  sb         $t0, 0x1($v1)
    /* 4FBA24 8035B614 8FA40038 */  lw         $a0, 0x38($sp)
  .L8035B618_4FBA28:
    /* 4FBA28 8035B618 3C058036 */  lui        $a1, %hi(func_80359CD4_4FA0E4)
    /* 4FBA2C 8035B61C 24A59CD4 */  addiu      $a1, $a1, %lo(func_80359CD4_4FA0E4)
    /* 4FBA30 8035B620 8C890050 */  lw         $t1, 0x50($a0)
    /* 4FBA34 8035B624 352A0001 */  ori        $t2, $t1, 0x1
    /* 4FBA38 8035B628 AC8A0050 */  sw         $t2, 0x50($a0)
    /* 4FBA3C 8035B62C E7A20020 */  swc1       $f2, 0x20($sp)
    /* 4FBA40 8035B630 0C0D65DC */  jal        func_80359770_4F9B80
    /* 4FBA44 8035B634 AFA30030 */   sw        $v1, 0x30($sp)
    /* 4FBA48 8035B638 3C058036 */  lui        $a1, %hi(func_8035C2D4_4FC6E4)
    /* 4FBA4C 8035B63C 24A5C2D4 */  addiu      $a1, $a1, %lo(func_8035C2D4_4FC6E4)
    /* 4FBA50 8035B640 8FA40038 */  lw         $a0, 0x38($sp)
    /* 4FBA54 8035B644 24060001 */  addiu      $a2, $zero, 0x1
    /* 4FBA58 8035B648 0C00230A */  jal        omCreateProcess
    /* 4FBA5C 8035B64C 24070007 */   addiu     $a3, $zero, 0x7
    /* 4FBA60 8035B650 8FA40038 */  lw         $a0, 0x38($sp)
    /* 4FBA64 8035B654 0C003198 */  jal        animSetTextureAnimationSpeed
    /* 4FBA68 8035B658 24050000 */   addiu     $a1, $zero, 0x0
    /* 4FBA6C 8035B65C 0C0023CB */  jal        omEndProcess
    /* 4FBA70 8035B660 00002025 */   or        $a0, $zero, $zero
    /* 4FBA74 8035B664 8FA30030 */  lw         $v1, 0x30($sp)
    /* 4FBA78 8035B668 1000008F */  b          .L8035B8A8_4FBCB8
    /* 4FBA7C 8035B66C C7A20020 */   lwc1      $f2, 0x20($sp)
  .L8035B670_4FBA80:
    /* 4FBA80 8035B670 8D620010 */  lw         $v0, 0x10($t3)
    /* 4FBA84 8035B674 3C01007F */  lui        $at, (0x7F6634 >> 16)
    /* 4FBA88 8035B678 34216634 */  ori        $at, $at, (0x7F6634 & 0xFFFF)
    /* 4FBA8C 8035B67C 0041082B */  sltu       $at, $v0, $at
    /* 4FBA90 8035B680 14200015 */  bnez       $at, .L8035B6D8_4FBAE8
    /* 4FBA94 8035B684 3C01007F */   lui       $at, (0x7F667F >> 16)
    /* 4FBA98 8035B688 3421667F */  ori        $at, $at, (0x7F667F & 0xFFFF)
    /* 4FBA9C 8035B68C 1041004E */  beq        $v0, $at, .L8035B7C8_4FBBD8
    /* 4FBAA0 8035B690 3C01007F */   lui       $at, (0x7F7F7F >> 16)
    /* 4FBAA4 8035B694 34217F7F */  ori        $at, $at, (0x7F7F7F & 0xFFFF)
    /* 4FBAA8 8035B698 1041004B */  beq        $v0, $at, .L8035B7C8_4FBBD8
    /* 4FBAAC 8035B69C 3C010099 */   lui       $at, (0x996666 >> 16)
    /* 4FBAB0 8035B6A0 34216666 */  ori        $at, $at, (0x996666 & 0xFFFF)
    /* 4FBAB4 8035B6A4 10410024 */  beq        $v0, $at, .L8035B738_4FBB48
    /* 4FBAB8 8035B6A8 3C0100B2 */   lui       $at, (0xB2997F >> 16)
    /* 4FBABC 8035B6AC 3421997F */  ori        $at, $at, (0xB2997F & 0xFFFF)
    /* 4FBAC0 8035B6B0 10410069 */  beq        $v0, $at, .L8035B858_4FBC68
    /* 4FBAC4 8035B6B4 3C0100FF */   lui       $at, (0xFF7FB2 >> 16)
    /* 4FBAC8 8035B6B8 34217FB2 */  ori        $at, $at, (0xFF7FB2 & 0xFFFF)
    /* 4FBACC 8035B6BC 10410042 */  beq        $v0, $at, .L8035B7C8_4FBBD8
    /* 4FBAD0 8035B6C0 3C0100FF */   lui       $at, (0xFF9919 >> 16)
    /* 4FBAD4 8035B6C4 34219919 */  ori        $at, $at, (0xFF9919 & 0xFFFF)
    /* 4FBAD8 8035B6C8 5041001C */  beql       $v0, $at, .L8035B73C_4FBB4C
    /* 4FBADC 8035B6CC 3C014150 */   lui       $at, (0x41500000 >> 16)
    /* 4FBAE0 8035B6D0 10000074 */  b          .L8035B8A4_4FBCB4
    /* 4FBAE4 8035B6D4 44801000 */   mtc1      $zero, $f2
  .L8035B6D8_4FBAE8:
    /* 4FBAE8 8035B6D8 3C010019 */  lui        $at, (0x193333 >> 16)
    /* 4FBAEC 8035B6DC 34213333 */  ori        $at, $at, (0x193333 & 0xFFFF)
    /* 4FBAF0 8035B6E0 10410015 */  beq        $v0, $at, .L8035B738_4FBB48
    /* 4FBAF4 8035B6E4 3C010033 */   lui       $at, (0x331919 >> 16)
    /* 4FBAF8 8035B6E8 34211919 */  ori        $at, $at, (0x331919 & 0xFFFF)
    /* 4FBAFC 8035B6EC 10410024 */  beq        $v0, $at, .L8035B780_4FBB90
    /* 4FBB00 8035B6F0 3C01004C */   lui       $at, (0x4C1900 >> 16)
    /* 4FBB04 8035B6F4 34211900 */  ori        $at, $at, (0x4C1900 & 0xFFFF)
    /* 4FBB08 8035B6F8 10410033 */  beq        $v0, $at, .L8035B7C8_4FBBD8
    /* 4FBB0C 8035B6FC 3C01004C */   lui       $at, (0x4C4C33 >> 16)
    /* 4FBB10 8035B700 34214C33 */  ori        $at, $at, (0x4C4C33 & 0xFFFF)
    /* 4FBB14 8035B704 10410030 */  beq        $v0, $at, .L8035B7C8_4FBBD8
    /* 4FBB18 8035B708 3C01004C */   lui       $at, (0x4C7F00 >> 16)
    /* 4FBB1C 8035B70C 34217F00 */  ori        $at, $at, (0x4C7F00 & 0xFFFF)
    /* 4FBB20 8035B710 10410009 */  beq        $v0, $at, .L8035B738_4FBB48
    /* 4FBB24 8035B714 3C01007F */   lui       $at, (0x7F4C00 >> 16)
    /* 4FBB28 8035B718 34214C00 */  ori        $at, $at, (0x7F4C00 & 0xFFFF)
    /* 4FBB2C 8035B71C 1041002A */  beq        $v0, $at, .L8035B7C8_4FBBD8
    /* 4FBB30 8035B720 3C01007F */   lui       $at, (0x7F6633 >> 16)
    /* 4FBB34 8035B724 34216633 */  ori        $at, $at, (0x7F6633 & 0xFFFF)
    /* 4FBB38 8035B728 5041003A */  beql       $v0, $at, .L8035B814_4FBC24
    /* 4FBB3C 8035B72C 3C014150 */   lui       $at, (0x41500000 >> 16)
    /* 4FBB40 8035B730 1000005C */  b          .L8035B8A4_4FBCB4
    /* 4FBB44 8035B734 44801000 */   mtc1      $zero, $f2
  .L8035B738_4FBB48:
    /* 4FBB48 8035B738 3C014150 */  lui        $at, (0x41500000 >> 16)
  .L8035B73C_4FBB4C:
    /* 4FBB4C 8035B73C 44815000 */  mtc1       $at, $f10
    /* 4FBB50 8035B740 8FA40034 */  lw         $a0, 0x34($sp)
    /* 4FBB54 8035B744 24050018 */  addiu      $a1, $zero, 0x18
    /* 4FBB58 8035B748 4602503C */  c.lt.s     $f10, $f2
    /* 4FBB5C 8035B74C 00000000 */  nop
    /* 4FBB60 8035B750 45000006 */  bc1f       .L8035B76C_4FBB7C
    /* 4FBB64 8035B754 00000000 */   nop
    /* 4FBB68 8035B758 AFA30030 */  sw         $v1, 0x30($sp)
    /* 4FBB6C 8035B75C 0C0D686E */  jal        func_8035A1B8_4FA5C8
    /* 4FBB70 8035B760 E7A20020 */   swc1      $f2, 0x20($sp)
    /* 4FBB74 8035B764 8FA30030 */  lw         $v1, 0x30($sp)
    /* 4FBB78 8035B768 C7A20020 */  lwc1       $f2, 0x20($sp)
  .L8035B76C_4FBB7C:
    /* 4FBB7C 8035B76C 3C018039 */  lui        $at, %hi(D_8038A370_52A780)
    /* 4FBB80 8035B770 C430A370 */  lwc1       $f16, %lo(D_8038A370_52A780)($at)
    /* 4FBB84 8035B774 46101082 */  mul.s      $f2, $f2, $f16
    /* 4FBB88 8035B778 1000004C */  b          .L8035B8AC_4FBCBC
    /* 4FBB8C 8035B77C 8FA5003C */   lw        $a1, 0x3C($sp)
  .L8035B780_4FBB90:
    /* 4FBB90 8035B780 3C014150 */  lui        $at, (0x41500000 >> 16)
    /* 4FBB94 8035B784 44819000 */  mtc1       $at, $f18
    /* 4FBB98 8035B788 8FA40034 */  lw         $a0, 0x34($sp)
    /* 4FBB9C 8035B78C 24050019 */  addiu      $a1, $zero, 0x19
    /* 4FBBA0 8035B790 4602903C */  c.lt.s     $f18, $f2
    /* 4FBBA4 8035B794 00000000 */  nop
    /* 4FBBA8 8035B798 45000006 */  bc1f       .L8035B7B4_4FBBC4
    /* 4FBBAC 8035B79C 00000000 */   nop
    /* 4FBBB0 8035B7A0 AFA30030 */  sw         $v1, 0x30($sp)
    /* 4FBBB4 8035B7A4 0C0D686E */  jal        func_8035A1B8_4FA5C8
    /* 4FBBB8 8035B7A8 E7A20020 */   swc1      $f2, 0x20($sp)
    /* 4FBBBC 8035B7AC 8FA30030 */  lw         $v1, 0x30($sp)
    /* 4FBBC0 8035B7B0 C7A20020 */  lwc1       $f2, 0x20($sp)
  .L8035B7B4_4FBBC4:
    /* 4FBBC4 8035B7B4 3C018039 */  lui        $at, %hi(D_8038A374_52A784)
    /* 4FBBC8 8035B7B8 C424A374 */  lwc1       $f4, %lo(D_8038A374_52A784)($at)
    /* 4FBBCC 8035B7BC 46041082 */  mul.s      $f2, $f2, $f4
    /* 4FBBD0 8035B7C0 1000003A */  b          .L8035B8AC_4FBCBC
    /* 4FBBD4 8035B7C4 8FA5003C */   lw        $a1, 0x3C($sp)
  .L8035B7C8_4FBBD8:
    /* 4FBBD8 8035B7C8 3C014150 */  lui        $at, (0x41500000 >> 16)
    /* 4FBBDC 8035B7CC 44813000 */  mtc1       $at, $f6
    /* 4FBBE0 8035B7D0 8FA40034 */  lw         $a0, 0x34($sp)
    /* 4FBBE4 8035B7D4 24050019 */  addiu      $a1, $zero, 0x19
    /* 4FBBE8 8035B7D8 4602303C */  c.lt.s     $f6, $f2
    /* 4FBBEC 8035B7DC 00000000 */  nop
    /* 4FBBF0 8035B7E0 45000006 */  bc1f       .L8035B7FC_4FBC0C
    /* 4FBBF4 8035B7E4 00000000 */   nop
    /* 4FBBF8 8035B7E8 AFA30030 */  sw         $v1, 0x30($sp)
    /* 4FBBFC 8035B7EC 0C0D686E */  jal        func_8035A1B8_4FA5C8
    /* 4FBC00 8035B7F0 E7A20020 */   swc1      $f2, 0x20($sp)
    /* 4FBC04 8035B7F4 8FA30030 */  lw         $v1, 0x30($sp)
    /* 4FBC08 8035B7F8 C7A20020 */  lwc1       $f2, 0x20($sp)
  .L8035B7FC_4FBC0C:
    /* 4FBC0C 8035B7FC 3C018039 */  lui        $at, %hi(D_8038A378_52A788)
    /* 4FBC10 8035B800 C428A378 */  lwc1       $f8, %lo(D_8038A378_52A788)($at)
    /* 4FBC14 8035B804 46081082 */  mul.s      $f2, $f2, $f8
    /* 4FBC18 8035B808 10000028 */  b          .L8035B8AC_4FBCBC
    /* 4FBC1C 8035B80C 8FA5003C */   lw        $a1, 0x3C($sp)
    /* 4FBC20 8035B810 3C014150 */  lui        $at, (0x41500000 >> 16)
  .L8035B814_4FBC24:
    /* 4FBC24 8035B814 44815000 */  mtc1       $at, $f10
    /* 4FBC28 8035B818 8FA40034 */  lw         $a0, 0x34($sp)
    /* 4FBC2C 8035B81C 24050019 */  addiu      $a1, $zero, 0x19
    /* 4FBC30 8035B820 4602503C */  c.lt.s     $f10, $f2
    /* 4FBC34 8035B824 00000000 */  nop
    /* 4FBC38 8035B828 45000006 */  bc1f       .L8035B844_4FBC54
    /* 4FBC3C 8035B82C 00000000 */   nop
    /* 4FBC40 8035B830 AFA30030 */  sw         $v1, 0x30($sp)
    /* 4FBC44 8035B834 0C0D686E */  jal        func_8035A1B8_4FA5C8
    /* 4FBC48 8035B838 E7A20020 */   swc1      $f2, 0x20($sp)
    /* 4FBC4C 8035B83C 8FA30030 */  lw         $v1, 0x30($sp)
    /* 4FBC50 8035B840 C7A20020 */  lwc1       $f2, 0x20($sp)
  .L8035B844_4FBC54:
    /* 4FBC54 8035B844 3C018039 */  lui        $at, %hi(D_8038A37C_52A78C)
    /* 4FBC58 8035B848 C430A37C */  lwc1       $f16, %lo(D_8038A37C_52A78C)($at)
    /* 4FBC5C 8035B84C 46101082 */  mul.s      $f2, $f2, $f16
    /* 4FBC60 8035B850 10000016 */  b          .L8035B8AC_4FBCBC
    /* 4FBC64 8035B854 8FA5003C */   lw        $a1, 0x3C($sp)
  .L8035B858_4FBC68:
    /* 4FBC68 8035B858 3C014150 */  lui        $at, (0x41500000 >> 16)
    /* 4FBC6C 8035B85C 44819000 */  mtc1       $at, $f18
    /* 4FBC70 8035B860 8FA40034 */  lw         $a0, 0x34($sp)
    /* 4FBC74 8035B864 2405001B */  addiu      $a1, $zero, 0x1B
    /* 4FBC78 8035B868 4602903C */  c.lt.s     $f18, $f2
    /* 4FBC7C 8035B86C 00000000 */  nop
    /* 4FBC80 8035B870 45000006 */  bc1f       .L8035B88C_4FBC9C
    /* 4FBC84 8035B874 00000000 */   nop
    /* 4FBC88 8035B878 AFA30030 */  sw         $v1, 0x30($sp)
    /* 4FBC8C 8035B87C 0C0D686E */  jal        func_8035A1B8_4FA5C8
    /* 4FBC90 8035B880 E7A20020 */   swc1      $f2, 0x20($sp)
    /* 4FBC94 8035B884 8FA30030 */  lw         $v1, 0x30($sp)
    /* 4FBC98 8035B888 C7A20020 */  lwc1       $f2, 0x20($sp)
  .L8035B88C_4FBC9C:
    /* 4FBC9C 8035B88C 3C018039 */  lui        $at, %hi(D_8038A380_52A790)
    /* 4FBCA0 8035B890 C424A380 */  lwc1       $f4, %lo(D_8038A380_52A790)($at)
    /* 4FBCA4 8035B894 46041082 */  mul.s      $f2, $f2, $f4
    /* 4FBCA8 8035B898 10000004 */  b          .L8035B8AC_4FBCBC
    /* 4FBCAC 8035B89C 8FA5003C */   lw        $a1, 0x3C($sp)
    /* 4FBCB0 8035B8A0 44801000 */  mtc1       $zero, $f2
  .L8035B8A4_4FBCB4:
    /* 4FBCB4 8035B8A4 00000000 */  nop
  .L8035B8A8_4FBCB8:
    /* 4FBCB8 8035B8A8 8FA5003C */  lw         $a1, 0x3C($sp)
  .L8035B8AC_4FBCBC:
    /* 4FBCBC 8035B8AC 27A40024 */  addiu      $a0, $sp, 0x24
    /* 4FBCC0 8035B8B0 AFA30030 */  sw         $v1, 0x30($sp)
    /* 4FBCC4 8035B8B4 E7A20020 */  swc1       $f2, 0x20($sp)
    /* 4FBCC8 8035B8B8 0C006B26 */  jal        Vec3fReflect
    /* 4FBCCC 8035B8BC 24A50004 */   addiu     $a1, $a1, 0x4
    /* 4FBCD0 8035B8C0 C7A20020 */  lwc1       $f2, 0x20($sp)
    /* 4FBCD4 8035B8C4 C7A60024 */  lwc1       $f6, 0x24($sp)
    /* 4FBCD8 8035B8C8 8FA30030 */  lw         $v1, 0x30($sp)
    /* 4FBCDC 8035B8CC 8FA20034 */  lw         $v0, 0x34($sp)
    /* 4FBCE0 8035B8D0 46023202 */  mul.s      $f8, $f6, $f2
    /* 4FBCE4 8035B8D4 C4660020 */  lwc1       $f6, 0x20($v1)
    /* 4FBCE8 8035B8D8 E4680008 */  swc1       $f8, 0x8($v1)
    /* 4FBCEC 8035B8DC C7AA0028 */  lwc1       $f10, 0x28($sp)
    /* 4FBCF0 8035B8E0 C4680008 */  lwc1       $f8, 0x8($v1)
    /* 4FBCF4 8035B8E4 46025402 */  mul.s      $f16, $f10, $f2
    /* 4FBCF8 8035B8E8 46083280 */  add.s      $f10, $f6, $f8
    /* 4FBCFC 8035B8EC E470000C */  swc1       $f16, 0xC($v1)
    /* 4FBD00 8035B8F0 C7B2002C */  lwc1       $f18, 0x2C($sp)
    /* 4FBD04 8035B8F4 46029102 */  mul.s      $f4, $f18, $f2
    /* 4FBD08 8035B8F8 E4640010 */  swc1       $f4, 0x10($v1)
    /* 4FBD0C 8035B8FC E44A001C */  swc1       $f10, 0x1C($v0)
    /* 4FBD10 8035B900 C472000C */  lwc1       $f18, 0xC($v1)
    /* 4FBD14 8035B904 C4700024 */  lwc1       $f16, 0x24($v1)
    /* 4FBD18 8035B908 46128100 */  add.s      $f4, $f16, $f18
    /* 4FBD1C 8035B90C E4440020 */  swc1       $f4, 0x20($v0)
    /* 4FBD20 8035B910 C4680010 */  lwc1       $f8, 0x10($v1)
    /* 4FBD24 8035B914 C4660028 */  lwc1       $f6, 0x28($v1)
    /* 4FBD28 8035B918 46083280 */  add.s      $f10, $f6, $f8
    /* 4FBD2C 8035B91C E44A0024 */  swc1       $f10, 0x24($v0)
    /* 4FBD30 8035B920 0C0D6C22 */  jal        Items_NotifyItemPosition
    /* 4FBD34 8035B924 8FA40038 */   lw        $a0, 0x38($sp)
    /* 4FBD38 8035B928 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 4FBD3C 8035B92C 27BD0038 */  addiu      $sp, $sp, 0x38
    /* 4FBD40 8035B930 03E00008 */  jr         $ra
    /* 4FBD44 8035B934 00000000 */   nop
endlabel func_8035B528_4FB938
