.section .late_rodata
nonmatching D_802C80F0_64A5A0

dlabel D_802C80F0_64A5A0
    /* 64A5A0 802C80F0 40490FDB */ .float 3.141592741
    /* 64A5A4 802C80F4 00000000 */ .float 0
    /* 64A5A8 802C80F8 00000000 */ .float 0
    /* 64A5AC 802C80FC 00000000 */ .float 0
enddlabel D_802C80F0_64A5A0


.section .text
/* Generated by spimdisasm 1.42.1 */

nonmatching func_802C3290_645740, 0xB8

glabel func_802C3290_645740
    /* 645740 802C3290 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* 645744 802C3294 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 645748 802C3298 AFB00018 */  sw         $s0, 0x18($sp)
    /* 64574C 802C329C 8C820048 */  lw         $v0, 0x48($a0)
    /* 645750 802C32A0 3C05802C */  lui        $a1, %hi(D_802C779C_649C4C)
    /* 645754 802C32A4 00808025 */  or         $s0, $a0, $zero
    /* 645758 802C32A8 8C4E004C */  lw         $t6, 0x4C($v0)
    /* 64575C 802C32AC 24A5779C */  addiu      $a1, $a1, %lo(D_802C779C_649C4C)
    /* 645760 802C32B0 25CF0014 */  addiu      $t7, $t6, 0x14
    /* 645764 802C32B4 AFAF0024 */  sw         $t7, 0x24($sp)
    /* 645768 802C32B8 8C980058 */  lw         $t8, 0x58($a0)
    /* 64576C 802C32BC 0C0D7C4E */  jal        Pokemon_SetAnimation
    /* 645770 802C32C0 AFB80020 */   sw        $t8, 0x20($sp)
    /* 645774 802C32C4 0C006785 */  jal        randRange
    /* 645778 802C32C8 24040168 */   addiu     $a0, $zero, 0x168
    /* 64577C 802C32CC 44822000 */  mtc1       $v0, $f4
    /* 645780 802C32D0 3C01802D */  lui        $at, %hi(D_802C80F0_64A5A0)
    /* 645784 802C32D4 C42880F0 */  lwc1       $f8, %lo(D_802C80F0_64A5A0)($at)
    /* 645788 802C32D8 468021A0 */  cvt.s.w    $f6, $f4
    /* 64578C 802C32DC 3C014334 */  lui        $at, (0x43340000 >> 16)
    /* 645790 802C32E0 44818000 */  mtc1       $at, $f16
    /* 645794 802C32E4 8FB90024 */  lw         $t9, 0x24($sp)
    /* 645798 802C32E8 3C05802C */  lui        $a1, %hi(func_802C3348_6457F8)
    /* 64579C 802C32EC 24A53348 */  addiu      $a1, $a1, %lo(func_802C3348_6457F8)
    /* 6457A0 802C32F0 46083282 */  mul.s      $f10, $f6, $f8
    /* 6457A4 802C32F4 02002025 */  or         $a0, $s0, $zero
    /* 6457A8 802C32F8 46105483 */  div.s      $f18, $f10, $f16
    /* 6457AC 802C32FC 0C0D7B7E */  jal        Pokemon_StartPathProc
    /* 6457B0 802C3300 E732000C */   swc1      $f18, 0xC($t9)
    /* 6457B4 802C3304 8FA80020 */  lw         $t0, 0x20($sp)
    /* 6457B8 802C3308 02002025 */  or         $a0, $s0, $zero
    /* 6457BC 802C330C 24050001 */  addiu      $a1, $zero, 0x1
    /* 6457C0 802C3310 0C0D7EFC */  jal        Pokemon_WaitForFlag
    /* 6457C4 802C3314 AD0000AC */   sw        $zero, 0xAC($t0)
    /* 6457C8 802C3318 3C01802C */  lui        $at, %hi(D_802C6354_648804)
    /* 6457CC 802C331C A4206354 */  sh         $zero, %lo(D_802C6354_648804)($at)
    /* 6457D0 802C3320 0C0D7F5C */  jal        Pokemon_RunCleanup
    /* 6457D4 802C3324 02002025 */   or        $a0, $s0, $zero
    /* 6457D8 802C3328 02002025 */  or         $a0, $s0, $zero
    /* 6457DC 802C332C 0C0D7B16 */  jal        Pokemon_SetState
    /* 6457E0 802C3330 00002825 */   or        $a1, $zero, $zero
    /* 6457E4 802C3334 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 6457E8 802C3338 8FB00018 */  lw         $s0, 0x18($sp)
    /* 6457EC 802C333C 27BD0030 */  addiu      $sp, $sp, 0x30
    /* 6457F0 802C3340 03E00008 */  jr         $ra
    /* 6457F4 802C3344 00000000 */   nop
endlabel func_802C3290_645740
