#include "common.h"

Gfx kangaskhan_part14_draw_far[] = {
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPSetAlphaCompare(G_AC_THRESHOLD),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_TEX_EDGE2),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsDPSetTile(G_IM_FMT_CI, G_IM_SIZ_16b, 0, 0x0000, G_TX_LOADTILE, 0, G_TX_NOMIRROR | G_TX_WRAP, 6, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_WRAP, 5, G_TX_NOLOD),
    gsDPSetTile(G_IM_FMT_CI, G_IM_SIZ_4b, 2, 0x0000, G_TX_RENDERTILE, 0, G_TX_NOMIRROR | G_TX_CLAMP, 6, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_CLAMP, 5, G_TX_NOLOD),
    gsDPSetTextureImage(G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, kangaskhan_tex_8016C0B8),
    gsDPLoadSync(),
    gsDPLoadTLUTCmd(5, 14),
    gsDPPipeSync(),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetTileSize(G_TX_RENDERTILE, 0, 0, 0x005C, 0x00BC),
    gsDPSetTextureImage(G_IM_FMT_CI, G_IM_SIZ_16b, 1, kangaskhan_tex_8016C0E0_png),
    gsDPLoadSync(),
    gsDPLoadBlock(G_TX_LOADTILE, 0, 0, 383, 1024),
    gsDPPipeSync(),
    gsSPClearGeometryMode(G_CULL_BACK),
    gsSPVertex(&kangaskhan_vtx[621], 3, 4),
    gsSP1Triangle(6, 5, 4, 0),
    gsDPPipeSync(),
    gsDPSetAlphaCompare(G_AC_NONE),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_OPA_SURF2),
    gsSPSetGeometryMode(G_CULL_BACK),
    gsDPSetTextureImage(G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, kangaskhan_tex_8016BBD8),
    gsDPLoadSync(),
    gsDPLoadTLUTCmd(5, 15),
    gsDPPipeSync(),
    gsDPSetTextureImage(G_IM_FMT_CI, G_IM_SIZ_16b, 1, kangaskhan_tex_8016BC00_png),
    gsDPLoadSync(),
    gsDPLoadBlock(G_TX_LOADTILE, 0, 0, 383, 1024),
    gsDPPipeSync(),
    gsSPModifyVertex(1, G_MWO_POINT_ST, 0xFE690177),
    gsSPModifyVertex(2, G_MWO_POINT_ST, 0xFE690177),
    gsSPModifyVertex(3, G_MWO_POINT_ST, 0x02F2019F),
    gsSPVertex(&kangaskhan_vtx[624], 5, 4),
    gsSP2Triangles(1, 8, 3, 0, 8, 7, 3, 0),
    gsSP2Triangles(6, 2, 3, 0, 5, 6, 4, 0),
    gsDPPipeSync(),
    gsDPSetTile(G_IM_FMT_CI, G_IM_SIZ_16b, 0, 0x0000, G_TX_LOADTILE, 0, G_TX_NOMIRROR | G_TX_WRAP, 6, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_WRAP, 6, G_TX_NOLOD),
    gsDPSetTile(G_IM_FMT_CI, G_IM_SIZ_4b, 3, 0x0000, G_TX_RENDERTILE, 0, G_TX_NOMIRROR | G_TX_CLAMP, 6, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_CLAMP, 6, G_TX_NOLOD),
    gsDPSetTextureImage(G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, kangaskhan_tex_8016C618),
    gsDPLoadSync(),
    gsDPLoadTLUTCmd(5, 14),
    gsDPPipeSync(),
    gsDPSetTileSize(G_TX_RENDERTILE, 0, 0, 0x00BC, 0x00BC),
    gsDPSetTextureImage(G_IM_FMT_CI, G_IM_SIZ_16b, 1, kangaskhan_tex_8016C640_png),
    gsDPLoadSync(),
    gsDPLoadBlock(G_TX_LOADTILE, 0, 0, 575, 683),
    gsDPPipeSync(),
    gsSPModifyVertex(0, G_MWO_POINT_ST, 0x034B0656),
    gsSPModifyVertex(1, G_MWO_POINT_ST, 0x068E0670),
    gsSPModifyVertex(2, G_MWO_POINT_ST, 0xFF7A0641),
    gsSPVertex(&kangaskhan_vtx[629], 4, 4),
    gsSP2Triangles(1, 0, 7, 0, 7, 6, 1, 0),
    gsSP2Triangles(6, 7, 5, 0, 5, 7, 4, 0),
    gsSP2Triangles(2, 4, 7, 0, 7, 0, 2, 0),
    gsSPEndDisplayList(),
};
