.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.0 */

nonmatching D_800B0240

dlabel D_800B0240
    /* 5BBF0 800B0240 40490FDB */ .float 3.141592741
    /* 5BBF4 800B0244 00000000 */ .float 0
enddlabel D_800B0240

.align 3
nonmatching D_800B0248

dlabel D_800B0248
    /* 5BBF8 800B0248 405FC00000000000 */ .double 127
enddlabel D_800B0248

.align 3
nonmatching D_800B0250

dlabel D_800B0250
    /* 5BC00 800B0250 405FC00000000000 */ .double 127
    /* 5BC08 800B0258 0000000000000000 */ .double 0
enddlabel D_800B0250
