.section .late_rodata
nonmatching D_802E38DC_734ADC

dlabel D_802E38DC_734ADC
    /* 734ADC 802E38DC 3DA3D70A */ .float 0.07999999821
enddlabel D_802E38DC_734ADC


.section .text
/* Generated by spimdisasm 1.42.0 */

nonmatching func_802DC1F8_72D3F8, 0x88

glabel func_802DC1F8_72D3F8
    /* 72D3F8 802DC1F8 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* 72D3FC 802DC1FC AFBF001C */  sw         $ra, 0x1C($sp)
    /* 72D400 802DC200 AFB00018 */  sw         $s0, 0x18($sp)
    /* 72D404 802DC204 3C01802E */  lui        $at, %hi(D_802E38DC_734ADC)
    /* 72D408 802DC208 8C820058 */  lw         $v0, 0x58($a0)
    /* 72D40C 802DC20C C42438DC */  lwc1       $f4, %lo(D_802E38DC_734ADC)($at)
    /* 72D410 802DC210 00808025 */  or         $s0, $a0, $zero
    /* 72D414 802DC214 E44400C4 */  swc1       $f4, 0xC4($v0)
    /* 72D418 802DC218 0C0D8814 */  jal        Pokemon_ResetPathPos
    /* 72D41C 802DC21C AFA20020 */   sw        $v0, 0x20($sp)
    /* 72D420 802DC220 3C05802E */  lui        $a1, %hi(D_802E2B3C_733D3C)
    /* 72D424 802DC224 24A52B3C */  addiu      $a1, $a1, %lo(D_802E2B3C_733D3C)
    /* 72D428 802DC228 0C0D7C4E */  jal        Pokemon_SetAnimation
    /* 72D42C 802DC22C 02002025 */   or        $a0, $s0, $zero
    /* 72D430 802DC230 3C05802E */  lui        $a1, %hi(func_802DC280_72D480)
    /* 72D434 802DC234 24A5C280 */  addiu      $a1, $a1, %lo(func_802DC280_72D480)
    /* 72D438 802DC238 0C0D7B7E */  jal        Pokemon_StartPathProc
    /* 72D43C 802DC23C 02002025 */   or        $a0, $s0, $zero
    /* 72D440 802DC240 8FAF0020 */  lw         $t7, 0x20($sp)
    /* 72D444 802DC244 3C0E802E */  lui        $t6, %hi(D_802E2C00_733E00)
    /* 72D448 802DC248 25CE2C00 */  addiu      $t6, $t6, %lo(D_802E2C00_733E00)
    /* 72D44C 802DC24C 02002025 */  or         $a0, $s0, $zero
    /* 72D450 802DC250 24050002 */  addiu      $a1, $zero, 0x2
    /* 72D454 802DC254 0C0D7EFC */  jal        Pokemon_WaitForFlag
    /* 72D458 802DC258 ADEE00AC */   sw        $t6, 0xAC($t7)
    /* 72D45C 802DC25C 3C05802E */  lui        $a1, %hi(D_802E2C40_733E40)
    /* 72D460 802DC260 24A52C40 */  addiu      $a1, $a1, %lo(D_802E2C40_733E40)
    /* 72D464 802DC264 0C0D7B2B */  jal        Pokemon_SetStateRandom
    /* 72D468 802DC268 02002025 */   or        $a0, $s0, $zero
    /* 72D46C 802DC26C 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 72D470 802DC270 8FB00018 */  lw         $s0, 0x18($sp)
    /* 72D474 802DC274 27BD0030 */  addiu      $sp, $sp, 0x30
    /* 72D478 802DC278 03E00008 */  jr         $ra
    /* 72D47C 802DC27C 00000000 */   nop
endlabel func_802DC1F8_72D3F8
