.section .late_rodata
.align 3
nonmatching D_802E38F8_734AF8

dlabel D_802E38F8_734AF8
    /* 734AF8 802E38F8 3FE3333333333333 */ .double 0.599999999999999978
enddlabel D_802E38F8_734AF8


.section .text
/* Generated by spimdisasm 1.42.1 */

nonmatching func_802DD034_72E234, 0xB4

glabel func_802DD034_72E234
    /* 72E234 802DD034 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 72E238 802DD038 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 72E23C 802DD03C AFB00018 */  sw         $s0, 0x18($sp)
    /* 72E240 802DD040 8C900058 */  lw         $s0, 0x58($a0)
    /* 72E244 802DD044 3C05802E */  lui        $a1, %hi(D_802E2B3C_733D3C)
    /* 72E248 802DD048 24A52B3C */  addiu      $a1, $a1, %lo(D_802E2B3C_733D3C)
    /* 72E24C 802DD04C 0C0D7C4E */  jal        Pokemon_SetAnimation
    /* 72E250 802DD050 AFA40020 */   sw        $a0, 0x20($sp)
    /* 72E254 802DD054 0C00676C */  jal        randFloat
    /* 72E258 802DD058 00000000 */   nop
    /* 72E25C 802DD05C 3C0142A0 */  lui        $at, (0x42A00000 >> 16)
    /* 72E260 802DD060 44812000 */  mtc1       $at, $f4
    /* 72E264 802DD064 3C01802E */  lui        $at, %hi(D_802E38F8_734AF8)
    /* 72E268 802DD068 D42A38F8 */  ldc1       $f10, %lo(D_802E38F8_734AF8)($at)
    /* 72E26C 802DD06C 46040182 */  mul.s      $f6, $f0, $f4
    /* 72E270 802DD070 3C014054 */  lui        $at, (0x40540000 >> 16)
    /* 72E274 802DD074 44819800 */  mtc1       $at, $f19
    /* 72E278 802DD078 44809000 */  mtc1       $zero, $f18
    /* 72E27C 802DD07C 3C063DCC */  lui        $a2, (0x3DCCCCCD >> 16)
    /* 72E280 802DD080 34C6CCCD */  ori        $a2, $a2, (0x3DCCCCCD & 0xFFFF)
    /* 72E284 802DD084 3C054248 */  lui        $a1, (0x42480000 >> 16)
    /* 72E288 802DD088 46003221 */  cvt.d.s    $f8, $f6
    /* 72E28C 802DD08C 24070003 */  addiu      $a3, $zero, 0x3
    /* 72E290 802DD090 462A4402 */  mul.d      $f16, $f8, $f10
    /* 72E294 802DD094 46328100 */  add.d      $f4, $f16, $f18
    /* 72E298 802DD098 462021A0 */  cvt.s.d    $f6, $f4
    /* 72E29C 802DD09C E6060098 */  swc1       $f6, 0x98($s0)
    /* 72E2A0 802DD0A0 0C0D85D2 */  jal        Pokemon_RunToTarget
    /* 72E2A4 802DD0A4 8FA40020 */   lw        $a0, 0x20($sp)
    /* 72E2A8 802DD0A8 3C053DCC */  lui        $a1, (0x3DCCCCCD >> 16)
    /* 72E2AC 802DD0AC 34A5CCCD */  ori        $a1, $a1, (0x3DCCCCCD & 0xFFFF)
    /* 72E2B0 802DD0B0 8FA40020 */  lw         $a0, 0x20($sp)
    /* 72E2B4 802DD0B4 0C0D8523 */  jal        Pokemon_TurnToTarget
    /* 72E2B8 802DD0B8 00003025 */   or        $a2, $zero, $zero
    /* 72E2BC 802DD0BC 8E0E008C */  lw         $t6, 0x8C($s0)
    /* 72E2C0 802DD0C0 AE000094 */  sw         $zero, 0x94($s0)
    /* 72E2C4 802DD0C4 00002025 */  or         $a0, $zero, $zero
    /* 72E2C8 802DD0C8 35CF0002 */  ori        $t7, $t6, 0x2
    /* 72E2CC 802DD0CC 0C0023CB */  jal        omEndProcess
    /* 72E2D0 802DD0D0 AE0F008C */   sw        $t7, 0x8C($s0)
    /* 72E2D4 802DD0D4 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 72E2D8 802DD0D8 8FB00018 */  lw         $s0, 0x18($sp)
    /* 72E2DC 802DD0DC 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 72E2E0 802DD0E0 03E00008 */  jr         $ra
    /* 72E2E4 802DD0E4 00000000 */   nop
endlabel func_802DD034_72E234
