.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.1 */

.align 2
nonmatching D_801C5530_98AD50

dlabel D_801C5530_98AD50
    /* 98AD50 801C5530 */ .asciz "%s can go to\nthe next course!"
    /* 25732063616E20676F20746F0A746865206E65787420636F7572736521000000 */
.align 2
enddlabel D_801C5530_98AD50
