#include "common.h"

Gfx muk_part12_draw_near[] = {
    gsDPPipeSync(),
    gsDPSetAlphaCompare(G_AC_NONE),
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_OPA_SURF2),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPTileSync(),
    gsDPSetTile(G_IM_FMT_RGBA, G_IM_SIZ_4b, 0, 0x0100, 5, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMASK, G_TX_NOLOD),
    gsDPSetTile(G_IM_FMT_CI, G_IM_SIZ_16b, 0, 0x0000, G_TX_LOADTILE, 0, G_TX_NOMIRROR | G_TX_WRAP, 5, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_WRAP, 5, G_TX_NOLOD),
    gsDPSetTile(G_IM_FMT_CI, G_IM_SIZ_4b, 2, 0x0000, G_TX_RENDERTILE, 0, G_TX_NOMIRROR | G_TX_CLAMP, 5, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_CLAMP, 5, G_TX_NOLOD),
    gsDPSetTextureImage(G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, muk_tex_8015DBF0),
    gsDPLoadSync(),
    gsDPLoadTLUTCmd(5, 15),
    gsDPPipeSync(),
    gsSPDisplayList(D_0E000000),
    gsDPLoadSync(),
    gsDPLoadBlock(G_TX_LOADTILE, 0, 0, 255, 1024),
    gsDPPipeSync(),
    gsSPModifyVertex(0, G_MWO_POINT_ST, 0x0B5D05C6),
    gsSPModifyVertex(1, G_MWO_POINT_ST, 0x0B4A05A8),
    gsSPModifyVertex(2, G_MWO_POINT_ST, 0x0A6605A0),
    gsSPModifyVertex(3, G_MWO_POINT_ST, 0x09FE05BF),
    gsSPVertex(&muk_vtx[200], 3, 28),
    gsSP2Triangles(28, 2, 1, 0, 1, 0, 29, 0),
    gsSP2Triangles(1, 29, 28, 0, 30, 29, 0, 0),
    gsSP2Triangles(30, 3, 2, 0, 0, 3, 30, 0),
    gsSP1Triangle(2, 28, 30, 0),
    gsSPEndDisplayList(),
};
