.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.42.1 */

nonmatching D_802B5000_main_menu_vpk0, 0x25BC0

dlabel D_802B5000_main_menu_vpk0
    /* 802B5000 */ .space 0x25BC0

nonmatching D_802DABC0_main_menu_vpk0, 0x768

dlabel D_802DABC0_main_menu_vpk0
    /* 802DABC0 */ .space 0x768

nonmatching D_802DB328_main_menu_vpk0, 0x260

dlabel D_802DB328_main_menu_vpk0
    /* 802DB328 */ .space 0x260

nonmatching D_802DB588_main_menu_vpk0, 0x760

dlabel D_802DB588_main_menu_vpk0
    /* 802DB588 */ .space 0x760

nonmatching D_802DBCE8_main_menu_vpk0, 0x4C0

dlabel D_802DBCE8_main_menu_vpk0
    /* 802DBCE8 */ .space 0x4C0

nonmatching D_802DC1A8_main_menu_vpk0, 0x570

dlabel D_802DC1A8_main_menu_vpk0
    /* 802DC1A8 */ .space 0x570

nonmatching D_802DC718_main_menu_vpk0, 0x260

dlabel D_802DC718_main_menu_vpk0
    /* 802DC718 */ .space 0x260

nonmatching D_802DC978_main_menu_vpk0, 0x510

dlabel D_802DC978_main_menu_vpk0
    /* 802DC978 */ .space 0x510

nonmatching D_802DCE88_main_menu_vpk0, 0x2C28

dlabel D_802DCE88_main_menu_vpk0
    /* 802DCE88 */ .space 0x2C28

nonmatching D_802DFAB0_main_menu_vpk0, 0x9320

dlabel D_802DFAB0_main_menu_vpk0
    /* 802DFAB0 */ .space 0x9320

nonmatching D_802E8DD0_main_menu_vpk0, 0x9320

dlabel D_802E8DD0_main_menu_vpk0
    /* 802E8DD0 */ .space 0x9320

nonmatching D_802F20F0_main_menu_vpk0, 0x2738

dlabel D_802F20F0_main_menu_vpk0
    /* 802F20F0 */ .space 0x2738

nonmatching D_802F4828_main_menu_vpk0, 0x1C68

dlabel D_802F4828_main_menu_vpk0
    /* 802F4828 */ .space 0x1C68

nonmatching D_802F6490_main_menu_vpk0, 0x1E38

dlabel D_802F6490_main_menu_vpk0
    /* 802F6490 */ .space 0x1E38

nonmatching D_802F82C8_main_menu_vpk0, 0xCF28

dlabel D_802F82C8_main_menu_vpk0
    /* 802F82C8 */ .space 0xCF28

nonmatching D_803051F0_main_menu_vpk0, 0x20B0

dlabel D_803051F0_main_menu_vpk0
    /* 803051F0 */ .space 0x20B0

nonmatching D_803072A0_main_menu_vpk0, 0x1760

dlabel D_803072A0_main_menu_vpk0
    /* 803072A0 */ .space 0x1760

nonmatching D_80308A00_main_menu_vpk0, 0xD70

dlabel D_80308A00_main_menu_vpk0
    /* 80308A00 */ .space 0xD70

nonmatching D_80309770_main_menu_vpk0, 0xD70

dlabel D_80309770_main_menu_vpk0
    /* 80309770 */ .space 0xD70

nonmatching D_8030A4E0_main_menu_vpk0, 0xD70

dlabel D_8030A4E0_main_menu_vpk0
    /* 8030A4E0 */ .space 0xD70

nonmatching D_8030B250_main_menu_vpk0, 0xD70

dlabel D_8030B250_main_menu_vpk0
    /* 8030B250 */ .space 0xD70

nonmatching D_8030BFC0_main_menu_vpk0, 0x2060

dlabel D_8030BFC0_main_menu_vpk0
    /* 8030BFC0 */ .space 0x2060

nonmatching D_8030E020_main_menu_vpk0, 0x2060

dlabel D_8030E020_main_menu_vpk0
    /* 8030E020 */ .space 0x2060

nonmatching D_80310080_main_menu_vpk0, 0x2060

dlabel D_80310080_main_menu_vpk0
    /* 80310080 */ .space 0x2060

nonmatching D_803120E0_main_menu_vpk0, 0x158

dlabel D_803120E0_main_menu_vpk0
    /* 803120E0 */ .space 0x158

nonmatching D_80312238_main_menu_vpk0, 0x6A8

dlabel D_80312238_main_menu_vpk0
    /* 80312238 */ .space 0x6A8

nonmatching D_803128E0_main_menu_vpk0, 0x3950

dlabel D_803128E0_main_menu_vpk0
    /* 803128E0 */ .space 0x3950

nonmatching D_80316230_main_menu_vpk0, 0x3950

dlabel D_80316230_main_menu_vpk0
    /* 80316230 */ .space 0x3950

nonmatching D_80319B80_main_menu_vpk0, 0x3950

dlabel D_80319B80_main_menu_vpk0
    /* 80319B80 */ .space 0x3950

nonmatching D_8031D4D0_main_menu_vpk0, 0x3950

dlabel D_8031D4D0_main_menu_vpk0
    /* 8031D4D0 */ .space 0x3950

nonmatching D_80320E20_main_menu_vpk0, 0x3950

dlabel D_80320E20_main_menu_vpk0
    /* 80320E20 */ .space 0x3950

nonmatching D_80324770_main_menu_vpk0, 0x3950

dlabel D_80324770_main_menu_vpk0
    /* 80324770 */ .space 0x3950

nonmatching D_803280C0_main_menu_vpk0, 0x3950

dlabel D_803280C0_main_menu_vpk0
    /* 803280C0 */ .space 0x3950

nonmatching D_8032BA10_main_menu_vpk0, 0x3950

dlabel D_8032BA10_main_menu_vpk0
    /* 8032BA10 */ .space 0x3950

nonmatching D_8032F360_main_menu_vpk0, 0x3950

dlabel D_8032F360_main_menu_vpk0
    /* 8032F360 */ .space 0x3950

nonmatching D_80332CB0_main_menu_vpk0, 0x3950

dlabel D_80332CB0_main_menu_vpk0
    /* 80332CB0 */ .space 0x3950

nonmatching D_80336600_main_menu_vpk0, 0x3950

dlabel D_80336600_main_menu_vpk0
    /* 80336600 */ .space 0x3950

nonmatching D_80339F50_main_menu_vpk0, 0x3950

dlabel D_80339F50_main_menu_vpk0
    /* 80339F50 */ .space 0x3950

nonmatching D_8033D8A0_main_menu_vpk0, 0x970

dlabel D_8033D8A0_main_menu_vpk0
    /* 8033D8A0 */ .space 0x970

nonmatching D_8033E210_main_menu_vpk0, 0x728

dlabel D_8033E210_main_menu_vpk0
    /* 8033E210 */ .space 0x728

nonmatching D_8033E938_main_menu_vpk0, 0x398

dlabel D_8033E938_main_menu_vpk0
    /* 8033E938 */ .space 0x398

nonmatching D_8033ECD0_main_menu_vpk0, 0xA0

dlabel D_8033ECD0_main_menu_vpk0
    /* 8033ECD0 */ .space 0xA0

nonmatching D_8033ED70_main_menu_vpk0, 0x728

dlabel D_8033ED70_main_menu_vpk0
    /* 8033ED70 */ .space 0x728

nonmatching D_8033F498_main_menu_vpk0, 0x720

dlabel D_8033F498_main_menu_vpk0
    /* 8033F498 */ .space 0x720

nonmatching D_8033FBB8_main_menu_vpk0, 0x15A8

dlabel D_8033FBB8_main_menu_vpk0
    /* 8033FBB8 */ .space 0x15A8

nonmatching D_80341160_main_menu_vpk0, 0x630

dlabel D_80341160_main_menu_vpk0
    /* 80341160 */ .space 0x630

nonmatching D_80341790_main_menu_vpk0, 0x4E0

dlabel D_80341790_main_menu_vpk0
    /* 80341790 */ .space 0x4E0

nonmatching D_80341C70_main_menu_vpk0, 0x4E0

dlabel D_80341C70_main_menu_vpk0
    /* 80341C70 */ .space 0x4E0

nonmatching D_80342150_main_menu_vpk0, 0x4E0

dlabel D_80342150_main_menu_vpk0
    /* 80342150 */ .space 0x4E0

nonmatching D_80342630_main_menu_vpk0, 0x4E0

dlabel D_80342630_main_menu_vpk0
    /* 80342630 */ .space 0x4E0

nonmatching D_80342B10_main_menu_vpk0, 0x4E0

dlabel D_80342B10_main_menu_vpk0
    /* 80342B10 */ .space 0x4E0

nonmatching D_80342FF0_main_menu_vpk0, 0x4E0

dlabel D_80342FF0_main_menu_vpk0
    /* 80342FF0 */ .space 0x4E0

nonmatching D_803434D0_main_menu_vpk0, 0x658

dlabel D_803434D0_main_menu_vpk0
    /* 803434D0 */ .space 0x658

nonmatching D_80343B28_main_menu_vpk0, 0xE0

dlabel D_80343B28_main_menu_vpk0
    /* 80343B28 */ .space 0xE0

nonmatching D_80343C08_main_menu_vpk0, 0x780

dlabel D_80343C08_main_menu_vpk0
    /* 80343C08 */ .space 0x780

nonmatching D_80344388_main_menu_vpk0, 0x150

dlabel D_80344388_main_menu_vpk0
    /* 80344388 */ .space 0x150

nonmatching D_803444D8_main_menu_vpk0, 0x140

dlabel D_803444D8_main_menu_vpk0
    /* 803444D8 */ .space 0x140

nonmatching D_80344618_main_menu_vpk0, 0x6A08

dlabel D_80344618_main_menu_vpk0
    /* 80344618 */ .space 0x6A08

nonmatching D_8034B020_main_menu_vpk0, 0x900

dlabel D_8034B020_main_menu_vpk0
    /* 8034B020 */ .space 0x900

nonmatching D_8034B920_main_menu_vpk0, 0x298

dlabel D_8034B920_main_menu_vpk0
    /* 8034B920 */ .space 0x298

nonmatching D_8034BBB8_main_menu_vpk0, 0x8F8

dlabel D_8034BBB8_main_menu_vpk0
    /* 8034BBB8 */ .space 0x8F8

nonmatching D_8034C4B0_main_menu_vpk0, 0x260

dlabel D_8034C4B0_main_menu_vpk0
    /* 8034C4B0 */ .space 0x260

nonmatching D_8034C710_main_menu_vpk0, 0xC90

dlabel D_8034C710_main_menu_vpk0
    /* 8034C710 */ .space 0xC90

nonmatching D_8034D3A0_main_menu_vpk0, 0x2738

dlabel D_8034D3A0_main_menu_vpk0
    /* 8034D3A0 */ .space 0x2738

nonmatching D_8034FAD8_main_menu_vpk0, 0x98A0

dlabel D_8034FAD8_main_menu_vpk0
    /* 8034FAD8 */ .space 0x98A0

nonmatching D_80359378_main_menu_vpk0, 0x6A8

dlabel D_80359378_main_menu_vpk0
    /* 80359378 */ .space 0x6A8

nonmatching D_80359A20_main_menu_vpk0, 0x110

dlabel D_80359A20_main_menu_vpk0
    /* 80359A20 */ .space 0x110

nonmatching D_80359B30_main_menu_vpk0, 0x1A0

dlabel D_80359B30_main_menu_vpk0
    /* 80359B30 */ .space 0x1A0

nonmatching D_80359CD0_main_menu_vpk0, 0x10788

dlabel D_80359CD0_main_menu_vpk0
    /* 80359CD0 */ .space 0x10788

nonmatching D_8036A458_main_menu_vpk0, 0x15200

dlabel D_8036A458_main_menu_vpk0
    /* 8036A458 */ .space 0x15200

nonmatching D_8037F658_main_menu_vpk0, 0x2708

dlabel D_8037F658_main_menu_vpk0
    /* 8037F658 */ .space 0x2708

nonmatching D_80381D60_main_menu_vpk0, 0x39A0

dlabel D_80381D60_main_menu_vpk0
    /* 80381D60 */ .space 0x39A0

nonmatching D_80385700_main_menu_vpk0, 0x5640

dlabel D_80385700_main_menu_vpk0
    /* 80385700 */ .space 0x5640

nonmatching D_8038AD40_main_menu_vpk0, 0x46A0

dlabel D_8038AD40_main_menu_vpk0
    /* 8038AD40 */ .space 0x46A0

nonmatching D_8038F3E0_main_menu_vpk0, 0x5E0

dlabel D_8038F3E0_main_menu_vpk0
    /* 8038F3E0 */ .space 0x5E0

nonmatching D_8038F9C0_main_menu_vpk0, 0x4120

dlabel D_8038F9C0_main_menu_vpk0
    /* 8038F9C0 */ .space 0x4120

nonmatching D_80393AE0_main_menu_vpk0, 0x250

dlabel D_80393AE0_main_menu_vpk0
    /* 80393AE0 */ .space 0x250

nonmatching D_80393D30_main_menu_vpk0, 0x90

dlabel D_80393D30_main_menu_vpk0
    /* 80393D30 */ .space 0x90

nonmatching D_80393DC0_main_menu_vpk0, 0x7E88

dlabel D_80393DC0_main_menu_vpk0
    /* 80393DC0 */ .space 0x7E88

nonmatching D_8039BC48_main_menu_vpk0, 0x5AE8

dlabel D_8039BC48_main_menu_vpk0
    /* 8039BC48 */ .space 0x5AE8

nonmatching D_803A1730_main_menu_vpk0, 0x4B0

dlabel D_803A1730_main_menu_vpk0
    /* 803A1730 */ .space 0x4B0

nonmatching D_803A1BE0_main_menu_vpk0, 0x63B0

dlabel D_803A1BE0_main_menu_vpk0
    /* 803A1BE0 */ .space 0x63B0

nonmatching D_803A7F90_main_menu_vpk0, 0x140

dlabel D_803A7F90_main_menu_vpk0
    /* 803A7F90 */ .space 0x140

nonmatching D_803A80D0_main_menu_vpk0, 0x6A0

dlabel D_803A80D0_main_menu_vpk0
    /* 803A80D0 */ .space 0x6A0
