#include "common.h"

Gfx ditto_part12_pre_near[] = {
    gsDPPipeSync(),
    gsSPSetGeometryMode(G_TEXTURE_GEN),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsSPTexture(0x07C0, 0x07C0, 0, G_TX_RENDERTILE, G_ON),
    gsSPVertex(&ditto_vtx[135], 1, 0),
    gsSPVertex(&ditto_vtx[114], 1, 1),
    gsSPVertex(&ditto_vtx[138], 1, 2),
    gsSPVertex(&ditto_vtx[92], 1, 3),
    gsSPVertex(&ditto_vtx[95], 1, 4),
    gsSPVertex(&ditto_vtx[133], 1, 5),
    gsSPVertex(&ditto_vtx[115], 1, 6),
    gsSPVertex(&ditto_vtx[94], 1, 7),
    gsSPVertex(&ditto_vtx[122], 1, 8),
    gsSPVertex(&ditto_vtx[107], 1, 9),
    gsSPVertex(&ditto_vtx[124], 2, 10),
    gsSPVertex(&ditto_vtx[106], 1, 12),
    gsSPVertex(&ditto_vtx[98], 1, 13),
    gsDPPipeSync(),
    gsDPPipeSync(),
    gsSPClearGeometryMode(G_TEXTURE_GEN),
    gsSPEndDisplayList(),
};
