#include "common.h"

Gfx ditto_part7_pre_near[] = {
    gsDPPipeSync(),
    gsSPSetGeometryMode(G_TEXTURE_GEN),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsSPTexture(0x07C0, 0x07C0, 0, G_TX_RENDERTILE, G_ON),
    gsSPVertex(&ditto_vtx[25], 1, 0),
    gsSPVertex(&ditto_vtx[21], 1, 1),
    gsSPVertex(&ditto_vtx[3], 2, 2),
    gsSPVertex(&ditto_vtx[0], 1, 4),
    gsSPVertex(&ditto_vtx[10], 1, 5),
    gsSPVertex(&ditto_vtx[14], 1, 6),
    gsSPVertex(&ditto_vtx[28], 1, 7),
    gsSPVertex(&ditto_vtx[26], 1, 8),
    gsSPVertex(&ditto_vtx[13], 1, 9),
    gsSPVertex(&ditto_vtx[20], 1, 10),
    gsSPVertex(&ditto_vtx[24], 1, 11),
    gsSPVertex(&ditto_vtx[11], 1, 12),
    gsSPVertex(&ditto_vtx[7], 1, 13),
    gsSPVertex(&ditto_vtx[2], 1, 14),
    gsDPPipeSync(),
    gsDPPipeSync(),
    gsSPClearGeometryMode(G_TEXTURE_GEN),
    gsSPEndDisplayList(),
};
