.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.1 */

.align 2
nonmatching D_800E6B90_64340

dlabel D_800E6B90_64340
    /* 64340 800E6B90 */ .asciz "blockModelCreate()"
    /* 626C6F636B4D6F64656C43726561746528290000 */
.align 2
enddlabel D_800E6B90_64340

.align 2
nonmatching D_800E6BA4_64354

dlabel D_800E6BA4_64354
    /* 64354 800E6BA4 */ .asciz "blockUVCreate()"
    /* 626C6F636B5556437265617465282900 */
.align 2
.align 2
    /* 64364 800E6BB4 */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_800E6BA4_64354

.align 3
nonmatching D_800E6BB8_64368

dlabel D_800E6BB8_64368
    /* 64368 800E6BB8 40C3880000000000 */ .double 10000
enddlabel D_800E6BB8_64368

.align 3
nonmatching D_800E6BC0_64370

dlabel D_800E6BC0_64370
    /* 64370 800E6BC0 408F400000000000 */ .double 1000
enddlabel D_800E6BC0_64370

nonmatching D_800E6BC8_64378

dlabel D_800E6BC8_64378
    /* 64378 800E6BC8 40C90FDB */ .float 6.283185482
    /* 6437C 800E6BCC 00000000 */ .float 0
enddlabel D_800E6BC8_64378
