.section .late_rodata
.align 3
nonmatching D_credits_801E9420

dlabel D_credits_801E9420
    /* A9FFE0 801E9420 4085E00000000000 */ .double 700
enddlabel D_credits_801E9420

.align 3
nonmatching D_credits_801E9428

dlabel D_credits_801E9428
    /* A9FFE8 801E9428 C070300000000000 */ .double -259
enddlabel D_credits_801E9428


.section .text
/* Generated by spimdisasm 1.42.2 */

nonmatching func_credits_801DD018, 0x114

glabel func_credits_801DD018
    /* A93BD8 801DD018 27BDFFC0 */  addiu      $sp, $sp, -0x40
    /* A93BDC 801DD01C AFBF003C */  sw         $ra, 0x3C($sp)
    /* A93BE0 801DD020 AFB40038 */  sw         $s4, 0x38($sp)
    /* A93BE4 801DD024 AFB30034 */  sw         $s3, 0x34($sp)
    /* A93BE8 801DD028 AFB20030 */  sw         $s2, 0x30($sp)
    /* A93BEC 801DD02C AFB1002C */  sw         $s1, 0x2C($sp)
    /* A93BF0 801DD030 AFB00028 */  sw         $s0, 0x28($sp)
    /* A93BF4 801DD034 F7B60020 */  sdc1       $f22, 0x20($sp)
    /* A93BF8 801DD038 F7B40018 */  sdc1       $f20, 0x18($sp)
    /* A93BFC 801DD03C 8C900048 */  lw         $s0, 0x48($a0)
    /* A93C00 801DD040 24130002 */  addiu      $s3, $zero, 0x2
    /* A93C04 801DD044 24140001 */  addiu      $s4, $zero, 0x1
    /* A93C08 801DD048 1200002E */  beqz       $s0, .Lcredits_801DD104
    /* A93C0C 801DD04C 3C01801F */   lui       $at, %hi(D_credits_801E9420)
    /* A93C10 801DD050 D4369420 */  ldc1       $f22, %lo(D_credits_801E9420)($at)
    /* A93C14 801DD054 3C01801F */  lui        $at, %hi(D_credits_801E9428)
    /* A93C18 801DD058 3C12801F */  lui        $s2, %hi(D_credits_801ECDA4)
    /* A93C1C 801DD05C 3C11801F */  lui        $s1, %hi(D_credits_801ED010)
    /* A93C20 801DD060 2631D010 */  addiu      $s1, $s1, %lo(D_credits_801ED010)
    /* A93C24 801DD064 2652CDA4 */  addiu      $s2, $s2, %lo(D_credits_801ECDA4)
    /* A93C28 801DD068 D4349428 */  ldc1       $f20, %lo(D_credits_801E9428)($at)
    /* A93C2C 801DD06C 860E0010 */  lh         $t6, 0x10($s0)
  .Lcredits_801DD070:
    /* A93C30 801DD070 25CFFFFF */  addiu      $t7, $t6, -0x1
    /* A93C34 801DD074 A60F0010 */  sh         $t7, 0x10($s0)
    /* A93C38 801DD078 86180010 */  lh         $t8, 0x10($s0)
    /* A93C3C 801DD07C 44982000 */  mtc1       $t8, $f4
    /* A93C40 801DD080 00000000 */  nop
    /* A93C44 801DD084 468021A1 */  cvt.d.w    $f6, $f4
    /* A93C48 801DD088 4634303C */  c.lt.d     $f6, $f20
    /* A93C4C 801DD08C 00000000 */  nop
    /* A93C50 801DD090 4502001A */  bc1fl      .Lcredits_801DD0FC
    /* A93C54 801DD094 8E100008 */   lw        $s0, 0x8($s0)
    /* A93C58 801DD098 8E220000 */  lw         $v0, 0x0($s1)
    /* A93C5C 801DD09C 10400004 */  beqz       $v0, .Lcredits_801DD0B0
    /* A93C60 801DD0A0 2459FFFF */   addiu     $t9, $v0, -0x1
    /* A93C64 801DD0A4 17200002 */  bnez       $t9, .Lcredits_801DD0B0
    /* A93C68 801DD0A8 AE390000 */   sw        $t9, 0x0($s1)
    /* A93C6C 801DD0AC A2530000 */  sb         $s3, 0x0($s2)
  .Lcredits_801DD0B0:
    /* A93C70 801DD0B0 92490000 */  lbu        $t1, 0x0($s2)
    /* A93C74 801DD0B4 5689000E */  bnel       $s4, $t1, .Lcredits_801DD0F0
    /* A93C78 801DD0B8 960D0024 */   lhu       $t5, 0x24($s0)
    /* A93C7C 801DD0BC 860A0010 */  lh         $t2, 0x10($s0)
    /* A93C80 801DD0C0 02002025 */  or         $a0, $s0, $zero
    /* A93C84 801DD0C4 448A4000 */  mtc1       $t2, $f8
    /* A93C88 801DD0C8 00000000 */  nop
    /* A93C8C 801DD0CC 468042A1 */  cvt.d.w    $f10, $f8
    /* A93C90 801DD0D0 46365400 */  add.d      $f16, $f10, $f22
    /* A93C94 801DD0D4 4620848D */  trunc.w.d  $f18, $f16
    /* A93C98 801DD0D8 440C9000 */  mfc1       $t4, $f18
    /* A93C9C 801DD0DC 0C0772BE */  jal        func_credits_801DCAF8
    /* A93CA0 801DD0E0 A60C0010 */   sh        $t4, 0x10($s0)
    /* A93CA4 801DD0E4 10000005 */  b          .Lcredits_801DD0FC
    /* A93CA8 801DD0E8 8E100008 */   lw        $s0, 0x8($s0)
    /* A93CAC 801DD0EC 960D0024 */  lhu        $t5, 0x24($s0)
  .Lcredits_801DD0F0:
    /* A93CB0 801DD0F0 35AE0004 */  ori        $t6, $t5, 0x4
    /* A93CB4 801DD0F4 A60E0024 */  sh         $t6, 0x24($s0)
    /* A93CB8 801DD0F8 8E100008 */  lw         $s0, 0x8($s0)
  .Lcredits_801DD0FC:
    /* A93CBC 801DD0FC 5600FFDC */  bnel       $s0, $zero, .Lcredits_801DD070
    /* A93CC0 801DD100 860E0010 */   lh        $t6, 0x10($s0)
  .Lcredits_801DD104:
    /* A93CC4 801DD104 8FBF003C */  lw         $ra, 0x3C($sp)
    /* A93CC8 801DD108 D7B40018 */  ldc1       $f20, 0x18($sp)
    /* A93CCC 801DD10C D7B60020 */  ldc1       $f22, 0x20($sp)
    /* A93CD0 801DD110 8FB00028 */  lw         $s0, 0x28($sp)
    /* A93CD4 801DD114 8FB1002C */  lw         $s1, 0x2C($sp)
    /* A93CD8 801DD118 8FB20030 */  lw         $s2, 0x30($sp)
    /* A93CDC 801DD11C 8FB30034 */  lw         $s3, 0x34($sp)
    /* A93CE0 801DD120 8FB40038 */  lw         $s4, 0x38($sp)
    /* A93CE4 801DD124 03E00008 */  jr         $ra
    /* A93CE8 801DD128 27BD0040 */   addiu     $sp, $sp, 0x40
endlabel func_credits_801DD018
