.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.2 */

nonmatching D_802F0360_5ED430

dlabel D_802F0360_5ED430
    /* 5ED430 802F0360 3EB33333 */ .float 0.349999994
    /* 5ED434 802F0364 00000000 */ .float 0
    /* 5ED438 802F0368 00000000 */ .float 0
    /* 5ED43C 802F036C 00000000 */ .float 0
enddlabel D_802F0360_5ED430
