.section .late_rodata
nonmatching D_802E4C50_6CCA30

dlabel D_802E4C50_6CCA30
    /* 6CCA30 802E4C50 40490FDB */ .float 3.141592741
    /* 6CCA34 802E4C54 00000000 */ .float 0
    /* 6CCA38 802E4C58 00000000 */ .float 0
    /* 6CCA3C 802E4C5C 00000000 */ .float 0
enddlabel D_802E4C50_6CCA30


.section .text
/* Generated by spimdisasm 1.42.1 */

nonmatching func_802DCFBC_6C4D9C, 0xAC

glabel func_802DCFBC_6C4D9C
    /* 6C4D9C 802DCFBC 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* 6C4DA0 802DCFC0 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 6C4DA4 802DCFC4 AFB00018 */  sw         $s0, 0x18($sp)
    /* 6C4DA8 802DCFC8 8C820048 */  lw         $v0, 0x48($a0)
    /* 6C4DAC 802DCFCC 00808025 */  or         $s0, $a0, $zero
    /* 6C4DB0 802DCFD0 8C4E004C */  lw         $t6, 0x4C($v0)
    /* 6C4DB4 802DCFD4 25CF0014 */  addiu      $t7, $t6, 0x14
    /* 6C4DB8 802DCFD8 AFAF0024 */  sw         $t7, 0x24($sp)
    /* 6C4DBC 802DCFDC 8C980058 */  lw         $t8, 0x58($a0)
    /* 6C4DC0 802DCFE0 24040168 */  addiu      $a0, $zero, 0x168
    /* 6C4DC4 802DCFE4 0C006785 */  jal        randRange
    /* 6C4DC8 802DCFE8 AFB80020 */   sw        $t8, 0x20($sp)
    /* 6C4DCC 802DCFEC 44822000 */  mtc1       $v0, $f4
    /* 6C4DD0 802DCFF0 3C01802E */  lui        $at, %hi(D_802E4C50_6CCA30)
    /* 6C4DD4 802DCFF4 C4284C50 */  lwc1       $f8, %lo(D_802E4C50_6CCA30)($at)
    /* 6C4DD8 802DCFF8 468021A0 */  cvt.s.w    $f6, $f4
    /* 6C4DDC 802DCFFC 3C014334 */  lui        $at, (0x43340000 >> 16)
    /* 6C4DE0 802DD000 44818000 */  mtc1       $at, $f16
    /* 6C4DE4 802DD004 8FB90024 */  lw         $t9, 0x24($sp)
    /* 6C4DE8 802DD008 3C05802E */  lui        $a1, %hi(func_802DD068_6C4E48)
    /* 6C4DEC 802DD00C 24A5D068 */  addiu      $a1, $a1, %lo(func_802DD068_6C4E48)
    /* 6C4DF0 802DD010 46083282 */  mul.s      $f10, $f6, $f8
    /* 6C4DF4 802DD014 02002025 */  or         $a0, $s0, $zero
    /* 6C4DF8 802DD018 46105483 */  div.s      $f18, $f10, $f16
    /* 6C4DFC 802DD01C 0C0D7B7E */  jal        Pokemon_StartPathProc
    /* 6C4E00 802DD020 E732000C */   swc1      $f18, 0xC($t9)
    /* 6C4E04 802DD024 8FA80020 */  lw         $t0, 0x20($sp)
    /* 6C4E08 802DD028 02002025 */  or         $a0, $s0, $zero
    /* 6C4E0C 802DD02C 24050001 */  addiu      $a1, $zero, 0x1
    /* 6C4E10 802DD030 0C0D7EFC */  jal        Pokemon_WaitForFlag
    /* 6C4E14 802DD034 AD0000AC */   sw        $zero, 0xAC($t0)
    /* 6C4E18 802DD038 3C01802E */  lui        $at, %hi(D_802E28AC_6CA68C)
    /* 6C4E1C 802DD03C A42028AC */  sh         $zero, %lo(D_802E28AC_6CA68C)($at)
    /* 6C4E20 802DD040 0C0D7F5C */  jal        Pokemon_RunCleanup
    /* 6C4E24 802DD044 02002025 */   or        $a0, $s0, $zero
    /* 6C4E28 802DD048 02002025 */  or         $a0, $s0, $zero
    /* 6C4E2C 802DD04C 0C0D7B16 */  jal        Pokemon_SetState
    /* 6C4E30 802DD050 00002825 */   or        $a1, $zero, $zero
    /* 6C4E34 802DD054 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 6C4E38 802DD058 8FB00018 */  lw         $s0, 0x18($sp)
    /* 6C4E3C 802DD05C 27BD0030 */  addiu      $sp, $sp, 0x30
    /* 6C4E40 802DD060 03E00008 */  jr         $ra
    /* 6C4E44 802DD064 00000000 */   nop
endlabel func_802DCFBC_6C4D9C
