.section .rodata
.align 2
nonmatching D_8004334C

dlabel D_8004334C
    /* 43F4C 8004334C */ .asciz "om : couldn't get MObj\n"
    /* 6F6D203A20636F756C646E277420676574204D4F626A0A00 */
.align 2
enddlabel D_8004334C


.section .text
/* Generated by spimdisasm 1.42.2 */

nonmatching func_8000898C, 0x78

glabel func_8000898C
    /* 958C 8000898C 3C068005 */  lui        $a2, %hi(D_8004AC18)
    /* 9590 80008990 24C6AC18 */  addiu      $a2, $a2, %lo(D_8004AC18)
    /* 9594 80008994 8CC30000 */  lw         $v1, 0x0($a2)
    /* 9598 80008998 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 959C 8000899C AFBF0014 */  sw         $ra, 0x14($sp)
    /* 95A0 800089A0 14600007 */  bnez       $v1, .L800089C0
    /* 95A4 800089A4 240400A8 */   addiu     $a0, $zero, 0xA8
    /* 95A8 800089A8 0C001528 */  jal        gtlMalloc
    /* 95AC 800089AC 24050004 */   addiu     $a1, $zero, 0x4
    /* 95B0 800089B0 3C068005 */  lui        $a2, %hi(D_8004AC18)
    /* 95B4 800089B4 24C6AC18 */  addiu      $a2, $a2, %lo(D_8004AC18)
    /* 95B8 800089B8 ACC20000 */  sw         $v0, 0x0($a2)
    /* 95BC 800089BC 00401825 */  or         $v1, $v0, $zero
  .L800089C0:
    /* 95C0 800089C0 14600006 */  bnez       $v1, .L800089DC
    /* 95C4 800089C4 3C058005 */   lui       $a1, %hi(D_8004AC1C)
    /* 95C8 800089C8 3C048004 */  lui        $a0, %hi(D_8004334C)
    /* 95CC 800089CC 0C0097C9 */  jal        error_printf
    /* 95D0 800089D0 2484334C */   addiu     $a0, $a0, %lo(D_8004334C)
  .L800089D4:
    /* 95D4 800089D4 1000FFFF */  b          .L800089D4
    /* 95D8 800089D8 00000000 */   nop
  .L800089DC:
    /* 95DC 800089DC 24A5AC1C */  addiu      $a1, $a1, %lo(D_8004AC1C)
    /* 95E0 800089E0 8CAF0000 */  lw         $t7, 0x0($a1)
    /* 95E4 800089E4 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 95E8 800089E8 8C6E0000 */  lw         $t6, 0x0($v1)
    /* 95EC 800089EC 25F80001 */  addiu      $t8, $t7, 0x1
    /* 95F0 800089F0 ACB80000 */  sw         $t8, 0x0($a1)
    /* 95F4 800089F4 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 95F8 800089F8 00601025 */  or         $v0, $v1, $zero
    /* 95FC 800089FC 03E00008 */  jr         $ra
    /* 9600 80008A00 ACCE0000 */   sw        $t6, 0x0($a2)
endlabel func_8000898C
