.section .rodata
.align 2
nonmatching D_800433B0

dlabel D_800433B0
    /* 43FB0 800433B0 */ .asciz "om : GObjProcess's priority is bad value\n"
    /* 6F6D203A20474F626A50726F636573732773207072696F72697479206973206261642076616C75650A000000 */
.align 2
enddlabel D_800433B0

.align 2
nonmatching D_800433DC

dlabel D_800433DC
    /* 43FDC 800433DC */ .asciz "om : GObjProcess's kind is bad value\n"
    /* 6F6D203A20474F626A50726F636573732773206B696E64206973206261642076616C75650A000000 */
.align 2
enddlabel D_800433DC


.section .text
/* Generated by spimdisasm 1.42.2 */

nonmatching omCreateProcess, 0x17C

glabel omCreateProcess
    /* 9828 80008C28 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* 982C 80008C2C AFA60038 */  sw         $a2, 0x38($sp)
    /* 9830 80008C30 30C600FF */  andi       $a2, $a2, 0xFF
    /* 9834 80008C34 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 9838 80008C38 14800003 */  bnez       $a0, .L80008C48
    /* 983C 80008C3C AFA50034 */   sw        $a1, 0x34($sp)
    /* 9840 80008C40 3C048005 */  lui        $a0, %hi(omCurrentObject)
    /* 9844 80008C44 8C84AC44 */  lw         $a0, %lo(omCurrentObject)($a0)
  .L80008C48:
    /* 9848 80008C48 AFA40030 */  sw         $a0, 0x30($sp)
    /* 984C 80008C4C A3A6003B */  sb         $a2, 0x3B($sp)
    /* 9850 80008C50 0C002028 */  jal        func_800080A0
    /* 9854 80008C54 AFA7003C */   sw        $a3, 0x3C($sp)
    /* 9858 80008C58 8FA7003C */  lw         $a3, 0x3C($sp)
    /* 985C 80008C5C 93A6003B */  lbu        $a2, 0x3B($sp)
    /* 9860 80008C60 AFA20024 */  sw         $v0, 0x24($sp)
    /* 9864 80008C64 2CE1000C */  sltiu      $at, $a3, 0xC
    /* 9868 80008C68 14200006 */  bnez       $at, .L80008C84
    /* 986C 80008C6C 8FA40034 */   lw        $a0, 0x34($sp)
    /* 9870 80008C70 3C048004 */  lui        $a0, %hi(D_800433B0)
    /* 9874 80008C74 0C0097C9 */  jal        error_printf
    /* 9878 80008C78 248433B0 */   addiu     $a0, $a0, %lo(D_800433B0)
  .L80008C7C:
    /* 987C 80008C7C 1000FFFF */  b          .L80008C7C
    /* 9880 80008C80 00000000 */   nop
  .L80008C84:
    /* 9884 80008C84 AC470010 */  sw         $a3, 0x10($v0)
    /* 9888 80008C88 A0460014 */  sb         $a2, 0x14($v0)
    /* 988C 80008C8C A0400015 */  sb         $zero, 0x15($v0)
    /* 9890 80008C90 8FAE0030 */  lw         $t6, 0x30($sp)
    /* 9894 80008C94 AC440020 */  sw         $a0, 0x20($v0)
    /* 9898 80008C98 10C00006 */  beqz       $a2, .L80008CB4
    /* 989C 80008C9C AC4E0018 */   sw        $t6, 0x18($v0)
    /* 98A0 80008CA0 24010001 */  addiu      $at, $zero, 0x1
    /* 98A4 80008CA4 10C10032 */  beq        $a2, $at, .L80008D70
    /* 98A8 80008CA8 00000000 */   nop
    /* 98AC 80008CAC 10000032 */  b          .L80008D78
    /* 98B0 80008CB0 3C048004 */   lui       $a0, %hi(D_800433DC)
  .L80008CB4:
    /* 98B4 80008CB4 0C001FA0 */  jal        func_80007E80
    /* 98B8 80008CB8 00000000 */   nop
    /* 98BC 80008CBC 8FAF0024 */  lw         $t7, 0x24($sp)
    /* 98C0 80008CC0 ADE2001C */  sw         $v0, 0x1C($t7)
    /* 98C4 80008CC4 0C002000 */  jal        func_80008000
    /* 98C8 80008CC8 AFA20028 */   sw        $v0, 0x28($sp)
    /* 98CC 80008CCC 8FA80028 */  lw         $t0, 0x28($sp)
    /* 98D0 80008CD0 3C0A8005 */  lui        $t2, %hi(D_8004A99C)
    /* 98D4 80008CD4 24430008 */  addiu      $v1, $v0, 0x8
    /* 98D8 80008CD8 254AA99C */  addiu      $t2, $t2, %lo(D_8004A99C)
    /* 98DC 80008CDC AD0301B8 */  sw         $v1, 0x1B8($t0)
    /* 98E0 80008CE0 8D580000 */  lw         $t8, 0x0($t2)
    /* 98E4 80008CE4 3C098004 */  lui        $t1, %hi(D_80040E80)
    /* 98E8 80008CE8 25290E80 */  addiu      $t1, $t1, %lo(D_80040E80)
    /* 98EC 80008CEC AD1801BC */  sw         $t8, 0x1BC($t0)
    /* 98F0 80008CF0 8D590000 */  lw         $t9, 0x0($t2)
    /* 98F4 80008CF4 8D250000 */  lw         $a1, 0x0($t1)
    /* 98F8 80008CF8 240E0033 */  addiu      $t6, $zero, 0x33
    /* 98FC 80008CFC 001958C2 */  srl        $t3, $t9, 3
    /* 9900 80008D00 000B60C0 */  sll        $t4, $t3, 3
    /* 9904 80008D04 006C6821 */  addu       $t5, $v1, $t4
    /* 9908 80008D08 24AF0001 */  addiu      $t7, $a1, 0x1
    /* 990C 80008D0C AD2F0000 */  sw         $t7, 0x0($t1)
    /* 9910 80008D10 AFAD0010 */  sw         $t5, 0x10($sp)
    /* 9914 80008D14 AFAE0014 */  sw         $t6, 0x14($sp)
    /* 9918 80008D18 8FA70030 */  lw         $a3, 0x30($sp)
    /* 991C 80008D1C 8FA60034 */  lw         $a2, 0x34($sp)
    /* 9920 80008D20 0C00D280 */  jal        osCreateThread
    /* 9924 80008D24 25040008 */   addiu     $a0, $t0, 0x8
    /* 9928 80008D28 8FA80028 */  lw         $t0, 0x28($sp)
    /* 992C 80008D2C 3C19FEDC */  lui        $t9, (0xFEDCBA98 >> 16)
    /* 9930 80008D30 3C098004 */  lui        $t1, %hi(D_80040E80)
    /* 9934 80008D34 8D0B01B8 */  lw         $t3, 0x1B8($t0)
    /* 9938 80008D38 3739BA98 */  ori        $t9, $t9, (0xFEDCBA98 & 0xFFFF)
    /* 993C 80008D3C 24180000 */  addiu      $t8, $zero, 0x0
    /* 9940 80008D40 25290E80 */  addiu      $t1, $t1, %lo(D_80040E80)
    /* 9944 80008D44 AD780038 */  sw         $t8, 0x38($t3)
    /* 9948 80008D48 AD79003C */  sw         $t9, 0x3C($t3)
    /* 994C 80008D4C 8D2C0000 */  lw         $t4, 0x0($t1)
    /* 9950 80008D50 3C010131 */  lui        $at, (0x1312D00 >> 16)
    /* 9954 80008D54 34212D00 */  ori        $at, $at, (0x1312D00 & 0xFFFF)
    /* 9958 80008D58 0181082A */  slt        $at, $t4, $at
    /* 995C 80008D5C 1420000A */  bnez       $at, .L80008D88
    /* 9960 80008D60 3C0D0098 */   lui       $t5, (0x989680 >> 16)
    /* 9964 80008D64 35AD9680 */  ori        $t5, $t5, (0x989680 & 0xFFFF)
    /* 9968 80008D68 10000007 */  b          .L80008D88
    /* 996C 80008D6C AD2D0000 */   sw        $t5, 0x0($t1)
  .L80008D70:
    /* 9970 80008D70 10000005 */  b          .L80008D88
    /* 9974 80008D74 AC44001C */   sw        $a0, 0x1C($v0)
  .L80008D78:
    /* 9978 80008D78 0C0097C9 */  jal        error_printf
    /* 997C 80008D7C 248433DC */   addiu     $a0, $a0, %lo(D_800433DC)
  .L80008D80:
    /* 9980 80008D80 1000FFFF */  b          .L80008D80
    /* 9984 80008D84 00000000 */   nop
  .L80008D88:
    /* 9988 80008D88 0C002046 */  jal        func_80008118
    /* 998C 80008D8C 8FA40024 */   lw        $a0, 0x24($sp)
    /* 9990 80008D90 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 9994 80008D94 8FA20024 */  lw         $v0, 0x24($sp)
    /* 9998 80008D98 27BD0030 */  addiu      $sp, $sp, 0x30
    /* 999C 80008D9C 03E00008 */  jr         $ra
    /* 99A0 80008DA0 00000000 */   nop
endlabel omCreateProcess
