.section .late_rodata
.align 3
nonmatching D_80044358

dlabel D_80044358
    /* 44F58 80044358 3FE62E42FEFA39EF */ .double 0.693147180559945286
enddlabel D_80044358

.align 3
nonmatching D_80044360

dlabel D_80044360
    /* 44F60 80044360 40EFFFE000000000 */ .double 65535
    /* 44F68 80044368 0000000000000000 */ .double 0
enddlabel D_80044360


.section .text
/* Generated by spimdisasm 1.42.0 */

nonmatching func_8002CD54, 0x1E4

glabel func_8002CD54
    /* 2D954 8002CD54 27BDFF48 */  addiu      $sp, $sp, -0xB8
    /* 2D958 8002CD58 8FA400C8 */  lw         $a0, 0xC8($sp)
    /* 2D95C 8002CD5C F7B40010 */  sdc1       $f20, 0x10($sp)
    /* 2D960 8002CD60 46206506 */  mov.d      $f20, $f12
    /* 2D964 8002CD64 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 2D968 8002CD68 1480000C */  bnez       $a0, .L8002CD9C
    /* 2D96C 8002CD6C F7B60018 */   sdc1      $f22, 0x18($sp)
    /* 2D970 8002CD70 462E603E */  c.le.d     $f12, $f14
    /* 2D974 8002CD74 340EFFFF */  ori        $t6, $zero, 0xFFFF
    /* 2D978 8002CD78 8FAF00CC */  lw         $t7, 0xCC($sp)
    /* 2D97C 8002CD7C 8FB800CC */  lw         $t8, 0xCC($sp)
    /* 2D980 8002CD80 45000004 */  bc1f       .L8002CD94
    /* 2D984 8002CD84 00001025 */   or        $v0, $zero, $zero
    /* 2D988 8002CD88 A5EE0000 */  sh         $t6, 0x0($t7)
    /* 2D98C 8002CD8C 10000065 */  b          .L8002CF24
    /* 2D990 8002CD90 24027FFF */   addiu     $v0, $zero, 0x7FFF
  .L8002CD94:
    /* 2D994 8002CD94 10000063 */  b          .L8002CF24
    /* 2D998 8002CD98 A7000000 */   sh        $zero, 0x0($t8)
  .L8002CD9C:
    /* 2D99C 8002CD9C 3C013FF0 */  lui        $at, (0x3FF00000 >> 16)
    /* 2D9A0 8002CDA0 4481B800 */  mtc1       $at, $f23
    /* 2D9A4 8002CDA4 4480B000 */  mtc1       $zero, $f22
    /* 2D9A8 8002CDA8 3C088004 */  lui        $t0, %hi(D_80042BB0)
    /* 2D9AC 8002CDAC 44802800 */  mtc1       $zero, $f5
    /* 2D9B0 8002CDB0 4636703C */  c.lt.d     $f14, $f22
    /* 2D9B4 8002CDB4 44802000 */  mtc1       $zero, $f4
    /* 2D9B8 8002CDB8 25082BB0 */  addiu      $t0, $t0, %lo(D_80042BB0)
    /* 2D9BC 8002CDBC 250B003C */  addiu      $t3, $t0, 0x3C
    /* 2D9C0 8002CDC0 45000002 */  bc1f       .L8002CDCC
    /* 2D9C4 8002CDC4 27B90038 */   addiu     $t9, $sp, 0x38
    /* 2D9C8 8002CDC8 4620B386 */  mov.d      $f14, $f22
  .L8002CDCC:
    /* 2D9CC 8002CDCC 4624A03E */  c.le.d     $f20, $f4
    /* 2D9D0 8002CDD0 44843000 */  mtc1       $a0, $f6
    /* 2D9D4 8002CDD4 3C013FF0 */  lui        $at, (0x3FF00000 >> 16)
    /* 2D9D8 8002CDD8 45000004 */  bc1f       .L8002CDEC
    /* 2D9DC 8002CDDC 46803221 */   cvt.d.w   $f8, $f6
    /* 2D9E0 8002CDE0 4481A800 */  mtc1       $at, $f21
    /* 2D9E4 8002CDE4 4480A000 */  mtc1       $zero, $f20
    /* 2D9E8 8002CDE8 00000000 */  nop
  .L8002CDEC:
    /* 2D9EC 8002CDEC 8D0A0000 */  lw         $t2, 0x0($t0)
    /* 2D9F0 8002CDF0 2508000C */  addiu      $t0, $t0, 0xC
    /* 2D9F4 8002CDF4 2739000C */  addiu      $t9, $t9, 0xC
    /* 2D9F8 8002CDF8 AF2AFFF4 */  sw         $t2, -0xC($t9)
    /* 2D9FC 8002CDFC 8D09FFF8 */  lw         $t1, -0x8($t0)
    /* 2DA00 8002CE00 AF29FFF8 */  sw         $t1, -0x8($t9)
    /* 2DA04 8002CE04 8D0AFFFC */  lw         $t2, -0x4($t0)
    /* 2DA08 8002CE08 150BFFF8 */  bne        $t0, $t3, .L8002CDEC
    /* 2DA0C 8002CE0C AF2AFFFC */   sw        $t2, -0x4($t9)
    /* 2DA10 8002CE10 8D0A0000 */  lw         $t2, 0x0($t0)
    /* 2DA14 8002CE14 4628B303 */  div.d      $f12, $f22, $f8
    /* 2DA18 8002CE18 2406001E */  addiu      $a2, $zero, 0x1E
    /* 2DA1C 8002CE1C AF2A0000 */  sw         $t2, 0x0($t9)
    /* 2DA20 8002CE20 0C00B34B */  jal        _ldexpf
    /* 2DA24 8002CE24 F7AE00C0 */   sdc1      $f14, 0xC0($sp)
    /* 2DA28 8002CE28 4620028D */  trunc.w.d  $f10, $f0
    /* 2DA2C 8002CE2C D7AE00C0 */  ldc1       $f14, 0xC0($sp)
    /* 2DA30 8002CE30 27A60080 */  addiu      $a2, $sp, 0x80
    /* 2DA34 8002CE34 44025000 */  mfc1       $v0, $f10
    /* 2DA38 8002CE38 46347303 */  div.d      $f12, $f14, $f20
    /* 2DA3C 8002CE3C 0C00B310 */  jal        _frexpf
    /* 2DA40 8002CE40 AFA20084 */   sw        $v0, 0x84($sp)
    /* 2DA44 8002CE44 46200306 */  mov.d      $f12, $f0
    /* 2DA48 8002CE48 0C00B34B */  jal        _ldexpf
    /* 2DA4C 8002CE4C 24060004 */   addiu     $a2, $zero, 0x4
    /* 2DA50 8002CE50 4620048D */  trunc.w.d  $f18, $f0
    /* 2DA54 8002CE54 8FAB0080 */  lw         $t3, 0x80($sp)
    /* 2DA58 8002CE58 3C018004 */  lui        $at, %hi(D_80044358)
    /* 2DA5C 8002CE5C 44806000 */  mtc1       $zero, $f12
    /* 2DA60 8002CE60 440E9000 */  mfc1       $t6, $f18
    /* 2DA64 8002CE64 448B3000 */  mtc1       $t3, $f6
    /* 2DA68 8002CE68 D4324358 */  ldc1       $f18, %lo(D_80044358)($at)
    /* 2DA6C 8002CE6C 000E78C0 */  sll        $t7, $t6, 3
    /* 2DA70 8002CE70 46803221 */  cvt.d.w    $f8, $f6
    /* 2DA74 8002CE74 03AFC021 */  addu       $t8, $sp, $t7
    /* 2DA78 8002CE78 D704FFF8 */  ldc1       $f4, -0x8($t8)
    /* 2DA7C 8002CE7C 3C013FF0 */  lui        $at, (0x3FF00000 >> 16)
    /* 2DA80 8002CE80 44816800 */  mtc1       $at, $f13
    /* 2DA84 8002CE84 46282280 */  add.d      $f10, $f4, $f8
    /* 2DA88 8002CE88 2406001E */  addiu      $a2, $zero, 0x1E
    /* 2DA8C 8002CE8C 46325382 */  mul.d      $f14, $f10, $f18
    /* 2DA90 8002CE90 0C00B34B */  jal        _ldexpf
    /* 2DA94 8002CE94 F7AE00A0 */   sdc1      $f14, 0xA0($sp)
    /* 2DA98 8002CE98 D7AE00A0 */  ldc1       $f14, 0xA0($sp)
    /* 2DA9C 8002CE9C 8FA20084 */  lw         $v0, 0x84($sp)
    /* 2DAA0 8002CEA0 4620B306 */  mov.d      $f12, $f22
    /* 2DAA4 8002CEA4 46207383 */  div.d      $f14, $f14, $f0
    /* 2DAA8 8002CEA8 10400009 */  beqz       $v0, .L8002CED0
    /* 2DAAC 8002CEAC 462EB080 */   add.d     $f2, $f22, $f14
    /* 2DAB0 8002CEB0 30480001 */  andi       $t0, $v0, 0x1
  .L8002CEB4:
    /* 2DAB4 8002CEB4 11000003 */  beqz       $t0, .L8002CEC4
    /* 2DAB8 8002CEB8 00021043 */   sra       $v0, $v0, 1
    /* 2DABC 8002CEBC 46226302 */  mul.d      $f12, $f12, $f2
    /* 2DAC0 8002CEC0 00000000 */  nop
  .L8002CEC4:
    /* 2DAC4 8002CEC4 46221082 */  mul.d      $f2, $f2, $f2
    /* 2DAC8 8002CEC8 5440FFFA */  bnel       $v0, $zero, .L8002CEB4
    /* 2DACC 8002CECC 30480001 */   andi      $t0, $v0, 0x1
  .L8002CED0:
    /* 2DAD0 8002CED0 462C6002 */  mul.d      $f0, $f12, $f12
    /* 2DAD4 8002CED4 3C018004 */  lui        $at, %hi(D_80044360)
    /* 2DAD8 8002CED8 8FAC00CC */  lw         $t4, 0xCC($sp)
    /* 2DADC 8002CEDC 46200082 */  mul.d      $f2, $f0, $f0
    /* 2DAE0 8002CEE0 00000000 */  nop
    /* 2DAE4 8002CEE4 46221302 */  mul.d      $f12, $f2, $f2
    /* 2DAE8 8002CEE8 4620618D */  trunc.w.d  $f6, $f12
    /* 2DAEC 8002CEEC 44033000 */  mfc1       $v1, $f6
    /* 2DAF0 8002CEF0 D4264360 */  ldc1       $f6, %lo(D_80044360)($at)
    /* 2DAF4 8002CEF4 00031C00 */  sll        $v1, $v1, 16
    /* 2DAF8 8002CEF8 00031403 */  sra        $v0, $v1, 16
    /* 2DAFC 8002CEFC 44822000 */  mtc1       $v0, $f4
    /* 2DB00 8002CF00 00000000 */  nop
    /* 2DB04 8002CF04 46802220 */  cvt.s.w    $f8, $f4
    /* 2DB08 8002CF08 460042A1 */  cvt.d.s    $f10, $f8
    /* 2DB0C 8002CF0C 462A6481 */  sub.d      $f18, $f12, $f10
    /* 2DB10 8002CF10 46269102 */  mul.d      $f4, $f18, $f6
    /* 2DB14 8002CF14 4620220D */  trunc.w.d  $f8, $f4
    /* 2DB18 8002CF18 440A4000 */  mfc1       $t2, $f8
    /* 2DB1C 8002CF1C 00000000 */  nop
    /* 2DB20 8002CF20 A58A0000 */  sh         $t2, 0x0($t4)
  .L8002CF24:
    /* 2DB24 8002CF24 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 2DB28 8002CF28 D7B40010 */  ldc1       $f20, 0x10($sp)
    /* 2DB2C 8002CF2C D7B60018 */  ldc1       $f22, 0x18($sp)
    /* 2DB30 8002CF30 03E00008 */  jr         $ra
    /* 2DB34 8002CF34 27BD00B8 */   addiu     $sp, $sp, 0xB8
endlabel func_8002CD54
