.section .late_rodata
nonmatching jtbl_802E3860_734A60

dlabel jtbl_802E3860_734A60
    /* 734A60 802E3860 802D8C20 */ .word .L802D8C20_729E20
    /* 734A64 802E3864 802D8C2C */ .word .L802D8C2C_729E2C
    /* 734A68 802E3868 802D8C38 */ .word .L802D8C38_729E38
    /* 734A6C 802E386C 802D8C58 */ .word .L802D8C58_729E58
    /* 734A70 802E3870 802D8C78 */ .word .L802D8C78_729E78
    /* 734A74 802E3874 00000000 */ .word 0x00000000
enddlabel jtbl_802E3860_734A60


.section .text
/* Generated by spimdisasm 1.42.1 */

nonmatching func_802D8BB8_729DB8, 0xEC

glabel func_802D8BB8_729DB8
    /* 729DB8 802D8BB8 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* 729DBC 802D8BBC AFBF001C */  sw         $ra, 0x1C($sp)
    /* 729DC0 802D8BC0 AFB00018 */  sw         $s0, 0x18($sp)
    /* 729DC4 802D8BC4 8C820058 */  lw         $v0, 0x58($a0)
    /* 729DC8 802D8BC8 3C05802E */  lui        $a1, %hi(func_802D8AA0_729CA0)
    /* 729DCC 802D8BCC 00808025 */  or         $s0, $a0, $zero
    /* 729DD0 802D8BD0 944E0008 */  lhu        $t6, 0x8($v0)
    /* 729DD4 802D8BD4 AC4000B0 */  sw         $zero, 0xB0($v0)
    /* 729DD8 802D8BD8 24A58AA0 */  addiu      $a1, $a1, %lo(func_802D8AA0_729CA0)
    /* 729DDC 802D8BDC 35D80200 */  ori        $t8, $t6, 0x200
    /* 729DE0 802D8BE0 37190800 */  ori        $t9, $t8, 0x800
    /* 729DE4 802D8BE4 A4580008 */  sh         $t8, 0x8($v0)
    /* 729DE8 802D8BE8 A4590008 */  sh         $t9, 0x8($v0)
    /* 729DEC 802D8BEC 0C0D7B64 */  jal        Pokemon_StartAuxProc
    /* 729DF0 802D8BF0 AFA20020 */   sw        $v0, 0x20($sp)
    /* 729DF4 802D8BF4 8FA20020 */  lw         $v0, 0x20($sp)
    /* 729DF8 802D8BF8 8C480088 */  lw         $t0, 0x88($v0)
    /* 729DFC 802D8BFC 2509FFFF */  addiu      $t1, $t0, -0x1
    /* 729E00 802D8C00 2D210005 */  sltiu      $at, $t1, 0x5
    /* 729E04 802D8C04 1020001E */  beqz       $at, .L802D8C80_729E80
    /* 729E08 802D8C08 00094880 */   sll       $t1, $t1, 2
    /* 729E0C 802D8C0C 3C01802E */  lui        $at, %hi(jtbl_802E3860_734A60)
    /* 729E10 802D8C10 00290821 */  addu       $at, $at, $t1
    /* 729E14 802D8C14 8C293860 */  lw         $t1, %lo(jtbl_802E3860_734A60)($at)
    /* 729E18 802D8C18 01200008 */  jr         $t1
    /* 729E1C 802D8C1C 00000000 */   nop
  .L802D8C20_729E20:
    /* 729E20 802D8C20 3C01802E */  lui        $at, %hi(D_802E1A20_732C20)
    /* 729E24 802D8C24 10000016 */  b          .L802D8C80_729E80
    /* 729E28 802D8C28 AC301A20 */   sw        $s0, %lo(D_802E1A20_732C20)($at)
  .L802D8C2C_729E2C:
    /* 729E2C 802D8C2C 3C01802E */  lui        $at, %hi(D_802E1A24_732C24)
    /* 729E30 802D8C30 10000013 */  b          .L802D8C80_729E80
    /* 729E34 802D8C34 AC301A24 */   sw        $s0, %lo(D_802E1A24_732C24)($at)
  .L802D8C38_729E38:
    /* 729E38 802D8C38 3C01802E */  lui        $at, %hi(D_802E1A28_732C28)
    /* 729E3C 802D8C3C 3C05802E */  lui        $a1, %hi(func_802D9900_72AB00)
    /* 729E40 802D8C40 AC301A28 */  sw         $s0, %lo(D_802E1A28_732C28)($at)
    /* 729E44 802D8C44 24A59900 */  addiu      $a1, $a1, %lo(func_802D9900_72AB00)
    /* 729E48 802D8C48 0C0D7B16 */  jal        Pokemon_SetState
    /* 729E4C 802D8C4C 02002025 */   or        $a0, $s0, $zero
    /* 729E50 802D8C50 1000000B */  b          .L802D8C80_729E80
    /* 729E54 802D8C54 00000000 */   nop
  .L802D8C58_729E58:
    /* 729E58 802D8C58 3C01802E */  lui        $at, %hi(D_802E1A2C_732C2C)
    /* 729E5C 802D8C5C 3C05802E */  lui        $a1, %hi(func_802D9950_72AB50)
    /* 729E60 802D8C60 AC301A2C */  sw         $s0, %lo(D_802E1A2C_732C2C)($at)
    /* 729E64 802D8C64 24A59950 */  addiu      $a1, $a1, %lo(func_802D9950_72AB50)
    /* 729E68 802D8C68 0C0D7B16 */  jal        Pokemon_SetState
    /* 729E6C 802D8C6C 02002025 */   or        $a0, $s0, $zero
    /* 729E70 802D8C70 10000003 */  b          .L802D8C80_729E80
    /* 729E74 802D8C74 00000000 */   nop
  .L802D8C78_729E78:
    /* 729E78 802D8C78 3C01802E */  lui        $at, %hi(D_802E1A30_732C30)
    /* 729E7C 802D8C7C AC301A30 */  sw         $s0, %lo(D_802E1A30_732C30)($at)
  .L802D8C80_729E80:
    /* 729E80 802D8C80 3C05802E */  lui        $a1, %hi(func_802D8CA4_729EA4)
    /* 729E84 802D8C84 24A58CA4 */  addiu      $a1, $a1, %lo(func_802D8CA4_729EA4)
    /* 729E88 802D8C88 0C0D7B16 */  jal        Pokemon_SetState
    /* 729E8C 802D8C8C 02002025 */   or        $a0, $s0, $zero
    /* 729E90 802D8C90 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 729E94 802D8C94 8FB00018 */  lw         $s0, 0x18($sp)
    /* 729E98 802D8C98 27BD0030 */  addiu      $sp, $sp, 0x30
    /* 729E9C 802D8C9C 03E00008 */  jr         $ra
    /* 729EA0 802D8CA0 00000000 */   nop
endlabel func_802D8BB8_729DB8
