.section .late_rodata
nonmatching D_beach_802CE1A4

dlabel D_beach_802CE1A4
    /* 566214 802CE1A4 40C90FDB */ .float 6.283185482
enddlabel D_beach_802CE1A4

nonmatching D_beach_802CE1A8

dlabel D_beach_802CE1A8
    /* 566218 802CE1A8 3E0EFA35 */ .float 0.1396263391
    /* 56621C 802CE1AC 00000000 */ .float 0
enddlabel D_beach_802CE1A8


.section .text
/* Generated by spimdisasm 1.42.1 */

nonmatching func_beach_802CBA48, 0xEC

glabel func_beach_802CBA48
    /* 563AB8 802CBA48 27BDFFB0 */  addiu      $sp, $sp, -0x50
    /* 563ABC 802CBA4C AFBF002C */  sw         $ra, 0x2C($sp)
    /* 563AC0 802CBA50 AFB10028 */  sw         $s1, 0x28($sp)
    /* 563AC4 802CBA54 AFB00024 */  sw         $s0, 0x24($sp)
    /* 563AC8 802CBA58 F7B60018 */  sdc1       $f22, 0x18($sp)
    /* 563ACC 802CBA5C F7B40010 */  sdc1       $f20, 0x10($sp)
    /* 563AD0 802CBA60 8C910058 */  lw         $s1, 0x58($a0)
    /* 563AD4 802CBA64 8C900048 */  lw         $s0, 0x48($a0)
    /* 563AD8 802CBA68 0C002F2A */  jal        ohWait
    /* 563ADC 802CBA6C 2404003C */   addiu     $a0, $zero, 0x3C
    /* 563AE0 802CBA70 3C063F7F */  lui        $a2, (0x3F7FFF58 >> 16)
    /* 563AE4 802CBA74 34C6FF58 */  ori        $a2, $a2, (0x3F7FFF58 & 0xFFFF)
    /* 563AE8 802CBA78 27A40034 */  addiu      $a0, $sp, 0x34
    /* 563AEC 802CBA7C 0C007F3A */  jal        GetInterpolatedVelocity
    /* 563AF0 802CBA80 8E2500E8 */   lw        $a1, 0xE8($s1)
    /* 563AF4 802CBA84 C7AC0034 */  lwc1       $f12, 0x34($sp)
    /* 563AF8 802CBA88 0C0066AF */  jal        atan2f
    /* 563AFC 802CBA8C C7AE003C */   lwc1      $f14, 0x3C($sp)
    /* 563B00 802CBA90 3C01802D */  lui        $at, %hi(D_beach_802CE1A4)
    /* 563B04 802CBA94 C42CE1A4 */  lwc1       $f12, %lo(D_beach_802CE1A4)($at)
    /* 563B08 802CBA98 3C01802D */  lui        $at, %hi(D_beach_802CE1A8)
    /* 563B0C 802CBA9C C436E1A8 */  lwc1       $f22, %lo(D_beach_802CE1A8)($at)
    /* 563B10 802CBAA0 460C0103 */  div.s      $f4, $f0, $f12
    /* 563B14 802CBAA4 02002025 */  or         $a0, $s0, $zero
    /* 563B18 802CBAA8 4406B000 */  mfc1       $a2, $f22
    /* 563B1C 802CBAAC 4600218D */  trunc.w.s  $f6, $f4
    /* 563B20 802CBAB0 440F3000 */  mfc1       $t7, $f6
    /* 563B24 802CBAB4 00000000 */  nop
    /* 563B28 802CBAB8 448F4000 */  mtc1       $t7, $f8
    /* 563B2C 802CBABC 00000000 */  nop
    /* 563B30 802CBAC0 468042A0 */  cvt.s.w    $f10, $f8
    /* 563B34 802CBAC4 460C5402 */  mul.s      $f16, $f10, $f12
    /* 563B38 802CBAC8 46100501 */  sub.s      $f20, $f0, $f16
    /* 563B3C 802CBACC 4405A000 */  mfc1       $a1, $f20
    /* 563B40 802CBAD0 0C0D83F2 */  jal        Pokemon_Turn
    /* 563B44 802CBAD4 00000000 */   nop
    /* 563B48 802CBAD8 5440000A */  bnel       $v0, $zero, .Lbeach_802CBB04
    /* 563B4C 802CBADC 8E38008C */   lw        $t8, 0x8C($s1)
  .Lbeach_802CBAE0:
    /* 563B50 802CBAE0 0C002F2A */  jal        ohWait
    /* 563B54 802CBAE4 24040001 */   addiu     $a0, $zero, 0x1
    /* 563B58 802CBAE8 4405A000 */  mfc1       $a1, $f20
    /* 563B5C 802CBAEC 4406B000 */  mfc1       $a2, $f22
    /* 563B60 802CBAF0 0C0D83F2 */  jal        Pokemon_Turn
    /* 563B64 802CBAF4 02002025 */   or        $a0, $s0, $zero
    /* 563B68 802CBAF8 1040FFF9 */  beqz       $v0, .Lbeach_802CBAE0
    /* 563B6C 802CBAFC 00000000 */   nop
    /* 563B70 802CBB00 8E38008C */  lw         $t8, 0x8C($s1)
  .Lbeach_802CBB04:
    /* 563B74 802CBB04 AE200094 */  sw         $zero, 0x94($s1)
    /* 563B78 802CBB08 00002025 */  or         $a0, $zero, $zero
    /* 563B7C 802CBB0C 37190002 */  ori        $t9, $t8, 0x2
    /* 563B80 802CBB10 0C0023CB */  jal        omEndProcess
    /* 563B84 802CBB14 AE39008C */   sw        $t9, 0x8C($s1)
    /* 563B88 802CBB18 8FBF002C */  lw         $ra, 0x2C($sp)
    /* 563B8C 802CBB1C D7B40010 */  ldc1       $f20, 0x10($sp)
    /* 563B90 802CBB20 D7B60018 */  ldc1       $f22, 0x18($sp)
    /* 563B94 802CBB24 8FB00024 */  lw         $s0, 0x24($sp)
    /* 563B98 802CBB28 8FB10028 */  lw         $s1, 0x28($sp)
    /* 563B9C 802CBB2C 03E00008 */  jr         $ra
    /* 563BA0 802CBB30 27BD0050 */   addiu     $sp, $sp, 0x50
endlabel func_beach_802CBA48
