.section .late_rodata
.align 3
nonmatching D_80044B88

dlabel D_80044B88
    /* 45788 80044B88 4197D78400000000 */ .double 100000000
enddlabel D_80044B88


.section .text
/* Generated by spimdisasm 1.42.1 */

nonmatching _Ldtob, 0x54C

glabel _Ldtob
    /* 3CED0 8003C2D0 27BDFF30 */  addiu      $sp, $sp, -0xD0
    /* 3CED4 8003C2D4 AFBF003C */  sw         $ra, 0x3C($sp)
    /* 3CED8 8003C2D8 AFB50038 */  sw         $s5, 0x38($sp)
    /* 3CEDC 8003C2DC AFB40034 */  sw         $s4, 0x34($sp)
    /* 3CEE0 8003C2E0 AFB30030 */  sw         $s3, 0x30($sp)
    /* 3CEE4 8003C2E4 AFB2002C */  sw         $s2, 0x2C($sp)
    /* 3CEE8 8003C2E8 AFB10028 */  sw         $s1, 0x28($sp)
    /* 3CEEC 8003C2EC AFB00024 */  sw         $s0, 0x24($sp)
    /* 3CEF0 8003C2F0 F7B40018 */  sdc1       $f20, 0x18($sp)
    /* 3CEF4 8003C2F4 AFA400D0 */  sw         $a0, 0xD0($sp)
    /* 3CEF8 8003C2F8 AFA500D4 */  sw         $a1, 0xD4($sp)
    /* 3CEFC 8003C2FC 8C820024 */  lw         $v0, 0x24($a0)
    /* 3CF00 8003C300 27B500B0 */  addiu      $s5, $sp, 0xB0
    /* 3CF04 8003C304 D4940000 */  ldc1       $f20, 0x0($a0)
    /* 3CF08 8003C308 04410003 */  bgez       $v0, .L8003C318
    /* 3CF0C 8003C30C 240F0006 */   addiu     $t7, $zero, 0x6
    /* 3CF10 8003C310 1000000C */  b          .L8003C344
    /* 3CF14 8003C314 AC8F0024 */   sw        $t7, 0x24($a0)
  .L8003C318:
    /* 3CF18 8003C318 1440000A */  bnez       $v0, .L8003C344
    /* 3CF1C 8003C31C 93B800D7 */   lbu       $t8, 0xD7($sp)
    /* 3CF20 8003C320 24010067 */  addiu      $at, $zero, 0x67
    /* 3CF24 8003C324 13010004 */  beq        $t8, $at, .L8003C338
    /* 3CF28 8003C328 AFB80048 */   sw        $t8, 0x48($sp)
    /* 3CF2C 8003C32C 24010047 */  addiu      $at, $zero, 0x47
    /* 3CF30 8003C330 57010005 */  bnel       $t8, $at, .L8003C348
    /* 3CF34 8003C334 8FAE00D0 */   lw        $t6, 0xD0($sp)
  .L8003C338:
    /* 3CF38 8003C338 8FAF00D0 */  lw         $t7, 0xD0($sp)
    /* 3CF3C 8003C33C 24190001 */  addiu      $t9, $zero, 0x1
    /* 3CF40 8003C340 ADF90024 */  sw         $t9, 0x24($t7)
  .L8003C344:
    /* 3CF44 8003C344 8FAE00D0 */  lw         $t6, 0xD0($sp)
  .L8003C348:
    /* 3CF48 8003C348 240107FF */  addiu      $at, $zero, 0x7FF
    /* 3CF4C 8003C34C 95C40000 */  lhu        $a0, 0x0($t6)
    /* 3CF50 8003C350 30837FF0 */  andi       $v1, $a0, 0x7FF0
    /* 3CF54 8003C354 0003C103 */  sra        $t8, $v1, 4
    /* 3CF58 8003C358 0018CC00 */  sll        $t9, $t8, 16
    /* 3CF5C 8003C35C 00191C03 */  sra        $v1, $t9, 16
    /* 3CF60 8003C360 14610018 */  bne        $v1, $at, .L8003C3C4
    /* 3CF64 8003C364 00000000 */   nop
    /* 3CF68 8003C368 A7A0009A */  sh         $zero, 0x9A($sp)
    /* 3CF6C 8003C36C 95D80000 */  lhu        $t8, 0x0($t6)
    /* 3CF70 8003C370 24030002 */  addiu      $v1, $zero, 0x2
    /* 3CF74 8003C374 00031400 */  sll        $v0, $v1, 16
    /* 3CF78 8003C378 3319000F */  andi       $t9, $t8, 0xF
    /* 3CF7C 8003C37C 5720000A */  bnel       $t9, $zero, .L8003C3A8
    /* 3CF80 8003C380 00027C03 */   sra       $t7, $v0, 16
    /* 3CF84 8003C384 95CF0002 */  lhu        $t7, 0x2($t6)
    /* 3CF88 8003C388 55E00007 */  bnel       $t7, $zero, .L8003C3A8
    /* 3CF8C 8003C38C 00027C03 */   sra       $t7, $v0, 16
    /* 3CF90 8003C390 95D80004 */  lhu        $t8, 0x4($t6)
    /* 3CF94 8003C394 57000004 */  bnel       $t8, $zero, .L8003C3A8
    /* 3CF98 8003C398 00027C03 */   sra       $t7, $v0, 16
    /* 3CF9C 8003C39C 95D90006 */  lhu        $t9, 0x6($t6)
    /* 3CFA0 8003C3A0 13200003 */  beqz       $t9, .L8003C3B0
    /* 3CFA4 8003C3A4 00027C03 */   sra       $t7, $v0, 16
  .L8003C3A8:
    /* 3CFA8 8003C3A8 10000014 */  b          .L8003C3FC
    /* 3CFAC 8003C3AC 01E01025 */   or        $v0, $t7, $zero
  .L8003C3B0:
    /* 3CFB0 8003C3B0 24030001 */  addiu      $v1, $zero, 0x1
    /* 3CFB4 8003C3B4 00031400 */  sll        $v0, $v1, 16
    /* 3CFB8 8003C3B8 00027C03 */  sra        $t7, $v0, 16
    /* 3CFBC 8003C3BC 1000000F */  b          .L8003C3FC
    /* 3CFC0 8003C3C0 01E01025 */   or        $v0, $t7, $zero
  .L8003C3C4:
    /* 3CFC4 8003C3C4 18600008 */  blez       $v1, .L8003C3E8
    /* 3CFC8 8003C3C8 3098800F */   andi      $t8, $a0, 0x800F
    /* 3CFCC 8003C3CC 8FB900D0 */  lw         $t9, 0xD0($sp)
    /* 3CFD0 8003C3D0 370E3FF0 */  ori        $t6, $t8, 0x3FF0
    /* 3CFD4 8003C3D4 246FFC02 */  addiu      $t7, $v1, -0x3FE
    /* 3CFD8 8003C3D8 A72E0000 */  sh         $t6, 0x0($t9)
    /* 3CFDC 8003C3DC A7AF009A */  sh         $t7, 0x9A($sp)
    /* 3CFE0 8003C3E0 10000006 */  b          .L8003C3FC
    /* 3CFE4 8003C3E4 2402FFFF */   addiu     $v0, $zero, -0x1
  .L8003C3E8:
    /* 3CFE8 8003C3E8 04610003 */  bgez       $v1, .L8003C3F8
    /* 3CFEC 8003C3EC 00001025 */   or        $v0, $zero, $zero
    /* 3CFF0 8003C3F0 10000002 */  b          .L8003C3FC
    /* 3CFF4 8003C3F4 24020002 */   addiu     $v0, $zero, 0x2
  .L8003C3F8:
    /* 3CFF8 8003C3F8 A7A0009A */  sh         $zero, 0x9A($sp)
  .L8003C3FC:
    /* 3CFFC 8003C3FC 18400012 */  blez       $v0, .L8003C448
    /* 3D000 8003C400 0002C400 */   sll       $t8, $v0, 16
    /* 3D004 8003C404 0002C400 */  sll        $t8, $v0, 16
    /* 3D008 8003C408 00187403 */  sra        $t6, $t8, 16
    /* 3D00C 8003C40C 24010002 */  addiu      $at, $zero, 0x2
    /* 3D010 8003C410 15C10004 */  bne        $t6, $at, .L8003C424
    /* 3D014 8003C414 8FB900D0 */   lw        $t9, 0xD0($sp)
    /* 3D018 8003C418 3C058004 */  lui        $a1, %hi(D_80044B78)
    /* 3D01C 8003C41C 10000003 */  b          .L8003C42C
    /* 3D020 8003C420 24A54B78 */   addiu     $a1, $a1, %lo(D_80044B78)
  .L8003C424:
    /* 3D024 8003C424 3C058004 */  lui        $a1, %hi(D_80044B7C)
    /* 3D028 8003C428 24A54B7C */  addiu      $a1, $a1, %lo(D_80044B7C)
  .L8003C42C:
    /* 3D02C 8003C42C 240F0003 */  addiu      $t7, $zero, 0x3
    /* 3D030 8003C430 AF2F0014 */  sw         $t7, 0x14($t9)
    /* 3D034 8003C434 8F240008 */  lw         $a0, 0x8($t9)
    /* 3D038 8003C438 0C00DD98 */  jal        memcpy
    /* 3D03C 8003C43C 24060003 */   addiu     $a2, $zero, 0x3
    /* 3D040 8003C440 100000ED */  b          .L8003C7F8
    /* 3D044 8003C444 8FBF003C */   lw        $ra, 0x3C($sp)
  .L8003C448:
    /* 3D048 8003C448 00187403 */  sra        $t6, $t8, 16
    /* 3D04C 8003C44C 15C00003 */  bnez       $t6, .L8003C45C
    /* 3D050 8003C450 00009825 */   or        $s3, $zero, $zero
    /* 3D054 8003C454 100000E2 */  b          .L8003C7E0
    /* 3D058 8003C458 A7A0009A */   sh        $zero, 0x9A($sp)
  .L8003C45C:
    /* 3D05C 8003C45C 44801800 */  mtc1       $zero, $f3
    /* 3D060 8003C460 44801000 */  mtc1       $zero, $f2
    /* 3D064 8003C464 93AF00D7 */  lbu        $t7, 0xD7($sp)
    /* 3D068 8003C468 87B9009A */  lh         $t9, 0x9A($sp)
    /* 3D06C 8003C46C 4622A03C */  c.lt.d     $f20, $f2
    /* 3D070 8003C470 24017597 */  addiu      $at, $zero, 0x7597
    /* 3D074 8003C474 00001825 */  or         $v1, $zero, $zero
    /* 3D078 8003C478 27B500B1 */  addiu      $s5, $sp, 0xB1
    /* 3D07C 8003C47C 45000002 */  bc1f       .L8003C488
    /* 3D080 8003C480 AFAF0048 */   sw        $t7, 0x48($sp)
    /* 3D084 8003C484 4620A507 */  neg.d      $f20, $f20
  .L8003C488:
    /* 3D088 8003C488 03210019 */  multu      $t9, $at
    /* 3D08C 8003C48C 3C010001 */  lui        $at, (0x186A0 >> 16)
    /* 3D090 8003C490 342186A0 */  ori        $at, $at, (0x186A0 & 0xFFFF)
    /* 3D094 8003C494 24050006 */  addiu      $a1, $zero, 0x6
    /* 3D098 8003C498 0000C012 */  mflo       $t8
    /* 3D09C 8003C49C 00000000 */  nop
    /* 3D0A0 8003C4A0 00000000 */  nop
    /* 3D0A4 8003C4A4 0301001A */  div        $zero, $t8, $at
    /* 3D0A8 8003C4A8 00007012 */  mflo       $t6
    /* 3D0AC 8003C4AC 25CFFFFC */  addiu      $t7, $t6, -0x4
    /* 3D0B0 8003C4B0 000FCC00 */  sll        $t9, $t7, 16
    /* 3D0B4 8003C4B4 0019C403 */  sra        $t8, $t9, 16
    /* 3D0B8 8003C4B8 07010019 */  bgez       $t8, .L8003C520
    /* 3D0BC 8003C4BC A7AF009A */   sh        $t7, 0x9A($sp)
    /* 3D0C0 8003C4C0 000FCC00 */  sll        $t9, $t7, 16
    /* 3D0C4 8003C4C4 0019C403 */  sra        $t8, $t9, 16
    /* 3D0C8 8003C4C8 240E0003 */  addiu      $t6, $zero, 0x3
    /* 3D0CC 8003C4CC 01D82023 */  subu       $a0, $t6, $t8
    /* 3D0D0 8003C4D0 2401FFFC */  addiu      $at, $zero, -0x4
    /* 3D0D4 8003C4D4 00811024 */  and        $v0, $a0, $at
    /* 3D0D8 8003C4D8 0002C823 */  negu       $t9, $v0
    /* 3D0DC 8003C4DC 1840002C */  blez       $v0, .L8003C590
    /* 3D0E0 8003C4E0 A7B9009A */   sh        $t9, 0x9A($sp)
    /* 3D0E4 8003C4E4 3C048004 */  lui        $a0, %hi(D_80044B30)
    /* 3D0E8 8003C4E8 24844B30 */  addiu      $a0, $a0, %lo(D_80044B30)
  .L8003C4EC:
    /* 3D0EC 8003C4EC 304E0001 */  andi       $t6, $v0, 0x1
    /* 3D0F0 8003C4F0 11C00006 */  beqz       $t6, .L8003C50C
    /* 3D0F4 8003C4F4 0002C843 */   sra       $t9, $v0, 1
    /* 3D0F8 8003C4F8 0003C0C0 */  sll        $t8, $v1, 3
    /* 3D0FC 8003C4FC 00987821 */  addu       $t7, $a0, $t8
    /* 3D100 8003C500 D5E40000 */  ldc1       $f4, 0x0($t7)
    /* 3D104 8003C504 4624A502 */  mul.d      $f20, $f20, $f4
    /* 3D108 8003C508 00000000 */  nop
  .L8003C50C:
    /* 3D10C 8003C50C 03201025 */  or         $v0, $t9, $zero
    /* 3D110 8003C510 1F20FFF6 */  bgtz       $t9, .L8003C4EC
    /* 3D114 8003C514 24630001 */   addiu     $v1, $v1, 0x1
    /* 3D118 8003C518 1000001E */  b          .L8003C594
    /* 3D11C 8003C51C 8FAF0048 */   lw        $t7, 0x48($sp)
  .L8003C520:
    /* 3D120 8003C520 87AE009A */  lh         $t6, 0x9A($sp)
    /* 3D124 8003C524 3C013FF0 */  lui        $at, (0x3FF00000 >> 16)
    /* 3D128 8003C528 00001825 */  or         $v1, $zero, $zero
    /* 3D12C 8003C52C 19C00018 */  blez       $t6, .L8003C590
    /* 3D130 8003C530 31D8FFFC */   andi      $t8, $t6, 0xFFFC
    /* 3D134 8003C534 00181400 */  sll        $v0, $t8, 16
    /* 3D138 8003C538 0018CC00 */  sll        $t9, $t8, 16
    /* 3D13C 8003C53C 44810800 */  mtc1       $at, $f1
    /* 3D140 8003C540 44800000 */  mtc1       $zero, $f0
    /* 3D144 8003C544 00197403 */  sra        $t6, $t9, 16
    /* 3D148 8003C548 00027C03 */  sra        $t7, $v0, 16
    /* 3D14C 8003C54C A7B8009A */  sh         $t8, 0x9A($sp)
    /* 3D150 8003C550 19C0000E */  blez       $t6, .L8003C58C
    /* 3D154 8003C554 01E01025 */   or        $v0, $t7, $zero
    /* 3D158 8003C558 3C048004 */  lui        $a0, %hi(D_80044B30)
    /* 3D15C 8003C55C 24844B30 */  addiu      $a0, $a0, %lo(D_80044B30)
  .L8003C560:
    /* 3D160 8003C560 304F0001 */  andi       $t7, $v0, 0x1
    /* 3D164 8003C564 11E00006 */  beqz       $t7, .L8003C580
    /* 3D168 8003C568 00027043 */   sra       $t6, $v0, 1
    /* 3D16C 8003C56C 0003C0C0 */  sll        $t8, $v1, 3
    /* 3D170 8003C570 0098C821 */  addu       $t9, $a0, $t8
    /* 3D174 8003C574 D7260000 */  ldc1       $f6, 0x0($t9)
    /* 3D178 8003C578 46260002 */  mul.d      $f0, $f0, $f6
    /* 3D17C 8003C57C 00000000 */  nop
  .L8003C580:
    /* 3D180 8003C580 01C01025 */  or         $v0, $t6, $zero
    /* 3D184 8003C584 1DC0FFF6 */  bgtz       $t6, .L8003C560
    /* 3D188 8003C588 24630001 */   addiu     $v1, $v1, 0x1
  .L8003C58C:
    /* 3D18C 8003C58C 4620A503 */  div.d      $f20, $f20, $f0
  .L8003C590:
    /* 3D190 8003C590 8FAF0048 */  lw         $t7, 0x48($sp)
  .L8003C594:
    /* 3D194 8003C594 24010066 */  addiu      $at, $zero, 0x66
    /* 3D198 8003C598 8FB800D0 */  lw         $t8, 0xD0($sp)
    /* 3D19C 8003C59C 15E10004 */  bne        $t7, $at, .L8003C5B0
    /* 3D1A0 8003C5A0 240E0030 */   addiu     $t6, $zero, 0x30
    /* 3D1A4 8003C5A4 87A5009A */  lh         $a1, 0x9A($sp)
    /* 3D1A8 8003C5A8 10000001 */  b          .L8003C5B0
    /* 3D1AC 8003C5AC 24A5000A */   addiu     $a1, $a1, 0xA
  .L8003C5B0:
    /* 3D1B0 8003C5B0 8F190024 */  lw         $t9, 0x24($t8)
    /* 3D1B4 8003C5B4 00B9A021 */  addu       $s4, $a1, $t9
    /* 3D1B8 8003C5B8 2A810014 */  slti       $at, $s4, 0x14
    /* 3D1BC 8003C5BC 14200002 */  bnez       $at, .L8003C5C8
    /* 3D1C0 8003C5C0 00000000 */   nop
    /* 3D1C4 8003C5C4 24140013 */  addiu      $s4, $zero, 0x13
  .L8003C5C8:
    /* 3D1C8 8003C5C8 1A800033 */  blez       $s4, .L8003C698
    /* 3D1CC 8003C5CC A3AE00B0 */   sb        $t6, 0xB0($sp)
    /* 3D1D0 8003C5D0 4634103C */  c.lt.d     $f2, $f20
    /* 3D1D4 8003C5D4 24130030 */  addiu      $s3, $zero, 0x30
    /* 3D1D8 8003C5D8 27B20074 */  addiu      $s2, $sp, 0x74
    /* 3D1DC 8003C5DC 4502002F */  bc1fl      .L8003C69C
    /* 3D1E0 8003C5E0 87B8009A */   lh        $t8, 0x9A($sp)
    /* 3D1E4 8003C5E4 4620A20D */  trunc.w.d  $f8, $f20
  .L8003C5E8:
    /* 3D1E8 8003C5E8 2694FFF8 */  addiu      $s4, $s4, -0x8
    /* 3D1EC 8003C5EC 26B50008 */  addiu      $s5, $s5, 0x8
    /* 3D1F0 8003C5F0 44114000 */  mfc1       $s1, $f8
    /* 3D1F4 8003C5F4 1A800008 */  blez       $s4, .L8003C618
    /* 3D1F8 8003C5F8 00000000 */   nop
    /* 3D1FC 8003C5FC 44915000 */  mtc1       $s1, $f10
    /* 3D200 8003C600 3C018004 */  lui        $at, %hi(D_80044B88)
    /* 3D204 8003C604 D4284B88 */  ldc1       $f8, %lo(D_80044B88)($at)
    /* 3D208 8003C608 46805121 */  cvt.d.w    $f4, $f10
    /* 3D20C 8003C60C 4624A181 */  sub.d      $f6, $f20, $f4
    /* 3D210 8003C610 46283502 */  mul.d      $f20, $f6, $f8
    /* 3D214 8003C614 00000000 */  nop
  .L8003C618:
    /* 3D218 8003C618 1A200011 */  blez       $s1, .L8003C660
    /* 3D21C 8003C61C 24100008 */   addiu     $s0, $zero, 0x8
    /* 3D220 8003C620 24100007 */  addiu      $s0, $zero, 0x7
    /* 3D224 8003C624 0600000E */  bltz       $s0, .L8003C660
    /* 3D228 8003C628 02402025 */   or        $a0, $s2, $zero
  .L8003C62C:
    /* 3D22C 8003C62C 02202825 */  or         $a1, $s1, $zero
    /* 3D230 8003C630 0C00F248 */  jal        ldiv
    /* 3D234 8003C634 2406000A */   addiu     $a2, $zero, 0xA
    /* 3D238 8003C638 8FB80078 */  lw         $t8, 0x78($sp)
    /* 3D23C 8003C63C 26B5FFFF */  addiu      $s5, $s5, -0x1
    /* 3D240 8003C640 27190030 */  addiu      $t9, $t8, 0x30
    /* 3D244 8003C644 A2B90000 */  sb         $t9, 0x0($s5)
    /* 3D248 8003C648 8FB10074 */  lw         $s1, 0x74($sp)
    /* 3D24C 8003C64C 5A200005 */  blezl      $s1, .L8003C664
    /* 3D250 8003C650 44801800 */   mtc1      $zero, $f3
    /* 3D254 8003C654 2610FFFF */  addiu      $s0, $s0, -0x1
    /* 3D258 8003C658 0603FFF4 */  bgezl      $s0, .L8003C62C
    /* 3D25C 8003C65C 02402025 */   or        $a0, $s2, $zero
  .L8003C660:
    /* 3D260 8003C660 44801800 */  mtc1       $zero, $f3
  .L8003C664:
    /* 3D264 8003C664 44801000 */  mtc1       $zero, $f2
    /* 3D268 8003C668 2610FFFF */  addiu      $s0, $s0, -0x1
    /* 3D26C 8003C66C 06000004 */  bltz       $s0, .L8003C680
  .L8003C670:
    /* 3D270 8003C670 2610FFFF */   addiu     $s0, $s0, -0x1
    /* 3D274 8003C674 26B5FFFF */  addiu      $s5, $s5, -0x1
    /* 3D278 8003C678 0601FFFD */  bgez       $s0, .L8003C670
    /* 3D27C 8003C67C A2B30000 */   sb        $s3, 0x0($s5)
  .L8003C680:
    /* 3D280 8003C680 1A800005 */  blez       $s4, .L8003C698
    /* 3D284 8003C684 26B50008 */   addiu     $s5, $s5, 0x8
    /* 3D288 8003C688 4634103C */  c.lt.d     $f2, $f20
    /* 3D28C 8003C68C 00000000 */  nop
    /* 3D290 8003C690 4503FFD5 */  bc1tl      .L8003C5E8
    /* 3D294 8003C694 4620A20D */   trunc.w.d $f8, $f20
  .L8003C698:
    /* 3D298 8003C698 87B8009A */  lh         $t8, 0x9A($sp)
  .L8003C69C:
    /* 3D29C 8003C69C 93AE00B1 */  lbu        $t6, 0xB1($sp)
    /* 3D2A0 8003C6A0 27AF00B0 */  addiu      $t7, $sp, 0xB0
    /* 3D2A4 8003C6A4 24020030 */  addiu      $v0, $zero, 0x30
    /* 3D2A8 8003C6A8 02AFA023 */  subu       $s4, $s5, $t7
    /* 3D2AC 8003C6AC 27190007 */  addiu      $t9, $t8, 0x7
    /* 3D2B0 8003C6B0 2694FFFF */  addiu      $s4, $s4, -0x1
    /* 3D2B4 8003C6B4 A7B9009A */  sh         $t9, 0x9A($sp)
    /* 3D2B8 8003C6B8 144E0009 */  bne        $v0, $t6, .L8003C6E0
    /* 3D2BC 8003C6BC 27B500B1 */   addiu     $s5, $sp, 0xB1
    /* 3D2C0 8003C6C0 87AF009A */  lh         $t7, 0x9A($sp)
  .L8003C6C4:
    /* 3D2C4 8003C6C4 26B50001 */  addiu      $s5, $s5, 0x1
    /* 3D2C8 8003C6C8 2694FFFF */  addiu      $s4, $s4, -0x1
    /* 3D2CC 8003C6CC 25F8FFFF */  addiu      $t8, $t7, -0x1
    /* 3D2D0 8003C6D0 A7B8009A */  sh         $t8, 0x9A($sp)
    /* 3D2D4 8003C6D4 92B90000 */  lbu        $t9, 0x0($s5)
    /* 3D2D8 8003C6D8 5059FFFA */  beql       $v0, $t9, .L8003C6C4
    /* 3D2DC 8003C6DC 87AF009A */   lh        $t7, 0x9A($sp)
  .L8003C6E0:
    /* 3D2E0 8003C6E0 8FAE0048 */  lw         $t6, 0x48($sp)
    /* 3D2E4 8003C6E4 24010066 */  addiu      $at, $zero, 0x66
    /* 3D2E8 8003C6E8 8FB800D0 */  lw         $t8, 0xD0($sp)
    /* 3D2EC 8003C6EC 15C10004 */  bne        $t6, $at, .L8003C700
    /* 3D2F0 8003C6F0 8FAF0048 */   lw        $t7, 0x48($sp)
    /* 3D2F4 8003C6F4 87A5009A */  lh         $a1, 0x9A($sp)
    /* 3D2F8 8003C6F8 10000009 */  b          .L8003C720
    /* 3D2FC 8003C6FC 24A50001 */   addiu     $a1, $a1, 0x1
  .L8003C700:
    /* 3D300 8003C700 24010065 */  addiu      $at, $zero, 0x65
    /* 3D304 8003C704 11E10003 */  beq        $t7, $at, .L8003C714
    /* 3D308 8003C708 24010045 */   addiu     $at, $zero, 0x45
    /* 3D30C 8003C70C 15E10003 */  bne        $t7, $at, .L8003C71C
    /* 3D310 8003C710 00001025 */   or        $v0, $zero, $zero
  .L8003C714:
    /* 3D314 8003C714 10000001 */  b          .L8003C71C
    /* 3D318 8003C718 24020001 */   addiu     $v0, $zero, 0x1
  .L8003C71C:
    /* 3D31C 8003C71C 00402825 */  or         $a1, $v0, $zero
  .L8003C720:
    /* 3D320 8003C720 8F190024 */  lw         $t9, 0x24($t8)
    /* 3D324 8003C724 00B99821 */  addu       $s3, $a1, $t9
    /* 3D328 8003C728 00137400 */  sll        $t6, $s3, 16
    /* 3D32C 8003C72C 000E9C03 */  sra        $s3, $t6, 16
    /* 3D330 8003C730 0293082A */  slt        $at, $s4, $s3
    /* 3D334 8003C734 10200004 */  beqz       $at, .L8003C748
    /* 3D338 8003C738 00000000 */   nop
    /* 3D33C 8003C73C 00149C00 */  sll        $s3, $s4, 16
    /* 3D340 8003C740 0013C403 */  sra        $t8, $s3, 16
    /* 3D344 8003C744 03009825 */  or         $s3, $t8, $zero
  .L8003C748:
    /* 3D348 8003C748 1A600025 */  blez       $s3, .L8003C7E0
    /* 3D34C 8003C74C 0274082A */   slt       $at, $s3, $s4
    /* 3D350 8003C750 10200007 */  beqz       $at, .L8003C770
    /* 3D354 8003C754 02751021 */   addu      $v0, $s3, $s5
    /* 3D358 8003C758 90590000 */  lbu        $t9, 0x0($v0)
    /* 3D35C 8003C75C 2B210035 */  slti       $at, $t9, 0x35
    /* 3D360 8003C760 54200004 */  bnel       $at, $zero, .L8003C774
    /* 3D364 8003C764 24050030 */   addiu     $a1, $zero, 0x30
    /* 3D368 8003C768 10000003 */  b          .L8003C778
    /* 3D36C 8003C76C 24050039 */   addiu     $a1, $zero, 0x39
  .L8003C770:
    /* 3D370 8003C770 24050030 */  addiu      $a1, $zero, 0x30
  .L8003C774:
    /* 3D374 8003C774 02751021 */  addu       $v0, $s3, $s5
  .L8003C778:
    /* 3D378 8003C778 904EFFFF */  lbu        $t6, -0x1($v0)
    /* 3D37C 8003C77C 2663FFFF */  addiu      $v1, $s3, -0x1
    /* 3D380 8003C780 00A02025 */  or         $a0, $a1, $zero
    /* 3D384 8003C784 14AE0009 */  bne        $a1, $t6, .L8003C7AC
    /* 3D388 8003C788 24010039 */   addiu     $at, $zero, 0x39
    /* 3D38C 8003C78C 00751021 */  addu       $v0, $v1, $s5
  .L8003C790:
    /* 3D390 8003C790 9059FFFF */  lbu        $t9, -0x1($v0)
    /* 3D394 8003C794 2673FFFF */  addiu      $s3, $s3, -0x1
    /* 3D398 8003C798 00137C00 */  sll        $t7, $s3, 16
    /* 3D39C 8003C79C 2463FFFF */  addiu      $v1, $v1, -0x1
    /* 3D3A0 8003C7A0 2442FFFF */  addiu      $v0, $v0, -0x1
    /* 3D3A4 8003C7A4 1099FFFA */  beq        $a0, $t9, .L8003C790
    /* 3D3A8 8003C7A8 000F9C03 */   sra       $s3, $t7, 16
  .L8003C7AC:
    /* 3D3AC 8003C7AC 14810004 */  bne        $a0, $at, .L8003C7C0
    /* 3D3B0 8003C7B0 02A31021 */   addu      $v0, $s5, $v1
    /* 3D3B4 8003C7B4 904E0000 */  lbu        $t6, 0x0($v0)
    /* 3D3B8 8003C7B8 25CF0001 */  addiu      $t7, $t6, 0x1
    /* 3D3BC 8003C7BC A04F0000 */  sb         $t7, 0x0($v0)
  .L8003C7C0:
    /* 3D3C0 8003C7C0 04610007 */  bgez       $v1, .L8003C7E0
    /* 3D3C4 8003C7C4 87AE009A */   lh        $t6, 0x9A($sp)
    /* 3D3C8 8003C7C8 26730001 */  addiu      $s3, $s3, 0x1
    /* 3D3CC 8003C7CC 0013C400 */  sll        $t8, $s3, 16
    /* 3D3D0 8003C7D0 25CF0001 */  addiu      $t7, $t6, 0x1
    /* 3D3D4 8003C7D4 A7AF009A */  sh         $t7, 0x9A($sp)
    /* 3D3D8 8003C7D8 00189C03 */  sra        $s3, $t8, 16
    /* 3D3DC 8003C7DC 26B5FFFF */  addiu      $s5, $s5, -0x1
  .L8003C7E0:
    /* 3D3E0 8003C7E0 8FB000D0 */  lw         $s0, 0xD0($sp)
    /* 3D3E4 8003C7E4 93B400D7 */  lbu        $s4, 0xD7($sp)
    /* 3D3E8 8003C7E8 02A08825 */  or         $s1, $s5, $zero
    /* 3D3EC 8003C7EC 0C00EF58 */  jal        func_8003BD60
    /* 3D3F0 8003C7F0 87B2009A */   lh        $s2, 0x9A($sp)
    /* 3D3F4 8003C7F4 8FBF003C */  lw         $ra, 0x3C($sp)
  .L8003C7F8:
    /* 3D3F8 8003C7F8 D7B40018 */  ldc1       $f20, 0x18($sp)
    /* 3D3FC 8003C7FC 8FB00024 */  lw         $s0, 0x24($sp)
    /* 3D400 8003C800 8FB10028 */  lw         $s1, 0x28($sp)
    /* 3D404 8003C804 8FB2002C */  lw         $s2, 0x2C($sp)
    /* 3D408 8003C808 8FB30030 */  lw         $s3, 0x30($sp)
    /* 3D40C 8003C80C 8FB40034 */  lw         $s4, 0x34($sp)
    /* 3D410 8003C810 8FB50038 */  lw         $s5, 0x38($sp)
    /* 3D414 8003C814 03E00008 */  jr         $ra
    /* 3D418 8003C818 27BD00D0 */   addiu     $sp, $sp, 0xD0
endlabel _Ldtob
    /* 3D41C 8003C81C 00000000 */  nop
