#include "common.h"

Gfx doduo_part13_draw_far[] = {
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsDPSetTile(G_IM_FMT_CI, G_IM_SIZ_16b, 0, 0x0000, G_TX_LOADTILE, 0, G_TX_NOMIRROR | G_TX_WRAP, 4, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_WRAP, 4, G_TX_NOLOD),
    gsDPSetTile(G_IM_FMT_CI, G_IM_SIZ_4b, 1, 0x0000, G_TX_RENDERTILE, 0, G_TX_NOMIRROR | G_TX_CLAMP, 4, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_CLAMP, 4, G_TX_NOLOD),
    gsDPSetTextureImage(G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, doduo_tex_80159DB8),
    gsDPLoadSync(),
    gsDPLoadTLUTCmd(5, 14),
    gsDPPipeSync(),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetTileSize(G_TX_RENDERTILE, 0, 0, 0x003C, 0x003C),
    gsDPSetTextureImage(G_IM_FMT_CI, G_IM_SIZ_16b, 1, doduo_tex_80159DE0_png),
    gsDPLoadSync(),
    gsDPLoadBlock(G_TX_LOADTILE, 0, 0, 63, 2048),
    gsDPPipeSync(),
    gsSPModifyVertex(0, G_MWO_POINT_ST, 0x01050146),
    gsSPModifyVertex(1, G_MWO_POINT_ST, 0x00000003),
    gsSPModifyVertex(2, G_MWO_POINT_ST, 0x01FF01FF),
    gsSPVertex(&doduo_vtx[394], 2, 3),
    gsSP1Triangle(0, 2, 4, 0),
    gsSPModifyVertex(0, G_MWO_POINT_ST, 0x01FFFFF9),
    gsSPModifyVertex(2, G_MWO_POINT_ST, 0x00040202),
    gsSP1Triangle(2, 1, 4, 0),
    gsSPModifyVertex(1, G_MWO_POINT_ST, 0x00040202),
    gsSP1Triangle(0, 3, 1, 0),
    gsSPEndDisplayList(),
};
