.section .late_rodata
nonmatching D_camera_check_80208C28

dlabel D_camera_check_80208C28
    /* 8A6418 80208C28 40C90FDB */ .float 6.283185482
enddlabel D_camera_check_80208C28

nonmatching D_camera_check_80208C2C

dlabel D_camera_check_80208C2C
    /* 8A641C 80208C2C 3E860A92 */ .float 0.2617993951
enddlabel D_camera_check_80208C2C


.section .text
/* Generated by spimdisasm 1.42.1 */

nonmatching func_camera_check_801DDF28, 0x9C

glabel func_camera_check_801DDF28
    /* 87B718 801DDF28 3C018021 */  lui        $at, %hi(D_camera_check_80208944)
    /* 87B71C 801DDF2C C4208944 */  lwc1       $f0, %lo(D_camera_check_80208944)($at)
    /* 87B720 801DDF30 3C018021 */  lui        $at, %hi(D_camera_check_80208C28)
    /* 87B724 801DDF34 C4228C28 */  lwc1       $f2, %lo(D_camera_check_80208C28)($at)
    /* 87B728 801DDF38 3C018021 */  lui        $at, %hi(D_camera_check_80208C2C)
    /* 87B72C 801DDF3C C4248C2C */  lwc1       $f4, %lo(D_camera_check_80208C2C)($at)
    /* 87B730 801DDF40 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 87B734 801DDF44 AFA40020 */  sw         $a0, 0x20($sp)
    /* 87B738 801DDF48 46040000 */  add.s      $f0, $f0, $f4
    /* 87B73C 801DDF4C 3C068021 */  lui        $a2, %hi(D_camera_check_80208948)
    /* 87B740 801DDF50 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 87B744 801DDF54 24C68948 */  addiu      $a2, $a2, %lo(D_camera_check_80208948)
    /* 87B748 801DDF58 4600103C */  c.lt.s     $f2, $f0
    /* 87B74C 801DDF5C 3C048025 */  lui        $a0, %hi(D_camera_check_80249900)
    /* 87B750 801DDF60 3C018021 */  lui        $at, %hi(D_camera_check_80208944)
    /* 87B754 801DDF64 2407000E */  addiu      $a3, $zero, 0xE
    /* 87B758 801DDF68 45000002 */  bc1f       .Lcamera_check_801DDF74
    /* 87B75C 801DDF6C 240E0048 */   addiu     $t6, $zero, 0x48
    /* 87B760 801DDF70 46020001 */  sub.s      $f0, $f0, $f2
  .Lcamera_check_801DDF74:
    /* 87B764 801DDF74 44050000 */  mfc1       $a1, $f0
    /* 87B768 801DDF78 8C849900 */  lw         $a0, %lo(D_camera_check_80249900)($a0)
    /* 87B76C 801DDF7C AFAE0010 */  sw         $t6, 0x10($sp)
    /* 87B770 801DDF80 0C077769 */  jal        func_camera_check_801DDDA4
    /* 87B774 801DDF84 E4208944 */   swc1      $f0, %lo(D_camera_check_80208944)($at)
    /* 87B778 801DDF88 3C018021 */  lui        $at, %hi(D_camera_check_80208944)
    /* 87B77C 801DDF8C C4208944 */  lwc1       $f0, %lo(D_camera_check_80208944)($at)
    /* 87B780 801DDF90 3C048025 */  lui        $a0, %hi(D_camera_check_80249904)
    /* 87B784 801DDF94 3C068021 */  lui        $a2, %hi(D_camera_check_80208950)
    /* 87B788 801DDF98 240F0048 */  addiu      $t7, $zero, 0x48
    /* 87B78C 801DDF9C 44050000 */  mfc1       $a1, $f0
    /* 87B790 801DDFA0 AFAF0010 */  sw         $t7, 0x10($sp)
    /* 87B794 801DDFA4 24C68950 */  addiu      $a2, $a2, %lo(D_camera_check_80208950)
    /* 87B798 801DDFA8 8C849904 */  lw         $a0, %lo(D_camera_check_80249904)($a0)
    /* 87B79C 801DDFAC 0C077769 */  jal        func_camera_check_801DDDA4
    /* 87B7A0 801DDFB0 24070064 */   addiu     $a3, $zero, 0x64
    /* 87B7A4 801DDFB4 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 87B7A8 801DDFB8 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 87B7AC 801DDFBC 03E00008 */  jr         $ra
    /* 87B7B0 801DDFC0 00000000 */   nop
endlabel func_camera_check_801DDF28
