#include "common.h"

Gfx arcanine_part9_draw_far[] = {
    gsDPPipeSync(),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_PASS2),
    gsDPSetTile(G_IM_FMT_CI, G_IM_SIZ_16b, 0, 0x0000, G_TX_LOADTILE, 0, G_TX_NOMIRROR | G_TX_WRAP, 5, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_WRAP, 5, G_TX_NOLOD),
    gsDPSetTile(G_IM_FMT_CI, G_IM_SIZ_4b, 2, 0x0000, G_TX_RENDERTILE, 0, G_TX_NOMIRROR | G_TX_CLAMP, 5, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_CLAMP, 5, G_TX_NOLOD),
    gsDPSetTextureImage(G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, arcanine_tex_skin6_pal),
    gsDPLoadSync(),
    gsDPLoadTLUTCmd(5, 14),
    gsDPPipeSync(),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetTileSize(G_TX_RENDERTILE, 0, 0, 0x007C, 0x007C),
    gsDPSetTextureImage(G_IM_FMT_CI, G_IM_SIZ_16b, 1, arcanine_tex_skin6_png),
    gsDPLoadSync(),
    gsDPLoadBlock(G_TX_LOADTILE, 0, 0, 255, 1024),
    gsDPPipeSync(),
    gsSPModifyVertex(0, G_MWO_POINT_ST, 0x02C3FF9E),
    gsSPModifyVertex(1, G_MWO_POINT_ST, 0x037F00DB),
    gsSPModifyVertex(2, G_MWO_POINT_ST, 0x03F4FFFD),
    gsSPVertex(&arcanine_vtx[515], 1, 3),
    gsSP2Triangles(0, 3, 1, 0, 3, 2, 1, 0),
    gsDPPipeSync(),
    gsDPSetTile(G_IM_FMT_CI, G_IM_SIZ_16b, 0, 0x0000, G_TX_LOADTILE, 0, G_TX_NOMIRROR | G_TX_WRAP, 6, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_WRAP, 5, G_TX_NOLOD),
    gsDPSetTile(G_IM_FMT_CI, G_IM_SIZ_4b, 2, 0x0000, G_TX_RENDERTILE, 0, G_TX_NOMIRROR | G_TX_CLAMP, 6, G_TX_NOLOD, G_TX_NOMIRROR | G_TX_CLAMP, 5, G_TX_NOLOD),
    gsDPSetTextureImage(G_IM_FMT_RGBA, G_IM_SIZ_16b, 1, arcanine_tex_skin4_pal),
    gsDPLoadSync(),
    gsDPLoadTLUTCmd(5, 4),
    gsDPPipeSync(),
    gsDPSetTileSize(G_TX_RENDERTILE, 0, 0, 0x007C, 0x00FC),
    gsDPSetTextureImage(G_IM_FMT_CI, G_IM_SIZ_16b, 1, arcanine_tex_skin4_png),
    gsDPLoadSync(),
    gsDPLoadBlock(G_TX_LOADTILE, 0, 0, 511, 1024),
    gsDPPipeSync(),
    gsSPModifyVertex(0, G_MWO_POINT_ST, 0xFBCD0792),
    gsSPModifyVertex(2, G_MWO_POINT_ST, 0xFD7C11F0),
    gsSPVertex(&arcanine_vtx[242], 1, 3),
    gsSPVertex(&arcanine_vtx[244], 1, 4),
    gsSPVertex(&arcanine_vtx[247], 1, 5),
    gsSPVertex(&arcanine_vtx[516], 2, 6),
    gsSPVertex(&arcanine_vtx[518], 1, 28),
    gsSPVertex(&arcanine_vtx[249], 1, 29),
    gsSPVertex(&arcanine_vtx[519], 1, 30),
    gsSP2Triangles(7, 30, 0, 0, 2, 7, 0, 0),
    gsSPModifyVertex(0, G_MWO_POINT_ST, 0x034C1737),
    gsSPModifyVertex(2, G_MWO_POINT_ST, 0xFF181399),
    gsSP2Triangles(28, 2, 29, 0, 2, 3, 29, 0),
    gsSP2Triangles(0, 6, 5, 0, 4, 0, 5, 0),
    gsSPEndDisplayList(),
};
